const fs=require('fs');
const battle=fs.readFileSync('js/battle.js','utf8');
const action=fs.readFileSync('js/action-variety-v3.30.0.js','utf8');
const css=fs.readFileSync('css/action-variety-v3.30.0.css','utf8');
const html=fs.readFileSync('index.html','utf8');
const failures=[];
const check=(ok,msg)=>{if(!ok)failures.push(msg)};
check(/phase-anticipation/.test(battle),'stance phase missing');
check(/phase-movement/.test(battle),'movement phase missing');
check(/phase-contact/.test(battle),'actual attack phase missing');
check(/phase-movement"\)\},heroLead\+140[\s\S]*phase-contact"\)\},heroLead\+320[\s\S]*phase-recover"\)\},heroLead\+620/.test(battle),'regular sequence is not stance -> movement -> actual attack');
check(/hero-frame-strike/.test(action)&&/attack\.src=chosen\.asset/.test(action)===false,'variant asset incorrectly replaces movement frame');
check(/strike\.src=chosen\.asset/.test(action),'variant asset is not assigned to strike frame');
check(/phase-movement \.hero-frame-anticipation\{opacity:0/.test(css),'stance frame remains visible during movement');
check(/phase-movement \.hero-frame-follow-through\{[^}]*opacity:1/.test(css),'movement does not use frame 4 / follow-through asset');
check(/phase-movement \.hero-frame-attack\{opacity:0/.test(css),'original actual attack leaks into movement');
check(/phase-contact:not\(\.charging-finisher\) \.hero-frame-strike\{[^}]*visibility:visible!important;opacity:1!important/.test(css),'strike frame is hidden by legacy battle visibility rules');
check(/charging-finisher\.phase-contact \.hero-frame-attack/.test(css),'finisher frame preservation missing');
check(/Attack Lab/.test(action)&&/attackLabStep/.test(action)&&/playAttackLab/.test(action),'DEV Attack Lab missing');
check(/step==='movement'\?h\.followThrough/.test(action),'Attack Lab movement does not use frame 4');
check(!/attackLabStep\('follow'\)/.test(action),'Attack Lab incorrectly exposes a fourth sequence step');
check((action.match(/<b>[123]<\/b>/g)||[]).length===3,'Attack Lab does not show exactly three sequence steps');
check((action.match(/bodyScale:/g)||[]).length===7&&(action.match(/footShiftX:/g)||[]).length===7,'seven contact attacks do not carry body/foot anchors');
const scales=[...action.matchAll(/bodyScale:([\d.]+)/g)].map(x=>Number(x[1])),shifts=[...action.matchAll(/footShiftX:([\d.-]+)/g)].map(x=>Number(x[1]));
check(scales.length===7&&scales.every(x=>x>=1&&x<=1.75),'contact body scale escapes conservative bounds');
const expectedScales=[1.48,1.48,1.42,1.72,1.25,1.25,1.25];
check(scales.length===expectedScales.length&&scales.every((x,i)=>Math.abs(x-expectedScales[i])<0.001),'contact body scale differs from the approved safe per-asset calibration');
check(shifts.length===7&&shifts.every(x=>x>=0&&x<=42),'contact foot anchor escapes safe horizontal bounds');
check(/--pa-contact-scale/.test(action)&&/--pa-contact-shift-x/.test(action),'contact anchor metadata is not applied');
check(/bottom:0!important/.test(css)&&/scale\(var\(--pa-contact-scale,1\)\)/.test(css),'single foot-anchored transform is missing');
check(!/pa-attack-(?:original|dash|arc|pulse|sweep|spiral|thorn) \.hero-frame-strike/.test(css),'unsafe per-class transform overrides remain');
const actionBust=html.match(/action-variety-v3\.30\.0\.js\?v=(\d+)\.(\d+)\.(\d+)/);
check(!!actionBust&&(+actionBust[1]>3||(+actionBust[1]===3&&(+actionBust[2]>32||(+actionBust[2]===32&&+actionBust[3]>=2)))),'action assets are not cache-busted to at least the compact Bunga contact-pose revision');
console.log(JSON.stringify({status:failures.length?'fail':'pass',failures},null,2));
process.exitCode=failures.length?1:0;
