const fs=require('fs'),assert=require('assert');
const js=fs.readFileSync('js/cikgu-manipulatives-v3.19.1.js','utf8');
const css=fs.readFileSync('css/cikgu-manipulatives-v3.19.1.css','utf8');
const pwa=fs.readFileSync('js/pwa.js','utf8');
const sw=fs.readFileSync('sw.js','utf8');
const lock=fs.readFileSync('CIKGU-WAJAR-MANIPULATIVES-LOCK-v3.19.1.md','utf8');
assert(/const VERSION='3\.19\.1'/.test(js),'manipulative version missing');
for(const mode of ['divide','fraction','decimal','percent','ratio','money','time','measure','data','coord'])assert(js.includes(`'${mode}'`),`missing ${mode} visual mode`);
assert(/12 objek → 3 kumpulan/.test(js)&&/Agih sama rata/.test(js),'division must model equal sharing');
assert(!/vcBoulder|batu penuh|slash — bahagi/.test(js),'division visual regressed to slicing one object');
assert(/measureKind/.test(js)&&/scaleScene/.test(js)&&/jugScene/.test(js)&&/rulerScene/.test(js),'measurement tool variants incomplete');
assert(/Peratus bermaksud “daripada 100”|Peratus bermaksud/.test(js),'percent concept missing');
assert(/x dahulu, y kemudian/.test(js),'coordinate order cue missing');
assert(!/scoreState\s*\(|\.mastery\s*=|recordFrontierResponse\s*\(/.test(js),'teaching layer must not mutate mastery/evidence engine');
assert(/prefers-reduced-motion:reduce/.test(css),'reduced-motion support missing');
assert(/const MANIPULATIVE_VERSION='3\.19\.1'/.test(pwa),'PWA loader missing manipulative version');
assert(/cikgu-manipulatives-v3\.19\.1\.js/.test(sw)&&/cikgu-manipulatives-v3\.19\.1\.css/.test(sw),'service worker missing manipulative files');
assert(/operasi bahagi.*agih/i.test(lock),'pedagogy lock missing division rule');
console.log('PASS Cikgu Wajar manipulatives v3.19.1 invariants');
