const fs=require('fs'),vm=require('vm');
const moduleCode=fs.readFileSync('js/effort-guard-v3.32.0.js','utf8');
const battle=fs.readFileSync('js/battle.js','utf8'),learning=fs.readFileSync('js/learning.js','utf8'),intervention=fs.readFileSync('js/engine/intervention.js','utf8'),html=fs.readFileSync('index.html','utf8'),css=fs.readFileSync('css/effort-restu-v3.32.0.css','utf8'),sw=fs.readFileSync('sw.js','utf8');
const failures=[],check=(ok,msg)=>{if(!ok)failures.push(msg)};
let now=1000;const context={sess:{},performance:{now:()=>now},Date,console};context.window=context;context.globalThis=context;vm.createContext(context);vm.runInContext(moduleCode,context);
const guard=context.PAEffortGuard,q1={token:1,skill:'D2.TEST',prompt:'Berapakah 7 + 8?'},q2={token:2,skill:'D2.TEST',prompt:'Pilih jawapan yang betul.'};
check(guard.firstWrong(q1,1)===false,'one fast wrong incorrectly locks the pupil');
guard.hintOpened(q1);now+=150;guard.retryResolved(q1,false);
check(guard.shouldCoach('D2.TEST')===true,'fast wrong after hint does not summon Cikgu Dimensi');
guard.coachStarted('D2.TEST');guard.coachFinished('D2.TEST');
check(guard.firstWrong(q2,1)===true,'post-coach rapid wrong does not request Guardian Restu');
check(guard.limit({prompt:'1 + 1 = ?'})<guard.limit({prompt:'Baca soalan yang lebih panjang ini dengan teliti sebelum memilih jawapan.'}),'reading-time threshold is not prompt-length aware');
check(/PAEffortGuard\?\.firstWrong/.test(battle)&&/PAEffortGuard\?\.hintOpened/.test(battle)&&/PAEffortGuard\?\.retryResolved/.test(battle),'battle evidence hooks incomplete');
check(/PAEffortGuard\?\.shouldCoach/.test(intervention),'Cikgu Dimensi routing hook missing');
check(/coachStarted/.test(learning)&&/coachFinished/.test(learning),'coach boundary hooks missing');
check(/mode==='effort'/.test(learning)&&/verifyEffortRestuPin/.test(learning)&&/pin!==db\.parentPin/.test(learning),'PIN-only Guardian Restu flow incomplete');
check(/if\(lock\.mode==='effort'\)return/.test(learning)&&/if\(db\?\.restuLock\?\.mode==='effort'\)return/.test(learning),'timer or Restu Key can bypass effort lock');
check(/effortRestuPanel/.test(html)&&/effortMode/.test(css),'effort Restu interface missing');
check(/effort-guard-v3\.32\.0\.js/.test(sw)&&/effort-restu-v3\.32\.0\.css/.test(sw),'effort files missing from offline shell');
console.log(JSON.stringify({status:failures.length?'fail':'pass',failures},null,2));process.exitCode=failures.length?1:0;
