const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..'),failures=[];
const read=file=>fs.readFileSync(path.join(root,file),'utf8'),check=(name,value)=>{if(!value)failures.push(name)};
const cloud=read('js/cloud.js'),css=read('css/cikgu-dimensi-core-v0.2.css'),portal=read('js/engine/dimensional-portal.js'),index=read('index.html');
check('idle-threshold-two-minutes',/IDLE_AFTER_MS=120000/.test(cloud));
check('idle-excluded-from-playing',/Date\.now\(\)-state\.lastInteractionAt<IDLE_AFTER_MS/.test(cloud));
check('mobile-interaction-resumes',/pointerdown/.test(cloud)&&/markInteraction/.test(cloud));
check('keyboard-interaction-resumes',/keydown/.test(cloud));
check('background-still-excluded',/!document\.hidden/.test(cloud));
check('resume-does-not-add-idle-gap',/if\(wasIdle\)state\.lastTick=performance\.now\(\)/.test(cloud));
check('cutin-is-band-not-wallpaper',/top:31%;height:38%/.test(css)&&/dvChallengerIn/.test(css));
check('cutin-slides-from-side',/translateX\(-115%\)/.test(css)&&/translateX\(0\)/.test(css));
check('summon-copy-retained',/Masa untuk Cikgu Dimensi!/.test(portal));
check('cloud-cache-bust',/cloud\.js\?v=(?!3\.16\.6)\d+\.\d+\.\d+/.test(index));
const report={status:failures.length?'fail':'pass',failures};console.log(JSON.stringify(report,null,2));process.exitCode=failures.length?1:0;
