const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),ctx={console,Math};ctx.window=ctx;ctx.sess={questionFingerprints:[],questionHistory:[],mode:'practice'};vm.createContext(ctx);
const files=['data/kssr/knowledge-graph.js','data/kssr/alignment-v3.9.0.js','questions/helpers.js','questions/d1/core.js',...Array.from({length:8},(_,i)=>`questions/d2/topic-${i+1}.js`),'questions/d3/core.js','questions/d4/core.js','questions/d5/core.js','questions/d6/core.js','questions/kssr-archetypes-v3.9.0.js','questions/kssr-content-v3.11.js','questions/index.js'];
for(const file of files)vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),ctx,{filename:file});vm.runInContext('globalThis.__skills=GRAPH.skills;globalThis.__generate=generate',ctx);
const failures=[];let checked=0;
function estimate(a,b,sym){if(sym==='+'||sym==='−'||sym==='-'){const unit=Math.max(a,b)>=1000?100:10,ra=Math.round(a/unit)*unit,rb=Math.round(b/unit)*unit;return sym==='+'?ra+rb:ra-rb}if(sym==='×'){const unit=a>=100?100:a>=20?10:1;return Math.round(a/unit)*unit*b}return a/b}
for(const skill of ctx.__skills){for(let i=0;i<240;i++){const q=ctx.__generate(skill.id,{evidence:5,confidence:60,mastery:60,correct:4,wrong:1}),plain=String(q.prompt||'').replace(/<[^>]+>/g,' ');if(!/Tanpa mengira semula sepenuhnya/i.test(plain))continue;const m=plain.match(/(-?\d+(?:\.\d+)?)\s*([+−\-×÷])\s*(-?\d+(?:\.\d+)?)/);if(!m)continue;checked++;const target=estimate(Number(m[1]),Number(m[3]),m[2]),correct=Math.abs(Number(q.answer)-target),wrong=(q.wrong||[]).map(x=>Math.abs(Number(x.v)-target));if(wrong.some(distance=>!Number.isFinite(distance)||distance<=correct))failures.push({skill:skill.id,prompt:plain.trim(),answer:q.answer,choices:q.wrong.map(x=>x.v),target});}}
if(checked<100)failures.push({type:'insufficient-reasonableness-samples',checked});
console.log(JSON.stringify({status:failures.length?'fail':'pass',checked,failures:failures.slice(0,20)},null,2));process.exitCode=failures.length?1:0;
