const fs=require('fs');
const battle=fs.readFileSync('js/battle.js','utf8');
const action=fs.readFileSync('js/action-variety-v3.30.0.js','utf8');
const css=fs.readFileSync('css/action-variety-v3.30.0.css','utf8');
const html=fs.readFileSync('index.html','utf8');
const failures=[];
const check=(ok,msg)=>{if(!ok)failures.push(msg)};
check(/phase-anticipation/.test(battle),'stance phase missing');
check(/phase-movement/.test(battle),'movement phase missing');
check(/phase-contact/.test(battle),'actual attack phase missing');
check(/phase-movement"\)\},heroLead\+140[\s\S]*phase-contact"\)\},heroLead\+320[\s\S]*phase-recover"\)\},heroLead\+620/.test(battle),'regular sequence is not stance -> movement -> actual attack');
check(/hero-frame-strike/.test(action)&&/attack\.src=chosen\.asset/.test(action)===false,'variant asset incorrectly replaces movement frame');
check(/strike\.src=chosen\.asset/.test(action),'variant asset is not assigned to strike frame');
check(/phase-movement \.hero-frame-anticipation\{opacity:0/.test(css),'stance frame remains visible during movement');
check(/phase-movement \.hero-frame-follow-through\{[^}]*opacity:1/.test(css),'movement does not use frame 4 / follow-through asset');
check(/phase-movement \.hero-frame-attack\{opacity:0/.test(css),'original actual attack leaks into movement');
check(/phase-contact:not\(\.charging-finisher\) \.hero-frame-strike\{[^}]*visibility:visible!important;opacity:1!important/.test(css),'strike frame is hidden by legacy battle visibility rules');
check(/charging-finisher\.phase-contact \.hero-frame-attack/.test(css),'finisher frame preservation missing');
check(/Attack Lab/.test(action)&&/attackLabStep/.test(action)&&/playAttackLab/.test(action),'DEV Attack Lab missing');
check(/step==='movement'\?h\.followThrough/.test(action),'Attack Lab movement does not use frame 4');
check(!/attackLabStep\('follow'\)/.test(action),'Attack Lab incorrectly exposes a fourth sequence step');
check((action.match(/<b>[123]<\/b>/g)||[]).length===3,'Attack Lab does not show exactly three sequence steps');
for(const id of ['original','dash','arc','pulse','sweep','spiral','thorn'])check(new RegExp('pa-attack-'+id+' \\.hero-frame-strike').test(css),'contact scale correction missing for '+id);
for(const id of ['original','sweep','spiral','thorn'])check(new RegExp('hero-bunga[^}]*pa-attack-'+id+'[^}]*scale\\(1\\.[2-9]').test(css),'Bunga remains undersized for '+id);
check(/v=3\.31\.6/.test(html),'action files are not cache-busted to 3.31.6');
console.log(JSON.stringify({status:failures.length?'fail':'pass',failures},null,2));
process.exitCode=failures.length?1:0;
