const fs=require('fs'),assert=require('assert');
const pwa=fs.readFileSync('js/pwa.js','utf8'),sw=fs.readFileSync('sw.js','utf8');
const builds=fs.readdirSync('.').map(n=>n.match(/^BUILD-(\d+)\.(\d+)\.(\d+)\.md$/)).filter(Boolean).map(m=>({v:`${m[1]}.${m[2]}.${m[3]}`,p:m.slice(1).map(Number)})).sort((a,b)=>a.p[0]-b.p[0]||a.p[1]-b.p[1]||a.p[2]-b.p[2]);
assert(builds.length,'release BUILD file missing');const expected=builds.at(-1).v;
const c=n=>pwa.match(new RegExp(`const ${n}='(\\d+\\.\\d+\\.\\d+)'`))?.[1];
assert.equal(c('APP_VERSION'),expected);assert.equal(c('Y6_REPAIR_VERSION'),expected);
assert.equal(c('DEPTH_VERSION'),'3.22.0');assert.equal(c('INTEGRITY_VERSION'),'3.18.1');
assert.equal(c('SENSORY_VERSION'),'3.19.0');assert.equal(c('MANIPULATIVE_VERSION'),'3.19.1');assert.equal(c('DAILY_REVIEW_VERSION'),'3.20.0');
assert.equal(c('DEV_EXPERIMENTS_VERSION'),'3.21.2');assert.equal(c('COMBAT_POLISH_VERSION'),'3.21.3');assert.equal(c('BOSS_LAB_VERSION'),'3.21.4');
assert.equal(c('TARGET_ANCHOR_VERSION'),'3.21.5');assert.equal(c('FINISHER_HOTSPOT_VERSION'),'3.21.6');assert.equal(c('TYPED_UI_VERSION'),'3.21.8');
assert.equal(sw.match(/CACHE_NAME='pahlawan-angka-v(\d+\.\d+\.\d+)'/)?.[1],expected);
assert(fs.existsSync(`questions/kssr-year6-space-data-v${expected}.js`));assert(fs.existsSync(`css/kssr-year6-space-data-v${expected}.css`));
assert(!/world-response-v3\.21\.0/.test(pwa+sw));
console.log(`PASS version sync v${expected}; KSSR depth 3.22.0 -> Year6 repair ${expected} -> existing UX/combat layers`);
