const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),failures=[],source=fs.readFileSync(path.join(root,'js/parent-learning-tools-v3.26.0.js'),'utf8'),start=source.indexOf('function printVisualDependent'),end=source.indexOf('function plainPrompt',start);if(start<0||end<0)throw new Error('Print safety helper not found');
const helper={};vm.createContext(helper);vm.runInContext(`${source.slice(start,end)};globalThis.visualDependent=printVisualDependent`,helper);const expect=(name,value,actual)=>{if(!value)failures.push({name,actual})};
expect('base-ten-block-rejected',helper.visualDependent('<div>3 ratus 4 puluh 2 sa</div>Apakah nombor yang ditunjukkan oleh blok nilai tempat?'),true);
expect('ordinary-place-value-kept',!helper.visualDependent('Apakah nilai digit 3 pada tempat ratus dalam 538?'),true);
expect('ordinary-expanded-number-kept',!helper.visualDependent('500 + 30 + 8 membentuk nombor?'),true);
const ctx={console,Math};ctx.window=ctx;ctx.sess={questionFingerprints:[],questionHistory:[],recent:[],mode:'practice'};vm.createContext(ctx);const files=['data/kssr/knowledge-graph.js','data/kssr/alignment-v3.9.0.js','questions/helpers.js','questions/d1/core.js',...Array.from({length:8},(_,i)=>`questions/d2/topic-${i+1}.js`),'questions/d3/core.js','questions/d4/core.js','questions/d5/core.js','questions/d6/core.js','questions/kssr-archetypes-v3.9.0.js','questions/kssr-content-v3.11.js','questions/index.js'];for(const file of files)vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),ctx,{filename:file});vm.runInContext('globalThis.skills=GRAPH.skills;globalThis.generateOne=generate',ctx);
let checked=0,rejected=0,baseTen=0;for(const skill of ctx.skills){ctx.sess.questionFingerprints=[];ctx.sess.questionHistory=[];for(let i=0;i<160;i++){const q=ctx.generateOne(skill.id,{evidence:5,confidence:60,mastery:60,correct:4,wrong:1}),raw=String(q.prompt||'');checked++;if(/blok\s+nilai\s+tempat/i.test(raw)){baseTen++;if(!helper.visualDependent(raw))failures.push({name:'base-ten-leak',skill:skill.id,prompt:raw.slice(0,180)})}if(helper.visualDependent(raw))rejected++}}
expect('base-ten-sample-coverage',baseTen>0,baseTen);const report={status:failures.length?'fail':'pass',checked,rejectedVisualDependent:rejected,baseTenSamples:baseTen,failures};console.log(JSON.stringify(report,null,2));process.exitCode=failures.length?1:0;
