const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),failures=[],source=fs.readFileSync(path.join(root,'js/parent-learning-tools-v3.26.0.js'),'utf8');
const start=source.indexOf('function worksheetDiversityKeys'),end=source.indexOf('function makeQuestions',start);if(start<0||end<0)throw new Error('Diversity engine not found');
const helper={};vm.createContext(helper);vm.runInContext(`${source.slice(start,end)};globalThis.keys=worksheetDiversityKeys;globalThis.accept=acceptDiverseItem`,helper);
const expect=(name,condition,actual)=>{if(!condition)failures.push({name,actual})};
expect('same-shape-concept',helper.keys({prompt:'Bentuk ini mempunyai satu puncak.',answer:'piramid'}).concept==='shape:piramid',helper.keys({prompt:'Bentuk ini mempunyai satu puncak.',answer:'piramid'}));
expect('compose-is-not-geometry',!helper.keys({prompt:'80 + 10 membentuk nombor?',answer:90}).format.endsWith(':geometry'),helper.keys({prompt:'80 + 10 membentuk nombor?',answer:90}));
const counts={skill:{},format:{},operation:{},concept:{}},limits={skill:5,format:3,operation:4},shape={prompt:'Bentuk ini mempunyai satu puncak.',answer:'piramid',skill:'shape'};
expect('first-concept-accepted',helper.accept(shape,counts,limits)===true,counts);expect('duplicate-concept-rejected',helper.accept(shape,counts,limits)===false,counts);
const addCases=[{prompt:'10 + 2 = ?',answer:12},{prompt:'___ + 3 = 14',answer:11},{prompt:'Tanpa mengira semula, jawapan manakah munasabah bagi 21 + 19?',answer:40},{prompt:'Aina mempunyai 12 buku dan menerima 4 buku lagi. Berapakah jumlahnya?',answer:16}];for(let i=0;i<4;i++)expect(`operation-cap-${i}`,helper.accept({...addCases[i],skill:`s${i}`},counts,limits)===true,counts);
expect('operation-cap-reject',helper.accept({prompt:'90 + 8 = ?',answer:98,skill:'s5'},counts,limits)===false,counts);

const ctx={console,Math};ctx.window=ctx;ctx.sess={questionFingerprints:[],questionHistory:[],recent:[],mode:'practice'};vm.createContext(ctx);
const files=['data/kssr/knowledge-graph.js','data/kssr/alignment-v3.9.0.js','questions/helpers.js','questions/d1/core.js',...Array.from({length:8},(_,i)=>`questions/d2/topic-${i+1}.js`),'questions/d3/core.js','questions/d4/core.js','questions/d5/core.js','questions/d6/core.js','questions/kssr-archetypes-v3.9.0.js','questions/kssr-content-v3.11.js','questions/index.js'];for(const file of files)vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),ctx,{filename:file});vm.runInContext('globalThis.skills=GRAPH.skills;globalThis.generateOne=generate',ctx);
const visual=/<(?:svg|img|canvas|table)\b|moneyVisual|clockFace|barChart|pictureGraph|coordinateGrid|shapeVisual|dataChart/i;
let scenarios=0;for(let grade=1;grade<=6;grade++){const core=ctx.skills.filter(x=>x.grade===grade&&x.role==='core');for(let offset=0;offset<Math.min(4,core.length);offset++){const pool=Array.from({length:Math.min(10,core.length)},(_,i)=>core[(offset+i)%core.length]);for(const target of [20,40]){const selected=[],seen=new Set(),tally={skill:{},format:{},operation:{},concept:{}},caps={skill:Math.max(3,Math.ceil(target/pool.length)+1),format:Math.max(3,Math.ceil(target/7)),operation:Math.max(4,Math.ceil(target/5))},relaxedCaps={skill:caps.skill+Math.ceil(target/10),format:caps.format+1,operation:caps.operation+Math.ceil(target/10)};ctx.sess.questionFingerprints=[];ctx.sess.questionHistory=[];let guard=0;while(selected.length<target&&guard++<target*90){const skill=pool[guard%pool.length],q=ctx.generateOne(skill.id,{evidence:5,confidence:60,mastery:60,correct:4,wrong:1}),prompt=String(q.prompt||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim(),key=prompt.toLowerCase();if(!prompt||visual.test(String(q.prompt||''))||seen.has(key))continue;const item={prompt,answer:q.answer,skill:skill.id},active=guard>target*55?relaxedCaps:caps;if(!helper.accept(item,tally,active))continue;seen.add(key);selected.push(item)}scenarios++;if(selected.length<target)failures.push({name:'unable-to-fill-balanced-sheet',grade,offset,target,selected:selected.length,caps,relaxedCaps,tally});for(const [key,value] of Object.entries(tally.operation))if(value>relaxedCaps.operation)failures.push({name:'operation-cap-exceeded',grade,target,key,value,cap:relaxedCaps.operation});for(const [key,value] of Object.entries(tally.format))if(value>relaxedCaps.format)failures.push({name:'format-cap-exceeded',grade,target,key,value,cap:relaxedCaps.format});for(const [key,value] of Object.entries(tally.concept))if(value>1)failures.push({name:'concept-duplicate',grade,target,key,value})}}}
const report={status:failures.length?'fail':'pass',scenarios,failures};console.log(JSON.stringify(report,null,2));process.exitCode=failures.length?1:0;
