const fs=require('fs'),assert=require('assert');
const js=fs.readFileSync('js/world-response-v3.21.0.js','utf8');
const css=fs.readFileSync('css/world-response-v3.21.0.css','utf8');
const pwa=fs.readFileSync('js/pwa.js','utf8');
const sw=fs.readFileSync('sw.js','utf8');
assert(/const VERSION='3\.21\.0'/.test(js),'world response version missing');
assert(/SECURE_MASTERY=85/.test(js)&&/SECURE_CONFIDENCE=70/.test(js)&&/SECURE_EVIDENCE=4/.test(js)&&/SECURE_STABILITY=55/.test(js),'learning proof thresholds missing');
assert(/PAContentIntegrity\?\.skillIntegrityReady/.test(js),'world progression must respect competency integrity');
assert(/Math\.max\(previous,measured\.stage\)/.test(js),'world milestones must be monotonic');
assert(/db\.worldResponse/.test(js),'world state must persist with the learner profile');
assert(!/addCoins\(|addXp\(|streak/.test(js),'world response must not be driven by rewards or streaks');
assert(/PETA DUNIA/.test(js)&&/DUNIA BERTINDAK BALAS/.test(js),'world feedback UI missing');
assert(/prefers-reduced-motion:reduce/.test(css),'reduced-motion support missing');
assert(/const WORLD_RESPONSE_VERSION='3\.21\.0'/.test(pwa),'PWA loader missing world response version');
assert(/world-response-v3\.21\.0\.js/.test(sw)&&/world-response-v3\.21\.0\.css/.test(sw),'service worker missing world response files');
console.log('PASS World Response to Learning v3.21.0 invariants');
