const fs=require('fs'),vm=require('vm'),assert=require('assert');
const code=fs.readFileSync('js/world-response-v3.21.0.js','utf8');
const skills=[{id:'A',grade:2,chapter:1},{id:'B',grade:2,chapter:1},{id:'C',grade:2,chapter:2},{id:'D',grade:2,chapter:2},{id:'LOCK',grade:2,chapter:3}];
const GRAPH={skills},META=Object.fromEntries(skills.map(x=>[x.id,x]));
const strong=()=>({mastery:90,confidence:80,evidence:5,stability:70,competencies:{core:{clean:1}}});
const states={A:strong(),B:{mastery:50,confidence:50,evidence:4,stability:40,competencies:{}},C:strong(),D:strong(),LOCK:strong()};
const version={textContent:''},html={dataset:{}},body={dataset:{screen:'game'},appendChild(){}},document={documentElement:html,body,querySelector(sel){if(sel==='.loginVersion')return version;return null},querySelectorAll(){return[]},getElementById(){return null},createElement(){return{className:'',dataset:{},style:{setProperty(){}},classList:{add(){},remove(){},contains(){return true}},setAttribute(){},querySelector(){return null},querySelectorAll(){return[]},appendChild(){},insertBefore(){},innerHTML:''}}};
let saves=0;const db={schoolGrade:2,coreFrontier:2,skills:states,coins:999,xp:9999};
const ctx={console,window:null,document,Date,Math,setTimeout:fn=>0,clearTimeout(){},GRAPH,META,db,scoreState:id=>states[id],save:()=>saves++,sess:{devBankTest:false},renderHub:()=>{},renderMissions:()=>{},recordMissionAnswer:()=>{}};ctx.window=ctx;
ctx.PAContentIntegrity={skillIntegrityReady:id=>id!=='B'||!!states.B.competencies?.core?.clean};
vm.runInNewContext(code,ctx,{filename:'world-response-v3.21.0.js'});
assert.equal(version.textContent,'Pahlawan Angka · v3.21.0');
assert.equal(ctx.PAWorldResponse.skillSecure('A'),true);
assert.equal(ctx.PAWorldResponse.skillSecure('B'),false);
let initial=ctx.PAWorldResponse.chapterState('1');assert.equal(initial.stage,2,'half of chapter skills should enter restoring stage');
assert.equal(ctx.PAWorldResponse.chapterState('2').stage,3,'two secure skills should fully restore chapter');
assert.equal(ctx.PAWorldResponse.chapterState('3').stage,0,'future locked chapter must not restore');
assert.equal(db.worldResponse.events.length,0,'first migration must not spam retrospective celebrations');
states.B={...strong()};db.skills.B=states.B;
let changed=ctx.PAWorldResponse.evaluate();assert.equal(changed.length,1);assert.equal(changed[0].stage,3);assert.equal(db.worldResponse.events.length,1,'new proof should queue one world event');
states.A={mastery:20,confidence:20,evidence:8,stability:10,competencies:{}};db.skills.A=states.A;ctx.PAWorldResponse.evaluate();
assert.equal(ctx.PAWorldResponse.chapterState('1').stage,3,'restored world milestone must not regress after a later mistake');
const before=db.worldResponse.landmarks['1'].bestStage;db.coins+=10000;db.xp+=10000;ctx.PAWorldResponse.evaluate();assert.equal(db.worldResponse.landmarks['1'].bestStage,before,'coins/xp must not affect world stage');
assert(saves>=1,'world advancement must persist');
console.log('PASS World Response to Learning v3.21.0 runtime integration');
