const fs=require('fs'),assert=require('assert');
const js=fs.readFileSync('questions/kssr-year6-space-data-v3.23.0.js','utf8');
const css=fs.readFileSync('css/kssr-year6-space-data-v3.23.0.css','utf8');
const pwa=fs.readFileSync('js/pwa.js','utf8');
const sw=fs.readFileSync('sw.js','utf8');

assert(/const VERSION='3\.23\.0'/.test(js));
assert(/const RETIRED=\['D6\.AREA','D6\.DATA'\]/.test(js),'legacy D6 AREA/DATA retirement missing');
for(const id of ['D6.ANGLE','D6.CIRCLE','D6.SPACE_PROBLEM','D6.PIE','D6.DATA_PROBLEM'])assert(js.includes(`id:'${id}'`),`new node missing ${id}`);
assert(/kssrStandards:\['6\.1\.1','6\.1\.2'\]/.test(js),'angle standards missing');
assert(/kssrStandards:\['6\.2\.1','6\.2\.2'\]/.test(js),'circle standards missing');
assert(/kssrStandards:\['8\.1\.1'\]/.test(js),'pie standard missing');
assert(/kssrStandards:\['8\.2\.1','8\.2\.2'\]/.test(js),'chance standards missing');
assert(/kssrStandards:\['8\.3\.1'\]/.test(js),'data problem standard missing');
assert(/domain:'Koordinat'.*kssrStandards:\['7\.1\.1'\]/s.test(js),'D6 coordinate unit correction missing');
assert(/'D6\.ANGLE':\[\['angle_measure_protractor'\],\['angle_construct_identify'\],\['polygon_regular_measure'\]\]/.test(js),'angle mandatory evidence missing');
assert(/'D6\.PIE':\[\['pie_complete_angle'\],\['pie_complete_quantity'\],\['pie_interpret'\]\]/.test(js),'pie mandatory evidence missing');
assert(/'D6\.PROB':\[\['chance_possible_reason'\],\['chance_scale_reason'\]\]/.test(js),'qualitative chance mandatory evidence missing');
assert(!/prob_fraction/.test(js),'legacy numeric probability archetype leaked into repair');
assert(!/pecahan kebarangkalian/.test(js.toLowerCase()),'numeric probability terminology leaked');
assert(!/7\/8/.test(js),'fractional chance shortcut leaked into qualitative hint');
assert(!/id==='D6\.AREA'/.test(js),'retired D6.AREA still generated');
assert(!/id==='D6\.DATA'/.test(js),'retired D6.DATA still generated');
assert(!/Isipadu = panjang × lebar × tinggi|kuboid .*Isipadu/i.test(js),'cuboid-volume content remained in new Year6 Space path');
assert(/45°/.test(js)&&/90°/.test(js)&&/180°/.test(js),'required pie-sector angle set missing');
assert(/protractorSvg/.test(js)&&/circleSvg/.test(js)&&/pieSvg/.test(js)&&/bagVisual/.test(js),'required Year6 diagrams missing');
assert(/y6-ball-red\{fill:#d9939a/.test(css)&&/y6-ball-blue\{fill:#8faed1/.test(css)&&/y6-ball-green\{fill:#9fc4ad/.test(css),'bag colours not visually distinguishable');

assert(/const APP_VERSION='3\.23\.0'/.test(pwa));
assert(/const DEPTH_VERSION='3\.22\.0'/.test(pwa));
assert(/const Y6_REPAIR_VERSION='3\.23\.0'/.test(pwa));
const depthPos=pwa.indexOf('questions/kssr-assessment-depth-v${DEPTH_VERSION}.js');
const y6Pos=pwa.indexOf('questions/kssr-year6-space-data-v${Y6_REPAIR_VERSION}.js');
assert(depthPos>=0&&y6Pos>depthPos,'Year6 repair must load after v3.22 depth');
assert(/loadScript\(depthJs[^\n]+loadY6Repair/.test(pwa),'dynamic load order depth -> Year6 repair missing');
assert(/year6SpaceData:Y6_REPAIR_VERSION/.test(pwa),'release metadata missing Year6 repair');
assert(/CACHE_NAME='pahlawan-angka-v3\.23\.0'/.test(sw));
assert(/kssr-year6-space-data-v3\.23\.0\.css/.test(sw)&&/kssr-year6-space-data-v3\.23\.0\.js/.test(sw),'service worker repair assets missing');
assert(!/world-response-v3\.21\.0/.test(pwa+sw),'World Response returned');
console.log('PASS v3.23.0 static: Year6 Space/Data graph, contracts, qualitative chance, load order and cache');
