(()=>{
'use strict';
const PRIVACY_VERSION='2026-08-22',TERMS_VERSION='2026-08-22',PENDING_KEY='pa_pending_guardian_consent_v1';
const $=id=>document.getElementById(id),esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
function ensureOverlay(){let o=$('paTrustOverlay');if(o)return o;o=document.createElement('div');o.id='paTrustOverlay';o.className='paTrustOverlay';o.setAttribute('role','dialog');o.setAttribute('aria-modal','true');document.body.appendChild(o);return o}
function privacyMarkup(){return `<small>PAHLAWAN ANGKA</small><h2>Notis Privasi</h2><p>Tarikh berkuat kuasa: 22 Ogos 2026</p><h3>Data yang dikumpulkan</h3><ul><li>Akaun penjaga: ID akaun dan e-mel Google.</li><li>Profil anak: nama paparan, darjah dan pilihan pahlawan.</li><li>Pembelajaran: soalan dijawab, betul atau belum tepat, penggunaan petunjuk, masa respons, kemajuan dan masa bermain aktif.</li><li>Maklum balas beta: mesej, versi aplikasi, skrin dan maklumat asas browser/peranti.</li></ul><p>Kami tidak meminta tarikh lahir, alamat rumah, nombor telefon atau e-mel anak.</p><h3>Tujuan</h3><p>Data digunakan untuk menyimpan kemajuan, menyesuaikan latihan, menghasilkan laporan penjaga, mengawal masa bermain dan membaiki aplikasi.</p><h3>Penyimpanan dan perkongsian</h3><p>Data disimpan melalui penyedia infrastruktur seperti Supabase dan hos aplikasi, yang mungkin memproses data di luar Malaysia. Kami tidak menjual data atau menggunakan data anak untuk pengiklanan.</p><h3>Tempoh dan hak penjaga</h3><p>Data disimpan selagi akaun digunakan atau diperlukan untuk menyediakan perkhidmatan. Penjaga boleh meminta akses, pembetulan atau pemadaman melalui <b>affierul@gmail.com</b>. Permintaan pemadaman akan diproses dalam masa 30 hari, tertakluk kepada salinan keselamatan dan kewajipan undang-undang.</p>`}
function termsMarkup(){return `<small>PAHLAWAN ANGKA</small><h2>Terma Beta</h2><p>Tarikh berkuat kuasa: 22 Ogos 2026</p><h3>Penggunaan oleh keluarga</h3><p>Akaun mesti diurus oleh ibu bapa atau penjaga. Anak menggunakan profil di bawah akaun penjaga dan tidak memerlukan akaun sendiri.</p><h3>Tujuan pendidikan</h3><p>Pahlawan Angka ialah alat latihan sokongan. Analisis, cadangan Cikgu Dimensi dan laporan bukan diagnosis klinikal, keputusan peperiksaan atau pengganti nasihat guru.</p><h3>Versi beta</h3><p>Ciri, kandungan dan progress boleh berubah ketika beta. Tiada pembayaran diproses dalam beta ini. Kami akan cuba melindungi progress, tetapi penjaga digalakkan memuat turun laporan penting.</p><h3>Penggunaan wajar</h3><p>Jangan cuba mengakses akaun keluarga lain, mengganggu sistem, menjual semula akses atau menyalin aset dan kandungan aplikasi untuk penerbitan semula.</p><h3>Maklum balas</h3><p>Maklum balas boleh digunakan untuk menambah baik produk tanpa mendedahkan identiti anak kepada umum. Hubungi <b>affierul@gmail.com</b> jika perlukan bantuan.</p>`}
function openLegal(type,mandatory=false){const o=ensureOverlay(),privacy=type==='privacy',content=mandatory?`${privacyMarkup()}<hr>${termsMarkup()}`:(privacy?privacyMarkup():termsMarkup());o.dataset.mandatory=mandatory?'1':'0';o.innerHTML=`<section class="paTrustPanel">${mandatory?'':`<button class="paTrustClose" type="button" onclick="PABetaTrust.close()" aria-label="Tutup">×</button>`}${content}${mandatory?'<button class="paTrustAccept" type="button" onclick="PABetaTrust.acceptMandatory()">Saya setuju dengan Notis Privasi dan Terma Beta</button>':''}</section>`;o.classList.add('show')}
function close(){const o=$('paTrustOverlay');if(o?.dataset.mandatory==='1')return;o?.classList.remove('show')}
function mountLogin(){const host=document.querySelector('.googleAuthPublic');if(!host||$('guardianConsent'))return;const button=$('googleAuthButton');button?.insertAdjacentHTML('beforebegin',`<label class="paConsentRow"><input id="guardianConsent" type="checkbox"><span>Saya ialah ibu bapa/penjaga dan bersetuju dengan <a href="#" onclick="event.preventDefault();PABetaTrust.openLegal('privacy')">Notis Privasi</a> serta <a href="#" onclick="event.preventDefault();PABetaTrust.openLegal('terms')">Terma Beta</a>.</span></label>`);host.insertAdjacentHTML('beforeend',`<div class="paTrustLinks"><button type="button" onclick="PABetaTrust.openLegal('privacy')">Privasi</button><span>·</span><button type="button" onclick="PABetaTrust.openLegal('terms')">Terma Beta</button></div>`)}
function prepareOAuth(){if(!$('guardianConsent')?.checked)return{ok:false,message:'Tandakan persetujuan penjaga sebelum meneruskan dengan Google.'};localStorage.setItem(PENDING_KEY,JSON.stringify({privacy:PRIVACY_VERSION,terms:TERMS_VERSION,at:Date.now()}));return{ok:true}}
async function ensureConsent(client,user){if(!client||!user)return false;const {data,error}=await client.from('guardian_consents').select('privacy_version,terms_version').eq('user_id',user.id).maybeSingle();if(error)throw error;if(data?.privacy_version===PRIVACY_VERSION&&data?.terms_version===TERMS_VERSION)return true;let pending=null;try{pending=JSON.parse(localStorage.getItem(PENDING_KEY)||'null')}catch(_){}if(pending?.privacy===PRIVACY_VERSION&&pending?.terms===TERMS_VERSION&&Date.now()-Number(pending.at||0)<3600000){await saveConsent(client,user);return true}openLegal('privacy',true);return false}
async function saveConsent(client,user){const {error}=await client.from('guardian_consents').upsert({user_id:user.id,privacy_version:PRIVACY_VERSION,terms_version:TERMS_VERSION,consented_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)throw error;localStorage.removeItem(PENDING_KEY)}
async function acceptMandatory(){const state=window.PACloud?.state,button=document.querySelector('.paTrustAccept');if(!state?.client||!state.user)return;if(button){button.disabled=true;button.textContent='Menyimpan…'}try{await saveConsent(state.client,state.user);$('paTrustOverlay')?.classList.remove('show');await window.PACloud?.resumeAfterConsent?.()}catch(error){if(button){button.disabled=false;button.textContent='Cuba sekali lagi'}console.warn('Consent save failed',error)}}
function feedbackMarkup(){return `<small>BETA 50 KELUARGA</small><h2>Beri maklum balas</h2><p>Ceritakan apa yang berlaku atau apa yang mengelirukan. Jangan masukkan nama penuh atau jawapan anak.</p><form class="paFeedbackForm" onsubmit="PABetaTrust.submitFeedback(event)"><label>Jenis maklum balas<select id="paFeedbackCategory"><option value="bug">Masalah teknikal</option><option value="confusing">Sukar difahami</option><option value="content">Soalan atau kandungan</option><option value="suggestion">Cadangan</option><option value="other">Lain-lain</option></select></label><label>Mesej<textarea id="paFeedbackMessage" minlength="10" maxlength="2000" required placeholder="Apa yang berlaku? Apa yang anda jangka akan berlaku?"></textarea></label><p class="paFeedbackNote">Konteks teknikal sahaja akan dilampirkan: versi aplikasi, skrin semasa dan jenis browser.</p><div id="paFeedbackError" class="paFeedbackError"></div><button id="paFeedbackSubmit" class="paTrustAccept" type="submit">Hantar maklum balas</button></form>`}
function openFeedback(){const o=ensureOverlay();o.dataset.mandatory='0';o.innerHTML=`<section class="paTrustPanel"><button class="paTrustClose" type="button" onclick="PABetaTrust.close()" aria-label="Tutup">×</button>${feedbackMarkup()}</section>`;o.classList.add('show')}
async function submitFeedback(event){event.preventDefault();const state=window.PACloud?.state,message=String($('paFeedbackMessage')?.value||'').trim(),category=$('paFeedbackCategory')?.value||'other',button=$('paFeedbackSubmit'),errorBox=$('paFeedbackError');if(message.length<10){errorBox.textContent='Tulis sekurang-kurangnya 10 aksara.';return}button.disabled=true;button.textContent='Menghantar…';errorBox.textContent='';const payload={user_id:state?.user?.id,child_id:state?.childId||null,category,message,app_version:String(window.PA_APP_VERSION||'unknown'),screen:document.body.dataset.screen||null,client_context:{platform:navigator.platform||'',language:navigator.language||'',viewport:`${innerWidth}x${innerHeight}`,online:navigator.onLine}};try{const {error}=await state.client.from('beta_feedback').insert(payload);if(error)throw error;button.textContent='Berjaya dihantar ✓';$('paFeedbackMessage').value='';setTimeout(close,900)}catch(error){console.warn('Feedback submit failed',error);errorBox.textContent='Belum dapat dihantar. Cuba semula sebentar lagi.';button.disabled=false;button.textContent='Hantar maklum balas'}}
function mountSettings(){const host=$('settingsTab');if(!host||host.querySelector('.paTrustCard'))return;host.insertAdjacentHTML('beforeend',`<section class="paTrustCard"><h3>Bantuan & privasi</h3><p>Laporkan masalah beta atau semak cara data keluarga digunakan.</p><div class="paTrustActions"><button type="button" onclick="PABetaTrust.openFeedback()">Lapor masalah</button><button type="button" onclick="PABetaTrust.openLegal('privacy')">Notis Privasi</button><button type="button" onclick="PABetaTrust.openLegal('terms')">Terma Beta</button></div></section>`)}
function boot(){mountLogin();mountSettings();new MutationObserver(()=>mountSettings()).observe(document.body,{childList:true,subtree:true})}
window.PABetaTrust={prepareOAuth,ensureConsent,acceptMandatory,openLegal,openFeedback,submitFeedback,close,mountSettings,versions:{privacy:PRIVACY_VERSION,terms:TERMS_VERSION}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
