// Isolated guest demo: 10 questions, no saved progress or cloud writes.
(()=>{'use strict';
const st={grade:2,hero:'wira',active:false,db:null,sess:null,items:[],results:[],pool:[]};
function mount(){const host=document.querySelector('#login .cloudLoginCard, #login .loginCard');if(!host||document.getElementById('paDemoButton'))return;const b=document.createElement('button');b.id='paDemoButton';b.className='btn secondary paDemoButton';b.type='button';b.innerHTML='<b>⚔ Cuba Demo</b><small>10 soalan · tanpa akaun</small>';b.onclick=open;host.insertBefore(b,host.querySelector('.loginDivider'));document.body.insertAdjacentHTML('beforeend',`<div id="paDemoOverlay" class="paDemoOverlay hidden" role="dialog" aria-modal="true"><section class="paDemoCard"><button class="paDemoClose" onclick="PADemo.close()">×</button><div class="eyebrow">DEMO IBU BAPA</div><h2>Cuba satu misi ringkas</h2><p>10 soalan campuran, dua cabaran adaptif dan mini boss. Tiada progres atau ganjaran disimpan.</p><label>Darjah<select id="paDemoGrade">${[1,2,3,4,5,6].map(n=>`<option value="${n}" ${n===2?'selected':''}>Darjah ${n}</option>`).join('')}</select></label><div class="paDemoHeroes">${['wira','bunga','sidma'].map((id,i)=>`<button data-demo-hero="${id}" class="${i?'':'active'}" onclick="PADemo.hero('${id}')"><img src="${HEROES[id].profile||HEROES[id].idle}" alt=""><b>${HEROES[id].name}</b></button>`).join('')}</div><button class="btn primary" onclick="PADemo.start()">Mulakan Demo</button></section></div>`)}
function open(){document.getElementById('paDemoOverlay')?.classList.remove('hidden')}function close(){document.getElementById('paDemoOverlay')?.classList.add('hidden')}function hero(id){st.hero=id;document.querySelectorAll('[data-demo-hero]').forEach(b=>b.classList.toggle('active',b.dataset.demoHero===id))}
function demoDb(){return{name:'Demo',schoolGrade:st.grade,hero:st.hero,demoMode:true,skills:{},coreFrontier:8,focus:null,logs:[],created:Date.now(),xp:0,coins:0,level:1,completedMissions:{},chapterStars:{},activeMissionChapter:null,rewards:{pets:{},auras:{},badges:{},equippedPet:null,equippedAura:null}}}
function start(){st.grade=Number(document.getElementById('paDemoGrade')?.value||2);st.items=[];st.results=[];st.active=true;const demoSession={demoMode:true,hp:20,ehp:12,streak:0,q:null,start:0,hint:false,enemy:1,recent:[],mode:'demo',missionChapter:null,missionAnswered:0,missionCorrect:0,missionHints:0,missionSkills:{},missionFinished:false,devBankTest:false,coachAdaptive:false,questionFingerprints:[],bossActive:false,bossDefeated:false,bossQuestionsAnswered:0};const previous=swapDemoState(demoDb(),demoSession);st.db=previous.db;st.sess=previous.sess;initAll();ensureProgression();st.pool=GRAPH.skills.filter(m=>m.grade===st.grade&&m.role==='core');if(!st.pool.length)st.pool=GRAPH.skills.filter(m=>m.grade===st.grade);close();applyHeroToBattle();updateMissionHud();nextQ();battle();screen('game')}
function chooseSkill(){const n=Number(sess.missionAnswered||0),available=st.pool.filter(m=>!sess.recent.slice(-3).includes(m.id)),pool=available.length?available:st.pool;if(n<7)return pool[n%pool.length]?.id||st.pool[0].id;const weak=[...st.pool].sort((a,b)=>(sess.missionSkills[a.id]||0)-(sess.missionSkills[b.id]||0));return weak[(n-7)%Math.min(3,weak.length)]?.id||st.pool[0].id}
function record(skill,ok,usedHint){
 const retried=!!sess.retryState;
 st.results.push({skill,ok:!!ok,firstCorrect:!!ok&&!retried,usedHint:!!usedHint,errors:(retried?1:0)+(ok?0:1),attempts:retried?2:1,hintOpens:Number(sess.hintLevel||0),seconds:Math.max(0,(performance.now()-sess.start)/1000),label:questionLearningTitle(META[skill],sess.q),competency:sess.q.competencyId||null});
 st.items.push({prompt:sess.q.prompt,answer:sess.q.answer,hint:sess.q.hint,skill});
}
function summary(){
 const total=st.results.length,first=st.results.filter(x=>x.firstCorrect).length,correct=st.results.filter(x=>x.ok).length,hints=st.results.filter(x=>x.usedHint).length;
 return {total,first,correct,hints,corrected:st.results.filter(x=>x.ok&&!x.firstCorrect).length,correctedWithHint:st.results.filter(x=>x.ok&&!x.firstCorrect&&x.usedHint).length,independent:st.results.filter(x=>x.firstCorrect&&!x.usedHint).length};
}
function focusSummary(){
 const groups=new Map();
 st.results.forEach(r=>{if(!r.errors&&!r.usedHint)return;const key=r.skill+':'+(r.competency||'');if(!groups.has(key))groups.set(key,{label:r.label,skill:r.skill,errors:0,hints:0,corrected:0,correctedWithHint:0,unresolved:0});const g=groups.get(key);g.errors+=r.errors;g.hints+=Number(r.usedHint);g.corrected+=Number(r.ok&&r.errors>0);g.correctedWithHint+=Number(r.ok&&r.errors>0&&r.usedHint);g.unresolved+=Number(!r.ok)});
 const ranked=[...groups.values()].sort((a,b)=>(b.unresolved*4+b.errors*2+b.hints)-(a.unresolved*4+a.errors*2+a.hints));return ranked.filter((g,i,all)=>all.findIndex(x=>kidFocusLabel(x.label).toLowerCase()===kidFocusLabel(g.label).toLowerCase())===i).slice(0,3);
}
function friendlyMessage(report){if(report.first===report.total)return 'Hebat! Semua jawapan kamu terus betul.';if(report.correct===report.total)return 'Bagus! Kamu tak mengalah dan berjaya baiki jawapan.';if(report.correct>=Math.ceil(report.total/2))return 'Bagus! Sedikit lagi untuk kuatkan kuasa Matematik kamu.';return 'Tak apa, cuba lagi. Setiap latihan buat kamu makin kuat!'}
function kidFocusLabel(value){return String(value||'Matematik').replace(/^Model\s+/i,'').replace(/^Operasi Gabungan Perpuluhan$/i,'Tambah dan tolak perpuluhan').replace(/\s+dalam Situasi$/i,' dalam cerita')}
function summaryMarkup(report,focus){const safe=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch])),top=focus.slice(0,3);return `<div class="paDemoFocusLead">${top.length?'Jom latih lagi:':'Kuasa Matematik kamu semakin hebat!'}</div>${top.length?`<div class="paDemoFocusChips">${top.map(x=>`<span>${safe(kidFocusLabel(x.label))}</span>`).join('')}</div>`:''}<div class="paDemoEncouragement">${safe(friendlyMessage(report))}</div><small class="paDemoScreeningNote">Ini baru cabaran ringkas 10 soalan.</small>`}
function restore(){swapDemoState(st.db,st.sess||{hp:20,ehp:12,streak:0,q:null,start:0,hint:false,enemy:1,recent:[],mode:'calibrate'});st.active=false}
function standardButtons(hidden){document.querySelectorAll('#result .resultCard > button.btn').forEach(b=>b.classList.toggle('hidden',hidden))}
function finish(){if(!st.active||sess.missionFinished)return;sess.missionFinished=true;const report=summary(),focus=focusSummary();restore();const result=document.getElementById('result');result.classList.add('paDemoResult');result.querySelector('.eyebrow').textContent='DEMO SELESAI';document.getElementById('resultTitle').textContent='Hebat, misi selesai!';document.getElementById('resultStars').textContent='';document.getElementById('resultScore').innerHTML=`<div class="paDemoScoreGrid"><span><b>${report.first}</b><small>Terus betul</small></span><span><b>${report.corrected}</b><small>Cuba lagi &amp; berjaya</small></span><span><b>${report.total-report.correct}</b><small>Belum berjaya</small></span></div>${report.hints?`<div class="paDemoHintUsed">💡 Petunjuk membantu pada ${report.hints} soalan</div>`:''}`;document.getElementById('resultRewards').innerHTML='<span>Demo ini tidak simpan syiling atau XP</span>';document.querySelector('#result .coachNote b').textContent='Misi seterusnya';document.getElementById('resultCoach').innerHTML=summaryMarkup(report,focus);let a=document.getElementById('paDemoResultActions');if(!a){a=document.createElement('div');a.id='paDemoResultActions';a.className='paDemoResultActions';document.querySelector('#result .resultCard').appendChild(a)}a.innerHTML='<button class="btn primary" onclick="PADemo.createProfile()">Cipta Profil & Mulakan Latihan</button><button id="paDemoWorksheet" class="btn secondary" onclick="PADemo.worksheet()">Muat Turun Lembaran Kerja</button><button class="btn secondary" onclick="PADemo.feedback()">Hantar Maklum Balas</button><button class="btn ghost" onclick="PADemo.back()">Kembali ke Log Masuk</button>';screen('result');standardButtons(true);worksheetButton()}
function resetResult(){const result=document.getElementById('result');result?.classList.remove('paDemoResult');const eyebrow=result?.querySelector('.eyebrow');if(eyebrow)eyebrow.textContent='MISSION COMPLETE';const coach=result?.querySelector('.coachNote b');if(coach)coach.textContent='Coach seterusnya'}
function createProfile(){document.getElementById('paDemoResultActions')?.remove();standardButtons(false);resetResult();screen('login');window.PACloud?.signInGoogle?.()}function back(){document.getElementById('paDemoResultActions')?.remove();standardButtons(false);resetResult();screen('login')}function worksheet(){window.PAParentTools?.demoWorksheet?.(st.items,st.grade)}
function worksheetButton(){const b=document.getElementById('paDemoWorksheet');if(!b)return;const count=window.PAParentTools?.demoPrintableItems?.(st.items)?.length||0;b.disabled=!count;b.textContent=count?`Muat Turun Lembaran Kerja (${count} soalan terpilih)`:'Tiada soalan sesuai untuk cetakan';b.title='Soalan yang memerlukan rajah atau graf tidak disertakan dalam versi cetakan ini.'}
function feedback(){const body=`Darjah dicuba: ${st.grade}\nBetul percubaan pertama: ${summary().first}/${summary().total}\nBetul akhir sesi: ${summary().correct}/${summary().total}\nSoalan menggunakan petunjuk: ${summary().hints}\nVersi aplikasi: ${window.PA_APP_VERSION||'-'}\n\nMaklum balas saya:\n`;location.href=`mailto:affierul@gmail.com?subject=${encodeURIComponent('Maklum Balas Demo Pahlawan Angka')}&body=${encodeURIComponent(body)}`}
window.PADemo={mount,open,close,hero,start,chooseSkill,record,summary,finish,worksheet,feedback,createProfile,back};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();})();
