// Isolated guest demo: 10 questions, no saved progress or cloud writes.
(()=>{'use strict';
const st={grade:2,hero:'wira',active:false,db:null,sess:null,items:[],results:[],pool:[]},clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
function mount(){const host=document.querySelector('#login .cloudLoginCard, #login .loginCard');if(!host||document.getElementById('paDemoButton'))return;const b=document.createElement('button');b.id='paDemoButton';b.className='btn secondary paDemoButton';b.type='button';b.innerHTML='<b>⚔ Cuba Demo</b><small>10 soalan · tanpa akaun</small>';b.onclick=open;host.insertBefore(b,host.querySelector('.loginDivider'));document.body.insertAdjacentHTML('beforeend',`<div id="paDemoOverlay" class="paDemoOverlay hidden" role="dialog" aria-modal="true"><section class="paDemoCard"><button class="paDemoClose" onclick="PADemo.close()">×</button><div class="eyebrow">DEMO IBU BAPA</div><h2>Cuba satu misi ringkas</h2><p>10 soalan campuran, dua cabaran adaptif dan mini boss. Tiada progres atau ganjaran disimpan.</p><label>Darjah<select id="paDemoGrade">${[1,2,3,4,5,6].map(n=>`<option value="${n}" ${n===2?'selected':''}>Darjah ${n}</option>`).join('')}</select></label><div class="paDemoHeroes">${['wira','bunga','sidma'].map((id,i)=>`<button data-demo-hero="${id}" class="${i?'':'active'}" onclick="PADemo.hero('${id}')"><img src="${HEROES[id].profile||HEROES[id].idle}" alt=""><b>${HEROES[id].name}</b></button>`).join('')}</div><button class="btn primary" onclick="PADemo.start()">Mulakan Demo</button></section></div>`)}
function open(){document.getElementById('paDemoOverlay')?.classList.remove('hidden')}function close(){document.getElementById('paDemoOverlay')?.classList.add('hidden')}function hero(id){st.hero=id;document.querySelectorAll('[data-demo-hero]').forEach(b=>b.classList.toggle('active',b.dataset.demoHero===id))}
function demoDb(){return{name:'Demo',schoolGrade:st.grade,hero:st.hero,demoMode:true,skills:{},coreFrontier:8,focus:null,logs:[],created:Date.now(),xp:0,coins:0,level:1,completedMissions:{},chapterStars:{},activeMissionChapter:null,rewards:{pets:{},auras:{},badges:{},equippedPet:null,equippedAura:null}}}
function start(){st.grade=Number(document.getElementById('paDemoGrade')?.value||2);st.items=[];st.results=[];st.active=true;const demoSession={demoMode:true,hp:20,ehp:12,streak:0,q:null,start:0,hint:false,enemy:1,recent:[],mode:'demo',missionChapter:null,missionAnswered:0,missionCorrect:0,missionHints:0,missionSkills:{},missionFinished:false,devBankTest:false,coachAdaptive:false,questionFingerprints:[],bossActive:false,bossDefeated:false,bossQuestionsAnswered:0};const previous=swapDemoState(demoDb(),demoSession);st.db=previous.db;st.sess=previous.sess;initAll();ensureProgression();st.pool=GRAPH.skills.filter(m=>m.grade===st.grade&&m.role==='core');if(!st.pool.length)st.pool=GRAPH.skills.filter(m=>m.grade===st.grade);close();applyHeroToBattle();updateMissionHud();nextQ();battle();screen('game')}
function chooseSkill(){const n=Number(sess.missionAnswered||0),available=st.pool.filter(m=>!sess.recent.slice(-3).includes(m.id)),pool=available.length?available:st.pool;if(n<7)return pool[n%pool.length]?.id||st.pool[0].id;const weak=[...st.pool].sort((a,b)=>(sess.missionSkills[a.id]||0)-(sess.missionSkills[b.id]||0));return weak[(n-7)%Math.min(3,weak.length)]?.id||st.pool[0].id}
function record(skill,ok){st.results.push({skill,ok});st.items.push({prompt:sess.q.prompt,answer:sess.q.answer,hint:sess.q.hint,skill})}
function restore(){swapDemoState(st.db,st.sess||{hp:20,ehp:12,streak:0,q:null,start:0,hint:false,enemy:1,recent:[],mode:'calibrate'});st.active=false}
function standardButtons(hidden){document.querySelectorAll('#result .resultCard > button.btn').forEach(b=>b.classList.toggle('hidden',hidden))}
function finish(){if(!st.active||sess.missionFinished)return;sess.missionFinished=true;const correct=sess.missionCorrect||0,accuracy=Math.round(correct/10*100),grade=st.grade,items=clone(st.items),results=clone(st.results),skills=Object.entries(sess.missionSkills||{}).sort((a,b)=>a[1]-b[1]),focus=META[skills[0]?.[0]]?.title||'latihan campuran';restore();st.grade=grade;st.items=items;st.results=results;document.getElementById('resultTitle').textContent=accuracy>=80?'Demo Hebat!':'Demo Selesai';document.getElementById('resultStars').textContent=accuracy>=80?'★★★':accuracy>=60?'★★☆':'★☆☆';document.getElementById('resultScore').textContent=`${correct}/10 betul · ${accuracy}%`;document.getElementById('resultRewards').innerHTML='<span>Demo tanpa syiling atau XP</span>';document.getElementById('resultCoach').textContent=`Cadangan: kukuhkan ${focus}. Cipta profil untuk simpan kemajuan sebenar.`;standardButtons(true);let a=document.getElementById('paDemoResultActions');if(!a){a=document.createElement('div');a.id='paDemoResultActions';a.className='paDemoResultActions';document.querySelector('#result .resultCard').appendChild(a)}a.innerHTML='<button class="btn primary" onclick="PADemo.createProfile()">Cipta Profil & Simpan Kemajuan</button><button class="btn secondary" onclick="PADemo.worksheet()">Muat Turun Worksheet Demo</button><button class="btn secondary" onclick="PADemo.feedback()">Hantar Maklum Balas</button><button class="btn ghost" onclick="PADemo.back()">Kembali ke Log Masuk</button>';screen('result')}
function createProfile(){document.getElementById('paDemoResultActions')?.remove();standardButtons(false);screen('login');window.PACloud?.signInGoogle?.()}function back(){document.getElementById('paDemoResultActions')?.remove();standardButtons(false);screen('login')}function worksheet(){window.PAParentTools?.demoWorksheet?.(st.items,st.grade)}
function feedback(){const body=`Darjah dicuba: ${st.grade}\nSkor demo: ${st.results.filter(x=>x.ok).length}/10\nVersi aplikasi: ${window.PA_APP_VERSION||'-'}\n\nMaklum balas saya:\n`;location.href=`mailto:affierul@gmail.com?subject=${encodeURIComponent('Maklum Balas Demo Pahlawan Angka')}&body=${encodeURIComponent(body)}`}
window.PADemo={mount,open,close,hero,start,chooseSkill,record,finish,worksheet,feedback,createProfile,back};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();})();
