const HEROES={
 wira:{name:'Wira',theme:'ice',idle:'assets/heroes/wira/idle.webp',hub:'assets/heroes/wira/hub/adventure-v1.webp',hubFx:'assets/fx/hub/wira-math-runes-v1.webp',anticipation:'assets/heroes/wira/frames/anticipation-v1.webp',auraFraming:'assets/heroes/wira/frames/aura-framing-v1.webp',attack:'assets/heroes/wira/attack.webp',followThrough:'assets/heroes/wira/frames/follow-through-v1.webp',finisher:'assets/fx/wira/finisher.webp'},
 bunga:{name:'Bunga',theme:'bloom',idle:'assets/heroes/bunga/redesign-v1/runtime/idle-master-v1.webp',hub:'assets/heroes/bunga/redesign-v1/runtime/idle-master-v1.webp',hubFx:'assets/fx/hub/bunga-fraction-bloom-v1.webp',profile:'assets/heroes/bunga/redesign-v1/runtime/profile-happy-v1.webp',anticipation:'assets/heroes/bunga/redesign-v1/runtime/kelopak-pecahan/quick-ready-v1.webp',auraFraming:'assets/heroes/bunga/redesign-v1/runtime/teorem-mekar/focus-eyes-closed-v1.webp',finisherFocus:'assets/heroes/bunga/redesign-v1/runtime/teorem-mekar/focus-eyes-closed-v1.webp',attack:'assets/heroes/bunga/redesign-v1/runtime/kelopak-pecahan/release-v1.webp',followThrough:'assets/heroes/bunga/redesign-v1/runtime/bulatan-harmoni/recovery-v1.webp',finisher:'assets/heroes/bunga/redesign-v1/runtime/teorem-mekar/fx-enemy-bloom-v1.webp',
  frames:{idleBreathe:'assets/heroes/bunga/redesign-v1/runtime/idle-breathe-v1.webp',skill1Ready:'assets/heroes/bunga/redesign-v1/runtime/kelopak-pecahan/quick-ready-v1.webp',skill1Aim:'assets/heroes/bunga/redesign-v1/runtime/kelopak-pecahan/staff-aim-v1.webp',skill1Release:'assets/heroes/bunga/redesign-v1/runtime/kelopak-pecahan/release-v1.webp',skill2Cast:'assets/heroes/bunga/redesign-v1/runtime/bulatan-harmoni/cast-start-v1.webp',skill2Charge:'assets/heroes/bunga/redesign-v1/runtime/bulatan-harmoni/levitate-charge-v1.webp',skill2Release:'assets/heroes/bunga/redesign-v1/runtime/bulatan-harmoni/remote-release-v1.webp',recovery:'assets/heroes/bunga/redesign-v1/runtime/bulatan-harmoni/recovery-v1.webp',hurt:'assets/heroes/bunga/redesign-v1/runtime/states/hurt-v1.webp',defeat:'assets/heroes/bunga/redesign-v1/runtime/states/defeat-v1.webp'},
  fx:{skill1Projectile:'assets/heroes/bunga/redesign-v1/runtime/kelopak-pecahan/fx-projectile-v1.webp',skill1Impact:'assets/heroes/bunga/redesign-v1/runtime/kelopak-pecahan/fx-impact-v1.webp',skill2Arc:'assets/heroes/bunga/redesign-v1/runtime/bulatan-harmoni/fx-charge-arc-v1.webp',skill2Impact:'assets/heroes/bunga/redesign-v1/runtime/bulatan-harmoni/fx-enemy-impact-v1.webp',finalAura:'assets/heroes/bunga/redesign-v1/runtime/teorem-mekar/fx-charge-aura-v1.webp',finalBloom:'assets/heroes/bunga/redesign-v1/runtime/teorem-mekar/fx-enemy-bloom-v1.webp',finalImpact:'assets/heroes/bunga/redesign-v1/runtime/teorem-mekar/fx-impact-end-v1.webp'}},
 sidma:{name:'Sidma',theme:'sigma',idle:'assets/heroes/sidma/idle.webp',hub:'assets/heroes/sidma/hub/adventure-v1.webp',hubFx:'assets/fx/hub/sidma-math-sigma-v1.webp',profile:'assets/heroes/sidma/profile-happy-v1.webp',anticipation:'assets/heroes/sidma/frames/attack-stance-v1.webp',auraFraming:'assets/heroes/sidma/frames/cast-start-v1.webp',finisherFocus:'assets/heroes/sidma/frames/finisher-focus-eyes-closed-v1.webp',attack:'assets/heroes/sidma/frames/release-v1.webp',followThrough:'assets/heroes/sidma/frames/recovery-v1.webp',finisher:'assets/fx/sidma/rumus-sigma/fx_sigma_impact.webp',
  frames:{attackStance:'assets/heroes/sidma/frames/attack-stance-v1.webp',castStart:'assets/heroes/sidma/frames/cast-start-v1.webp',release:'assets/heroes/sidma/frames/release-v1.webp',recovery:'assets/heroes/sidma/frames/recovery-v1.webp',skill2Dash:'assets/heroes/sidma/frames/skill2-dash-v1.webp',skill2Impact:'assets/heroes/sidma/frames/skill2-impact-v1.webp'},
  fx:{charge:'assets/fx/sidma/rumus-sigma/fx_sidma_charge.webp',projectile:'assets/fx/sidma/rumus-sigma/fx_sigma_projectile.webp',impact:'assets/fx/sidma/rumus-sigma/fx_sigma_impact.webp',impactEnd:'assets/fx/sidma/rumus-sigma/fx_sigma_impact_end.webp'}}
};
