/* Wira final v2 — enemy-side ice-electric seal, isolated from normal attacks. */
(function(){
  const TIMING={form:1080,arc:1190,compress:1360,impact:1420,end:1740};
  let timers=[];const after=(ms,fn)=>timers.push(setTimeout(fn,ms));
  function clearTimers(){timers.forEach(clearTimeout);timers=[]}
  function make(id,cls,parent,tag='div'){let el=document.getElementById(id);if(el)return el;el=document.createElement(tag);el.id=id;el.className=cls;el.setAttribute('aria-hidden','true');if(tag==='img')el.alt='';parent.appendChild(el);return el}
  function centre(arena,enemy){const a=arena.getBoundingClientRect(),e=(enemy.querySelector('.enemySpriteWrap')||enemy).getBoundingClientRect();return{x:e.left-a.left+e.width/2,y:e.top-a.top+e.height*.5,size:Math.min(a.width*.38,e.height*1.35)}}
  function position(el,p){el.style.left=p.x+'px';el.style.top=p.y+'px';el.style.setProperty('--wira-final-size',p.size+'px')}
  function ensure(){const arena=document.getElementById('battleArena');if(!arena)return null;const seal=make('wiraFrostSeal','wira-frost-seal',arena),core=make('wiraIceCore','wira-ice-core',arena,'img'),burst=make('wiraIceBurst','wira-ice-burst',arena,'img');core.src='assets/fx/wira/finisher.webp';burst.src='assets/fx/wira/finisher.webp';if(!seal.children.length)for(let i=0;i<6;i++){const arc=document.createElement('i');arc.style.setProperty('--arc-angle',(i*60)+'deg');seal.appendChild(arc)}return{arena,seal,core,burst}}
  function sound(cue){if(typeof paMuted!=='undefined'&&paMuted)return;const ctx=typeof ensureBattleAudio==='function'&&ensureBattleAudio();if(!ctx)return;const now=ctx.currentTime,out=ctx.createGain();out.gain.value=.34*(typeof PA_VOLUME_SCALE==='number'?PA_VOLUME_SCALE:1);out.connect(ctx.destination);const tone=(type,a,b,start,duration,level)=>{const o=ctx.createOscillator(),g=ctx.createGain(),at=now+start;o.type=type;o.frequency.setValueAtTime(a,at);o.frequency.exponentialRampToValueAtTime(Math.max(35,b),at+duration);g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(level,at+.012);g.gain.exponentialRampToValueAtTime(.0001,at+duration);o.connect(g).connect(out);o.start(at);o.stop(at+duration+.03)};if(cue==='charge'){tone('sine',120,260,0,.75,.17);tone('triangle',330,740,.12,.58,.08)}else if(cue==='arc'){tone('sawtooth',760,190,0,.16,.08);tone('sine',980,520,.03,.25,.11)}else{tone('triangle',150,45,0,.42,.27);tone('sine',1120,510,.02,.64,.17)}setTimeout(()=>{try{out.disconnect()}catch(_){}},1200)}
  function run(){reset();const enemy=document.getElementById('enemy'),parts=ensure();if(!enemy||!parts)return;sound('charge');after(TIMING.form,()=>{const p=centre(parts.arena,enemy);[parts.seal,parts.core,parts.burst].forEach(x=>position(x,p));parts.seal.classList.add('form');parts.core.classList.add('form')});after(TIMING.arc,()=>{parts.seal.classList.add('arcing');sound('arc')});after(TIMING.compress,()=>{parts.seal.classList.add('compress');parts.core.classList.add('compress')});after(TIMING.impact,()=>{parts.seal.classList.remove('form','arcing','compress');parts.core.classList.remove('form','compress');void parts.burst.offsetWidth;parts.burst.classList.add('impact');sound('impact')});after(TIMING.end,reset)}
  function reset(){clearTimers();['wiraFrostSeal','wiraIceCore','wiraIceBurst'].forEach(id=>document.getElementById(id)?.classList.remove('form','arcing','compress','impact'))}
  const originalPrepare=window.prepareHeroAttackVariant,originalClear=window.clearHeroAttackVariant;
  window.prepareHeroAttackVariant=function(el,finisher){const hero=(typeof db!=='undefined'&&db&&db.hero)||'wira';if(hero==='wira'&&finisher){run();return}reset();if(typeof originalPrepare==='function')originalPrepare(el,finisher)};
  window.clearHeroAttackVariant=function(el){const hero=(typeof db!=='undefined'&&db&&db.hero)||'wira';if(hero==='wira')reset();if(typeof originalClear==='function')originalClear(el)};
  window.PAWiraFinisher={TIMING,run,reset};
})();
