// Pahlawan Angka release loader.
(()=>{
  const APP_VERSION=globalThis.PA_APP_VERSION||'0.0.0';
  const INTEGRITY_VERSION='3.18.1';
  const DEPTH_VERSION='3.22.1';
  const Y1_COMPETENCY_V2_VERSION='2.0.0';
  const Y1_CURRICULUM_V2_VERSION='3.62.6';
  const Y1_ADAPTIVE_VERSION='3.62.6';
  const D4_CURRICULUM_VERSION='3.58.0';
  const Y6_REPAIR_VERSION='3.23.0';
  const Y6_CURRICULUM_VERSION='3.60.3';
  const Y6_EXPERIENCE_VERSION='3.60.4';
  const Y6_MONEY_REAL_VERSION='3.60.5';
  const Y6_COMPETENCY_V2_VERSION='2.0.0';
  const Y6_CURRICULUM_V2_VERSION='3.61.0';
  const Y6_ADAPTIVE_VERSION='3.61.1';
  const SENSORY_VERSION='3.19.0';
  const MANIPULATIVE_VERSION='3.19.1';
  const DAILY_REVIEW_VERSION='3.20.0';
  const DEV_EXPERIMENTS_VERSION='3.21.2';
  const COMBAT_POLISH_VERSION='3.21.3';
  const BOSS_LAB_VERSION='3.21.4';
  const TARGET_ANCHOR_VERSION='3.21.5';
  const FINISHER_HOTSPOT_VERSION='3.21.6';
  const TYPED_UI_VERSION='3.21.8';
  const GAME_QUESTION_VERSION='3.62.4';
  const PROFILE_MANAGER_VERSION='3.24.2';

  const guard=`questions/kssr-content-integrity-v${INTEGRITY_VERSION}.js?v=${APP_VERSION}`;
  const depthCss=`css/kssr-assessment-depth-v${DEPTH_VERSION}.css?v=${DEPTH_VERSION}`;
  const depthJs=`questions/kssr-assessment-depth-v${DEPTH_VERSION}.js?v=${APP_VERSION}`;
  const y1CompetencyV2Js=`data/kssr/year1-competencies-v2.js?v=${APP_VERSION}`;
  const y1V2RuntimeJs=`questions/kssr-year1-v2-runtime-v${Y1_CURRICULUM_V2_VERSION}.js?v=${APP_VERSION}`;
  const y1V2Unit1Js=`questions/kssr-year1-v2-unit1-v${Y1_CURRICULUM_V2_VERSION}.js?v=${APP_VERSION}`;
  const y1V2Unit2Js=`questions/kssr-year1-v2-unit2-v${Y1_CURRICULUM_V2_VERSION}.js?v=${APP_VERSION}`;
  const y1V2Unit34Js=`questions/kssr-year1-v2-unit34-v${Y1_CURRICULUM_V2_VERSION}.js?v=${APP_VERSION}`;
  const y1V2Unit56Js=`questions/kssr-year1-v2-unit56-v${Y1_CURRICULUM_V2_VERSION}.js?v=${APP_VERSION}`;
  const y1V2Unit78Js=`questions/kssr-year1-v2-unit78-v${Y1_CURRICULUM_V2_VERSION}.js?v=${APP_VERSION}`;
  const y1CurriculumV2Js=`questions/kssr-year1-curriculum-v2-v${Y1_CURRICULUM_V2_VERSION}.js?v=${APP_VERSION}`;
  const y1AdaptiveJs=`questions/kssr-year1-adaptive-v${Y1_ADAPTIVE_VERSION}.js?v=${APP_VERSION}`;
  const d4CurriculumJs=`questions/kssr-year4-curriculum-v${D4_CURRICULUM_VERSION}.js?v=${APP_VERSION}`;
  const y6Css=`css/kssr-year6-space-data-v${Y6_REPAIR_VERSION}.css?v=${Y6_REPAIR_VERSION}`;
  const y6Js=`questions/kssr-year6-space-data-v${Y6_REPAIR_VERSION}.js?v=${Y6_REPAIR_VERSION}`;
  const y6CurriculumJs=`questions/kssr-year6-curriculum-v${Y6_CURRICULUM_VERSION}.js?v=${APP_VERSION}`;
  const y6ExperienceJs=`questions/kssr-year6-experience-v${Y6_EXPERIENCE_VERSION}.js?v=${APP_VERSION}`;
  const y6MoneyRealJs=`questions/kssr-year6-money-real-v${Y6_MONEY_REAL_VERSION}.js?v=${APP_VERSION}`;
  const y6CompetencyV2Js=`data/kssr/year6-competencies-v2.js?v=${APP_VERSION}`;
  const y6V2RuntimeJs=`questions/kssr-year6-v2-runtime-v${Y6_CURRICULUM_V2_VERSION}.js?v=${APP_VERSION}`;
  const y6V2Unit1Js=`questions/kssr-year6-v2-unit1-v${Y6_CURRICULUM_V2_VERSION}.js?v=${APP_VERSION}`;
  const y6V2Unit2Js=`questions/kssr-year6-v2-unit2-v${Y6_CURRICULUM_V2_VERSION}.js?v=${APP_VERSION}`;
  const y6V2Unit45Js=`questions/kssr-year6-v2-unit45-v${Y6_CURRICULUM_V2_VERSION}.js?v=${APP_VERSION}`;
  const y6V2Unit6AngleJs=`questions/kssr-year6-v2-unit6-angle-v${Y6_CURRICULUM_V2_VERSION}.js?v=${APP_VERSION}`;
  const y6V2Unit6CircleJs=`questions/kssr-year6-v2-unit6-circle-v${Y6_CURRICULUM_V2_VERSION}.js?v=${APP_VERSION}`;
  const y6V2Unit6SpaceJs=`questions/kssr-year6-v2-unit6-space-v${Y6_CURRICULUM_V2_VERSION}.js?v=${APP_VERSION}`;
  const y6V2Unit7Js=`questions/kssr-year6-v2-unit7-v${Y6_CURRICULUM_V2_VERSION}.js?v=${APP_VERSION}`;
  const y6V2Unit8Js=`questions/kssr-year6-v2-unit8-v${Y6_CURRICULUM_V2_VERSION}.js?v=${APP_VERSION}`;
  const y6CurriculumV2Js=`questions/kssr-year6-curriculum-v2-v${Y6_CURRICULUM_V2_VERSION}.js?v=${APP_VERSION}`;
  const y6AdaptiveJs=`questions/kssr-year6-adaptive-v${Y6_ADAPTIVE_VERSION}.js?v=${APP_VERSION}`;
  const sensoryCss=`css/sensory-learning-v${SENSORY_VERSION}.css?v=${SENSORY_VERSION}`;
  const sensoryJs=`js/sensory-learning-v${SENSORY_VERSION}.js?v=${APP_VERSION}`;
  const manipCss=`css/cikgu-manipulatives-v${MANIPULATIVE_VERSION}.css?v=${MANIPULATIVE_VERSION}-time-lab-1`;
  const manipJs=`js/cikgu-manipulatives-v${MANIPULATIVE_VERSION}.js?v=${MANIPULATIVE_VERSION}-time-lab-1`;
  const gamesCss='css/cikgu-mini-games-v1.0.0.css?v=1.0.0-dev-menu-1';
  const fractionJs='js/fraction-lesson-v1.js?v=3.56.4';
  const gamesJs='js/cikgu-mini-games-v1.0.0.js?v=3.56.4';
  const devGamesJs='js/dev-coach-games-v1.0.0.js?v=3.56.4';
  const dailyCss=`css/daily-spaced-review-v${DAILY_REVIEW_VERSION}.css?v=${DAILY_REVIEW_VERSION}`;
  const dailyJs=`js/daily-spaced-review-v${DAILY_REVIEW_VERSION}.js?v=${DAILY_REVIEW_VERSION}`;
  const devCss=`css/dev-experiments-v${DEV_EXPERIMENTS_VERSION}.css?v=${DEV_EXPERIMENTS_VERSION}`;
  const devJs=`js/dev-experiments-v${DEV_EXPERIMENTS_VERSION}.js?v=${DEV_EXPERIMENTS_VERSION}`;
  const combatCss=`css/combat-polish-v${COMBAT_POLISH_VERSION}.css?v=${COMBAT_POLISH_VERSION}`;
  const combatJs=`js/combat-polish-v${COMBAT_POLISH_VERSION}.js?v=${COMBAT_POLISH_VERSION}`;
  const bossCss=`css/boss-stage-dev-v${BOSS_LAB_VERSION}.css?v=${APP_VERSION}`;
  const bossJs=`js/dev-boss-lab-v${BOSS_LAB_VERSION}.js?v=${BOSS_LAB_VERSION}`;
  const targetCss=`css/combat-target-anchor-v${TARGET_ANCHOR_VERSION}.css?v=${TARGET_ANCHOR_VERSION}`;
  const targetJs=`js/combat-target-anchor-v${TARGET_ANCHOR_VERSION}.js?v=${TARGET_ANCHOR_VERSION}`;
  const finisherCss=`css/finisher-alpha-hotspots-v${FINISHER_HOTSPOT_VERSION}.css?v=${FINISHER_HOTSPOT_VERSION}`;
  const finisherJs=`js/finisher-alpha-hotspots-v${FINISHER_HOTSPOT_VERSION}.js?v=${FINISHER_HOTSPOT_VERSION}`;
  const typedCss=`css/typed-answer-ui-v${TYPED_UI_VERSION}.css?v=${TYPED_UI_VERSION}`;
  const typedJs=`js/typed-answer-ui-v${TYPED_UI_VERSION}.js?v=${TYPED_UI_VERSION}`;
  const gameQuestionCss=`css/game-question-interactions-v${GAME_QUESTION_VERSION}.css?v=${GAME_QUESTION_VERSION}`;
  const gameQuestionJs=`js/game-question-interactions-v${GAME_QUESTION_VERSION}.js?v=${APP_VERSION}`;
  const profileCss=`css/profile-manager-v${PROFILE_MANAGER_VERSION}.css?v=${PROFILE_MANAGER_VERSION}`;
  const profileJs=`js/profile-manager-v${PROFILE_MANAGER_VERSION}.js?v=${APP_VERSION}`;

  if(document.readyState==='loading'){
    if(!document.querySelector(`script[src^="questions/kssr-content-integrity-v${INTEGRITY_VERSION}.js"]`))document.write(`<script src="${guard}"><\/script>`);
    if(!document.querySelector(`link[href^="css/kssr-assessment-depth-v${DEPTH_VERSION}.css"]`))document.write(`<link rel="stylesheet" href="${depthCss}">`);
    if(!document.querySelector(`script[src^="questions/kssr-assessment-depth-v${DEPTH_VERSION}.js"]`))document.write(`<script src="${depthJs}"><\/script>`);
    if(!document.querySelector('script[src^="data/kssr/year1-competencies-v2.js"]'))document.write(`<script src="${y1CompetencyV2Js}"><\/script>`);
    if(!document.querySelector(`script[src^="questions/kssr-year1-v2-runtime-v${Y1_CURRICULUM_V2_VERSION}.js"]`))document.write(`<script src="${y1V2RuntimeJs}"><\/script>`);
    if(!document.querySelector(`script[src^="questions/kssr-year1-v2-unit1-v${Y1_CURRICULUM_V2_VERSION}.js"]`))document.write(`<script src="${y1V2Unit1Js}"><\/script>`);
    if(!document.querySelector(`script[src^="questions/kssr-year1-v2-unit2-v${Y1_CURRICULUM_V2_VERSION}.js"]`))document.write(`<script src="${y1V2Unit2Js}"><\/script>`);
    if(!document.querySelector(`script[src^="questions/kssr-year1-v2-unit34-v${Y1_CURRICULUM_V2_VERSION}.js"]`))document.write(`<script src="${y1V2Unit34Js}"><\/script>`);
    if(!document.querySelector(`script[src^="questions/kssr-year1-v2-unit56-v${Y1_CURRICULUM_V2_VERSION}.js"]`))document.write(`<script src="${y1V2Unit56Js}"><\/script>`);
    if(!document.querySelector(`script[src^="questions/kssr-year1-v2-unit78-v${Y1_CURRICULUM_V2_VERSION}.js"]`))document.write(`<script src="${y1V2Unit78Js}"><\/script>`);
    if(!document.querySelector(`script[src^="questions/kssr-year1-curriculum-v2-v${Y1_CURRICULUM_V2_VERSION}.js"]`))document.write(`<script src="${y1CurriculumV2Js}"><\/script>`);
    if(!document.querySelector(`script[src^="questions/kssr-year1-adaptive-v${Y1_ADAPTIVE_VERSION}.js"]`))document.write(`<script src="${y1AdaptiveJs}"><\/script>`);
    if(!document.querySelector(`script[src^="questions/kssr-year4-curriculum-v${D4_CURRICULUM_VERSION}.js"]`))document.write(`<script src="${d4CurriculumJs}"><\/script>`);
    if(!document.querySelector(`link[href^="css/kssr-year6-space-data-v${Y6_REPAIR_VERSION}.css"]`))document.write(`<link rel="stylesheet" href="${y6Css}">`);
    if(!document.querySelector(`script[src^="questions/kssr-year6-space-data-v${Y6_REPAIR_VERSION}.js"]`))document.write(`<script src="${y6Js}"><\/script>`);
    if(!document.querySelector(`script[src^="questions/kssr-year6-curriculum-v${Y6_CURRICULUM_VERSION}.js"]`))document.write(`<script src="${y6CurriculumJs}"><\/script>`);
    if(!document.querySelector(`script[src^="questions/kssr-year6-experience-v${Y6_EXPERIENCE_VERSION}.js"]`))document.write(`<script src="${y6ExperienceJs}"><\/script>`);
    if(!document.querySelector(`script[src^="questions/kssr-year6-money-real-v${Y6_MONEY_REAL_VERSION}.js"]`))document.write(`<script src="${y6MoneyRealJs}"><\/script>`);
    if(!document.querySelector('script[src^="data/kssr/year6-competencies-v2.js"]'))document.write(`<script src="${y6CompetencyV2Js}"><\/script>`);
    if(!document.querySelector(`script[src^="questions/kssr-year6-v2-runtime-v${Y6_CURRICULUM_V2_VERSION}.js"]`))document.write(`<script src="${y6V2RuntimeJs}"><\/script>`);
    if(!document.querySelector(`script[src^="questions/kssr-year6-v2-unit1-v${Y6_CURRICULUM_V2_VERSION}.js"]`))document.write(`<script src="${y6V2Unit1Js}"><\/script>`);
    if(!document.querySelector(`script[src^="questions/kssr-year6-v2-unit2-v${Y6_CURRICULUM_V2_VERSION}.js"]`))document.write(`<script src="${y6V2Unit2Js}"><\/script>`);
    if(!document.querySelector(`script[src^="questions/kssr-year6-v2-unit45-v${Y6_CURRICULUM_V2_VERSION}.js"]`))document.write(`<script src="${y6V2Unit45Js}"><\/script>`);
    if(!document.querySelector(`script[src^="questions/kssr-year6-v2-unit6-angle-v${Y6_CURRICULUM_V2_VERSION}.js"]`))document.write(`<script src="${y6V2Unit6AngleJs}"><\/script>`);
    if(!document.querySelector(`script[src^="questions/kssr-year6-v2-unit6-circle-v${Y6_CURRICULUM_V2_VERSION}.js"]`))document.write(`<script src="${y6V2Unit6CircleJs}"><\/script>`);
    if(!document.querySelector(`script[src^="questions/kssr-year6-v2-unit6-space-v${Y6_CURRICULUM_V2_VERSION}.js"]`))document.write(`<script src="${y6V2Unit6SpaceJs}"><\/script>`);
    if(!document.querySelector(`script[src^="questions/kssr-year6-v2-unit7-v${Y6_CURRICULUM_V2_VERSION}.js"]`))document.write(`<script src="${y6V2Unit7Js}"><\/script>`);
    if(!document.querySelector(`script[src^="questions/kssr-year6-v2-unit8-v${Y6_CURRICULUM_V2_VERSION}.js"]`))document.write(`<script src="${y6V2Unit8Js}"><\/script>`);
    if(!document.querySelector(`script[src^="questions/kssr-year6-curriculum-v2-v${Y6_CURRICULUM_V2_VERSION}.js"]`))document.write(`<script src="${y6CurriculumV2Js}"><\/script>`);
    if(!document.querySelector(`script[src^="questions/kssr-year6-adaptive-v${Y6_ADAPTIVE_VERSION}.js"]`))document.write(`<script src="${y6AdaptiveJs}"><\/script>`);
    if(!document.querySelector(`link[href^="css/sensory-learning-v${SENSORY_VERSION}.css"]`))document.write(`<link rel="stylesheet" href="${sensoryCss}">`);
    if(!document.querySelector(`script[src^="js/sensory-learning-v${SENSORY_VERSION}.js"]`))document.write(`<script src="${sensoryJs}"><\/script>`);
    if(!document.querySelector(`link[href^="css/cikgu-manipulatives-v${MANIPULATIVE_VERSION}.css"]`))document.write(`<link rel="stylesheet" href="${manipCss}">`);
    if(!document.querySelector(`script[src^="js/cikgu-manipulatives-v${MANIPULATIVE_VERSION}.js"]`))document.write(`<script src="${manipJs}"><\/script>`);
    if(!document.querySelector('link[href^="css/cikgu-mini-games-v1.0.0.css"]'))document.write(`<link rel="stylesheet" href="${gamesCss}">`);
    if(!document.querySelector('script[src^="js/fraction-lesson-v1.js"]'))document.write(`<script src="${fractionJs}"><\/script>`);
    if(!document.querySelector('script[src^="js/cikgu-mini-games-v1.0.0.js"]'))document.write(`<script src="${gamesJs}"><\/script>`);
    if(!document.querySelector('script[src^="js/dev-coach-games-v1.0.0.js"]'))document.write(`<script src="${devGamesJs}"><\/script>`);
    if(!document.querySelector(`link[href^="css/daily-spaced-review-v${DAILY_REVIEW_VERSION}.css"]`))document.write(`<link rel="stylesheet" href="${dailyCss}">`);
    if(!document.querySelector(`script[src^="js/daily-spaced-review-v${DAILY_REVIEW_VERSION}.js"]`))document.write(`<script src="${dailyJs}"><\/script>`);
    if(!document.querySelector(`link[href^="css/dev-experiments-v${DEV_EXPERIMENTS_VERSION}.css"]`))document.write(`<link rel="stylesheet" href="${devCss}">`);
    if(!document.querySelector(`script[src^="js/dev-experiments-v${DEV_EXPERIMENTS_VERSION}.js"]`))document.write(`<script src="${devJs}"><\/script>`);
    if(!document.querySelector(`link[href^="css/combat-polish-v${COMBAT_POLISH_VERSION}.css"]`))document.write(`<link rel="stylesheet" href="${combatCss}">`);
    if(!document.querySelector(`script[src^="js/combat-polish-v${COMBAT_POLISH_VERSION}.js"]`))document.write(`<script src="${combatJs}"><\/script>`);
    if(!document.querySelector(`link[href^="css/boss-stage-dev-v${BOSS_LAB_VERSION}.css"]`))document.write(`<link rel="stylesheet" href="${bossCss}">`);
    if(!document.querySelector(`script[src^="js/dev-boss-lab-v${BOSS_LAB_VERSION}.js"]`))document.write(`<script src="${bossJs}"><\/script>`);
    if(!document.querySelector(`link[href^="css/combat-target-anchor-v${TARGET_ANCHOR_VERSION}.css"]`))document.write(`<link rel="stylesheet" href="${targetCss}">`);
    if(!document.querySelector(`script[src^="js/combat-target-anchor-v${TARGET_ANCHOR_VERSION}.js"]`))document.write(`<script src="${targetJs}"><\/script>`);
    if(!document.querySelector(`link[href^="css/finisher-alpha-hotspots-v${FINISHER_HOTSPOT_VERSION}.css"]`))document.write(`<link rel="stylesheet" href="${finisherCss}">`);
    if(!document.querySelector(`script[src^="js/finisher-alpha-hotspots-v${FINISHER_HOTSPOT_VERSION}.js"]`))document.write(`<script src="${finisherJs}"><\/script>`);
    if(!document.querySelector(`link[href^="css/typed-answer-ui-v${TYPED_UI_VERSION}.css"]`))document.write(`<link rel="stylesheet" href="${typedCss}">`);
    if(!document.querySelector(`script[src^="js/typed-answer-ui-v${TYPED_UI_VERSION}.js"]`))document.write(`<script src="${typedJs}"><\/script>`);
    if(!document.querySelector(`link[href^="css/game-question-interactions-v${GAME_QUESTION_VERSION}.css"]`))document.write(`<link rel="stylesheet" href="${gameQuestionCss}">`);
    if(!document.querySelector(`script[src^="js/game-question-interactions-v${GAME_QUESTION_VERSION}.js"]`))document.write(`<script src="${gameQuestionJs}"><\/script>`);
    if(!document.querySelector(`link[href^="css/profile-manager-v${PROFILE_MANAGER_VERSION}.css"]`))document.write(`<link rel="stylesheet" href="${profileCss}">`);
    if(!document.querySelector(`script[src^="js/profile-manager-v${PROFILE_MANAGER_VERSION}.js"]`))document.write(`<script src="${profileJs}"><\/script>`);
  }else{
    const loadCss=(src,selector)=>{if(document.querySelector(selector))return;const l=document.createElement('link');l.rel='stylesheet';l.href=src;document.head.appendChild(l);};
    const loadScript=(src,selector,onload)=>{if(document.querySelector(selector)){onload?.();return}const s=document.createElement('script');s.src=src;s.async=false;if(onload)s.onload=onload;document.head.appendChild(s);};
    const loadProfile=()=>{loadCss(profileCss,`link[href^="css/profile-manager-v${PROFILE_MANAGER_VERSION}.css"]`);loadScript(profileJs,`script[src^="js/profile-manager-v${PROFILE_MANAGER_VERSION}.js"]`);};
    const loadGameQuestions=()=>{loadCss(gameQuestionCss,`link[href^="css/game-question-interactions-v${GAME_QUESTION_VERSION}.css"]`);loadScript(gameQuestionJs,`script[src^="js/game-question-interactions-v${GAME_QUESTION_VERSION}.js"]`,loadProfile);};
    const loadTyped=()=>{loadCss(typedCss,`link[href^="css/typed-answer-ui-v${TYPED_UI_VERSION}.css"]`);loadScript(typedJs,`script[src^="js/typed-answer-ui-v${TYPED_UI_VERSION}.js"]`,loadGameQuestions);};
    const loadFinisher=()=>{loadCss(finisherCss,`link[href^="css/finisher-alpha-hotspots-v${FINISHER_HOTSPOT_VERSION}.css"]`);loadScript(finisherJs,`script[src^="js/finisher-alpha-hotspots-v${FINISHER_HOTSPOT_VERSION}.js"]`,loadTyped);};
    const loadTarget=()=>{loadCss(targetCss,`link[href^="css/combat-target-anchor-v${TARGET_ANCHOR_VERSION}.css"]`);loadScript(targetJs,`script[src^="js/combat-target-anchor-v${TARGET_ANCHOR_VERSION}.js"]`,loadFinisher);};
    const loadBoss=()=>{loadCss(bossCss,`link[href^="css/boss-stage-dev-v${BOSS_LAB_VERSION}.css"]`);loadScript(bossJs,`script[src^="js/dev-boss-lab-v${BOSS_LAB_VERSION}.js"]`,loadTarget);};
    const loadCombat=()=>{loadCss(combatCss,`link[href^="css/combat-polish-v${COMBAT_POLISH_VERSION}.css"]`);loadScript(combatJs,`script[src^="js/combat-polish-v${COMBAT_POLISH_VERSION}.js"]`,loadBoss);};
    const loadDev=()=>{loadCss(devCss,`link[href^="css/dev-experiments-v${DEV_EXPERIMENTS_VERSION}.css"]`);loadScript(devJs,`script[src^="js/dev-experiments-v${DEV_EXPERIMENTS_VERSION}.js"]`,loadCombat);};
    const loadDaily=()=>{loadCss(dailyCss,`link[href^="css/daily-spaced-review-v${DAILY_REVIEW_VERSION}.css"]`);loadScript(dailyJs,`script[src^="js/daily-spaced-review-v${DAILY_REVIEW_VERSION}.js"]`,loadDev);};
    const loadDevGames=()=>loadScript(devGamesJs,'script[src^="js/dev-coach-games-v1.0.0.js"]',loadDaily);
    const loadGames=()=>{loadCss(gamesCss,'link[href^="css/cikgu-mini-games-v1.0.0.css"]');loadScript(fractionJs,'script[src^="js/fraction-lesson-v1.js"]',()=>loadScript(gamesJs,'script[src^="js/cikgu-mini-games-v1.0.0.js"]',loadDevGames));};
    const loadManip=()=>{loadCss(manipCss,`link[href^="css/cikgu-manipulatives-v${MANIPULATIVE_VERSION}.css"]`);loadScript(manipJs,`script[src^="js/cikgu-manipulatives-v${MANIPULATIVE_VERSION}.js"]`,loadGames);};
    const loadSensory=()=>{loadCss(sensoryCss,`link[href^="css/sensory-learning-v${SENSORY_VERSION}.css"]`);loadScript(sensoryJs,`script[src^="js/sensory-learning-v${SENSORY_VERSION}.js"]`,loadManip);};
    const loadY6Adaptive=()=>loadScript(y6AdaptiveJs,`script[src^="questions/kssr-year6-adaptive-v${Y6_ADAPTIVE_VERSION}.js"]`,loadSensory);
    const loadY6V2Final=()=>loadScript(y6CurriculumV2Js,`script[src^="questions/kssr-year6-curriculum-v2-v${Y6_CURRICULUM_V2_VERSION}.js"]`,loadY6Adaptive);
    const loadY6V2Unit8=()=>loadScript(y6V2Unit8Js,`script[src^="questions/kssr-year6-v2-unit8-v${Y6_CURRICULUM_V2_VERSION}.js"]`,loadY6V2Final);
    const loadY6V2Unit7=()=>loadScript(y6V2Unit7Js,`script[src^="questions/kssr-year6-v2-unit7-v${Y6_CURRICULUM_V2_VERSION}.js"]`,loadY6V2Unit8);
    const loadY6V2Unit6Space=()=>loadScript(y6V2Unit6SpaceJs,`script[src^="questions/kssr-year6-v2-unit6-space-v${Y6_CURRICULUM_V2_VERSION}.js"]`,loadY6V2Unit7);
    const loadY6V2Unit6Circle=()=>loadScript(y6V2Unit6CircleJs,`script[src^="questions/kssr-year6-v2-unit6-circle-v${Y6_CURRICULUM_V2_VERSION}.js"]`,loadY6V2Unit6Space);
    const loadY6V2Unit6Angle=()=>loadScript(y6V2Unit6AngleJs,`script[src^="questions/kssr-year6-v2-unit6-angle-v${Y6_CURRICULUM_V2_VERSION}.js"]`,loadY6V2Unit6Circle);
    const loadY6V2Unit45=()=>loadScript(y6V2Unit45Js,`script[src^="questions/kssr-year6-v2-unit45-v${Y6_CURRICULUM_V2_VERSION}.js"]`,loadY6V2Unit6Angle);
    const loadY6V2Unit2=()=>loadScript(y6V2Unit2Js,`script[src^="questions/kssr-year6-v2-unit2-v${Y6_CURRICULUM_V2_VERSION}.js"]`,loadY6V2Unit45);
    const loadY6V2Unit1=()=>loadScript(y6V2Unit1Js,`script[src^="questions/kssr-year6-v2-unit1-v${Y6_CURRICULUM_V2_VERSION}.js"]`,loadY6V2Unit2);
    const loadY6V2Runtime=()=>loadScript(y6V2RuntimeJs,`script[src^="questions/kssr-year6-v2-runtime-v${Y6_CURRICULUM_V2_VERSION}.js"]`,loadY6V2Unit1);
    const loadY6CompetencyV2=()=>loadScript(y6CompetencyV2Js,'script[src^="data/kssr/year6-competencies-v2.js"]',loadY6V2Runtime);
    const loadY6MoneyReal=()=>loadScript(y6MoneyRealJs,`script[src^="questions/kssr-year6-money-real-v${Y6_MONEY_REAL_VERSION}.js"]`,loadY6CompetencyV2);
    const loadY6Experience=()=>loadScript(y6ExperienceJs,`script[src^="questions/kssr-year6-experience-v${Y6_EXPERIENCE_VERSION}.js"]`,loadY6MoneyReal);
    const loadY6Curriculum=()=>loadScript(y6CurriculumJs,`script[src^="questions/kssr-year6-curriculum-v${Y6_CURRICULUM_VERSION}.js"]`,loadY6Experience);
    const loadY6Repair=()=>{loadCss(y6Css,`link[href^="css/kssr-year6-space-data-v${Y6_REPAIR_VERSION}.css"]`);loadScript(y6Js,`script[src^="questions/kssr-year6-space-data-v${Y6_REPAIR_VERSION}.js"]`,loadY6Curriculum);};
    const loadD4Curriculum=()=>loadScript(d4CurriculumJs,`script[src^="questions/kssr-year4-curriculum-v${D4_CURRICULUM_VERSION}.js"]`,loadY6Repair);
    const loadY1Adaptive=()=>loadScript(y1AdaptiveJs,`script[src^="questions/kssr-year1-adaptive-v${Y1_ADAPTIVE_VERSION}.js"]`,loadD4Curriculum);
    const loadY1V2Final=()=>loadScript(y1CurriculumV2Js,`script[src^="questions/kssr-year1-curriculum-v2-v${Y1_CURRICULUM_V2_VERSION}.js"]`,loadY1Adaptive);
    const loadY1V2Unit78=()=>loadScript(y1V2Unit78Js,`script[src^="questions/kssr-year1-v2-unit78-v${Y1_CURRICULUM_V2_VERSION}.js"]`,loadY1V2Final);
    const loadY1V2Unit56=()=>loadScript(y1V2Unit56Js,`script[src^="questions/kssr-year1-v2-unit56-v${Y1_CURRICULUM_V2_VERSION}.js"]`,loadY1V2Unit78);
    const loadY1V2Unit34=()=>loadScript(y1V2Unit34Js,`script[src^="questions/kssr-year1-v2-unit34-v${Y1_CURRICULUM_V2_VERSION}.js"]`,loadY1V2Unit56);
    const loadY1V2Unit2=()=>loadScript(y1V2Unit2Js,`script[src^="questions/kssr-year1-v2-unit2-v${Y1_CURRICULUM_V2_VERSION}.js"]`,loadY1V2Unit34);
    const loadY1V2Unit1=()=>loadScript(y1V2Unit1Js,`script[src^="questions/kssr-year1-v2-unit1-v${Y1_CURRICULUM_V2_VERSION}.js"]`,loadY1V2Unit2);
    const loadY1V2Runtime=()=>loadScript(y1V2RuntimeJs,`script[src^="questions/kssr-year1-v2-runtime-v${Y1_CURRICULUM_V2_VERSION}.js"]`,loadY1V2Unit1);
    const loadY1CompetencyV2=()=>loadScript(y1CompetencyV2Js,'script[src^="data/kssr/year1-competencies-v2.js"]',loadY1V2Runtime);
    const loadDepth=()=>{loadCss(depthCss,`link[href^="css/kssr-assessment-depth-v${DEPTH_VERSION}.css"]`);loadScript(depthJs,`script[src^="questions/kssr-assessment-depth-v${DEPTH_VERSION}.js"]`,loadY1CompetencyV2);};
    loadScript(guard,`script[src^="questions/kssr-content-integrity-v${INTEGRITY_VERSION}.js"]`,loadDepth);
  }
  window.PARelease={version:APP_VERSION,integrity:INTEGRITY_VERSION,kssrDepth:DEPTH_VERSION,year1CompetencyV2:Y1_COMPETENCY_V2_VERSION,year1CurriculumV2:Y1_CURRICULUM_V2_VERSION,year1Adaptive:Y1_ADAPTIVE_VERSION,year6SpaceData:Y6_REPAIR_VERSION,year6Curriculum:Y6_CURRICULUM_VERSION,year6Experience:Y6_EXPERIENCE_VERSION,year6MoneyReal:Y6_MONEY_REAL_VERSION,year6CompetencyV2:Y6_COMPETENCY_V2_VERSION,year6CurriculumV2:Y6_CURRICULUM_V2_VERSION,year6Adaptive:Y6_ADAPTIVE_VERSION,sensory:SENSORY_VERSION,manipulatives:MANIPULATIVE_VERSION,dailyReview:DAILY_REVIEW_VERSION,devExperiments:DEV_EXPERIMENTS_VERSION,combatPolish:COMBAT_POLISH_VERSION,bossLab:BOSS_LAB_VERSION,targetAnchor:TARGET_ANCHOR_VERSION,finisherHotspots:FINISHER_HOTSPOT_VERSION,typedAnswerUI:TYPED_UI_VERSION,gameQuestions:GAME_QUESTION_VERSION,profileManager:PROFILE_MANAGER_VERSION};
})();

(()=>{
  if(!('serviceWorker' in navigator))return;
  window.addEventListener('load',()=>{
    navigator.serviceWorker.register('./sw.js',{scope:'./',updateViaCache:'none'}).then(registration=>{
      registration.update().catch(()=>{});
      document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')registration.update().catch(()=>{});});
    }).catch(error=>console.warn('PWA service worker tidak dapat didaftarkan:',error));
  });
})();
