// Year 6 Curriculum Bank v2 — Unit 2: Pecahan, Perpuluhan dan Peratus
(function(){
'use strict';
const RT=window.PAY6V2Runtime;if(!RT)return;
const {GEN,Nq,choose,q,mark,chooseMode,bandModes,stage,tidy,frac}=RT;

GEN['2.1.1']=function(id,s){
 const mode=chooseMode(id,'2.1.1',bandModes(s,['whole_div_fraction','fraction_div_whole'],['whole_div_fraction','fraction_div_whole','fraction_div_fraction','mixed_div_fraction'],['fraction_div_fraction','mixed_div_fraction','sharing_story','error']));
 if(mode==='whole_div_fraction'){const whole=choose([2,3,4]),d=choose([2,4]),ans=whole*d;return mark(q(whole+' ÷ 1/'+d+' = ?',ans,[Nq(frac(whole,d),'fraction'),Nq(whole+d,'fraction'),Nq(ans+1,'fraction')],'Bahagi dengan pecahan = darab dengan songsangan.','Tahun 6 · Bahagi Pecahan'),id,'2.1.1',mode,'symbolic',stage(s)===1?'procedure':'application',s,['fraction']);}
 if(mode==='fraction_div_whole'){const pair=choose([[3,4,2],[2,3,2],[5,6,3]]),ans=frac(pair[0],pair[1]*pair[2]);return mark(q(pair[0]+'/'+pair[1]+' ÷ '+pair[2]+' = ?',ans,[Nq(frac(pair[0]*pair[2],pair[1]),'fraction'),Nq(frac(pair[0],pair[1]+pair[2]),'fraction'),Nq(frac(pair[2],pair[1]),'fraction')],'Darab dengan 1/'+pair[2]+'.','Tahun 6 · Pecahan Bahagi Nombor Bulat'),id,'2.1.1',mode,'symbolic',stage(s)===1?'procedure':'application',s,['fraction']);}
 if(mode==='fraction_div_fraction'){const a=choose([[3,4,1,2],[2,3,1,3],[5,6,5,12]]),ans=frac(a[0]*a[3],a[1]*a[2]);return mark(q(a[0]+'/'+a[1]+' ÷ '+a[2]+'/'+a[3]+' = ?',ans,[Nq(frac(a[0]*a[2],a[1]*a[3]),'fraction'),Nq(frac(a[0]+a[2],a[1]+a[3]),'fraction'),Nq(frac(a[0]*a[1],a[2]*a[3]),'fraction')],'Darab pecahan pertama dengan songsangan pecahan kedua.','Tahun 6 · Pecahan Bahagi Pecahan'),id,'2.1.1',mode,'symbolic',stage(s)===3?'reasoning':'application',s,['fraction']);}
 if(mode==='mixed_div_fraction')return mark(q('2 1/4 ÷ 3/4 = ?',3,[Nq('1 1/2','fraction'),Nq('2 1/2','fraction'),Nq('4','fraction')],'2 1/4 = 9/4; 9/4 × 4/3 = 3.','Tahun 6 · Nombor Bercampur Bahagi Pecahan'),id,'2.1.1',mode,'symbolic',stage(s)===3?'reasoning':'application',s,['fraction']);
 if(mode==='sharing_story')return mark(q('Terdapat 3 L jus. Setiap bekas memuatkan 3/4 L. Berapa bekas penuh boleh diisi?',4,[Nq(3,'fraction'),Nq(5,'fraction'),Nq('2 1/4','fraction')],'Bilangan bekas = 3 ÷ 3/4.','Tahun 6 · Bahagi Pecahan dalam Konteks'),id,'2.1.1',mode,'story','reasoning',s,['fraction','division']);
 return mark(q('Murid mengira 2 ÷ 1/4 = 1/2. Penilaian?','salah, jawapannya 8',[Nq('betul','fraction'),Nq('salah, jawapannya 2 1/4','fraction'),Nq('salah, jawapannya 4','fraction')],'Berapa banyak suku terdapat dalam 2?','Tahun 6 · Analisis Bahagi Pecahan'),id,'2.1.1',mode,'verbal','reasoning',s,['fraction','error_analysis']);
};

GEN['2.2.1']=function(id,s){
 const mode=chooseMode(id,'2.2.1',bandModes(s,['multiply'],['multiply','rate','missing_factor'],['rate','missing_factor','estimate','error']));
 if(mode==='multiply'){const a=choose([1.25,2.4,3.75]),b=choose([1.2,2.5,3.2]),ans=tidy(a*b,3);return mark(q(a+' × '+b+' = ?',String(ans),[Nq(String(tidy(ans*10,3)),'decimal'),Nq(String(tidy(a+b,3)),'decimal'),Nq(String(tidy(ans+0.1,3)),'decimal')],'Darab seperti nombor bulat kemudian tentukan tempat perpuluhan.','Tahun 6 · Darab Perpuluhan'),id,'2.2.1',mode,'symbolic',stage(s)===1?'procedure':'application',s,['decimal']);}
 if(mode==='rate'){const rate=choose([1.25,1.5,2.4]),qty=choose([2.5,3.5,4.5]),ans=tidy(rate*qty,3);return mark(q('Setiap meter kain memerlukan '+rate+' L pewarna. Untuk '+qty+' m, berapa liter?',ans+' L',[Nq(tidy(rate+qty,3)+' L','decimal'),Nq(tidy(ans/10,3)+' L','decimal'),Nq(rate+' L','decimal')],'Darab kadar dengan panjang.','Tahun 6 · Aplikasi Darab Perpuluhan'),id,'2.2.1',mode,'story',stage(s)===3?'reasoning':'application',s,['decimal','rate']);}
 if(mode==='missing_factor'){const b=choose([0.5,1.5,2.5]),x=choose([1.2,2.4,3.6]),total=tidy(x*b,3);return mark(q('□ × '+b+' = '+total+'. Nilai □?',String(x),[Nq(String(total),'decimal'),Nq(String(tidy(total-b,2)),'decimal'),Nq(String(tidy(x+1,2)),'decimal')],'Bahagi hasil dengan faktor diketahui.','Tahun 6 · Faktor Perpuluhan Hilang'),id,'2.2.1',mode,'symbolic',stage(s)===3?'reasoning':'application',s,['decimal','inverse']);}
 if(mode==='estimate')return mark(q('Tanpa kira tepat, 3.75 × 2.4 paling hampir kepada?',9,[Nq(0.9,'estimate'),Nq(90,'estimate'),Nq(6,'estimate')],'4 × 2.4 hampir 9.6.','Tahun 6 · Anggaran Darab Perpuluhan'),id,'2.2.1',mode,'verbal','reasoning',s,['decimal','estimate']);
 return mark(q('Murid menulis 2.4 × 1.5 = 36. Penilaian?','salah, jawapannya 3.6',[Nq('betul','decimal'),Nq('salah, jawapannya 0.36','decimal'),Nq('salah, jawapannya 36.0','decimal')],'2.4 × 1.5 mestilah sekitar 3 hingga 4.','Tahun 6 · Analisis Darab Perpuluhan'),id,'2.2.1',mode,'verbal','reasoning',s,['decimal','error_analysis']);
};

GEN['2.2.2']=function(id,s){
 const mode=chooseMode(id,'2.2.2',bandModes(s,['divide'],['divide','packing','missing_divisor'],['packing','missing_divisor','unit_rate','error']));
 if(mode==='divide'){const d=choose([0.2,0.25,0.4,0.5,1.25]),quot=choose([1.2,2.4,3.2,4.5]),a=tidy(d*quot,3);return mark(q(a+' ÷ '+d+' = ?',String(quot),[Nq(String(tidy(quot*10,3)),'decimal'),Nq(String(tidy(a-d,3)),'decimal'),Nq(String(tidy(quot+0.5,3)),'decimal')],'Jadikan pembahagi nombor bulat dengan menggerakkan titik pada kedua-dua nombor sama banyak.','Tahun 6 · Bahagi Perpuluhan'),id,'2.2.2',mode,'symbolic',stage(s)===1?'procedure':'application',s,['decimal']);}
 if(mode==='packing'){const each=choose([0.8,1.2,1.5,2.4]),n=choose([4,5,6]),total=tidy(each*n,2);return mark(q(total+' kg bahan dibahagi kepada bekas '+each+' kg. Berapa bekas penuh?',n,[Nq(n-1,'decimal'),Nq(n+1,'decimal'),Nq(tidy(total-each,2),'decimal')],'Bilangan bekas = jumlah ÷ kapasiti setiap bekas.','Tahun 6 · Bahagi Perpuluhan dalam Konteks'),id,'2.2.2',mode,'story',stage(s)===3?'reasoning':'application',s,['decimal','division']);}
 if(mode==='missing_divisor')return mark(q('7.2 ÷ □ = 3. Apakah nilai □?',2.4,[Nq(21.6,'decimal'),Nq(4.2,'decimal'),Nq(10.2,'decimal')],'Pembahagi = 7.2 ÷ 3.','Tahun 6 · Pembahagi Hilang'),id,'2.2.2',mode,'symbolic',stage(s)===3?'reasoning':'application',s,['decimal','inverse']);
 if(mode==='unit_rate')return mark(q('4.8 L jus mengisi 6 botol sama banyak. Isi padu setiap botol?','0.8 L',[Nq('1.2 L','decimal'),Nq('2.8 L','decimal'),Nq('28.8 L','decimal')],'4.8 ÷ 6 = 0.8.','Tahun 6 · Kadar Unit Perpuluhan'),id,'2.2.2',mode,'story','reasoning',s,['decimal','unit_rate']);
 return mark(q('Murid berkata 4.8 ÷ 0.6 = 0.8. Penilaian?','salah, jawapannya 8',[Nq('betul','decimal'),Nq('salah, jawapannya 80','decimal'),Nq('salah, jawapannya 4.2','decimal')],'0.6 × 8 = 4.8.','Tahun 6 · Analisis Bahagi Perpuluhan'),id,'2.2.2',mode,'verbal','reasoning',s,['decimal','error_analysis']);
};

GEN['2.3.1']=function(id,s){
 const mode=chooseMode(id,'2.3.1',bandModes(s,['decimal_to_percent','percent_to_decimal'],['decimal_to_percent','percent_to_decimal','compare'],['compare','claim','order']));
 const p=choose([[1.05,105],[1.2,120],[1.25,125],[1.5,150],[1.75,175],[2,200]]);
 if(mode==='decimal_to_percent')return mark(q('Tukar <b>'+p[0]+'</b> kepada peratus.',p[1]+'%',[Nq((p[1]/10)+'%','percent'),Nq(p[0]+'%','percent'),Nq((p[1]-100)+'%','percent')],'Darab perpuluhan dengan 100%.','Tahun 6 · Peratus Melebihi 100%'),id,'2.3.1',mode,'symbolic',stage(s)===1?'procedure':'application',s,['percent']);
 if(mode==='percent_to_decimal')return mark(q(p[1]+'% ditulis sebagai perpuluhan ialah?',String(p[0]),[Nq(String(p[0]/10),'percent'),Nq(String(p[1]),'percent'),Nq(String(p[0]+1),'percent')],'Bahagi peratus dengan 100.','Tahun 6 · Peratus kepada Perpuluhan'),id,'2.3.1',mode,'symbolic',stage(s)===1?'procedure':'application',s,['percent']);
 if(mode==='compare')return mark(q('Yang manakah lebih besar: 1.35 atau 125%?','1.35',[Nq('125%','percent'),Nq('sama nilai','percent'),Nq('tidak boleh dibanding','percent')],'125% = 1.25.','Tahun 6 · Banding Peratus dan Perpuluhan'),id,'2.3.1',mode,'verbal',stage(s)===3?'reasoning':'application',s,['percent','compare']);
 if(mode==='claim')return mark(q('Murid berkata 175% = 0.175. Penilaian?','salah, 175% = 1.75',[Nq('betul','percent'),Nq('salah, 175% = 17.5','percent'),Nq('salah, 175% = 175','percent')],'175 ÷ 100 = 1.75.','Tahun 6 · Analisis Penukaran Peratus'),id,'2.3.1',mode,'verbal','reasoning',s,['percent','error_analysis']);
 return mark(q('Susun daripada kecil ke besar: 110%, 1.5, 125%.','110%, 125%, 1.5',[Nq('1.5, 125%, 110%','percent'),Nq('125%, 110%, 1.5','percent'),Nq('110%, 1.5, 125%','percent')],'Tukar kepada format yang sama.','Tahun 6 · Susun Peratus >100%'),id,'2.3.1',mode,'verbal','reasoning',s,['percent','order']);
};

GEN['2.3.2']=function(id,s){
 const mode=chooseMode(id,'2.3.2',bandModes(s,['add','subtract'],['add','subtract','points'],['points','missing','error']));
 if(mode==='add'){const a=choose([25,40,75,120,150]),b=choose([10,20,25,50]),ans=a+b;return mark(q(a+'% + '+b+'% = ?',ans+'%',[Nq(Math.abs(a-b)+'%','percent'),Nq((ans/100)+'%','percent'),Nq((ans+10)+'%','percent')],'Tambah nilai peratus.','Tahun 6 · Tambah Peratus'),id,'2.3.2',mode,'symbolic',stage(s)===1?'procedure':'application',s,['percent']);}
 if(mode==='subtract'){const a=choose([125,150,175,200]),b=choose([25,50,75]),ans=a-b;return mark(q(a+'% − '+b+'% = ?',ans+'%',[Nq((a+b)+'%','percent'),Nq((ans/100)+'%','percent'),Nq((ans+25)+'%','percent')],'Tolak nilai peratus.','Tahun 6 · Tolak Peratus'),id,'2.3.2',mode,'symbolic',stage(s)===1?'procedure':'application',s,['percent']);}
 if(mode==='points')return mark(q('Kadar meningkat daripada 120% kepada 155%. Peningkatan ialah?','35 mata peratus',[Nq('275 mata peratus','percent'),Nq('29.2 mata peratus','percent'),Nq('155 mata peratus','percent')],'Cari beza terus antara dua peratus.','Tahun 6 · Perubahan Peratus'),id,'2.3.2',mode,'story',stage(s)===3?'reasoning':'application',s,['percent','difference']);
 if(mode==='missing')return mark(q('□% + 45% = 170%. Nilai □?','125%',[Nq('115%','percent'),Nq('135%','percent'),Nq('215%','percent')],'170% − 45% = 125%.','Tahun 6 · Peratus Hilang'),id,'2.3.2',mode,'symbolic','reasoning',s,['percent','inverse']);
 return mark(q('Murid mengira 150% − 25% = 12500%. Penilaian?','salah, jawapannya 125%',[Nq('betul','percent'),Nq('salah, 175%','percent'),Nq('salah, 1.25%','percent')],'Tolak nombor peratus secara terus.','Tahun 6 · Analisis Operasi Peratus'),id,'2.3.2',mode,'verbal','reasoning',s,['percent','error_analysis']);
};

GEN['2.3.3']=function(id,s){
 const mode=chooseMode(id,'2.3.3',bandModes(s,['of_quantity','quantity_as_percent'],['of_quantity','quantity_as_percent','reverse','compare'],['reverse','compare','claim','multi']));
 if(mode==='of_quantity'){const pct=choose([110,125,150,175,200]),base=choose([40,80,120]),ans=base*pct/100;return mark(q(pct+'% daripada '+base+' = ?',ans,[Nq(base,'percent'),Nq(base*(pct-100)/100,'percent'),Nq(base+pct,'operation')],'Darab kuantiti dengan peratus/100.','Tahun 6 · Nilai Peratus'),id,'2.3.3',mode,'symbolic',stage(s)===1?'procedure':'application',s,['percent']);}
 if(mode==='quantity_as_percent')return mark(q('67.5 g ialah berapa peratus daripada 45 g?','150%',[Nq('66.7%','percent'),Nq('125%','percent'),Nq('22.5%','percent')],'67.5 ÷ 45 × 100%.','Tahun 6 · Kuantiti sebagai Peratus'),id,'2.3.3',mode,'story',stage(s)===3?'reasoning':'application',s,['percent','ratio']);
 if(mode==='reverse'){const pct=choose([125,150,200]),whole=choose([40,80,120]),part=whole*pct/100;return mark(q(part+' ialah '+pct+'% daripada suatu nilai. Nilai asal?',whole,[Nq(part,'percent'),Nq(part*pct/100,'percent'),Nq(whole+20,'percent')],'Bahagi bahagian dengan peratus/100.','Tahun 6 · Nilai Asal Peratus'),id,'2.3.3',mode,'symbolic',stage(s)===3?'reasoning':'application',s,['percent','inverse']);}
 if(mode==='compare')return mark(q('A = 125% daripada 80. B = 150% daripada 60. Yang lebih besar?','A, nilainya 100',[Nq('B, nilainya 90','percent'),Nq('sama nilai','percent'),Nq('tidak boleh dibanding','percent')],'Cari kedua-dua nilai.','Tahun 6 · Banding Nilai Peratus'),id,'2.3.3',mode,'verbal','reasoning',s,['percent','compare']);
 if(mode==='claim')return mark(q('Murid berkata 150% daripada 40 ialah 60 kerana 150%=1.5. Penilaian?','betul',[Nq('salah, 50','percent'),Nq('salah, 150%=0.15','percent'),Nq('tidak boleh dinilai','percent')],'1.5 × 40 = 60.','Tahun 6 · Menilai Penaakulan Peratus'),id,'2.3.3',mode,'verbal','reasoning',s,['percent','error_analysis']);
 return mark(q('Nilai asal 80 dinaikkan kepada 150%, kemudian dikurangkan 25 mata peratus. Nilai akhir?',100,[Nq(120,'percent'),Nq(20,'percent'),Nq(125,'percent')],'Peratus akhir 125%; 125% daripada 80 = 100.','Tahun 6 · Peratus Pelbagai Langkah'),id,'2.3.3',mode,'story','reasoning',s,['percent','multi_step']);
};

GEN['2.4.1']=function(id,s){
 const mode=chooseMode(id,'2.4.1',bandModes(s,['simple','bracket'],['simple','bracket','fraction_decimal','unknown'],['fraction_decimal','unknown','method','error']));
 if(mode==='simple')return mark(q('12 + 1/2 × 8 = ?',16,[Nq(52,'operation'),Nq(10,'operation'),Nq(20,'operation')],'Darab 1/2 × 8 dahulu.','Tahun 6 · Operasi Bergabung Pelbagai Nombor'),id,'2.4.1',mode,'symbolic',stage(s)===1?'procedure':'application',s,['mixed_operation']);
 if(mode==='bracket')return mark(q('(3.5 + 2.5) × 4 = ?',24,[Nq(13.5,'operation'),Nq(10,'operation'),Nq(28,'operation')],'Kurungan dahulu.','Tahun 6 · Operasi Bergabung Perpuluhan'),id,'2.4.1',mode,'symbolic',stage(s)===1?'procedure':'application',s,['mixed_operation']);
 if(mode==='fraction_decimal')return mark(q('20 − 3/4 × 8 + 1.5 = ?',15.5,[Nq(21.5,'operation'),Nq(10,'operation'),Nq(14.5,'operation')],'3/4 × 8 = 6; kemudian kira dari kiri ke kanan.','Tahun 6 · Operasi Pecahan dan Perpuluhan'),id,'2.4.1',mode,'symbolic',stage(s)===3?'reasoning':'application',s,['mixed_operation']);
 if(mode==='unknown')return mark(q('□ + 1/2 × 10 = 17. Nilai □?',12,[Nq(7,'operation'),Nq(22,'operation'),Nq(24,'operation')],'1/2 × 10 = 5; 17 − 5 = 12.','Tahun 6 · Anu dalam Operasi Bergabung'),id,'2.4.1',mode,'symbolic',stage(s)===3?'reasoning':'application',s,['mixed_operation','inverse']);
 if(mode==='method')return mark(q('Untuk 10 + 0.5 × 8, Murid A mendapat 14 dengan darab dahulu. Murid B mendapat 84 dengan tambah dahulu. Siapa betul?','Murid A',[Nq('Murid B','mixed_operation'),Nq('kedua-duanya betul','mixed_operation'),Nq('kedua-duanya salah','mixed_operation')],'Darab sebelum tambah.','Tahun 6 · Menilai Kaedah Operasi'),id,'2.4.1',mode,'verbal','reasoning',s,['mixed_operation','method']);
 return mark(q('Murid mengira (2.5 + 1/2) × 4 = 10.5. Penilaian?','salah, jawapannya 12',[Nq('betul','mixed_operation'),Nq('salah, 8','mixed_operation'),Nq('salah, 16','mixed_operation')],'1/2=0.5; 3.0 × 4 = 12.','Tahun 6 · Analisis Operasi Bergabung'),id,'2.4.1',mode,'verbal','reasoning',s,['mixed_operation','error_analysis']);
};

GEN['2.5.1']=function(id,s){
 const mode=chooseMode(id,'2.5.1',bandModes(s,['recipe','sharing'],['recipe','sharing','percent_context','mixed_context'],['percent_context','mixed_context','reverse','claim']));
 if(mode==='recipe')return mark(q('Satu resipi menggunakan 3/4 L susu. Untuk 4 resipi, berapa liter?', '3 L',[Nq('1 L','fraction'),Nq('4 L','fraction'),Nq('2 1/4 L','fraction')],'3/4 × 4 = 3.','Tahun 6 · Masalah Pecahan Harian'),id,'2.5.1',mode,'story','application',s,['fraction','context']);
 if(mode==='sharing')return mark(q('6.4 kg beras dibahagi sama banyak ke dalam 8 beg. Jisim setiap beg?','0.8 kg',[Nq('1.25 kg','decimal'),Nq('5.6 kg','decimal'),Nq('0.08 kg','decimal')],'6.4 ÷ 8 = 0.8.','Tahun 6 · Masalah Perpuluhan Harian'),id,'2.5.1',mode,'story','application',s,['decimal','context']);
 if(mode==='percent_context')return mark(q('Sasaran kehadiran 64 orang. Kehadiran sebenar ialah 125% daripada sasaran. Berapa orang hadir?',80,[Nq(64,'percent'),Nq(100,'percent'),Nq(45,'percent')],'125% × 64 = 80.','Tahun 6 · Masalah Peratus Harian'),id,'2.5.1',mode,'story',stage(s)===3?'reasoning':'application',s,['percent','context']);
 if(mode==='mixed_context')return mark(q('Tangki ada 12 L air. 1/4 digunakan, kemudian 2.5 L ditambah. Baki akhir?','11.5 L',[Nq('5.5 L','mixed_operation'),Nq('9 L','mixed_operation'),Nq('14.5 L','mixed_operation')],'1/4 daripada 12 = 3; 12−3+2.5.','Tahun 6 · Masalah Pelbagai Bentuk Nombor'),id,'2.5.1',mode,'story','reasoning',s,['mixed_operation','multi_step']);
 if(mode==='reverse')return mark(q('Selepas menggunakan 25% bekalan, masih tinggal 60 unit. Bekalan asal?',80,[Nq(75,'percent'),Nq(240,'percent'),Nq(45,'percent')],'60 ialah 75% daripada asal.','Tahun 6 · Masalah Songsang Peratus'),id,'2.5.1',mode,'story','reasoning',s,['percent','inverse']);
 return mark(q('Aiman berkata 2 1/2 L boleh mengisi tiga bekas 3/4 L dan berbaki 1/4 L. Betulkah?','betul',[Nq('salah, hanya 2 bekas','fraction'),Nq('salah, baki 1/2 L','fraction'),Nq('salah, tiada baki','fraction')],'3 × 3/4 = 2 1/4; baki 1/4.','Tahun 6 · Penaakulan Masalah Pecahan'),id,'2.5.1',mode,'verbal','reasoning',s,['fraction','reasoning']);
};

document.documentElement?.setAttribute('data-y6-v2-unit2','3.61.0');
})();