// Pahlawan Angka v3.22.0 — KSSR Assessment Depth & Variety
// Explicit skill contracts only. No cross-skill generic override.
(function(){
'use strict';
const VERSION='3.22.0';
const banks=window.PAQuestionBanks=window.PAQuestionBanks||{};
const previous={};
['d1','d2t1','d2t2','d2t3','d2t4','d2t5','d2t6','d2t7','d2t8','d3','d4','d5','d6'].forEach(k=>previous[k]=banks[k]);

const gcd2=(a,b)=>{a=Math.abs(a);b=Math.abs(b);while(b){let t=b;b=a%b;a=t}return a||1};
const frac=(n,d)=>{if(d<0){n=-n;d=-d}const g=gcd2(n,d);n/=g;d/=g;return d===1?String(n):`${n}/${d}`};
const mixed=(n,d)=>{const g=gcd2(n,d);n/=g;d/=g;if(d===1)return String(n);if(n<d)return `${n}/${d}`;const w=Math.floor(n/d),r=n%d;return r?`${w} ${r}/${d}`:String(w)};
const money=n=>typeof moneyFmtUpper==='function'?moneyFmtUpper(n):`RM${Number(n).toFixed(2).replace(/\.00$/,'')}`;
const clean=v=>String(v).replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
const sessRef=()=>{try{return typeof sess!=='undefined'?sess:window.sess}catch(_){return window.sess}};
const recentModes=id=>(sessRef()?.questionHistory||[]).filter(x=>x.skillId===id).slice(-8).map(x=>String(x.archetypeId||'').replace(/^depth_/,''));
function rotate(id,modes){
  const recent=recentModes(id),last=recent.at(-1),counts=Object.fromEntries(modes.map(x=>[x,recent.filter(y=>y===x).length]));
  const pool=modes.filter(x=>x!==last);
  return (pool.length?pool:modes).sort((a,b)=>counts[a]-counts[b]||Math.random()-.5)[0];
}
function depth(q,id,mode,rep='symbolic',demand='procedure',targets=[]){
  if(!q)return q;
  q.familyKey=id;q.competencyId=mode;q.archetypeId=`depth_${mode}`;q.representation=rep;q.demand=demand;
  q.contextId=`kssr:${id}:${mode}`;q.difficultyBand=demand==='reasoning'?4:demand==='application'?3:demand==='procedure'?2:1;
  q.misconceptionTargets=targets.length?targets:[q.wrong?.[0]?.tag||'generated'];
  q.kssrDepthVersion=VERSION;return q;
}
const chooseMode=(id,s,modes)=>{
  const mastery=Number(s?.mastery||0), evidence=Number(s?.evidence||0);
  let allowed=modes;
  if(evidence<2||mastery<30)allowed=modes.filter(x=>!/(reason|multi|inverse|missing|mixed|composite|zone|proportion)/.test(x))||modes;
  return rotate(id,allowed.length?allowed:modes);
};
const wrongNums=(ans,step=1,tag='operation')=>[N(ans+step,tag),N(Math.max(0,ans-step),tag),N(ans+step*2,tag)];
const numLine=(min,max,value,label='')=>{
  const w=310,h=72,p=22,range=max-min||1,x=p+(value-min)/range*(w-2*p);
  const ticks=Array.from({length:6},(_,i)=>{const tx=p+i*(w-2*p)/5,n=Math.round(min+i*range/5);return `<g><line x1="${tx}" y1="34" x2="${tx}" y2="42"/><text x="${tx}" y="59">${n}</text></g>`}).join('');
  return `<div class="kssrDiagram"><svg viewBox="0 0 ${w} ${h}" aria-label="garis nombor"><line x1="${p}" y1="38" x2="${w-p}" y2="38" class="kd-line"/>${ticks}<circle cx="${x}" cy="38" r="6" class="kd-accent"/><text x="${x}" y="18" class="kd-label">${label||value}</text></svg></div>`;
};
const fractionStrip=(n,d,color='#5b8def')=>{
  const w=300,h=68,x0=10,y=14,iw=280/d;
  let cells='';for(let i=0;i<d;i++)cells+=`<rect x="${x0+i*iw}" y="${y}" width="${iw}" height="38" class="${i<n?'kd-fill':'kd-empty'}"/>`;
  return `<div class="kssrDiagram" style="--kd-accent:${color}"><svg viewBox="0 0 ${w} ${h}" aria-label="jalur pecahan">${cells}</svg></div>`;
};
const fractionSet=(n,d)=>{
  const cols=Math.min(5,d),rows=Math.ceil(d/cols),w=300,h=Math.max(80,rows*48+16),r=13,gap=44,x0=(w-(cols-1)*gap)/2,y0=28;
  let dots='';for(let i=0;i<d;i++){let c=i%cols,rr=Math.floor(i/cols);dots+=`<circle cx="${x0+c*gap}" cy="${y0+rr*46}" r="${r}" class="${i<n?'kd-fill':'kd-empty'}"/>`}
  return `<div class="kssrDiagram"><svg viewBox="0 0 ${w} ${h}" aria-label="kumpulan pecahan">${dots}</svg></div>`;
};
const hundredGrid=pct=>{
  let cells='';for(let i=0;i<100;i++){let x=10+(i%10)*25,y=8+Math.floor(i/10)*18;cells+=`<rect x="${x}" y="${y}" width="22" height="15" rx="2" class="${i<pct?'kd-fill':'kd-empty'}"/>`}
  return `<div class="kssrDiagram"><svg viewBox="0 0 270 200" aria-label="petak seratus">${cells}</svg></div>`;
};
const pictograph=(labels,vals,key=1)=>{
  let rows=labels.map((l,i)=>`<div class="kd-picto-row"><b>${l}</b><span>${'●'.repeat(Math.max(0,Math.round(vals[i]/key)))}</span></div>`).join('');
  return `<div class="kssrDiagram kd-pictograph">${rows}<small>● = ${key}</small></div>`;
};
const miniTable=(headers,rows)=>`<div class="kssrDiagram"><table class="kd-table"><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const ruler=(cm,mark)=>{
  const w=310,h=72,p=18,x=p+(mark/cm)*(w-2*p);let ticks='';
  for(let i=0;i<=cm;i++){let tx=p+i*(w-2*p)/cm;ticks+=`<line x1="${tx}" y1="28" x2="${tx}" y2="${i%5===0?50:42}" class="kd-line"/><text x="${tx}" y="65">${i%5===0?i:''}</text>`}
  return `<div class="kssrDiagram"><svg viewBox="0 0 ${w} ${h}" aria-label="pembaris">${ticks}<path d="M ${x} 9 L ${x-7} 22 L ${x+7} 22 Z" class="kd-accent"/></svg></div>`;
};
const rectDiagram=(l,w,cut=0)=>{
  const W=300,H=150;
  if(!cut)return `<div class="kssrDiagram"><svg viewBox="0 0 ${W} ${H}"><rect x="60" y="28" width="180" height="90" class="kd-shape"/><text x="150" y="140">${l} cm</text><text x="32" y="76">${w} cm</text></svg></div>`;
  return `<div class="kssrDiagram"><svg viewBox="0 0 ${W} ${H}"><path d="M45 25 H250 V118 H155 V82 H45 Z" class="kd-shape"/><text x="147" y="142">${l} cm</text><text x="18" y="76">${w} cm</text><text x="194" y="78">${cut} cm</text></svg></div>`;
};
const coordinateMap=(points,scale=1)=>{
  const w=300,h=245,p=38,max=6,step=(w-2*p)/max;
  let grid='';for(let i=0;i<=max;i++){let x=p+i*step,y=h-p-i*step;grid+=`<line x1="${x}" y1="${p}" x2="${x}" y2="${h-p}" class="kd-grid"/><line x1="${p}" y1="${y}" x2="${w-p}" y2="${y}" class="kd-grid"/><text x="${x}" y="${h-14}">${i}</text><text x="18" y="${y+4}">${i}</text>`}
  let pts=points.map(o=>{let x=p+o.x*step,y=h-p-o.y*step;return `<circle cx="${x}" cy="${y}" r="7" class="kd-accent"/><text x="${x+10}" y="${y-8}" class="kd-label">${o.label}</text>`}).join('');
  return `<div class="kssrDiagram"><svg viewBox="0 0 ${w} ${h}" aria-label="grid koordinat">${grid}${pts}</svg>${scale!==1?`<small>1 petak = ${scale} km</small>`:''}</div>`;
};
const spinner=(parts,win)=>{
  const w=220,h=190,cx=110,cy=92,r=72;let seg='';
  for(let i=0;i<parts;i++){const a1=-Math.PI/2+i*2*Math.PI/parts,a2=-Math.PI/2+(i+1)*2*Math.PI/parts,x1=cx+r*Math.cos(a1),y1=cy+r*Math.sin(a1),x2=cx+r*Math.cos(a2),y2=cy+r*Math.sin(a2),large=(2*Math.PI/parts)>Math.PI?1:0;seg+=`<path d="M${cx},${cy} L${x1},${y1} A${r},${r} 0 ${large},1 ${x2},${y2} Z" class="${i<win?'kd-fill':'kd-empty'}"/>`}
  return `<div class="kssrDiagram"><svg viewBox="0 0 ${w} ${h}" aria-label="roda kebarangkalian">${seg}<circle cx="${cx}" cy="${cy}" r="5" class="kd-accent"/></svg></div>`;
};
const timeBar=(startMin,endMin)=>{
 const fmt=m=>`${Math.floor((m%1440)/60)}:${String(m%60).padStart(2,'0')}`;return `<div class="kssrDiagram kd-timebar"><span>${fmt(startMin)}</span><div><i></i></div><span>${fmt(endMin)}</span></div>`;
};
const makeWrongFractions=(ans,n,d)=>[N(frac(Math.max(1,n-1),d),'fraction'),N(frac(n,d+1),'fraction'),N(frac(n+1,d),'fraction')];

// D1 — concrete before symbolic; no rounding in place-value.
function d1(id,s,shift){
 let mode;
 if(id==='D1.N20'||id==='D1.N100'){
  const max=id==='D1.N20'?(Number(s?.evidence||0)<3?9:20):100;
  mode=chooseMode(id,s,['compare','missing_line','order','count_visual']);
  if(mode==='count_visual'){const n=R(3,Math.min(max,18));return depth(Q(`${fractionSet(n,n)}Berapakah bilangan bulatan?`,n,wrongNums(n,1,'count'),'Kira satu demi satu.','Tahun 1 · Bilangan',true,true),id,mode,'visual','concept',['count']);}
  if(mode==='missing_line'){const a=R(1,Math.max(2,max-3)),ans=a+1;return depth(Q(numLine(Math.max(0,a-2),Math.min(max,a+3),ans,'?')+`Nombor pada titik ? ialah?`,ans,[N(a,'pattern'),N(a+2,'pattern'),N(Math.min(max,a+3),'pattern')],'Kira mengikut urutan.','Tahun 1 · Garis Nombor',true,true),id,mode,'visual','concept',['pattern']);}
  let vals=[];while(vals.length<4){let n=R(1,max);if(!vals.includes(n))vals.push(n)}
  if(mode==='order'){const sorted=[...vals].sort((a,b)=>a-b);return depth(Q(`Susun nombor daripada kecil kepada besar.<br><b>${vals.join(', ')}</b>`,sorted.join(', '),[N([...sorted].reverse().join(', '),'compare'),N(vals.join(', '),'compare'),N(sorted.slice(1).concat(sorted[0]).join(', '),'compare')],'Cari nombor paling kecil dahulu.','Tahun 1 · Susun Nombor',true,true),id,mode,'symbolic','concept',['compare']);}
  const ask=Math.random()<.5?'paling besar':'paling kecil',ans=ask==='paling besar'?Math.max(...vals):Math.min(...vals);return depth(Q(`Pilih nombor yang ${ask}.<br><b>${vals.join(', ')}</b>`,ans,vals.filter(x=>x!==ans).slice(0,3).map(x=>N(x,'compare')),'Banding nilai satu demi satu.','Tahun 1 · Banding Nombor',true,shift),id,mode,'symbolic','concept',['compare']);
 }
 if(id==='D1.PV100'){
   mode=chooseMode(id,s,['blocks','place','expanded','compose']);let n=R(10,99),t=Math.floor(n/10),o=n%10;
   if(mode==='blocks'){return depth(Q(`${typeof base10Visual==='function'?base10Visual(n):''}Apakah nombor yang ditunjukkan?`,n,[N(t+o,'digit_value'),N(o*10+t,'place'),N(n+10,'place')],'Kira puluh dan sa.','Tahun 1 · Nilai Tempat',true,true),id,mode,'visual','concept',['place']);}
   if(mode==='place'){const ask=Math.random()<.5?'puluh':'sa',ans=ask==='puluh'?t:o;return depth(Q(`Dalam <b>${n}</b>, digit pada tempat <b>${ask}</b> ialah?`,ans,[N(ask==='puluh'?o:t,'place'),N(ans*10,'digit_value'),N(n,'place')],'Lihat kedudukan digit.','Tahun 1 · Tempat Digit',true,true),id,mode,'symbolic','concept',['place']);}
   if(mode==='expanded'){return depth(Q(`Cerakinkan <b>${n}</b>.`,`${t*10} + ${o}`,[N(`${t} + ${o}`,'digit_value'),N(`${o*10} + ${t}`,'place'),N(`${n} + 0`,'place')],'Puluh bernilai 10 kali digitnya.','Tahun 1 · Cerakin',true,true),id,mode,'symbolic','procedure',['place']);}
   return depth(Q(`<b>${t} puluh</b> dan <b>${o} sa</b> membentuk nombor?`,n,[N(t+o,'digit_value'),N(o*10+t,'place'),N(n+10,'place')],'Gabungkan puluh dan sa.','Tahun 1 · Bina Nombor',true,true),id,mode,'verbal','concept',['place']);
 }
 if(id==='D1.CMP100'){let a=R(1,100),b=R(1,100);while(a===b)b=R(1,100);mode=chooseMode(id,s,['word_compare','symbol']);if(mode==='symbol'){let ans=a>b?'>':'<';return depth(Q(`<b>${a}</b> ___ <b>${b}</b>`,ans,[N(ans==='>'?'<':'>','compare'),N('=','compare'),N('≠','compare')],'Banding puluh dahulu.','Tahun 1 · Simbol Banding',true,true),id,mode,'symbolic','concept',['compare']);}let ask=Math.random()<.5?'lebih besar':'lebih kecil',ans=ask==='lebih besar'?Math.max(a,b):Math.min(a,b);return depth(Q(`Yang manakah ${ask}: <b>${a}</b> atau <b>${b}</b>?`,ans,[N(ans===a?b:a,'compare'),N(Math.abs(a-b),'operation'),N(a+b,'operation')],'Banding nilai nombor.','Tahun 1 · Banding',true,shift),id,mode,'verbal','concept',['compare']);}
 if(['D1.ADD20','D1.ADD100','D1.SUB20','D1.SUB100'].includes(id)){
   const add=id.includes('ADD'),max=id.endsWith('20')?20:100;mode=chooseMode(id,s,['visual','story','symbolic']);
   let a,b;if(add){a=R(2,Math.floor(max*.65));b=R(1,max-a)}else{a=R(3,max);b=R(1,a)}const ans=add?a+b:a-b;
   if(mode==='visual'&&max<=20){const vis=fractionSet(a,a)+fractionSet(b,b);return depth(Q(`${vis}${add?'Gabungkan':'Daripada'} <b>${a}</b> ${add?`dan <b>${b}</b>`:`objek, keluarkan <b>${b}</b>`}. Berapa ${add?'semuanya':'tinggal'}?`,ans,wrongNums(ans,1,'operation'),add?'Gabungkan dua kumpulan.':'Keluarkan kemudian kira baki.','Tahun 1 · Model Operasi',true,true),id,mode,'visual','concept',['operation']);}
   if(mode==='story'){return depth(Q(add?`Aina ada ${a} pelekat dan mendapat ${b} lagi. Berapa semuanya?`:`Aina ada ${a} pelekat dan memberi ${b}. Berapa tinggal?`,ans,wrongNums(ans,add?2:1,'operation'),add?'“Lagi” menambah jumlah.':'“Tinggal” selepas memberi bermaksud tolak.','Tahun 1 · Cerita Operasi',true,true),id,mode,'story','application',['operation']);}
   return depth(add?addQ(a,b,ans,'Tahun 1',shift):subQ(a,b,ans,'Tahun 1',shift),id,mode,'symbolic','procedure',['operation']);
 }
 if(id==='D1.FRAC'){
  mode=chooseMode(id,s,['shade_name','word_match','sharing']);const pairs=[[1,2,'satu perdua'],[1,4,'satu perempat'],[2,4,'dua perempat'],[3,4,'tiga perempat']],p=pick(pairs),[n,d,word]=p;
  if(mode==='word_match')return depth(Q(`${fractionStrip(n,d)}Pilih nama pecahan yang betul.`,word,[N('satu perdua','fraction'),N('satu perempat','fraction'),N('dua perempat','fraction'),N('tiga perempat','fraction')].filter(x=>clean(x.v)!==word).slice(0,3),'Bahagian mesti sama besar.','Tahun 1 · Nama Pecahan',true,true),id,mode,'visual','concept',['fraction']);
  if(mode==='sharing'){const people=d===2?2:4;return depth(Q(`Sebiji kek dibahagi sama rata kepada <b>${people}</b> bahagian. Amir mendapat <b>${n}</b> bahagian.${fractionStrip(n,d)}Pecahan kek Amir ialah?`,`${n}/${d}`,makeWrongFractions(`${n}/${d}`,n,d),'Penyebut ialah jumlah bahagian sama besar.','Tahun 1 · Kongsi Sama Rata',true,true),id,mode,'story','concept',['fraction']);}
  return depth(Q(`${fractionStrip(n,d)}Bahagian berlorek mewakili?`,`${n}/${d}`,makeWrongFractions(`${n}/${d}`,n,d),'Kira semua bahagian sama besar dan bahagian berlorek.','Tahun 1 · Pecahan Visual',true,true),id,mode,'visual','concept',['fraction']);
 }
 if(id==='D1.MONEY'){mode=chooseMode(id,s,['recognise','combine','compare']);const cents=pick([10,20,50,100,200,500]);if(mode==='recognise')return depth(Q(`${typeof moneyVisual==='function'?moneyVisual(cents):''}Nilai wang ini ialah?`,typeof moneyFmt==='function'?moneyFmt(cents):`${cents} sen`,[N(cents<100?`${Math.max(5,cents-10)} sen`:`RM${cents/100+1}`,'money'),N(`${cents} RM`,'money'),N(cents,'money')],'Lihat nilai pada wang.','Tahun 1 · Kenal Wang',true,true),id,mode,'visual','concept',['money']);const a=pick([10,20,50,100]);let b=pick([10,20,50,100]);while(b===a)b=pick([10,20,50,100]);const sum=a+b;if(mode==='combine')return depth(Q(`${typeof moneyVisual==='function'?moneyVisual(a):''}${typeof moneyVisual==='function'?moneyVisual(b):''}Jumlah wang?`,typeof moneyFmt==='function'?moneyFmt(sum):sum,[N(typeof moneyFmt==='function'?moneyFmt(Math.abs(a-b)):Math.abs(a-b),'money'),N(typeof moneyFmt==='function'?moneyFmt(sum+10):sum+10,'money'),N(typeof moneyFmt==='function'?moneyFmt(Math.max(0,sum-10)):sum-10,'money')],'Tambah nilai kedua-dua wang.','Tahun 1 · Jumlah Wang',true,true),id,mode,'visual','procedure',['money']);return depth(Q(`Yang manakah lebih besar nilainya: ${typeof moneyFmt==='function'?moneyFmt(a):a} atau ${typeof moneyFmt==='function'?moneyFmt(b):b}?`,typeof moneyFmt==='function'?moneyFmt(Math.max(a,b)):Math.max(a,b),[N(typeof moneyFmt==='function'?moneyFmt(Math.min(a,b)):Math.min(a,b),'money'),N(typeof moneyFmt==='function'?moneyFmt(sum):sum,'money'),N('Sama nilai','money')],'Banding nilai wang.','Tahun 1 · Banding Wang',true,true),id,mode,'verbal','concept',['money']);}
 if(id==='D1.TIME'){mode=chooseMode(id,s,['hour','half_hour','daily_order']);if(mode==='daily_order'){let q=pick([['Sarapan','pagi'],['Tidur','malam'],['Makan tengah hari','tengah hari']]);return depth(Q(`Aktiviti <b>${q[0]}</b> biasanya berlaku pada waktu?`,q[1],[N('pagi','time'),N('tengah hari','time'),N('malam','time')].filter(x=>x.v!==q[1]),'Fikir rutin harian.','Tahun 1 · Waktu Harian',false,true),id,mode,'story','concept',['time']);}let h=R(1,12),m=mode==='half_hour'?30:0,ans=`${h}:${String(m).padStart(2,'0')}`;return depth(Q(`${clockSvg(h,m)}Jam menunjukkan pukul?`,ans,[N(`${h}:00`,'time'),N(`${h}:30`,'time'),N(`${h%12+1}:${String(m).padStart(2,'0')}`,'time')].filter(x=>x.v!==ans).slice(0,3),'Jarum pendek menunjukkan jam; jarum panjang menunjukkan minit.','Tahun 1 · Baca Jam',true,true),id,mode,'visual','concept',['time']);}
 if(id==='D1.MEASURE'){mode=chooseMode(id,s,['length_compare','mass_compare','capacity_compare']);if(mode==='length_compare'){let a=R(70,130),b=R(40,65);return depth(Q(`<div class="kssrDiagram kd-bars"><i style="width:${a}px"></i><i style="width:${b}px"></i></div>Batang manakah lebih panjang?`,'batang atas',[N('batang bawah','unit'),N('sama panjang','unit'),N('tidak boleh ditentukan','unit')],'Banding hujung kedua-dua batang.','Tahun 1 · Panjang',true,true),id,mode,'visual','concept',['unit']);}if(mode==='mass_compare')return depth(Q(`Sebuah tembikai dan sebiji anggur diletakkan pada penimbang. Yang manakah biasanya lebih berat?`,'tembikai',[N('anggur','unit'),N('sama berat','unit'),N('tidak boleh dibandingkan','unit')],'Banding objek berdasarkan jisim biasa.','Tahun 1 · Jisim',false,true),id,mode,'story','concept',['unit']);return depth(Q(`Antara baldi dan cawan, yang manakah biasanya boleh mengisi lebih banyak air?`,'baldi',[N('cawan','unit'),N('sama banyak','unit'),N('sudu','unit')],'Banding kapasiti bekas.','Tahun 1 · Isi Padu Cecair',false,true),id,mode,'story','concept',['unit']);}
 if(id==='D1.SHAPE'){mode=chooseMode(id,s,['identify2d','property2d','identify3d']);if(mode==='identify2d'){let sh=pick([['triangle','segi tiga'],['square','segi empat sama'],['circle','bulatan']]);return depth(Q(`${shapeSvg(sh[0])}Bentuk ini ialah?`,sh[1],[N('segi empat tepat','shape'),N('bulatan','shape'),N('segi tiga','shape')].filter(x=>x.v!==sh[1]).slice(0,3),'Perhatikan sisi dan bucu.','Tahun 1 · Bentuk 2D',true,true),id,mode,'visual','concept',['shape']);}if(mode==='property2d')return depth(Q(`${shapeSvg('triangle')}Berapakah bilangan sisi bentuk ini?`,3,[N(2,'shape'),N(4,'shape'),N(5,'shape')],'Kira sisi lurus.','Tahun 1 · Ciri Bentuk',true,true),id,mode,'visual','concept',['shape']);return depth(Q(`Objek manakah berbentuk seperti <b>kubus</b>?`,'dadu',[N('bola','shape'),N('tin minuman','shape'),N('pinggan','shape')],'Kubus mempunyai muka segi empat sama.','Tahun 1 · Bentuk 3D',false,true),id,mode,'story','concept',['shape']);}
 if(id==='D1.DATA'){mode=chooseMode(id,s,['most','count','difference']);let labels=['Epal','Oren','Pisang'],vals=[R(2,5),R(2,5),R(2,5)];while(new Set(vals).size<3)vals=[R(2,5),R(2,5),R(2,5)];let vis=pictograph(labels,vals);if(mode==='most'){let mx=Math.max(...vals),ans=labels[vals.indexOf(mx)];return depth(Q(`${vis}Buah manakah paling banyak?`,ans,labels.filter(x=>x!==ans).map(x=>N(x,'data')).concat([N('Sama banyak','data')]).slice(0,3),'Cari baris dengan simbol paling banyak.','Tahun 1 · Data',true,true),id,mode,'visual','concept',['data']);}if(mode==='count'){let i=R(0,2);return depth(Q(`${vis}Berapakah ${labels[i]}?`,vals[i],wrongNums(vals[i],1,'data'),'Kira simbol pada baris yang betul.','Tahun 1 · Baca Data',true,true),id,mode,'visual','concept',['data']);}let hi=vals.indexOf(Math.max(...vals)),lo=vals.indexOf(Math.min(...vals)),ans=vals[hi]-vals[lo];return depth(Q(`${vis}Berapa lebih ${labels[hi]} berbanding ${labels[lo]}?`,ans,wrongNums(ans,1,'data'),'Tolak bilangan kecil daripada bilangan besar.','Tahun 1 · Beza Data',true,true),id,mode,'visual','application',['data']);}
 return null;
}

// D3 — representation + equivalence + compatible-denominator operations.
function d3(id,s,shift){
 let mode;
 if(id==='D3.N10000'){mode=chooseMode(id,s,['compare','round','sequence']);let a=R(1000,9999);if(mode==='compare'){let b=R(1000,9999);while(a===b)b=R(1000,9999);return depth(Q(`Yang manakah lebih besar?<br><b>${a}</b> atau <b>${b}</b>`,Math.max(a,b),[N(Math.min(a,b),'compare'),N(Math.abs(a-b),'operation'),N(a+b,'operation')],'Banding digit dari kiri.','Tahun 3 · Nombor',true,shift),id,mode,'symbolic','concept',['compare']);}if(mode==='round'){let unit=pick([10,100,1000]),ans=Math.round(a/unit)*unit;return depth(Q(`Bundarkan <b>${a}</b> kepada ${unit===10?'puluh':unit===100?'ratus':'ribu'} terdekat.`,ans,[N(Math.floor(a/unit)*unit,'round'),N(Math.ceil(a/unit)*unit,'round'),N(a,'round')],'Lihat digit di sebelah kanan nilai yang dibundarkan.','Tahun 3 · Membundar',true,true),id,mode,'symbolic','procedure',['round']);}if(mode==='sequence'){let step=pick([25,50,100,250]),start=R(1000,7000),ans=start+3*step;return depth(Q(`${start}, ${start+step}, ${start+2*step}, ?`,ans,[N(ans-step,'pattern'),N(ans+step,'pattern'),N(start+3,'pattern')],'Cari beza yang tetap.','Tahun 3 · Pola Nombor',true,true),id,mode,'symbolic','reasoning',['pattern']);}return previous.d3?.(id,s,shift);}
 if(id==='D3.PV10000'){mode=chooseMode(id,s,['place','expanded','compose','missing_value']);let n=uniqueDigitNumber(4),st=String(n),pos=R(0,3),d=+st[pos],pow=3-pos,ans=d*10**pow;if(mode==='place')return depth(Q(`Nilai digit <b>${d}</b> dalam <b>${n}</b> ialah?`,ans,[N(d,'digit_value'),N(d*10**Math.max(0,pow-1),'place'),N(ans+100,'place')],'Nilai digit bergantung pada tempat.','Tahun 3 · Nilai Tempat',true,true),id,mode,'symbolic','concept',['place']);let vals=[+st[0]*1000,+st[1]*100,+st[2]*10,+st[3]];if(mode==='expanded')return depth(Q(`Cerakinkan <b>${n}</b>.`,vals.filter(v=>v).join(' + '),[N(st.split('').join(' + '),'digit_value'),N([...vals].reverse().join(' + '),'place'),N(`${n}+0`,'place')],'Tulis nilai sebenar setiap digit.','Tahun 3 · Cerakin',true,true),id,mode,'symbolic','procedure',['place']);if(mode==='missing_value'){return depth(Q(`<b>${n}</b> = ${vals.map((v,i)=>i===pos?'___':v).join(' + ')}<br>Nilai hilang?`,ans,[N(d,'digit_value'),N(ans+10,'place'),N(Math.max(0,ans-10),'place')],'Cari nilai tempat digit yang hilang.','Tahun 3 · Nilai Hilang',true,true),id,mode,'symbolic','reasoning',['place']);}return previous.d3?.(id,s,shift);}
 if(id==='D3.ADD10000'||id==='D3.SUB10000'){const add=id.includes('ADD');mode=chooseMode(id,s,['symbolic','story','missing']);let a=add?R(1500,7000):R(4000,9999),b=R(300,add?Math.min(2500,9999-a):Math.min(3500,a-1)),ans=add?a+b:a-b;if(mode==='story')return depth(Q(add?`Sebuah perpustakaan ada ${a} buku dan menerima ${b} lagi. Jumlah?`:`Sebuah stor ada ${a} kotak dan menghantar ${b}. Baki?`,ans,wrongNums(ans,100,'operation'),add?'Tambah kuantiti yang diterima.':'Tolak kuantiti yang keluar.','Tahun 3 · Masalah Operasi',true,true),id,mode,'story','application',['operation']);if(mode==='missing'){let total=add?ans:a;return depth(Q(add?`${a} + ___ = ${ans}`:`${a} − ___ = ${ans}`,b,[N(ans,'operation'),N(a,'operation'),N(Math.abs(a-b),'operation')],'Gunakan operasi songsang untuk cari nilai hilang.','Tahun 3 · Nilai Hilang',true,true),id,mode,'symbolic','reasoning',['operation']);}return depth(add?addQ(a,b,ans,'Tahun 3',shift):subQ(a,b,ans,'Tahun 3',shift),id,mode,'symbolic','procedure',['operation']);}
 if(id==='D3.MUL'){mode=chooseMode(id,s,['fact','array_story','two_digit','missing']);if(mode==='fact'){let a=R(2,12),b=R(2,12),ans=a*b;return depth(Q(`${a} × ${b} = ?`,ans,[N(a+b,'operation'),N(ans+a,'fact'),N(Math.max(1,ans-b),'fact')],'Gunakan fakta darab.','Tahun 3 · Darab',true,shift),id,mode,'symbolic','procedure',['fact']);}if(mode==='two_digit'){let a=R(12,99),b=R(2,9),ans=a*b;return depth(Q(`${a} × ${b} = ?`,ans,[N(ans+b,'fact'),N(a+b,'operation'),N(ans-10,'place')],'Darab sa dan puluh.','Tahun 3 · Darab',true,true),id,mode,'symbolic','procedure',['place','fact']);}if(mode==='missing'){let a=R(3,9),b=R(3,9),total=a*b;return depth(Q(`___ × ${b} = ${total}`,a,[N(b,'fact'),N(a+1,'fact'),N(Math.max(1,a-1),'fact')],'Gunakan fakta darab songsang.','Tahun 3 · Faktor Hilang',true,true),id,mode,'symbolic','reasoning',['fact']);}let groups=R(3,8),each=R(3,9),ans=groups*each;return depth(Q(`Ada ${groups} bakul, setiap bakul ada ${each} epal. Jumlah epal?`,ans,[N(groups+each,'operation'),N(ans+groups,'fact'),N(ans-each,'fact')],'Kumpulan sama banyak menggunakan darab.','Tahun 3 · Darab dalam Situasi',true,true),id,mode,'story','application',['fact']);}
 if(id==='D3.DIV'){mode=chooseMode(id,s,['exact','remainder','story','missing']);let d=R(2,9),q=R(3,12);if(mode==='remainder'){let rem=R(1,d-1),total=d*q+rem,ans=`${q} baki ${rem}`;return depth(Q(`${total} ÷ ${d} = ?`,ans,[N(q,'division'),N(`${q+1} baki ${rem}`,'division'),N(`${q} baki ${Math.max(0,rem-1)}`,'division')],'Cari kumpulan penuh dan baki.','Tahun 3 · Bahagi Berbaki',true,true),id,mode,'symbolic','procedure',['division']);}let total=d*q;if(mode==='story')return depth(Q(`${total} buku disusun sama rata pada ${d} rak. Setiap rak ada?`,q,[N(d,'division'),N(q+1,'division'),N(q-1,'division')],'Bahagi kepada kumpulan sama banyak.','Tahun 3 · Bahagi dalam Situasi',true,true),id,mode,'story','application',['division']);if(mode==='missing')return depth(Q(`${total} ÷ ___ = ${q}`,d,[N(q,'division'),N(d+1,'division'),N(Math.max(1,d-1),'division')],'Guna hubungan darab-bahagi.','Tahun 3 · Pembahagi Hilang',true,true),id,mode,'symbolic','reasoning',['division']);return depth(Q(`${total} ÷ ${d} = ?`,q,[N(d,'division'),N(q+1,'division'),N(q-1,'division')],'Gunakan fakta bahagi.','Tahun 3 · Bahagi',true,shift),id,mode,'symbolic','procedure',['division']);}
 if(id==='D3.FRAC'){
   mode=chooseMode(id,s,['group_fraction','equivalent','simplest','add_related','sub_related']);
   if(mode==='group_fraction'){let d=pick([4,5,6,8,10]),n=R(1,d-1);return depth(Q(`${fractionSet(n,d)}Apakah pecahan bulatan yang berlorek?`,`${n}/${d}`,makeWrongFractions('',n,d),'Pengangka ialah bilangan dipilih; penyebut jumlah objek.','Tahun 3 · Pecahan Kumpulan',true,true),id,mode,'visual','concept',['fraction']);}
   if(mode==='equivalent'){let d=pick([2,3,4,5]),n=R(1,d-1),k=pick([2,3]),ans=`${n*k}/${d*k}`;return depth(Q(`${fractionStrip(n,d)}Pecahan setara bagi <b>${n}/${d}</b>?`,ans,[N(`${n}/${d*k}`,'fraction'),N(`${n*k}/${d}`,'fraction'),N(`${n+k}/${d+k}`,'fraction')],'Darab pengangka dan penyebut dengan nombor sama.','Tahun 3 · Pecahan Setara',true,true),id,mode,'visual','concept',['fraction']);}
   if(mode==='simplest'){let base=pick([[2,4],[3,6],[4,8],[5,10],[6,9],[8,10]]),ans=frac(base[0],base[1]);return depth(Q(`Ringkaskan <b>${base[0]}/${base[1]}</b> kepada bentuk termudah.`,ans,[N(`${base[0]-1}/${base[1]}`,'fraction'),N(`${base[0]}/${base[1]-1}`,'fraction'),N(`${base[0]/gcd2(base[0],base[1])}/${base[1]}`,'fraction')],'Bahagi pengangka dan penyebut dengan faktor sepunya.','Tahun 3 · Bentuk Termudah',true,true),id,mode,'symbolic','procedure',['fraction']);}
   let related=pick([[2,4],[2,6],[2,8],[2,10],[3,6],[3,9],[5,10],[4,8]]),d1=related[0],d2=related[1],a=R(1,d1-1),b=R(1,d2-1),l=d2,n1=a*(l/d1),n2=b;
   if(mode==='sub_related'){let leftA=a,leftD=d1,rightA=b,rightD=d2,leftN=n1,rightN=n2;if(leftN<rightN){[leftA,rightA]=[rightA,leftA];[leftD,rightD]=[rightD,leftD];[leftN,rightN]=[rightN,leftN];}let ans=frac(leftN-rightN,l);return depth(Q(`${fractionStrip(leftA,leftD)}<b>${leftA}/${leftD} − ${rightA}/${rightD}</b> = ?`,ans,[N(frac(Math.abs(leftN-rightN),leftD+rightD),'fraction'),N(frac(leftN+rightN,l),'operation'),N(frac(Math.max(1,leftN-rightN+1),l),'fraction')],'Samakan penyebut dahulu.','Tahun 3 · Tolak Pecahan',true,true),id,mode,'visual','procedure',['fraction']);}
   let ans=frac(n1+n2,l);return depth(Q(`${fractionStrip(a,d1)}<b>${a}/${d1} + ${b}/${d2}</b> = ?`,ans,[N(frac(a+b,d1+d2),'fraction'),N(frac(n1*n2,l),'fraction'),N(frac(n1+n2,l+1),'fraction')],'Samakan penyebut dahulu.','Tahun 3 · Tambah Pecahan',true,true),id,mode,'visual','procedure',['fraction']);
 }
 if(id==='D3.DEC'){mode=chooseMode(id,s,['place','compare','fraction_link','add']);if(mode==='place'){let a=R(10,999)/100,txt=a.toFixed(2),digit=txt.split('.')[1][1];return depth(Q(`Dalam <b>${txt}</b>, nilai digit <b>${digit}</b> pada tempat perseratus ialah?`,`${digit}/100`,[N(`${digit}/10`,'place'),N(digit,'digit_value'),N(`${txt.split('.')[1][0]}/100`,'place')],'Digit kedua selepas titik ialah perseratus.','Tahun 3 · Nilai Perpuluhan',true,true),id,mode,'symbolic','concept',['decimal','place']);}if(mode==='fraction_link'){let p=pick([[1,10,'0.1'],[3,10,'0.3'],[25,100,'0.25'],[50,100,'0.5'],[75,100,'0.75']]);return depth(Q(`${hundredGrid(Math.round(Number(p[2])*100))}<b>${p[0]}/${p[1]}</b> bersamaan perpuluhan?`,p[2],[N(String(Number(p[2])*10),'decimal'),N(String(Number(p[2])+.1),'decimal'),N(String(Math.max(0,Number(p[2])-.1)),'decimal')],'Persepuluh/perseratus boleh ditulis sebagai perpuluhan.','Tahun 3 · Pecahan dan Perpuluhan',true,true),id,mode,'visual','concept',['decimal','fraction']);}if(mode==='compare'){let a=R(1,99)/100,b=R(1,99)/100;while(a===b)b=R(1,99)/100;let ans=a>b?'>':'<';return depth(Q(`${a.toFixed(2)} ___ ${b.toFixed(2)}`,ans,[N(ans==='>'?'<':'>','decimal'),N('=','decimal'),N('≠','decimal')],'Banding persepuluh kemudian perseratus.','Tahun 3 · Banding Perpuluhan',true,true),id,mode,'symbolic','concept',['decimal']);}let a=R(10,50)/10,b=R(1,30)/10,ans=a+b;return depth(Q(`${a.toFixed(1)} + ${b.toFixed(1)} = ?`,ans.toFixed(1),[N((ans+.1).toFixed(1),'decimal'),N((ans+1).toFixed(1),'decimal'),N((ans-.1).toFixed(1),'decimal')],'Selarikan titik perpuluhan.','Tahun 3 · Tambah Perpuluhan',true,true),id,mode,'symbolic','procedure',['decimal']);}
 if(id==='D3.MONEY'){mode=chooseMode(id,s,['change','total','multi_buy']);let price=R(8,60),pay=pick([50,100]);if(pay<price)pay=100;if(mode==='multi_buy'){let qty=pick([2,3,4]),p=R(5,25),total=p*qty;return depth(Q(`${qty} barang berharga RM${p} setiap satu. Jumlah?`,money(total),[N(money(p+qty),'money'),N(money(total+5),'money'),N(money(p),'money')],'Darab harga seunit dengan kuantiti.','Tahun 3 · Wang',true,true),id,mode,'story','application',['money']);}if(mode==='total'){let a=R(5,30),b=R(5,30),total=a+b;return depth(Q(`RM${a} + RM${b} = ?`,money(total),[N(money(Math.abs(a-b)),'money'),N(money(total+10),'money'),N(money(a),'money')],'Tambah ringgit dengan ringgit.','Tahun 3 · Operasi Wang',true,true),id,mode,'symbolic','procedure',['money']);}let ans=pay-price;return depth(Q(`Harga RM${price}, bayar RM${pay}. Baki?`,money(ans),[N(money(price),'money'),N(money(pay+price),'operation'),N(money(ans+10),'same_end')],'Baki = bayaran − harga.','Tahun 3 · Baki Wang',true,true),id,mode,'story','application',['money']);}
 if(id==='D3.TIME'){mode=chooseMode(id,s,['elapsed','end_time','timeline']);let h=R(7,10),m=pick([0,15,30,45]),dur=pick([30,45,60,75,90]),start=h*60+m,end=start+dur,fmt=x=>`${Math.floor(x/60)}:${String(x%60).padStart(2,'0')}`;if(mode==='elapsed'){return depth(Q(`${timeBar(start,end)}Berapa lama dari ${fmt(start)} hingga ${fmt(end)}?`,dur,[N(dur+15,'time'),N(Math.max(15,dur-15),'time'),N(end,'time')],'Kira beza masa mula dan tamat.','Tahun 3 · Tempoh Masa',true,true),id,mode,'visual','application',['time']);}return depth(Q(`Mula ${fmt(start)}, tempoh ${dur} minit. Tamat?`,fmt(end),[N(fmt(start),'time'),N(fmt(end+30),'time'),N(fmt(Math.max(0,end-30)),'time')],'Tambah tempoh kepada masa mula.','Tahun 3 · Masa Tamat',true,true),id,mode,mode==='timeline'?'visual':'story','application',['time']);}
 if(id==='D3.MEASURE'){mode=chooseMode(id,s,['length_convert','mass_convert','liquid_convert']);let type=mode==='mass_convert'?'mass':mode==='liquid_convert'?'liquid':'length';if(type==='mass'){let kg=R(1,5),g=pick([100,200,500]),ans=kg*1000+g;return depth(Q(`${kg} kg ${g} g = ? g`,ans,[N(kg+g,'unit'),N(kg*100+g,'unit'),N(ans+100,'unit')],'1 kg = 1000 g.','Tahun 3 · Jisim',true,true),id,mode,'symbolic','procedure',['unit']);}if(type==='liquid'){let L=R(1,5),ml=pick([100,250,500]),ans=L*1000+ml;return depth(Q(`${L} L ${ml} mL = ? mL`,ans,[N(L+ml,'unit'),N(L*100+ml,'unit'),N(ans+100,'unit')],'1 L = 1000 mL.','Tahun 3 · Isi Padu Cecair',true,true),id,mode,'symbolic','procedure',['unit']);}let cm=pick([150,200,250,300,350,400]),ans=cm/100;return depth(Q(`${cm} cm = ? m`,ans,[N(cm/10,'unit'),N(cm,'unit'),N(ans+1,'unit')],'100 cm = 1 m.','Tahun 3 · Panjang',true,true),id,mode,'symbolic','procedure',['unit']);}
 if(id==='D3.SHAPE'){mode=chooseMode(id,s,['perimeter','missing_side','property']);if(mode==='property')return depth(Q(`${shapeSvg('rectangle')}Segi empat tepat mempunyai berapa sisi?`,4,[N(2,'shape'),N(3,'shape'),N(5,'shape')],'Kira semua sisi.','Tahun 3 · Ciri Bentuk',true,true),id,mode,'visual','concept',['shape']);let l=R(4,12),w=R(2,8),p=2*(l+w);if(mode==='missing_side'){let given=p;return depth(Q(`Perimeter segi empat tepat ialah ${given} cm. Panjang ${l} cm. Lebarnya?`,w,[N(l,'shape'),N(p-l,'operation'),N(w+2,'shape')],'Perimeter = 2 × (panjang + lebar).','Tahun 3 · Sisi Hilang',true,true),id,mode,'symbolic','reasoning',['shape']);}return depth(Q(`${rectDiagram(l,w)}Perimeter?`,p,[N(l*w,'area'),N(l+w,'operation'),N(p+2,'shape')],'Jumlahkan semua sisi.','Tahun 3 · Perimeter',true,true),id,mode,'visual','procedure',['shape']);}
 if(id==='D3.DATA'){mode=chooseMode(id,s,['total','difference','read','pictograph']);let labels=['A','B','C','D'],vals=labels.map(()=>R(3,12)),vis=barChart(labels,vals);if(mode==='pictograph'){let pv=[R(2,6),R(2,6),R(2,6)],pl=['Buku','Pensel','Pemadam'],i=R(0,2);return depth(Q(`${pictograph(pl,pv)}Berapakah ${pl[i]}?`,pv[i],wrongNums(pv[i],1,'data'),'Kira simbol pada baris yang betul.','Tahun 3 · Piktograf',true,true),id,mode,'visual','concept',['data']);}if(mode==='read'){let i=R(0,3);return depth(Q(`${vis}Nilai kategori ${labels[i]} ialah?`,vals[i],wrongNums(vals[i],2,'data'),'Baca tinggi palang pada skala.','Tahun 3 · Baca Carta',true,true),id,mode,'visual','concept',['data']);}if(mode==='difference'){let hi=vals.indexOf(Math.max(...vals)),lo=vals.indexOf(Math.min(...vals)),ans=vals[hi]-vals[lo];return depth(Q(`${vis}Beza kategori tertinggi dan terendah?`,ans,wrongNums(ans,2,'data'),'Baca dua nilai, kemudian tolak.','Tahun 3 · Tafsir Data',true,true),id,mode,'visual','application',['data']);}let sum=vals.reduce((a,b)=>a+b,0);return depth(Q(`${vis}Jumlah semua data?`,sum,[N(Math.max(...vals),'data'),N(sum+4,'data'),N(sum-4,'data')],'Tambah semua nilai.','Tahun 3 · Jumlah Data',true,true),id,mode,'visual','application',['data']);}
 return null;
}

// D4 — mixed representations; beginning of upper-primary multi-step demand.
function d4(id,s,shift){
 let mode;
 if(id==='D4.N100000'){mode=chooseMode(id,s,['compare','round','sequence']);let a=R(10000,99999);if(mode==='round'){let unit=pick([10,100,1000,10000]),ans=Math.round(a/unit)*unit;return depth(Q(`Bundarkan <b>${a}</b> kepada ${unit.toLocaleString('en-US')} terdekat.`,ans,[N(Math.floor(a/unit)*unit,'round'),N(Math.ceil(a/unit)*unit,'round'),N(a,'round')],'Lihat digit penentu.','Tahun 4 · Membundar',true,true),id,mode,'symbolic','procedure',['round']);}if(mode==='sequence'){let st=R(10000,70000),step=pick([250,500,1000,2500]),ans=st+3*step;return depth(Q(`${st}, ${st+step}, ${st+2*step}, ?`,ans,[N(ans-step,'pattern'),N(ans+step,'pattern'),N(st+3,'pattern')],'Cari perubahan tetap.','Tahun 4 · Pola Nombor',true,true),id,mode,'symbolic','reasoning',['pattern']);}return previous.d4?.(id,s,shift);}
 if(id==='D4.PV100000'){mode=chooseMode(id,s,['place','missing']);let n=uniqueDigitNumber(5),st=String(n),pos=R(0,4),d=+st[pos],pow=4-pos,ans=d*10**pow;if(mode==='missing'){let vals=[+st[0]*10000,+st[1]*1000,+st[2]*100,+st[3]*10,+st[4]];return depth(Q(`${n} = ${vals.map((v,i)=>i===pos?'___':v).join(' + ')}<br>Nilai hilang?`,ans,[N(d,'digit_value'),N(ans+100,'place'),N(Math.max(0,ans-100),'place')],'Cari nilai tempat digit.','Tahun 4 · Nilai Tempat',true,true),id,mode,'symbolic','reasoning',['place']);}return previous.d4?.(id,s,shift);}
 if(id==='D4.ADD'||id==='D4.SUB'){const add=id==='D4.ADD';mode=chooseMode(id,s,['symbolic','story','three_step','missing']);let a=add?R(12000,60000):R(40000,99999),b=R(1000,add?Math.min(25000,99999-a):Math.min(25000,a-1000)),c=R(500,5000);if(add&&a+b+c>100000)c=0;if(!add&&a-b-c<0)c=0;let ans=add?a+b+(mode==='three_step'?c:0):a-b-(mode==='three_step'?c:0);if(mode==='story')return depth(Q(add?`Hari pertama ${a} pengunjung, hari kedua ${b}. Jumlah?`:`Stok ${a} unit. ${b} unit dijual. Baki?`,ans,wrongNums(ans,1000,'operation'),add?'Tambah kedua-dua kuantiti.':'Tolak yang telah digunakan.','Tahun 4 · Masalah Operasi',true,true),id,mode,'story','application',['operation']);if(mode==='three_step')return depth(Q(`${a} ${add?'+':'−'} ${b} ${add?'+':'−'} ${c} = ?`,ans,wrongNums(ans,100,'operation'),'Kira satu langkah pada satu masa.','Tahun 4 · Operasi Berurutan',true,true),id,mode,'symbolic','application',['operation']);if(mode==='missing'){let target=add?a+b:a-b;return depth(Q(add?`${a} + ___ = ${target}`:`${a} − ___ = ${target}`,b,[N(target,'operation'),N(a,'operation'),N(Math.abs(a-b),'operation')],'Gunakan operasi songsang.','Tahun 4 · Nilai Hilang',true,true),id,mode,'symbolic','reasoning',['operation']);}return depth(add?addQ(a,b,a+b,'Tahun 4',shift):subQ(a,b,a-b,'Tahun 4',shift),id,mode,'symbolic','procedure',['operation']);}
 if(id==='D4.MUL'){mode=chooseMode(id,s,['two_by_one','multi_story','missing','estimate']);let a=R(25,999),b=R(2,9),ans=a*b;if(mode==='multi_story')return depth(Q(`${b} kotak mengandungi ${a} unit setiap satu. Jumlah?`,ans,[N(a+b,'operation'),N(ans+b,'fact'),N(ans-10,'place')],'Darab kuantiti setiap kumpulan.','Tahun 4 · Darab dalam Situasi',true,true),id,mode,'story','application',['fact']);if(mode==='missing')return depth(Q(`___ × ${b} = ${ans}`,a,[N(b,'fact'),N(a+b,'operation'),N(a+10,'place')],'Bahagi hasil dengan faktor diketahui.','Tahun 4 · Faktor Hilang',true,true),id,mode,'symbolic','reasoning',['fact']);if(mode==='estimate'){let est=Math.round(a/100)*100*b;return depth(Q(`Anggaran munasabah bagi ${a} × ${b} ialah?`,est,[N(ans,'estimate'),N(Math.round(a/10)*10,'estimate'),N(est+b*100,'estimate')],'Bundarkan nombor besar dahulu.','Tahun 4 · Anggaran Darab',true,true),id,mode,'symbolic','reasoning',['estimate']);}return depth(Q(`${a} × ${b} = ?`,ans,[N(a+b,'operation'),N(ans+b,'fact'),N(Math.round(ans/100)*100,'fact')],'Darab mengikut nilai tempat.','Tahun 4 · Darab',true,true),id,mode,'symbolic','procedure',['fact','place']);}
 if(id==='D4.DIV'){mode=chooseMode(id,s,['exact','remainder','story','missing']);let d=R(2,9),q=R(20,300),rem=mode==='remainder'?R(1,d-1):0,total=d*q+rem,ans=rem?`${q} baki ${rem}`:q;if(mode==='story')return depth(Q(`${d*q} buku dibahagi sama rata kepada ${d} kelas. Setiap kelas dapat?`,q,[N(d,'division'),N(q+2,'division'),N(q-2,'division')],'Bahagi jumlah kepada kumpulan sama.','Tahun 4 · Bahagi dalam Situasi',true,true),id,mode,'story','application',['division']);if(mode==='missing')return depth(Q(`${d*q} ÷ ___ = ${q}`,d,[N(q,'division'),N(d+1,'division'),N(Math.max(1,d-1),'division')],'Gunakan hubungan darab-bahagi.','Tahun 4 · Pembahagi Hilang',true,true),id,mode,'symbolic','reasoning',['division']);return depth(Q(`${total} ÷ ${d} = ?`,ans,[N(q,'division'),N(rem?`${q+1} baki ${rem}`:q+2,'division'),N(rem?`${q} baki ${Math.max(0,rem-1)}`:q-2,'division')],'Cari hasil bahagi dan baki jika ada.','Tahun 4 · Bahagi',true,true),id,mode,'symbolic','procedure',['division']);}
 if(id==='D4.FRAC'){
   mode=chooseMode(id,s,['improper_to_mixed','mixed_to_improper','add_three','subtract','mixed_operation','fraction_quantity']);
   if(mode==='improper_to_mixed'){let d=pick([2,3,4,5,6,8,10]),n=R(d+1,d*4-1),ans=mixed(n,d);return depth(Q(`Tukar <b>${n}/${d}</b> kepada nombor bercampur.`,ans,[N(`${Math.floor(n/d)} ${n%d+1}/${d}`,'fraction'),N(`${n-d}/${d}`,'fraction'),N(`${Math.ceil(n/d)} ${n%d}/${d}`,'fraction')],'Bahagi pengangka dengan penyebut.','Tahun 4 · Pecahan Tak Wajar',true,true),id,mode,'symbolic','procedure',['fraction']);}
   if(mode==='mixed_to_improper'){let d=pick([2,3,4,5,6,8,10]),w=R(1,4),n=R(1,d-1),ans=`${w*d+n}/${d}`;return depth(Q(`Tukar <b>${w} ${n}/${d}</b> kepada pecahan tak wajar.`,ans,[N(`${w+n}/${d}`,'fraction'),N(`${w*d-n}/${d}`,'fraction'),N(`${w*d+n}/${d+1}`,'fraction')],'Darab nombor bulat dengan penyebut, tambah pengangka.','Tahun 4 · Nombor Bercampur',true,true),id,mode,'symbolic','procedure',['fraction']);}
   if(mode==='fraction_quantity'){let d=pick([2,3,4,5,6,8,10]),n=R(1,d-1),qty=d*R(3,12),ans=qty*n/d;return depth(Q(`${fractionStrip(n,d)}<b>${n}/${d}</b> daripada ${qty} ialah?`,ans,[N(qty/d,'fraction'),N(qty*n,'operation'),N(qty-n,'operation')],'Bahagi jumlah kepada penyebut, kemudian darab pengangka.','Tahun 4 · Pecahan daripada Kuantiti',true,true),id,mode,'visual','application',['fraction']);}
   let d=pick([4,5,6,8,10]),a=R(1,d-1),b=R(1,d-1),c=R(1,d-1);
   if(mode==='add_three'){let ans=frac(a+b+c,d);return depth(Q(`${a}/${d} + ${b}/${d} + ${c}/${d} = ?`,ans,[N(frac(a+b,d),'fraction'),N(frac(a+b+c,d+1),'fraction'),N(frac(a*b*c,d),'fraction')],'Penyebut sama: tambah semua pengangka, kemudian ringkaskan.','Tahun 4 · Tambah Pecahan',true,true),id,mode,'symbolic','application',['fraction']);}
   if(mode==='subtract'){let hi=Math.max(a,b),lo=Math.min(a,b),ans=frac(hi-lo,d);return depth(Q(`${hi}/${d} − ${lo}/${d} = ?`,ans,[N(frac(hi+lo,d),'operation'),N(frac(hi-lo,d+1),'fraction'),N(frac(Math.max(1,hi-lo+1),d),'fraction')],'Penyebut sama, tolak pengangka.','Tahun 4 · Tolak Pecahan',true,true),id,mode,'symbolic','procedure',['fraction']);}
   let first=Math.max(a,b),ans=frac(first+b-c,d);if(first+b-c<=0)return d4(id,s,shift);return depth(Q(`${first}/${d} + ${b}/${d} − ${c}/${d} = ?`,ans,[N(frac(first+b+c,d),'operation'),N(frac(first+b-c,d+1),'fraction'),N(frac(first-c,d),'fraction')],'Buat tambah dan tolak mengikut urutan.','Tahun 4 · Operasi Gabungan Pecahan',true,true),id,mode,'symbolic','application',['fraction']);
 }
 if(id==='D4.DEC'){mode=chooseMode(id,s,['add_three','subtract_two','multiply','divide','place']);if(mode==='place'){let n=R(100,9999)/1000,txt=n.toFixed(3),d=txt.split('.')[1][2];return depth(Q(`Nilai digit <b>${d}</b> pada tempat perseribu dalam <b>${txt}</b>?`,`${d}/1000`,[N(`${d}/100`,'place'),N(`${d}/10`,'place'),N(d,'digit_value')],'Digit ketiga selepas titik ialah perseribu.','Tahun 4 · Nilai Perpuluhan',true,true),id,mode,'symbolic','concept',['decimal']);}if(mode==='multiply'){let a=R(10,999)/100,b=pick([2,3,4,5,10,100]),ans=tidyNumber(a*b,3);return depth(Q(`${decimalFmt(a,2)} × ${b} = ?`,String(ans),[N(String(tidyNumber(ans+.1,3)),'decimal'),N(String(tidyNumber(ans+1,3)),'decimal'),N(String(tidyNumber(a+b,3)),'operation')],'Darab nilai, kemudian letak titik perpuluhan dengan betul.','Tahun 4 · Darab Perpuluhan',true,true),id,mode,'symbolic','procedure',['decimal']);}if(mode==='divide'){let b=pick([2,4,5,10,100]),ans=R(10,200)/100,a=tidyNumber(ans*b,3);return depth(Q(`${a} ÷ ${b} = ?`,String(tidyNumber(ans,3)),[N(String(tidyNumber(ans+.1,3)),'decimal'),N(String(tidyNumber(ans*10,3)),'decimal'),N(String(tidyNumber(a-b,3)),'operation')],'Bahagi dan semak kedudukan titik perpuluhan.','Tahun 4 · Bahagi Perpuluhan',true,true),id,mode,'symbolic','procedure',['decimal']);}let a=R(100,9000)/1000,b=R(10,2500)/1000,c=R(10,1200)/1000;if(mode==='subtract_two'){if(a<b+c)a=b+c+R(100,1000)/1000;let ans=tidyNumber(a-b-c,3);return depth(Q(`${a.toFixed(3)} − ${b.toFixed(3)} − ${c.toFixed(3)} = ?`,ans.toFixed(3),[N((ans+.1).toFixed(3),'decimal'),N((ans+.01).toFixed(3),'decimal'),N((ans-.01).toFixed(3),'decimal')],'Selarikan titik perpuluhan dan tolak satu demi satu.','Tahun 4 · Tolak Perpuluhan',true,true),id,mode,'symbolic','application',['decimal']);}let ans=tidyNumber(a+b+c,3);return depth(Q(`${a.toFixed(3)} + ${b.toFixed(3)} + ${c.toFixed(3)} = ?`,ans.toFixed(3),[N((ans+.1).toFixed(3),'decimal'),N((ans+.01).toFixed(3),'decimal'),N((ans-.01).toFixed(3),'decimal')],'Selarikan titik dan tambah sehingga tiga nombor.','Tahun 4 · Tambah Perpuluhan',true,true),id,mode,'symbolic','application',['decimal']);}
 if(id==='D4.MONEY'){mode=chooseMode(id,s,['multi_item','change','budget','compare_deal']);if(mode==='multi_item'){let p=R(8,45),q=pick([2,3,4]),fee=pick([0,5,10]),ans=p*q+fee;return depth(Q(`${q} buku berharga RM${p} setiap satu${fee?` dan caj RM${fee}`:''}. Jumlah?`,money(ans),[N(money(p+q+fee),'operation'),N(money(p*q),'money'),N(money(ans+10),'money')],'Darab harga dengan kuantiti, kemudian tambah caj jika ada.','Tahun 4 · Masalah Wang',true,true),id,mode,'story','application',['money']);}if(mode==='budget'){let budget=pick([100,150,200]),a=R(20,60),b=R(10,50),ans=budget-a-b;return depth(Q(`Bajet RM${budget}. Belanja RM${a} dan RM${b}. Baki bajet?`,money(ans),[N(money(budget-a),'money'),N(money(a+b),'operation'),N(money(ans+10),'same_end')],'Tolak semua perbelanjaan daripada bajet.','Tahun 4 · Bajet',true,true),id,mode,'story','application',['money']);}if(mode==='change'){let price=R(25,85),pay=100,ans=pay-price;return depth(Q(`Harga barang RM${price}. Bayar RM${pay}. Baki?`,money(ans),[N(money(price),'money'),N(money(pay+price),'operation'),N(money(ans+10),'same_end')],'Baki = bayaran − harga.','Tahun 4 · Baki Wang',true,true),id,mode,'story','application',['money']);}let p1=R(15,35),q1=2,p2=p1*2-R(1,5),ans='Pakej B';return depth(Q(`${miniTable(['Pilihan','Harga'],[['Pakej A',`2 × RM${p1}`],['Pakej B',`RM${p2}`]])}Pilihan manakah lebih murah?`,ans,[N('Pakej A','money'),N('Sama harga','money'),N('Tidak boleh ditentukan','money')],'Kira jumlah Pakej A dahulu, kemudian banding.','Tahun 4 · Banding Harga',true,true),id,mode,'table','reasoning',['money']);}
 if(id==='D4.TIME'){mode=chooseMode(id,s,['clock24','duration','convert','add_time','timeline']);if(mode==='clock24'){let h=R(13,23),m=pick([0,15,30,45]),ans=`${h}:${String(m).padStart(2,'0')}`;return depth(Q(`Pukul ${h-12}:${String(m).padStart(2,'0')} petang dalam sistem 24 jam ialah?`,ans,[N(`${h-12}:${String(m).padStart(2,'0')}`,'time'),N(`${h+1}:${String(m).padStart(2,'0')}`,'time'),N(`${h}:00`,'time')],'Selepas 12 tengah hari, tambah 12 pada jam.','Tahun 4 · Sistem 24 Jam',true,true),id,mode,'symbolic','procedure',['time']);}if(mode==='convert'){let dekad=R(2,8),ans=dekad*10;return depth(Q(`${dekad} dekad = ? tahun`,ans,[N(dekad*100,'time'),N(dekad,'time'),N(ans+10,'time')],'1 dekad = 10 tahun.','Tahun 4 · Hubungan Masa',true,true),id,mode,'symbolic','procedure',['time']);}let start=R(7,16)*60+pick([0,15,30,45]),dur=pick([35,45,60,75,90,120]),end=start+dur,fmt=x=>`${Math.floor(x/60)}:${String(x%60).padStart(2,'0')}`;if(mode==='duration')return depth(Q(`${timeBar(start,end)}Tempoh perjalanan?`,dur,[N(dur+15,'time'),N(dur-15,'time'),N(end,'time')],'Cari beza antara masa tamat dan mula.','Tahun 4 · Tempoh',true,true),id,mode,'visual','application',['time']);return depth(Q(`Mula ${fmt(start)}, tempoh ${dur} minit. Tamat?`,fmt(end),[N(fmt(start),'time'),N(fmt(end+30),'time'),N(fmt(end-30),'time')],'Tambah tempoh pada masa mula.','Tahun 4 · Jadual Masa',true,true),id,mode,mode==='timeline'?'visual':'story','application',['time']);}
 if(id==='D4.MEASURE'){mode=chooseMode(id,s,['length','mass','liquid','compare']);const t=pick(['length','mass','liquid']);if(t==='length'){let m=R(1,9),cm=R(1,19)*5,ans=m*100+cm;return depth(Q(`${m} m ${cm} cm = ? cm`,ans,[N(m+cm,'unit'),N(m*10+cm,'unit'),N(ans+10,'unit')],'1 m = 100 cm.','Tahun 4 · Panjang',true,true),id,'length','symbolic','procedure',['unit']);}if(t==='mass'){let kg=R(1,8),g=R(1,9)*100,ans=kg*1000+g;return depth(Q(`${kg} kg ${g} g = ? g`,ans,[N(kg+g,'unit'),N(kg*100+g,'unit'),N(ans+100,'unit')],'1 kg = 1000 g.','Tahun 4 · Jisim',true,true),id,'mass','symbolic','procedure',['unit']);}let L=R(1,8),ml=R(1,9)*100,ans=L*1000+ml;return depth(Q(`${L} L ${ml} mL = ? mL`,ans,[N(L+ml,'unit'),N(L*100+ml,'unit'),N(ans+100,'unit')],'1 L = 1000 mL.','Tahun 4 · Isi Padu Cecair',true,true),id,'liquid','symbolic','procedure',['unit']);}
 if(id==='D4.PERIM'){mode=chooseMode(id,s,['rectangle','missing_side','composite']);let l=R(5,15),w=R(3,10),p=2*(l+w);if(mode==='missing_side')return depth(Q(`Perimeter segi empat tepat ${p} cm dan panjang ${l} cm. Lebar?`,w,[N(l,'shape'),N(p-l,'operation'),N(w+2,'shape')],'Bahagikan perimeter kepada dua, kemudian tolak panjang.','Tahun 4 · Sisi Hilang',true,true),id,mode,'symbolic','reasoning',['shape']);if(mode==='composite'){let a=R(6,12),b=R(4,8),cut=R(2,Math.min(4,b-1)),ans=2*(a+b);return depth(Q(`${rectDiagram(a,b,cut)}Bentuk L ini terbentuk dengan memotong satu penjuru segi empat tepat. Jika potongan tidak mengubah jumlah sisi luar mendatar/menegak, perimeter asal ${a} cm × ${b} cm ialah?`,ans,[N(a*b,'area'),N(2*(a+b-cut),'shape'),N(a+b,'operation')],'Jejaki semua sisi luar; sisi yang dipotong diganti oleh sisi sama panjang.','Tahun 4 · Perimeter Komposit',true,true),id,mode,'visual','reasoning',['shape']);}return depth(Q(`${rectDiagram(l,w)}Perimeter?`,p,[N(l*w,'area'),N(l+w,'operation'),N(p+4,'shape')],'Perimeter = 2 × (panjang + lebar).','Tahun 4 · Perimeter',true,true),id,mode,'visual','procedure',['shape']);}
 if(id==='D4.DATA'){mode=chooseMode(id,s,['read','difference','total','two_step']);let labels=['Isnin','Selasa','Rabu','Khamis'],vals=labels.map(()=>R(10,35)),vis=barChart(labels,vals);if(mode==='read'){let i=R(0,3);return depth(Q(`${vis}Nilai pada ${labels[i]}?`,vals[i],wrongNums(vals[i],5,'data'),'Baca skala palang.','Tahun 4 · Baca Data',true,true),id,mode,'visual','concept',['data']);}if(mode==='difference'){let hi=vals.indexOf(Math.max(...vals)),lo=vals.indexOf(Math.min(...vals)),ans=vals[hi]-vals[lo];return depth(Q(`${vis}Beza nilai tertinggi dan terendah?`,ans,wrongNums(ans,5,'data'),'Tolak nilai rendah daripada nilai tinggi.','Tahun 4 · Tafsir Data',true,true),id,mode,'visual','application',['data']);}if(mode==='two_step'){let i=R(0,1),ans=vals[i]+vals[i+1];return depth(Q(`${vis}Jumlah ${labels[i]} dan ${labels[i+1]}?`,ans,[N(vals[i],'data'),N(vals[i+1],'data'),N(ans+5,'data')],'Baca dua palang kemudian tambah.','Tahun 4 · Data Dua Langkah',true,true),id,mode,'visual','application',['data']);}let sum=vals.reduce((a,b)=>a+b,0);return depth(Q(`${vis}Jumlah semua empat hari?`,sum,[N(Math.max(...vals),'data'),N(sum+10,'data'),N(sum-10,'data')],'Tambah semua nilai.','Tahun 4 · Jumlah Data',true,true),id,mode,'visual','application',['data']);}
 return null;
}

// D5 — actual upper-primary shift: fraction multiplication, decimal ×/÷, >100% ideas, richer time/measure.
function d5(id,s,shift){
 let mode;
 if(id==='D5.N1000000'){mode=chooseMode(id,s,['compare','round','sequence','fraction_million']);if(mode==='round'){let n=R(100000,999999),unit=pick([1000,10000,100000]),ans=Math.round(n/unit)*unit;return depth(Q(`Bundarkan <b>${n}</b> kepada ${unit.toLocaleString('en-US')} terdekat.`,ans,[N(Math.floor(n/unit)*unit,'round'),N(Math.ceil(n/unit)*unit,'round'),N(n,'round')],'Lihat digit penentu di sebelah kanan nilai tempat.','Tahun 5 · Membundar',true,true),id,mode,'symbolic','procedure',['round']);}if(mode==='sequence'){let n=R(100000,700000),step=pick([2500,5000,10000,25000]),ans=n+3*step;return depth(Q(`${n}, ${n+step}, ${n+2*step}, ?`,ans,[N(ans-step,'pattern'),N(ans+step,'pattern'),N(n+3,'pattern')],'Cari perubahan tetap antara nombor.','Tahun 5 · Pola Nombor',true,true),id,mode,'symbolic','reasoning',['pattern']);}if(mode==='fraction_million'){let f=pick([[1,2,500000],[1,4,250000],[3,4,750000],[1,5,200000]]);return depth(Q(`<b>${f[0]}/${f[1]}</b> daripada 1 000 000 ialah?`,f[2],[N(f[2]/10,'place'),N(f[1]*100000,'operation'),N(1000000-f[2],'fraction')],'Bahagi sejuta mengikut penyebut, kemudian darab pengangka.','Tahun 5 · Pecahan Sejuta',true,true),id,mode,'symbolic','application',['fraction']);}return previous.d5?.(id,s,shift);}
 if(id==='D5.PV1000000'){mode=chooseMode(id,s,['place','expanded','missing','compose']);let n=uniqueDigitNumber(6),st=String(n),pos=R(0,5),vals=[+st[0]*100000,+st[1]*10000,+st[2]*1000,+st[3]*100,+st[4]*10,+st[5]],ans=vals[pos];if(mode==='missing')return depth(Q(`${n} = ${vals.map((v,i)=>i===pos?'___':v).join(' + ')}<br>Nilai hilang?`,ans,[N(+st[pos],'digit_value'),N(ans+1000,'place'),N(Math.max(0,ans-1000),'place')],'Gunakan nilai tempat hingga ratus ribu.','Tahun 5 · Nilai Tempat',true,true),id,mode,'symbolic','reasoning',['place']);if(mode==='expanded')return depth(Q(`Cerakinkan <b>${n}</b>.`,vals.filter(v=>v).join(' + '),[N(st.split('').join(' + '),'digit_value'),N([...vals].reverse().join(' + '),'place'),N(`${n}+0`,'place')],'Tulis nilai sebenar setiap digit.','Tahun 5 · Cerakin',true,true),id,mode,'symbolic','procedure',['place']);if(mode==='compose')return depth(Q(`${vals.filter(v=>v).join(' + ')} = ?`,n,[N(Number(st.split('').reverse().join('')),'place'),N(vals.reduce((a,b)=>a+b,0)+1000,'place'),N(st.split('').map(Number).reduce((a,b)=>a+b,0),'digit_value')],'Gabungkan semua nilai tempat.','Tahun 5 · Bina Nombor',true,true),id,mode,'symbolic','procedure',['place']);return depth(Q(`Nilai digit <b>${st[pos]}</b> dalam <b>${n}</b>?`,ans,[N(+st[pos],'digit_value'),N(ans/10,'place'),N(ans*10,'place')],'Kenal pasti kedudukan digit.','Tahun 5 · Nilai Digit',true,true),id,mode,'symbolic','concept',['place']);}
 if(id==='D5.MUL'){mode=chooseMode(id,s,['two_digit','story','missing','estimate']);let a=R(100,999),b=R(11,25),ans=a*b;if(mode==='story')return depth(Q(`${b} kotak, ${a} unit setiap kotak. Jumlah unit?`,ans,[N(a+b,'operation'),N(ans+b,'fact'),N(ans-100,'place')],'Darab kuantiti seunit dengan bilangan kotak.','Tahun 5 · Darab dalam Situasi',true,true),id,mode,'story','application',['fact']);if(mode==='missing')return depth(Q(`___ × ${b} = ${ans}`,a,[N(b,'fact'),N(a+b,'operation'),N(a+100,'place')],'Bahagi hasil dengan faktor diketahui.','Tahun 5 · Faktor Hilang',true,true),id,mode,'symbolic','reasoning',['fact']);if(mode==='estimate'){let ea=Math.round(a/100)*100,eb=Math.round(b/10)*10,e=ea*eb;return depth(Q(`Anggaran munasabah bagi ${a} × ${b}?`,e,[N(ans,'estimate'),N(ea+eb,'estimate'),N(e+1000,'estimate')],'Bundarkan kedua-dua faktor untuk anggaran.','Tahun 5 · Anggaran Darab',true,true),id,mode,'symbolic','reasoning',['estimate']);}return depth(Q(`${a} × ${b} = ?`,ans,[N(a+b,'operation'),N(ans+10,'fact'),N(Math.round(ans/100)*100,'fact')],'Darab mengikut nilai tempat.','Tahun 5 · Darab Pelbagai Digit',true,true),id,mode,'symbolic','procedure',['fact','place']);}
 if(id==='D5.DIV'){mode=chooseMode(id,s,['two_digit','remainder','story','missing']);let d=pick([12,15,20,24,25]),q=R(12,80),rem=mode==='remainder'?R(1,d-1):0,total=d*q+rem,ans=rem?`${q} baki ${rem}`:q;if(mode==='story'){return depth(Q(`${d*q} risalah dibahagi sama rata kepada ${d} kelas. Setiap kelas?`,q,[N(d,'division'),N(q+5,'division'),N(q-5,'division')],'Bahagi jumlah dengan bilangan kelas.','Tahun 5 · Bahagi dalam Situasi',true,true),id,mode,'story','application',['division']);}if(mode==='missing')return depth(Q(`${d*q} ÷ ___ = ${q}`,d,[N(q,'division'),N(d+5,'division'),N(Math.max(1,d-5),'division')],'Gunakan operasi songsang.','Tahun 5 · Pembahagi Hilang',true,true),id,mode,'symbolic','reasoning',['division']);return depth(Q(`${total} ÷ ${d} = ?`,ans,[N(q,'division'),N(rem?`${q+1} baki ${rem}`:q+5,'division'),N(rem?`${q} baki ${Math.max(0,rem-1)}`:q-5,'division')],'Bahagi dengan pembahagi dua digit.','Tahun 5 · Bahagi Pelbagai Digit',true,true),id,mode,'symbolic','procedure',['division']);}
 if(id==='D5.FRAC'){
   mode=chooseMode(id,s,['proper_x_whole','proper_x_proper','mixed_x_whole','mixed_x_proper','visual_model']);
   if(mode==='proper_x_whole'){let d=pick([2,3,4,5,6,8,10]),n=R(1,d-1),w=R(2,9),ans=frac(n*w,d);return depth(Q(`<b>${n}/${d} × ${w}</b> = ?`,ans,[N(frac(n+w,d),'fraction'),N(frac(n*w,d*w),'fraction'),N(frac(n,d*w),'fraction')],'Darab pengangka dengan nombor bulat, kemudian ringkaskan.','Tahun 5 · Darab Pecahan',true,true),id,mode,'symbolic','procedure',['fraction']);}
   if(mode==='proper_x_proper'){let d1=pick([2,3,4,5,6,8,10]),n1=R(1,d1-1),d2=pick([2,3,4,5,6,8,10]),n2=R(1,d2-1),ans=frac(n1*n2,d1*d2);return depth(Q(`${fractionStrip(n1,d1)}<b>${n1}/${d1} × ${n2}/${d2}</b> = ?`,ans,[N(frac(n1+n2,d1+d2),'fraction'),N(frac(n1*n2,d1+d2),'fraction'),N(frac(n1+n2,d1*d2),'fraction')],'Darab pengangka dengan pengangka dan penyebut dengan penyebut.','Tahun 5 · Darab Dua Pecahan',true,true),id,mode,'visual','procedure',['fraction']);}
   if(mode==='visual_model'){let d=pick([2,3,4,5,6,8,10]),n=R(1,d-1),k=pick([2,3,4]),ans=frac(n*k,d);return depth(Q(`${fractionStrip(n,d)}Gambar mewakili <b>${n}/${d}</b>. Jika kuantiti ini diambil <b>${k} kali</b>, hasil ${n}/${d} × ${k} ialah?`,ans,[N(frac(n+k,d),'fraction'),N(frac(n,d*k),'fraction'),N(frac(n*k,d*k),'fraction')],'Darab pecahan bermaksud mengambil pecahan itu berulang kali.','Tahun 5 · Model Darab Pecahan',true,true),id,mode,'visual','concept',['fraction']);}
   let d=pick([2,3,4,5,6,8,10]),w=R(1,3),n=R(1,d-1),im=w*d+n;
   if(mode==='mixed_x_whole'){let k=R(2,5),ans=mixed(im*k,d);return depth(Q(`<b>${w} ${n}/${d} × ${k}</b> = ?`,ans,[N(frac(im+k,d),'fraction'),N(mixed(im*k,d*k),'fraction'),N(String(w*k),'fraction')],'Tukar nombor bercampur kepada pecahan tak wajar dahulu.','Tahun 5 · Darab Nombor Bercampur',true,true),id,mode,'symbolic','application',['fraction']);}
   let d2=pick([2,3,4,5,6,8,10]),n2=R(1,d2-1),ans=mixed(im*n2,d*d2);return depth(Q(`<b>${w} ${n}/${d} × ${n2}/${d2}</b> = ?`,ans,[N(frac(im+n2,d+d2),'fraction'),N(mixed(im*n2,d+d2),'fraction'),N(frac(im,d),'fraction')],'Tukar kepada pecahan tak wajar, kemudian darab dan ringkaskan.','Tahun 5 · Darab Pecahan Bercampur',true,true),id,mode,'symbolic','application',['fraction']);
 }
 if(id==='D5.DEC'){mode=chooseMode(id,s,['round3','combined','multiply','divide','place']);if(mode==='round3'){let n=R(10000,99999)/10000,ans=Number(n.toFixed(3));return depth(Q(`Bundarkan <b>${n.toFixed(4)}</b> kepada 3 tempat perpuluhan.`,ans.toFixed(3),[N(n.toFixed(4),'decimal'),N(n.toFixed(2),'decimal'),N((ans+.001).toFixed(3),'decimal')],'Lihat digit keempat selepas titik.','Tahun 5 · Bundar Perpuluhan',true,true),id,mode,'symbolic','procedure',['round','decimal']);}if(mode==='multiply'){let a=R(100,9999)/1000,b=pick([12,15,20,25,100,1000]),ans=tidyNumber(a*b,3);return depth(Q(`${a} × ${b} = ?`,String(ans),[N(String(tidyNumber(ans+.1,3)),'decimal'),N(String(tidyNumber(a+b,3)),'operation'),N(String(tidyNumber(ans/10,3)),'decimal')],'Darab dan semak kedudukan titik perpuluhan.','Tahun 5 · Darab Perpuluhan',true,true),id,mode,'symbolic','procedure',['decimal']);}if(mode==='divide'){let d=pick([4,5,10,20,25,100,1000]),ans=R(10,500)/100,a=tidyNumber(ans*d,3);return depth(Q(`${a} ÷ ${d} = ?`,String(tidyNumber(ans,3)),[N(String(tidyNumber(ans*10,3)),'decimal'),N(String(tidyNumber(ans+.1,3)),'decimal'),N(String(tidyNumber(a-d,3)),'operation')],'Bahagi dan semak nilai tempat perpuluhan.','Tahun 5 · Bahagi Perpuluhan',true,true),id,mode,'symbolic','procedure',['decimal']);}let a=R(1000,9000)/1000,b=R(100,2500)/1000,c=R(100,1800)/1000;if(a+b<c)c=R(100,900)/1000;let ans=tidyNumber(a+b-c,3);return depth(Q(`${a.toFixed(3)} + ${b.toFixed(3)} − ${c.toFixed(3)} = ?`,ans.toFixed(3),[N((ans+.1).toFixed(3),'decimal'),N((ans+.01).toFixed(3),'decimal'),N((ans-.01).toFixed(3),'decimal')],'Selarikan titik, selesaikan mengikut urutan.','Tahun 5 · Operasi Gabungan Perpuluhan',true,true),id,mode,'symbolic','application',['decimal']);}
 if(id==='D5.PERCENT'){mode=chooseMode(id,s,['mixed_to_percent','over100_quantity','inverse','visual']);if(mode==='mixed_to_percent'){let p=pick([[1,1,2,150],[1,1,4,125],[2,1,2,250],[1,3,4,175]]);return depth(Q(`Tukar <b>${p[0]} ${p[1]}/${p[2]}</b> kepada peratus.`,`${p[3]}%`,[N(`${p[3]-100}%`,'percent'),N(`${p[0]*100}%`,'percent'),N(`${p[3]+25}%`,'percent')],'Tukar nombor bercampur kepada perpuluhan/pecahan per 100.','Tahun 5 · Peratus Lebih 100',true,true),id,mode,'symbolic','procedure',['percent']);}if(mode==='over100_quantity'){let pct=pick([110,120,125,150,175,200]),base=pick([40,80,100,120,160]),ans=base*pct/100;return depth(Q(`${pct}% daripada ${base} = ?`,ans,[N(base,'percent'),N(base*(pct-100)/100,'percent'),N(base+pct,'operation')],'100% ialah keseluruhan; lebih 100% melebihi nilai asal.','Tahun 5 · Nilai Peratus',true,true),id,mode,'symbolic','application',['percent']);}if(mode==='inverse'){let pct=pick([25,50,75,125,150]),whole=pick([40,80,120,160]),part=whole*pct/100;return depth(Q(`${part} ialah <b>${pct}%</b> daripada suatu nilai. Nilai asal?`,whole,[N(part,'percent'),N(part*pct/100,'percent'),N(whole+20,'operation')],'Bahagi nilai diberi dengan kadar peratus dalam bentuk perpuluhan.','Tahun 5 · Nilai Asal',true,true),id,mode,'symbolic','reasoning',['percent']);}let pct=pick([25,50,75,125]);return depth(Q(`${pct<=100?hundredGrid(pct):''}Peratus yang ditunjukkan/ditanya ialah <b>${pct}%</b>. Dalam bentuk perpuluhan?`,String(pct/100),[N(String(pct/10),'percent'),N(String(100/pct),'percent'),N(String(pct),'percent')],'Bahagi peratus dengan 100.','Tahun 5 · Hubungan Peratus',true,true),id,mode,'visual','concept',['percent']);}
 if(id==='D5.MONEY'){mode=chooseMode(id,s,['discount','budget','compare_deal','multi_step']);if(mode==='discount'){let price=pick([40,60,80,100,120,160]),disc=pick([10,20,25]),off=price*disc/100,ans=price-off;return depth(Q(`Harga RM${price}, diskaun ${disc}%. Harga selepas diskaun?`,money(ans),[N(money(off),'percent'),N(money(price+off),'operation'),N(money(ans+10),'same_end')],'Cari nilai diskaun, kemudian tolak.','Tahun 5 · Diskaun',true,true),id,mode,'story','application',['money','percent']);}if(mode==='budget'){let budget=pick([300,400,500]),a=R(60,150),b=R(40,120),c=R(20,80),ans=budget-a-b-c;return depth(Q(`Bajet RM${budget}. Belanja RM${a}, RM${b} dan RM${c}. Baki?`,money(ans),[N(money(budget-a-b),'money'),N(money(a+b+c),'operation'),N(money(ans+20),'same_end')],'Jumlah belanja atau tolak setiap belanja daripada bajet.','Tahun 5 · Bajet',true,true),id,mode,'story','application',['money']);}if(mode==='multi_step'){let unit=R(20,50),qty=pick([2,3,4]),disc=pick([10,20]),gross=unit*qty,ans=gross*(100-disc)/100;return depth(Q(`${qty} barang × RM${unit}, kemudian diskaun ${disc}% pada jumlah. Bayaran?`,money(ans),[N(money(gross),'money'),N(money(gross*disc/100),'percent'),N(money(ans+10),'money')],'Cari jumlah harga dahulu, kemudian nilai selepas diskaun.','Tahun 5 · Wang Pelbagai Langkah',true,true),id,mode,'story','reasoning',['money','percent']);}let a=R(20,40),b=a*3-R(1,8),ans='Pakej B';return depth(Q(`${miniTable(['Pilihan','Harga'],[['A',`3 × RM${a}`],['B',`RM${b}`]])}Pilihan mana lebih murah?`,ans,[N('Pakej A','money'),N('Sama harga','money'),N('Tidak boleh ditentukan','money')],'Kira kos penuh setiap pilihan.','Tahun 5 · Banding Tawaran',true,true),id,mode,'table','reasoning',['money']);}
 if(id==='D5.TIME'){mode=chooseMode(id,s,['day_hour','month_day','leap','fraction_convert','elapsed_multi']);if(mode==='leap')return depth(Q(`Tahun <b>2024</b> ialah tahun lompat. Berapa hari dalam Februari?`,29,[N(28,'time'),N(30,'time'),N(31,'time')],'Tahun lompat mempunyai 29 hari dalam Februari.','Tahun 5 · Kalendar',false,true),id,mode,'verbal','concept',['time']);if(mode==='fraction_convert'){let h=pick([1.5,2.5,3.25,1.75]),ans=h*60;return depth(Q(`${h} jam = ? minit`,ans,[N(h*100,'time'),N(h*30,'time'),N(ans+30,'time')],'1 jam = 60 minit; darab termasuk bahagian perpuluhan.','Tahun 5 · Penukaran Masa',true,true),id,mode,'symbolic','procedure',['time']);}if(mode==='day_hour'){let days=R(1,4),hours=pick([6,12,18]),ans=days*24+hours;return depth(Q(`${days} hari ${hours} jam = ? jam`,ans,[N(days+hours,'time'),N(days*12+hours,'time'),N(ans+24,'time')],'1 hari = 24 jam.','Tahun 5 · Hari dan Jam',true,true),id,mode,'symbolic','procedure',['time']);}if(mode==='month_day'){let months=R(1,3),days=R(2,20);return depth(Q(`Untuk latihan ini, gunakan 1 bulan = 30 hari. ${months} bulan ${days} hari = ? hari`,months*30+days,[N(months+days,'time'),N(months*31+days,'time'),N(months*30,'time')],'Gunakan hubungan yang dinyatakan dalam soalan.','Tahun 5 · Bulan dan Hari',true,true),id,mode,'symbolic','procedure',['time']);}let start=8*60+pick([15,30,45]),d1=pick([24,48]),d2=pick([45,90,120]),total=d1*60+d2,end=start+total;return depth(Q(`Program bermula ${Math.floor(start/60)}:${String(start%60).padStart(2,'0')}. Tempoh ${d1} jam ${d2} minit. Berapa jumlah tempoh dalam minit?`,total,[N(d1+d2,'time'),N(d1*60,'time'),N(total+60,'time')],'Tukar jam kepada minit kemudian tambah.','Tahun 5 · Tempoh Lanjutan',true,true),id,mode,'story','application',['time']);}
 if(id==='D5.MEASURE'){mode=chooseMode(id,s,['decimal_convert','fraction_convert','add_three','multiply','divide']);let type=pick(['length','mass','liquid']);if(mode==='decimal_convert'){if(type==='length'){let m=R(1000,9999)/1000,ans=m*100;return depth(Q(`${m.toFixed(3)} m = ? cm`,tidyNumber(ans,1),[N(tidyNumber(m*10,1),'unit'),N(tidyNumber(m*1000,1),'unit'),N(tidyNumber(ans+10,1),'unit')],'1 m = 100 cm.','Tahun 5 · Panjang Perpuluhan',true,true),id,mode,'symbolic','procedure',['unit']);}if(type==='mass'){let kg=R(1000,9999)/1000,ans=kg*1000;return depth(Q(`${kg.toFixed(3)} kg = ? g`,tidyNumber(ans),[N(tidyNumber(kg*100),'unit'),N(tidyNumber(kg+1000),'unit'),N(tidyNumber(ans+100),'unit')],'1 kg = 1000 g.','Tahun 5 · Jisim Perpuluhan',true,true),id,mode,'symbolic','procedure',['unit']);}let L=R(1000,9999)/1000,ans=L*1000;return depth(Q(`${L.toFixed(3)} L = ? mL`,tidyNumber(ans),[N(tidyNumber(L*100),'unit'),N(tidyNumber(L+1000),'unit'),N(tidyNumber(ans+100),'unit')],'1 L = 1000 mL.','Tahun 5 · Isipadu Perpuluhan',true,true),id,mode,'symbolic','procedure',['unit']);}
 if(mode==='fraction_convert'){let n=pick([1,2,3]),d=pick([2,4]),m=n/d,ans=m*100;return depth(Q(`${n}/${d} m = ? cm`,ans,[N(m,'unit'),N(n*100,'unit'),N(ans+25,'unit')],'Tukar pecahan meter kepada meter perpuluhan, kemudian ×100.','Tahun 5 · Pecahan Ukuran',true,true),id,mode,'symbolic','procedure',['unit']);}
 let a=pick([1.25,1.5,2.25,2.5]),b=pick([0.5,0.75,1.25]),c=pick([0.25,0.5]);if(mode==='add_three'){let ans=tidyNumber(a+b+c,2);return depth(Q(`${a} m + ${b} m + ${c} m = ? m`,ans,[N(tidyNumber(ans+.5,2),'unit'),N(tidyNumber(ans-.25,2),'unit'),N(tidyNumber(a+b,2),'unit')],'Pastikan semua unit sama sebelum tambah.','Tahun 5 · Operasi Ukuran',true,true),id,mode,'symbolic','application',['unit']);}if(mode==='divide'){let divisor=pick([4,5,10,20,25]),total=tidyNumber(a*divisor,2);return depth(Q(`${total} L ÷ ${divisor} = ? L`,a,[N(tidyNumber(a*10,2),'unit'),N(tidyNumber(a+.5,2),'unit'),N(tidyNumber(total-divisor,2),'operation')],'Bahagi nilai ukuran dengan nombor yang diberi.','Tahun 5 · Bahagi Ukuran',true,true),id,mode,'symbolic','application',['unit']);}
 let k=pick([12,20,25]),ans=tidyNumber(a*k,2);return depth(Q(`${a} L × ${k} = ? L`,ans,[N(tidyNumber(a+k,2),'operation'),N(tidyNumber(ans/10,2),'unit'),N(tidyNumber(ans+1,2),'unit')],'Darab nilai ukuran seperti nombor perpuluhan.','Tahun 5 · Darab Ukuran',true,true),id,mode,'symbolic','application',['unit']);}
 if(id==='D5.AREA'){mode=chooseMode(id,s,['rectangle','missing_side','composite','compare']);let l=R(6,14),w=R(4,10),area=l*w;if(mode==='missing_side'){return depth(Q(`Luas segi empat tepat ${area} cm². Panjang ${l} cm. Lebar?`,w,[N(l,'area'),N(area-l,'operation'),N(w+2,'area')],'Lebar = luas ÷ panjang.','Tahun 5 · Dimensi Hilang',true,true),id,mode,'symbolic','reasoning',['area']);}if(mode==='composite'){let l2=R(3,l-1),w2=R(2,w-1),ans=area-l2*w2;return depth(Q(`${rectDiagram(l,w,l2)}Segi empat tepat ${l} cm × ${w} cm dipotong bahagian ${l2} cm × ${w2} cm. Luas baki?`,ans,[N(area,'area'),N(l2*w2,'area'),N(ans+l2,'area')],'Luas baki = luas besar − luas potongan.','Tahun 5 · Luas Komposit',true,true),id,mode,'visual','application',['area']);}if(mode==='compare'){let l2=R(5,12),w2=R(3,9),a2=l2*w2,ans=area>a2?'A':'B';return depth(Q(`${miniTable(['Bentuk','Panjang','Lebar'],[['A',l,w],['B',l2,w2]])}Bentuk manakah mempunyai luas lebih besar?`,ans,[N(ans==='A'?'B':'A','area'),N('Sama luas','area'),N('Tidak boleh ditentukan','area')],'Kira luas kedua-dua bentuk sebelum membandingkan.','Tahun 5 · Banding Luas',true,true),id,mode,'table','reasoning',['area']);}return depth(Q(`${rectDiagram(l,w)}Luas?`,area,[N(2*(l+w),'area'),N(l+w,'operation'),N(area+w,'area')],'Luas = panjang × lebar.','Tahun 5 · Luas Segi Empat',true,true),id,mode,'visual','procedure',['area']);}
 if(id==='D5.COORD'){mode=chooseMode(id,s,['read','translate','distance','missing']);let A={x:R(1,4),y:R(1,4),label:'A'},B={x:R(1,4),y:R(1,4),label:'B'};if(mode==='read'){let ans=`(${A.x},${A.y})`;return depth(Q(`${coordinateMap([A])}Koordinat A?`,ans,[N(`(${A.y},${A.x})`,'coord'),N(`(${A.x+1},${A.y})`,'coord'),N(`(${A.x},${Math.max(0,A.y-1)})`,'coord')],'Baca x dahulu kemudian y.','Tahun 5 · Koordinat',true,true),id,mode,'visual','concept',['coord']);}if(mode==='translate'){if(mode==='route'){let C={x:R(1,5),y:R(1,5),label:'C'},d1=Math.abs(A.x-B.x)+Math.abs(A.y-B.y),d2=Math.abs(B.x-C.x)+Math.abs(B.y-C.y),ans=(d1+d2)*scale;return depth(Q(`${coordinateMap([A,B,C],scale)}Laluan A → B → C bergerak mendatar/menegak. Jumlah jarak sebenar?`,`${ans} km`,[N(`${(d1+d2)} km`,'coord'),N(`${Math.max(d1,d2)*scale} km`,'coord'),N(`${ans+scale} km`,'coord')],'Kira petak bagi setiap bahagian laluan, jumlahkan, kemudian darab skala.','Tahun 6 · Laluan Berskala',true,true),id,mode,'visual','reasoning',['coord']);}if(mode==='missing_point'){let dx=pick([1,2]),dy=pick([1,2]),target={x:A.x+dx,y:A.y+dy,label:'B'},ans=`(${target.x},${target.y})`;return depth(Q(`${coordinateMap([A])}B ialah ${dx} petak kanan dan ${dy} petak atas A. Koordinat B?`,ans,[N(`(${target.y},${target.x})`,'coord'),N(`(${A.x-dx},${A.y+dy})`,'coord'),N(`(${A.x+dx},${A.y-dy})`,'coord')],'Gunakan perubahan x dan y.','Tahun 6 · Titik Hilang',true,true),id,mode,'visual','reasoning',['coord']);}let dx=pick([1,2]),dy=pick([1,2]),ans=`(${A.x+dx},${A.y+dy})`;return depth(Q(`${coordinateMap([A])}A bergerak ${dx} petak ke kanan dan ${dy} petak ke atas. Koordinat baharu?`,ans,[N(`(${A.x+dy},${A.y+dx})`,'coord'),N(`(${A.x-dx},${A.y+dy})`,'coord'),N(`(${A.x+dx},${A.y-dy})`,'coord')],'Kanan menambah x; atas menambah y.','Tahun 5 · Gerakan Koordinat',true,true),id,mode,'visual','application',['coord']);}if(mode==='missing'){let dx=pick([1,2]),dy=pick([1,2]),target={x:A.x+dx,y:A.y+dy,label:'B'},ans=`(${target.x},${target.y})`;return depth(Q(`${coordinateMap([A])}B terletak ${dx} petak ke kanan dan ${dy} petak ke atas A. Koordinat B?`,ans,[N(`(${target.y},${target.x})`,'coord'),N(`(${A.x-dx},${A.y+dy})`,'coord'),N(`(${A.x+dx},${A.y-dy})`,'coord')],'Gerakan kanan menambah x dan gerakan atas menambah y.','Tahun 5 · Titik Hilang',true,true),id,mode,'visual','reasoning',['coord']);}let horiz=Math.abs(A.x-B.x),vert=Math.abs(A.y-B.y),ans=horiz+vert;return depth(Q(`${coordinateMap([A,B])}Jika bergerak mendatar kemudian menegak dari A ke B, berapa jumlah petak dilalui?`,ans,[N(Math.max(horiz,vert),'coord'),N(horiz*vert,'coord'),N(Math.abs(horiz-vert),'coord')],'Cari beza x dan beza y, kemudian tambah.','Tahun 5 · Jarak Grid',true,true),id,mode,'visual','reasoning',['coord']);}
 if(id==='D5.DATA'){mode=chooseMode(id,s,['mean','missing_mean','compare','interpret']);let vals=[R(20,40),R(20,40),R(20,40),R(20,40)];if(mode==='mean'){let sum=vals.reduce((a,b)=>a+b,0);sum-=sum%4;vals[3]=Math.max(4,sum-vals[0]-vals[1]-vals[2]);sum=vals.reduce((a,b)=>a+b,0);let ans=sum/4;return depth(Q(`${miniTable(['Hari','Nilai'],vals.map((v,i)=>[['I','S','R','K'][i],v]))}Purata?`,ans,[N(Math.max(...vals),'data'),N(sum,'operation'),N(Math.round(sum/3),'data')],'Purata = jumlah ÷ bilangan data.','Tahun 5 · Purata',true,true),id,mode,'table','application',['data']);}if(mode==='missing_mean'){let mean=pick([20,25,30]),a=R(10,30),b=R(10,30),c=R(10,30),ans=mean*4-a-b-c;if(ans<0)return d5(id,s,shift);return depth(Q(`Purata 4 nombor ialah ${mean}. Tiga nombor ialah ${a}, ${b}, ${c}. Nombor keempat?`,ans,[N(mean,'data'),N(a+b+c,'operation'),N(ans+5,'data')],'Jumlah diperlukan = purata × bilangan data.','Tahun 5 · Nilai Hilang daripada Purata',true,true),id,mode,'symbolic','reasoning',['data']);}let labels=['A','B','C','D'],vis=barChart(labels,vals);let hi=vals.indexOf(Math.max(...vals)),lo=vals.indexOf(Math.min(...vals)),ans=vals[hi]-vals[lo];if(mode==='compare'){return depth(Q(`${vis}Kategori manakah mempunyai nilai tertinggi?`,labels[hi],labels.filter(x=>x!==labels[hi]).slice(0,3).map(x=>N(x,'data')),'Banding semua palang.','Tahun 5 · Banding Data',true,true),id,mode,'visual','concept',['data']);}if(mode==='interpret'){let total=vals[0]+vals[1];return depth(Q(`${vis}Jumlah kategori A dan B?`,total,[N(vals[0],'data'),N(vals[1],'data'),N(total+5,'data')],'Baca dua nilai kemudian tambah.','Tahun 5 · Tafsir Data',true,true),id,mode,'visual','application',['data']);}return depth(Q(`${vis}Beza nilai tertinggi dan terendah?`,ans,wrongNums(ans,5,'data'),'Baca dua nilai dan cari beza.','Tahun 5 · Tafsir Data',true,true),id,mode,'visual','application',['data']);}
 return null;
}

// D6 — actual new competency, not digit inflation: fraction division, decimal×decimal/÷decimal, time zones, proportional ratio.
function d6(id,s,shift){
 let mode;
 if(id==='D6.NUMBERS'){mode=chooseMode(id,s,['ten_million','million_fraction','prime_composite','pattern','reasonableness']);if(mode==='ten_million'){let n=R(1000000,9999999),step=pick([1000,10000,100000]),ans=n+3*step;return depth(Q(`${n.toLocaleString('en-US')}, ${(n+step).toLocaleString('en-US')}, ${(n+2*step).toLocaleString('en-US')}, ?`,ans,[N(ans-step,'pattern'),N(ans+step,'pattern'),N(n+3,'pattern')],'Cari perubahan tetap pada nilai tempat.','Tahun 6 · Nombor hingga 10 Juta',true,true),id,mode,'symbolic','reasoning',['pattern']);}if(mode==='million_fraction'){let f=pick([[1,2,.5],[1,4,.25],[3,4,.75],[1,5,.2],[3,5,.6]]),ans=f[2]*1000000;return depth(Q(`<b>${f[0]}/${f[1]} juta</b> bersamaan?`,ans,[N(ans/10,'place'),N(f[1]*100000,'operation'),N(1000000-ans,'fraction')],'1 juta = 1 000 000. Ambil pecahan daripada sejuta.','Tahun 6 · Pecahan Juta',true,true),id,mode,'symbolic','application',['fraction']);}if(mode==='prime_composite'){let n=pick([29,31,37,49,51,57,61,77]),prime=[29,31,37,61].includes(n),ans=prime?'nombor perdana':'nombor gubahan';return depth(Q(`<b>${n}</b> ialah?`,ans,[N(prime?'nombor gubahan':'nombor perdana','fact'),N('nombor genap','fact'),N('bukan nombor bulat','fact')],'Semak bilangan faktor. Nombor perdana mempunyai tepat dua faktor.','Tahun 6 · Perdana dan Gubahan',true,true),id,mode,'symbolic','concept',['fact']);}if(mode==='reasonableness'){let a=R(2000000,5000000),b=R(1000000,3000000),claim=a+b+R(500000,1000000),ans='tidak munasabah';return depth(Q(`Anggaran ${a.toLocaleString()} + ${b.toLocaleString()} ≈ ${claim.toLocaleString()}. Penilaian?`,ans,[N('munasabah','estimate'),N('tepat tanpa mengira','estimate'),N('maklumat tidak cukup','estimate')],'Bundarkan kedua-dua nombor dan banding dengan anggaran.','Tahun 6 · Kemunasabahan',false,true),id,mode,'verbal','reasoning',['estimate']);}return previous.d6?.(id,s,shift);}
 if(id==='D6.OPS'){mode=chooseMode(id,s,['order_two_ops','brackets','unknown','story_multi','reasonableness']);if(mode==='brackets'){let a=R(20,60),b=R(5,15),c=R(2,9),ans=(a+b)*c;return depth(Q(`(${a} + ${b}) × ${c} = ?`,ans,[N(a+b*c,'operation'),N(a+b+c,'operation'),N((a+b)+c,'operation')],'Selesaikan dalam kurungan dahulu.','Tahun 6 · Operasi Gabungan',true,true),id,mode,'symbolic','procedure',['operation']);}if(mode==='unknown'){let b=R(3,9),c=R(20,70),x=R(10,50),total=x*b+c;return depth(Q(`□ × ${b} + ${c} = ${total}. Nilai □?`,x,[N((total-c),'operation'),N(Math.round(total/b),'operation'),N(x+5,'operation')],'Tolak dahulu, kemudian bahagi untuk cari nilai tidak diketahui.','Tahun 6 · Nilai Tidak Diketahui',true,true),id,mode,'symbolic','reasoning',['operation']);}if(mode==='story_multi'){let boxes=R(4,9),each=R(20,50),used=R(15,60),ans=boxes*each-used;return depth(Q(`Ada ${boxes} kotak, ${each} unit setiap kotak. ${used} unit digunakan. Berapa baki?`,ans,[N(boxes*(each-used),'operation'),N(boxes+each-used,'operation'),N(boxes*each+used,'operation')],'Darab dahulu untuk jumlah, kemudian tolak yang digunakan.','Tahun 6 · Masalah Operasi Gabungan',true,true),id,mode,'story','application',['operation']);}if(mode==='reasonableness'){let a=R(480,950),b=R(18,42),claim=a*b+R(5000,9000),ans='tidak munasabah';return depth(Q(`Seorang murid menganggarkan ${a} × ${b} ≈ ${claim}. Adakah anggaran itu munasabah?`,ans,[N('munasabah','estimate'),N('tepat tanpa mengira','estimate'),N('maklumat tidak cukup','estimate')],'Bundarkan kedua-dua faktor dan bandingkan magnitud hasil.','Tahun 6 · Kemunasabahan Operasi',false,true),id,mode,'verbal','reasoning',['estimate']);}let a=R(40,90),b=R(10,25),c=R(2,9),ans=a+b*c;return depth(Q(`${a} + ${b} × ${c} = ?`,ans,[N((a+b)*c,'operation'),N(a+b+c,'operation'),N(a*b+c,'operation')],'Darab dahulu, kemudian tambah.','Tahun 6 · Tertib Operasi',true,true),id,mode,'symbolic','procedure',['operation']);}
 if(id==='D6.FRAC'){
   mode=chooseMode(id,s,['proper_div_whole','whole_div_proper','proper_div_proper','mixed_div_whole','mixed_div_proper','sharing_model']);
   if(mode==='sharing_model'){let d=pick([2,4,6,8]),n=R(1,d-1),groups=pick([2,3]),ans=frac(n,d*groups);return depth(Q(`${fractionStrip(n,d)}Bahagian <b>${n}/${d}</b> dibahagi sama rata kepada ${groups} orang. Setiap orang mendapat?`,ans,[N(frac(n*groups,d),'fraction'),N(frac(n,d),'fraction'),N(frac(n,d+groups),'fraction')],'Membahagi pecahan kepada kumpulan sama banyak mengecilkan setiap bahagian.','Tahun 6 · Model Bahagi Pecahan',true,true),id,mode,'visual','concept',['fraction']);}if(mode==='proper_div_whole'){let d=pick([2,3,4,5,6,8,10]),n=R(1,d-1),w=R(2,6),ans=frac(n,d*w);return depth(Q(`<b>${n}/${d} ÷ ${w}</b> = ?`,ans,[N(frac(n*w,d),'fraction'),N(frac(n,d),'fraction'),N(frac(n+w,d*w),'fraction')],'Membahagi dengan nombor bulat menjadikan setiap bahagian lebih kecil.','Tahun 6 · Bahagi Pecahan',true,true),id,mode,'symbolic','procedure',['fraction']);}
   if(mode==='whole_div_proper'){let w=R(1,5),d=pick([2,3,4,5,6,8,10]),n=R(1,d-1),ans=frac(w*d,n);return depth(Q(`<b>${w} ÷ ${n}/${d}</b> = ?`,ans,[N(frac(w*n,d),'fraction'),N(frac(w,d),'fraction'),N(frac(w*d,d),'fraction')],'Darab dengan songsangan pecahan pembahagi.','Tahun 6 · Bahagi dengan Pecahan',true,true),id,mode,'symbolic','procedure',['fraction']);}
   if(mode==='proper_div_proper'){let d1=pick([2,3,4,5,6,8,10]),n1=R(1,d1-1),d2=pick([2,3,4,5,6,8,10]),n2=R(1,d2-1),ans=frac(n1*d2,d1*n2);return depth(Q(`${fractionStrip(n1,d1)}<b>${n1}/${d1} ÷ ${n2}/${d2}</b> = ?`,ans,[N(frac(n1*n2,d1*d2),'fraction'),N(frac(n1+n2,d1+d2),'fraction'),N(frac(n1*d1,n2*d2),'fraction')],'Kekalkan pecahan pertama, darab songsangan pecahan kedua.','Tahun 6 · Bahagi Dua Pecahan',true,true),id,mode,'visual','procedure',['fraction']);}
   let d=pick([2,3,4,5,6,8,10]),w=R(1,3),n=R(1,d-1),im=w*d+n;
   if(mode==='mixed_div_whole'){let k=R(2,5),ans=mixed(im,d*k);return depth(Q(`<b>${w} ${n}/${d} ÷ ${k}</b> = ?`,ans,[N(mixed(im*k,d),'fraction'),N(frac(im,d),'fraction'),N(frac(im+k,d*k),'fraction')],'Tukar nombor bercampur kepada pecahan tak wajar, kemudian bahagi.','Tahun 6 · Bahagi Nombor Bercampur',true,true),id,mode,'symbolic','application',['fraction']);}
   let d2=pick([2,3,4,5,6,8,10]),n2=R(1,d2-1),ans=mixed(im*d2,d*n2);return depth(Q(`<b>${w} ${n}/${d} ÷ ${n2}/${d2}</b> = ?`,ans,[N(frac(im*n2,d*d2),'fraction'),N(frac(im+n2,d+d2),'fraction'),N(mixed(im*n2,d*d2),'fraction')],'Tukar kepada pecahan tak wajar, kemudian darab songsangan.','Tahun 6 · Bahagi Pecahan Bercampur',true,true),id,mode,'symbolic','application',['fraction']);
 }
 if(id==='D6.DEC'){mode=chooseMode(id,s,['decimal_x_decimal','decimal_div_decimal','missing_factor','story_multi']);if(mode==='decimal_x_decimal'){let a=R(12,999)/100,b=R(11,99)/10,ans=tidyNumber(a*b,3);return depth(Q(`${a.toFixed(2)} × ${b.toFixed(1)} = ?`,String(ans),[N(String(tidyNumber(ans+.1,3)),'decimal'),N(String(tidyNumber(a+b,3)),'operation'),N(String(tidyNumber(ans/10,3)),'decimal')],'Darab sebagai nombor bulat, kemudian tentukan jumlah tempat perpuluhan.','Tahun 6 · Darab Perpuluhan',true,true),id,mode,'symbolic','procedure',['decimal']);}if(mode==='decimal_div_decimal'){let d=pick([0.2,0.25,0.4,0.5,1.25,2.5]),q=pick([1.2,1.5,2.4,3.2,4.5]),a=tidyNumber(d*q,3);return depth(Q(`${a} ÷ ${d} = ?`,String(q),[N(String(tidyNumber(q*10,3)),'decimal'),N(String(tidyNumber(q+.1,3)),'decimal'),N(String(tidyNumber(a-d,3)),'operation')],'Jadikan pembahagi nombor bulat dengan menggerakkan titik pada kedua-dua nombor sama banyak.','Tahun 6 · Bahagi Perpuluhan',true,true),id,mode,'symbolic','procedure',['decimal']);}if(mode==='missing_factor'){let b=pick([0.5,1.5,2.5]),x=pick([1.2,2.4,3.6,4.8]),total=tidyNumber(x*b,3);return depth(Q(`□ × ${b} = ${total}. Nilai □?`,String(x),[N(String(total),'decimal'),N(String(tidyNumber(total/b+1,2)),'decimal'),N(String(tidyNumber(total-b,2)),'operation')],'Bahagi hasil dengan faktor yang diketahui.','Tahun 6 · Nilai Perpuluhan Hilang',true,true),id,mode,'symbolic','reasoning',['decimal']);}let unit=pick([1.25,1.5,2.4]),qty=pick([2.5,3.5,4.5]),ans=tidyNumber(unit*qty,3);return depth(Q(`Setiap meter kain berharga RM${unit.toFixed(2)}. Harga ${qty} m?`,money(ans),[N(money(unit+qty),'operation'),N(money(ans+1),'decimal'),N(money(unit),'decimal')],'Darab kadar seunit dengan kuantiti perpuluhan.','Tahun 6 · Aplikasi Perpuluhan',true,true),id,mode,'story','application',['decimal']);}
 if(id==='D6.PERCENT'){mode=chooseMode(id,s,['decimal_to_percent_over100','add_percent','sub_percent','over100_quantity','inverse']);if(mode==='decimal_to_percent_over100'){let d=pick([1.05,1.2,1.25,1.5,1.75,2.0]),ans=`${d*100}%`;return depth(Q(`Tukar <b>${d}</b> kepada peratus.`,ans,[N(`${d*10}%`,'percent'),N(`${d}%`,'percent'),N(`${d*100-100}%`,'percent')],'Darab perpuluhan dengan 100%.','Tahun 6 · Peratus >100',true,true),id,mode,'symbolic','procedure',['percent']);}if(mode==='add_percent'){let a=pick([25,40,75,120,150]),b=pick([10,20,25,50]),ans=a+b;return depth(Q(`${a}% + ${b}% = ?`,`${ans}%`,[N(`${Math.abs(a-b)}%`,'percent'),N(`${ans/100}%`,'percent'),N(`${a+b+10}%`,'percent')],'Tambah nilai peratus seperti nombor biasa.','Tahun 6 · Operasi Peratus',true,true),id,mode,'symbolic','procedure',['percent']);}if(mode==='sub_percent'){let a=pick([125,150,175,200]),b=pick([25,50,75]),ans=a-b;return depth(Q(`${a}% − ${b}% = ?`,`${ans}%`,[N(`${a+b}%`,'percent'),N(`${ans/100}%`,'percent'),N(`${ans+25}%`,'percent')],'Tolak nilai peratus.','Tahun 6 · Operasi Peratus',true,true),id,mode,'symbolic','procedure',['percent']);}if(mode==='inverse'){let pct=pick([40,50,80,125,150]),whole=pick([40,80,100,120,160]),part=whole*pct/100;return depth(Q(`${part} ialah ${pct}% daripada suatu nilai. Nilai asal?`,whole,[N(part,'percent'),N(part*pct/100,'percent'),N(whole+20,'operation')],'Nilai asal = bahagian ÷ (peratus/100).','Tahun 6 · Nilai Asal Peratus',true,true),id,mode,'symbolic','reasoning',['percent']);}let pct=pick([110,125,150,175,200]),base=pick([40,80,120,160]),ans=base*pct/100;return depth(Q(`${pct}% daripada ${base} = ?`,ans,[N(base,'percent'),N(base*(pct-100)/100,'percent'),N(base+pct,'operation')],'Lebih 100% menghasilkan nilai melebihi kuantiti asal.','Tahun 6 · Nilai Peratus',true,true),id,mode,'symbolic','application',['percent']);}
 if(id==='D6.RATIO'){mode=chooseMode(id,s,['simplify','equivalent','proportion','ratio_table','inverse']);if(mode==='simplify'){let a=pick([2,3,4,5]),b=pick([3,4,5,6]),k=pick([2,3,4,5]),A=a*k,B=b*k,g=gcd2(A,B),ans=`${A/g}:${B/g}`;return depth(Q(`Ringkaskan nisbah <b>${A}:${B}</b>.`,ans,[N(`${A}:${b}`,'ratio'),N(`${a}:${B}`,'ratio'),N(`${A/g+1}:${B/g}`,'ratio')],'Bahagi kedua-dua kuantiti dengan faktor sepunya terbesar.','Tahun 6 · Nisbah Termudah',true,true),id,mode,'symbolic','procedure',['ratio']);}if(mode==='proportion'){let a=pick([2,3,4]),b=pick([3,4,5]),known=a*pick([4,5,6]),factor=known/a,ans=b*factor;return depth(Q(`Nisbah merah:biru = ${a}:${b}. Jika merah = ${known}, biru = ?`,ans,[N(known+b,'ratio'),N(known/a,'ratio'),N(ans+b,'ratio')],'Cari faktor skala daripada bahagian merah, gunakan faktor sama pada biru.','Tahun 6 · Kadaran',true,true),id,mode,'symbolic','application',['ratio']);}if(mode==='ratio_table'){let a=pick([2,3,4]),b=pick([3,5,6]),k=pick([2,3,4]),ans=b*k;return depth(Q(`${miniTable(['A','B'],[[a,b],[a*k,'?']])}Lengkapkan jadual nisbah.`,ans,[N(b+k,'ratio'),N(a*k,'ratio'),N(ans+k,'ratio')],'Darab kedua-dua lajur dengan faktor sama.','Tahun 6 · Jadual Nisbah',true,true),id,mode,'table','reasoning',['ratio']);}if(mode==='inverse'){let a=pick([2,3,4]),b=pick([3,4,5]),total=(a+b)*pick([4,5,6]),one=total/(a+b),ans=a*one;return depth(Q(`Nisbah A:B = ${a}:${b} dan jumlah A+B = ${total}. Nilai A?`,ans,[N(b*one,'ratio'),N(one,'ratio'),N(total-a,'ratio')],'Jumlah bahagian nisbah dahulu, cari nilai satu bahagian, kemudian darab bahagian A.','Tahun 6 · Nisbah daripada Jumlah',true,true),id,mode,'symbolic','reasoning',['ratio']);}let a=pick([2,3,4]),b=pick([3,4,5]),k=pick([2,3,4]),ans=`${a*k}:${b*k}`;return depth(Q(`Nisbah setara bagi <b>${a}:${b}</b>?`,ans,[N(`${a+b}:${b}`,'ratio'),N(`${a}:${b*k}`,'ratio'),N(`${a*k}:${b}`,'ratio')],'Darab kedua-dua bahagian dengan nombor sama.','Tahun 6 · Nisbah Setara',true,true),id,mode,'symbolic','concept',['ratio']);}
 if(id==='D6.MONEY'){mode=chooseMode(id,s,['budget','discount_tax','saving_target','compare_plan']);if(mode==='budget'){let income=pick([500,600,800]),needs=R(180,300),save=pick([100,150,200]),wants=R(60,120),ans=income-needs-save-wants;return depth(Q(`${miniTable(['Item','RM'],[['Pendapatan',income],['Keperluan',needs],['Simpanan',save],['Kehendak',wants]])}Baki selepas semua peruntukan?`,money(ans),[N(money(income-needs),'money'),N(money(needs+save+wants),'operation'),N(money(ans+50),'same_end')],'Tolak semua peruntukan daripada pendapatan.','Tahun 6 · Bajet',true,true),id,mode,'table','application',['money']);}if(mode==='discount_tax'){let price=pick([100,120,160,200]),disc=pick([10,20,25]),after=price*(100-disc)/100,fee=pick([5,10]),ans=after+fee;return depth(Q(`Harga RM${price}, diskaun ${disc}%, kemudian caj RM${fee}. Bayaran akhir?`,money(ans),[N(money(after),'money'),N(money(price-price*disc/100),'percent'),N(money(price+fee),'operation')],'Cari harga selepas diskaun dahulu, kemudian tambah caj.','Tahun 6 · Transaksi Pelbagai Langkah',true,true),id,mode,'story','application',['money','percent']);}if(mode==='saving_target'){let target=pick([600,900,1200]),months=pick([6,9,12]),saved=pick([20,30,40]),ans=target/months;return depth(Q(`Sasaran RM${target} dalam ${months} bulan. Perlu simpan purata berapa sebulan?`,money(ans),[N(money(saved),'money'),N(money(target-months),'operation'),N(money(ans+10),'money')],'Bahagi sasaran dengan bilangan bulan.','Tahun 6 · Matlamat Simpanan',true,true),id,mode,'story','reasoning',['money']);}let monthly=pick([60,80,100]),months=pick([6,9,12]),bonus=pick([0,50,100]),planA=monthly*months+bonus,planB=(monthly+10)*months,ans=planA>planB?'Pelan A':'Pelan B';return depth(Q(`${miniTable(['Pelan','Jumlah'],[['A',`RM${monthly} × ${months} + RM${bonus}`],['B',`RM${monthly+10} × ${months}`]])}Pelan simpanan mana menghasilkan jumlah lebih besar?`,ans,[N(ans==='Pelan A'?'Pelan B':'Pelan A','money'),N('Sama jumlah','money'),N('Tidak boleh ditentukan','money')],'Kira jumlah kedua-dua pelan sebelum membandingkan.','Tahun 6 · Banding Pelan Simpanan',true,true),id,mode,'table','reasoning',['money']);}
 if(id==='D6.TIME'){mode=chooseMode(id,s,['zone_forward','zone_backward','zone_duration','zone_table']);let cities=[['Bandar A',8],['Bandar B',9],['Bandar C',4],['Bandar D',2]],a=pick(cities),b=pick(cities.filter(x=>x[0]!==a[0]));if(mode==='zone_forward'){const c=cities.filter(x=>x[1]>a[1]);if(c.length)b=pick(c);}if(mode==='zone_backward'){const c=cities.filter(x=>x[1]<a[1]);if(c.length)b=pick(c);}let hour=R(6,20),minute=pick([0,15,30,45]),delta=b[1]-a[1],target=((hour+delta)%24+24)%24,fmt=(h,m)=>`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`,ans=fmt(target,minute);let table=miniTable(['Bandar','Zon'],[[a[0],`UTC${a[1]>=0?'+':''}${a[1]}`],[b[0],`UTC${b[1]>=0?'+':''}${b[1]}`]]);if(mode==='zone_duration'){let dur=pick([2,3,4]),arrival=((target+dur)%24+24)%24,arr=fmt(arrival,minute);return depth(Q(`${table}Siaran bermula di ${a[0]} pada ${fmt(hour,minute)} dan berlangsung ${dur} jam. Waktu tamat di ${b[0]}?`,arr,[N(ans,'time'),N(fmt((arrival+1)%24,minute),'time'),N(fmt(((arrival-1)%24+24)%24,minute),'time')],'Tukar waktu mula ke zon destinasi, kemudian tambah tempoh.','Tahun 6 · Zon Masa Dua Langkah',true,true),id,mode,'table','reasoning',['time']);}return depth(Q(`${table}Apabila ${a[0]} menunjukkan ${fmt(hour,minute)}, waktu di ${b[0]}?`,ans,[N(fmt((target+1)%24,minute),'time'),N(fmt(((target-1)%24+24)%24,minute),'time'),N(fmt(hour,minute),'time')],`${b[0]} berbeza ${Math.abs(delta)} jam; ${delta>=0?'tambah':'tolak'} perbezaan zon.`,'Tahun 6 · Zon Masa',true,true),id,mode,'table','application',['time']);}
 if(id==='D6.MEASURE'){mode=chooseMode(id,s,['length_relation','mass_relation','liquid_relation','multi_step']);let type=pick(['length','mass','liquid']);if(type==='length'){let each=pick([1.25,1.5,2.4,2.5]),count=pick([3,4,5]),used=pick([0.5,1,1.5]),ans=tidyNumber(each*count-used,2);return depth(Q(`${count} gulung tali masing-masing ${each} m. ${used} m digunakan. Baki panjang?`,`${ans} m`,[N(`${tidyNumber(each*count,2)} m`,'unit'),N(`${tidyNumber(ans+1,2)} m`,'unit'),N(`${tidyNumber(each+count-used,2)} m`,'operation')],'Cari jumlah panjang dahulu, kemudian tolak yang digunakan.','Tahun 6 · Hubungan Panjang',true,true),id,mode,'story','application',['unit']);}if(type==='mass'){let pack=pick([0.75,1.25,1.5]),count=pick([4,6,8]),ans=tidyNumber(pack*count,2);return depth(Q(`${count} pek masing-masing ${pack} kg. Jumlah jisim?`,`${ans} kg`,[N(`${tidyNumber(pack+count,2)} kg`,'operation'),N(`${tidyNumber(ans/10,2)} kg`,'unit'),N(`${tidyNumber(ans+1,2)} kg`,'unit')],'Darab jisim setiap pek dengan bilangan pek.','Tahun 6 · Hubungan Jisim',true,true),id,mode,'story','application',['unit']);}let bottle=pick([0.75,1.25,1.5]),count=pick([4,6,8]),poured=pick([1,2,2.5]),ans=tidyNumber(bottle*count-poured,2);return depth(Q(`${count} botol masing-masing ${bottle} L. ${poured} L digunakan. Baki?`,`${ans} L`,[N(`${tidyNumber(bottle*count,2)} L`,'unit'),N(`${tidyNumber(ans+1,2)} L`,'unit'),N(`${tidyNumber(bottle+count-poured,2)} L`,'operation')],'Cari jumlah isipadu kemudian tolak yang digunakan.','Tahun 6 · Hubungan Isi Padu',true,true),id,mode,'story','application',['unit']);}
 if(id==='D6.AREA'){mode=chooseMode(id,s,['composite_area','missing_dimension','volume','perimeter_reason']);if(mode==='volume'){let l=R(6,12),w=R(4,9),h=R(2,6),ans=l*w*h;return depth(Q(`Kuboid ${l} cm × ${w} cm × ${h} cm. Isipadu?`,ans,[N(l*w,'area'),N(2*(l+w+h),'area'),N(ans+h,'area')],'Isipadu = panjang × lebar × tinggi.','Tahun 6 · Isipadu',true,true),id,mode,'symbolic','procedure',['area']);}if(mode==='missing_dimension'){let l=R(8,15),w=R(4,10),area=l*w;return depth(Q(`Luas segi empat tepat ${area} cm². Lebar ${w} cm. Panjang?`,l,[N(w,'area'),N(area-w,'operation'),N(l+2,'area')],'Panjang = luas ÷ lebar.','Tahun 6 · Dimensi Hilang',true,true),id,mode,'symbolic','reasoning',['area']);}if(mode==='perimeter_reason'){let l=R(8,16),w=R(5,12),p=2*(l+w);return depth(Q(`Sebuah segi empat tepat berperimeter ${p} cm. Panjang ${l} cm. Lebar?`,w,[N(l,'area'),N(p-l,'operation'),N(w+2,'area')],'Bahagi perimeter kepada dua untuk dapat panjang + lebar.','Tahun 6 · Penaakulan Perimeter',true,true),id,mode,'symbolic','reasoning',['area']);}let l=R(10,18),w=R(6,12),cutL=R(2,Math.min(5,l-2)),cutW=R(2,Math.min(4,w-2)),ans=l*w-cutL*cutW;return depth(Q(`${rectDiagram(l,w,cutL)}Segi empat tepat ${l}×${w} cm dipotong ${cutL}×${cutW} cm. Luas baki?`,ans,[N(l*w,'area'),N(cutL*cutW,'area'),N(ans+cutL,'area')],'Luas baki = luas keseluruhan − luas potongan.','Tahun 6 · Luas Komposit',true,true),id,mode,'visual','application',['area']);}
 if(id==='D6.COORD'){mode=chooseMode(id,s,['scaled_distance','direction','missing_point','route']);let A={x:R(1,3),y:R(1,4),label:'A'},B={x:R(3,5),y:R(1,5),label:'B'},scale=pick([2,5,10]);if(mode==='scaled_distance'){let dist=(Math.abs(A.x-B.x)+Math.abs(A.y-B.y))*scale;return depth(Q(`${coordinateMap([A,B],scale)}Bergerak mendatar kemudian menegak dari A ke B. Jarak sebenar?`,`${dist} km`,[N(`${dist/scale} km`,'coord'),N(`${Math.max(Math.abs(A.x-B.x),Math.abs(A.y-B.y))*scale} km`,'coord'),N(`${dist+scale} km`,'coord')],'Kira bilangan petak mendatar + menegak, kemudian darab skala.','Tahun 6 · Jarak Berskala',true,true),id,mode,'visual','application',['coord']);}if(mode==='direction'){let dx=B.x-A.x,dy=B.y-A.y,ans=`${Math.abs(dx)} kanan, ${Math.abs(dy)} ${dy>=0?'atas':'bawah'}`;return depth(Q(`${coordinateMap([A,B])}Dari A ke B, gerakan yang betul?`,ans,[N(`${Math.abs(dy)} kanan, ${Math.abs(dx)} atas`,'coord'),N(`${Math.abs(dx)} kiri, ${Math.abs(dy)} atas`,'coord'),N(`${Math.abs(dx)} kanan, ${Math.abs(dy)} bawah`,'coord')],'Banding perubahan x dan y.','Tahun 6 · Arah Koordinat',true,true),id,mode,'visual','reasoning',['coord']);}if(mode==='route'){let C={x:R(1,5),y:R(1,5),label:'C'},d1=Math.abs(A.x-B.x)+Math.abs(A.y-B.y),d2=Math.abs(B.x-C.x)+Math.abs(B.y-C.y),ans=(d1+d2)*scale;return depth(Q(`${coordinateMap([A,B,C],scale)}Laluan A → B → C bergerak mendatar/menegak. Jumlah jarak sebenar?`,`${ans} km`,[N(`${(d1+d2)} km`,'coord'),N(`${Math.max(d1,d2)*scale} km`,'coord'),N(`${ans+scale} km`,'coord')],'Kira petak bagi setiap bahagian laluan, jumlahkan, kemudian darab skala.','Tahun 6 · Laluan Berskala',true,true),id,mode,'visual','reasoning',['coord']);}if(mode==='missing_point'){let dx=pick([1,2]),dy=pick([1,2]),target={x:A.x+dx,y:A.y+dy,label:'B'},ans=`(${target.x},${target.y})`;return depth(Q(`${coordinateMap([A])}B ialah ${dx} petak kanan dan ${dy} petak atas A. Koordinat B?`,ans,[N(`(${target.y},${target.x})`,'coord'),N(`(${A.x-dx},${A.y+dy})`,'coord'),N(`(${A.x+dx},${A.y-dy})`,'coord')],'Gunakan perubahan x dan y.','Tahun 6 · Titik Hilang',true,true),id,mode,'visual','reasoning',['coord']);}let dx=pick([1,2]),dy=pick([1,2]),ans=`(${A.x+dx},${A.y+dy})`;return depth(Q(`${coordinateMap([A])}Titik baharu ialah ${dx} petak kanan dan ${dy} petak atas dari A. Koordinat?`,ans,[N(`(${A.y+dy},${A.x+dx})`,'coord'),N(`(${A.x-dx},${A.y+dy})`,'coord'),N(`(${A.x+dx},${A.y-dy})`,'coord')],'Kanan menambah x, atas menambah y.','Tahun 6 · Koordinat dan Arah',true,true),id,mode,'visual','application',['coord']);}
 if(id==='D6.DATA'){mode=chooseMode(id,s,['probability_spinner','probability_bag','mean_missing','compare_probability','chart_reason']);if(mode==='probability_spinner'){let parts=pick([4,6,8]),win=R(1,parts-1),ans=frac(win,parts);return depth(Q(`${spinner(parts,win)}Kebarangkalian mendapat sektor berlorek?`,ans,[N(frac(parts-win,parts),'data'),N(frac(win,parts+1),'data'),N(frac(1,win),'data')],'Kebarangkalian = hasil dikehendaki ÷ jumlah hasil sama kemungkinan.','Tahun 6 · Kebarangkalian',true,true),id,mode,'visual','concept',['data']);}if(mode==='probability_bag'){let red=R(2,6),blue=R(2,6),green=R(1,4),sum=red+blue+green,ans=frac(red,sum);return depth(Q(`${miniTable(['Warna','Bilangan'],[['Merah',red],['Biru',blue],['Hijau',green]])}Satu guli dipilih secara rawak. Kebarangkalian merah?`,ans,[N(frac(blue,sum),'data'),N(frac(red,sum+1),'data'),N(frac(sum-red,sum),'data')],'Bilangan merah dibahagi jumlah semua guli.','Tahun 6 · Kebarangkalian',true,true),id,mode,'table','application',['data']);}if(mode==='mean_missing'){let mean=pick([20,25,30,35]),a=R(10,35),b=R(10,35),c=R(10,35),ans=mean*4-a-b-c;if(ans<0)return d6(id,s,shift);return depth(Q(`Purata 4 bacaan ialah ${mean}. Tiga bacaan: ${a}, ${b}, ${c}. Bacaan keempat?`,ans,[N(mean,'data'),N(a+b+c,'operation'),N(ans+5,'data')],'Jumlah = purata × bilangan data.','Tahun 6 · Data Nilai Hilang',true,true),id,mode,'symbolic','reasoning',['data']);}if(mode==='compare_probability'){let aRed=R(2,6),aAll=aRed+R(2,6),bRed=R(2,6),bAll=bRed+R(2,6);while(aRed*bAll===bRed*aAll){bRed=R(2,6);bAll=bRed+R(2,6);}let ans=aRed/aAll>bRed/bAll?'Beg A':'Beg B';return depth(Q(`${miniTable(['','Merah','Jumlah'],[['Beg A',aRed,aAll],['Beg B',bRed,bAll]])}Beg manakah memberi peluang lebih tinggi memilih merah?`,ans,[N(ans==='Beg A'?'Beg B':'Beg A','data'),N('Sama peluang','data'),N('Tidak boleh ditentukan','data')],'Banding nisbah merah kepada jumlah, bukan bilangan merah sahaja.','Tahun 6 · Banding Kebarangkalian',true,true),id,mode,'table','reasoning',['data']);}let labels=['A','B','C','D'],vals=labels.map(()=>R(12,40)),vis=barChart(labels,vals),sum=vals.reduce((a,b)=>a+b,0),ans=Math.round(sum/4);if(mode==='chart_reason'){let hi=vals.indexOf(Math.max(...vals)),lo=vals.indexOf(Math.min(...vals)),diff=vals[hi]-vals[lo];return depth(Q(`${vis}Berapa tambahan diperlukan oleh kategori ${labels[lo]} untuk menyamai ${labels[hi]}?`,diff,[N(vals[hi],'data'),N(vals[lo],'data'),N(diff+5,'data')],'Cari beza antara nilai tertinggi dan nilai kategori yang lebih rendah.','Tahun 6 · Penaakulan Carta',true,true),id,mode,'visual','reasoning',['data']);}return depth(Q(`${vis}Purata hampir bagi empat kategori?`,ans,[N(Math.max(...vals),'data'),N(sum,'operation'),N(Math.round(sum/3),'data')],'Jumlahkan semua nilai kemudian bahagi empat.','Tahun 6 · Tafsir Data',true,true),id,mode,'visual','application',['data']);}
 return null;
}

// D2 already has the strongest contract-specific repair layer from v3.18.1.
// Keep it authoritative rather than reintroducing cross-skill overrides.
const D2_IDS=[
'D2.1.1','D2.1.2','D2.1.3','D2.1.4','D2.1.5','D2.1.6','D2.1.7','D2.1.8',
'D2.2.1','D2.2.2','D2.2.3','D2.2.4','D2.2.5',
'D2.3.1','D2.3.2','D2.3.3','D2.3.4',
'D2.4.1','D2.4.2','D2.4.3','D2.4.4','D2.4.5','D2.4.6','D2.4.7',
'D2.5.1','D2.5.2','D2.5.3','D2.6.1','D2.6.2','D2.6.3','D2.6.4',
'D2.7.1','D2.7.2','D2.7.3','D2.8.1','D2.8.2','D2.8.3'];

const CONTRACT_STATUS={};
D2_IDS.forEach(id=>CONTRACT_STATUS[id]='preserve-integrity-v3.18.1');
[
'D1.N20','D1.N100','D1.PV100','D1.CMP100','D1.ADD20','D1.SUB20','D1.ADD100','D1.SUB100','D1.FRAC','D1.MONEY','D1.TIME','D1.MEASURE','D1.SHAPE','D1.DATA',
'D3.N10000','D3.PV10000','D3.ADD10000','D3.SUB10000','D3.MUL','D3.DIV','D3.FRAC','D3.DEC','D3.MONEY','D3.TIME','D3.MEASURE','D3.SHAPE','D3.DATA',
'D4.N100000','D4.PV100000','D4.ADD','D4.SUB','D4.MUL','D4.DIV','D4.FRAC','D4.DEC','D4.MONEY','D4.TIME','D4.MEASURE','D4.PERIM','D4.DATA',
'D5.N1000000','D5.PV1000000','D5.MUL','D5.DIV','D5.FRAC','D5.DEC','D5.PERCENT','D5.MONEY','D5.TIME','D5.MEASURE','D5.AREA','D5.COORD','D5.DATA',
'D6.NUMBERS','D6.OPS','D6.FRAC','D6.DEC','D6.PERCENT','D6.RATIO','D6.MONEY','D6.TIME','D6.MEASURE','D6.AREA','D6.COORD','D6.DATA'
].forEach(id=>CONTRACT_STATUS[id]='depth-v3.22.0');

function wrapBank(key,gradeFn,prefix){
 const prev=previous[key];
 banks[key]=function(id,s,shift){
   if(!String(id).startsWith(prefix))return prev?.(id,s,shift)||null;
   const q=gradeFn(id,s,shift);
   return q||prev?.(id,s,shift)||null;
 };
}
wrapBank('d1',d1,'D1.');
wrapBank('d3',d3,'D3.');
wrapBank('d4',d4,'D4.');
wrapBank('d5',d5,'D5.');
wrapBank('d6',d6,'D6.');

window.PAKSSRDepth={
 version:VERSION,
 contractStatus:CONTRACT_STATUS,
 visualHelpers:{numLine,fractionStrip,fractionSet,hundredGrid,pictograph,miniTable,ruler,rectDiagram,coordinateMap,spinner,timeBar},
 generators:{d1,d3,d4,d5,d6}
};
document.documentElement?.setAttribute('data-kssr-depth',VERSION);
})();