// KSSR archetype layer: preserves every bank/scoring field while rotating the
// mathematical action, representation and cognitive demand.
(function(){
 const banks=window.PAQuestionBanks||{};
 const originals={};Object.keys(banks).forEach(k=>originals[k]=banks[k]);
 const safe=s=>String(s??'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
 const strategyByDomain={Nombor:'Banding nilai tempat dari kiri',Operasi:'Pilih operasi dan ikut tertibnya',Pecahan:'Gunakan pengangka dan penyebut',Perpuluhan:'Selarikan nilai tempat perpuluhan',Peratus:'Hubungkan nilai dengan 100%',Wang:'Tentukan jumlah, belanja atau baki',Masa:'Gunakan garis masa dan unit yang sama',Ukuran:'Samakan unit sebelum mengira',Ruang:'Gunakan ciri dan ukuran bentuk',Kedudukan:'Baca arah dan kedudukan relatif',Koordinat:'Baca paksi-x dahulu, kemudian paksi-y',Nisbah:'Kekalkan urutan dua kuantiti',Kadaran:'Cari nilai bagi satu unit dahulu',Data:'Baca label dan skala sebelum mengira',Kebolehjadian:'Banding bilangan hasil yang mungkin'};
 const misconceptionLabels={place:'Tersalah nilai tempat',digit_value:'Menggunakan digit, bukan nilainya',operation:'Memilih operasi yang salah',units_only:'Mengira digit hujung sahaja',same_end:'Memilih ikut digit akhir',pattern:'Tidak menggunakan beza yang tetap',round:'Tersalah digit penentu',fraction:'Pengangka dan penyebut tertukar',decimal:'Titik perpuluhan tidak diselarikan',money:'Nilai wang atau baki tersalah',time:'Jam, minit atau tempoh tertukar',unit:'Faktor penukaran unit tersalah',shape:'Ciri bentuk tersalah',data:'Label atau skala carta tersalah',fact:'Fakta darab tersalah',division:'Hubungan darab-bahagi tersalah',percent:'Tidak menghubungkan dengan 100%',ratio:'Urutan atau faktor nisbah tersalah',area:'Luas, perimeter dan isipadu tertukar',coord:'Paksi-x dan paksi-y tertukar',generated:'Cara kira tidak sepadan'};
 function meta(q,id,a,representation,demand,context='general',targets=[]){q.archetypeId=a;q.representation=representation;q.demand=demand;q.contextId=context;q.difficultyBand=demand==='reasoning'?4:demand==='application'?3:demand==='procedure'?2:1;q.misconceptionTargets=targets;q.familyKey=id;return q}
 function recentFor(id){return ((typeof sess!=='undefined'&&sess?.questionHistory)||[]).filter(x=>x.skillId===id).slice(-4)}
 function rotate(id,modes){const used=recentFor(id),clean=x=>String(x||'').replace(/^content_/,'');const last=clean(used.at(-1)?.archetypeId);const pool=modes.filter(x=>x!==last);const counts=Object.fromEntries(modes.map(x=>[x,used.filter(y=>clean(y.archetypeId)===x).length]));pool.sort((a,b)=>counts[a]-counts[b]||Math.random()-.5);return pool[0]||modes[0]}
 function methodQuestion(id,q){
  const m=META[id],correct=strategyByDomain[m.domain]||safe(q.hint)||'Kenal pasti maklumat dan operasi';
  const wrong=['Tambah semua nombor tanpa melihat soalan','Pilih jawapan yang mempunyai digit sama','Abaikan unit dan rajah','Gunakan operasi secara rawak'].filter(x=>x!==correct).slice(0,3).map(x=>N(x,'operation'));
  return meta(Q(`${q.prompt}<div class="kssrTask"><b>Fikir cara:</b> Langkah manakah paling sesuai untuk memulakan soalan ini?</div>`,correct,wrong,`Cari apa yang diketahui, apa yang dicari dan model atau operasi yang sesuai.`,`${q.kind} · Fikir Cara`,true,true),id,'choose_strategy','model','concept','strategy',[q.wrong?.[0]?.tag||'operation']);
 }
 function errorQuestion(id,q){
  const bad=q.wrong?.[0]||N('jawapan lain','generated'),tag=bad.tag||'generated',correct=misconceptionLabels[tag]||'Cara kira tidak sepadan dengan soalan';
  const alt=Object.entries(misconceptionLabels).filter(([k,v])=>k!==tag&&v!==correct).sort(()=>Math.random()-.5).slice(0,3).map(([k,v])=>N(v,k));
  return meta(Q(`${q.prompt}<div class="kssrTask error"><b>Semak cara:</b> Seorang murid memilih <b>${safe(bad.label??bad.v)}</b>. Apakah kesalahan yang paling mungkin?</div>`,correct,alt,`Bandingkan jawapan murid dengan unit, model dan operasi yang diminta.`,`${q.kind} · Semak Kesalahan`,true,true),id,'error_analysis','error-analysis','reasoning','peer-check',[tag]);
 }
 function baseWithMeta(id,q){const tag=q.wrong?.[0]?.tag||'generated';return meta(q,id,'solve_direct',q.prompt.includes('<svg')?'visual':'symbolic','procedure','direct',[tag])}

 function measurement(id){
  const cfg={
   'D3.MEASURE':{major:'m',minor:'cm',factor:100,majorName:'meter',minorName:'sentimeter',context:'reben'},
   'D4.MEASURE':{major:'km',minor:'m',factor:1000,majorName:'kilometer',minorName:'meter',context:'laluan'},
   'D5.MEASURE':{major:'L',minor:'mL',factor:1000,majorName:'liter',minorName:'mililiter',context:'minuman'},
   'D6.MEASURE':{major:'kg',minor:'g',factor:1000,majorName:'kilogram',minorName:'gram',context:'parcel'}
  }[id];if(!cfg)return null;
  const modes=['mixed_to_minor','minor_to_mixed','missing_component','compare_units','operation_story','conversion_error'],mode=rotate(id,modes),A=R(1,8),B=cfg.factor===100?R(1,19)*5:R(1,19)*50,total=A*cfg.factor+B;
  if(mode==='mixed_to_minor')return meta(Q(`${A} ${cfg.major} ${B} ${cfg.minor} = berapa ${cfg.minor}?`,total,[N(A+B,'unit'),N(A*(cfg.factor/10)+B,'unit'),N(total+cfg.factor,'unit')],`1 ${cfg.major} = ${cfg.factor} ${cfg.minor}.`,`${META[id].gradeLabel||'KSSR'} · Tukar Unit`,true,true),id,mode,'symbolic','procedure',cfg.context,['unit_factor','ignore_major_unit']);
  if(mode==='minor_to_mixed'){const ans=`${A} ${cfg.major} ${B} ${cfg.minor}`;return meta(Q(`${total} ${cfg.minor} = ?`,ans,[N(`${total} ${cfg.major}`,'unit'),N(`${A+B} ${cfg.major} ${cfg.minor}`,'unit'),N(`${A} ${cfg.major} ${B+cfg.factor/10} ${cfg.minor}`,'unit')],`Kumpulkan setiap ${cfg.factor} ${cfg.minor} sebagai 1 ${cfg.major}.`,'KSSR · Tukar Terbalik',true,true),id,mode,'symbolic','concept',cfg.context,['unit_factor']);}
  if(mode==='missing_component'){const ans=B;return meta(Q(`${A} ${cfg.major} ___ ${cfg.minor} = ${total} ${cfg.minor}. Apakah nombor yang hilang?`,ans,[N(A+B,'unit'),N(total-A,'unit'),N(cfg.factor-B,'unit')],`Tukar ${A} ${cfg.major} kepada ${A*cfg.factor} ${cfg.minor}, kemudian cari bakinya.`,'KSSR · Nilai Hilang',true,true),id,mode,'symbolic','reasoning','missing',['unit_factor']);}
  if(mode==='compare_units'){const other=total+pick([-100,-50,50,100]),ans=total>other?'A':'B';return meta(Q(`${cfg.context==='parcel'?'Parcel':'Kuantiti'} A ialah <b>${A} ${cfg.major} ${B} ${cfg.minor}</b>. ${cfg.context==='parcel'?'Parcel':'Kuantiti'} B ialah <b>${other} ${cfg.minor}</b>. Yang manakah lebih besar?`,ans,[N(ans==='A'?'B':'A','unit'),N('Sama','unit'),N('Tidak dapat ditentukan','unit')],`Samakan kedua-duanya dalam ${cfg.minor}, kemudian bandingkan.`,'KSSR · Banding Ukuran',true,true),id,mode,'story','application',cfg.context,['compare_units']);}
  if(mode==='operation_story'){const extra=pick([100,200,250,500]),ans=total+extra;return meta(Q(`Satu ${cfg.context} mempunyai ${A} ${cfg.major} ${B} ${cfg.minor}. Sebanyak ${extra} ${cfg.minor} ditambah. Berapakah jumlah dalam ${cfg.minor}?`,ans,[N(total-extra,'operation'),N(A+B+extra,'unit'),N(ans+cfg.factor,'unit')],`Samakan unit, kemudian tambah.`,'KSSR · Selesaikan Masalah',true,true),id,mode,'story','application',cfg.context,['operation','unit_factor']);}
  const claim=A+B,correct='Dia menambah nombor tanpa menukar unit';return meta(Q(`Nadia berkata <b>${A} ${cfg.major} ${B} ${cfg.minor} = ${claim} ${cfg.minor}</b>. Apakah kesalahannya?`,correct,[N('Dia sepatutnya menolak kedua-dua nombor','operation'),N('Dia menukar unit dua kali','unit'),N('Tiada kesalahan','unit')],`Nilai ${A} ${cfg.major} mesti didarab ${cfg.factor} dahulu.`,'KSSR · Analisis Kesalahan',true,true),id,mode,'error-analysis','reasoning','peer-check',['ignore_major_unit']);
 }

 function addedSkill(id){
  if(id==='D3.PERCENT'||id==='D4.PERCENT'){const p=pick([10,20,25,40,50,60,75]),mode=rotate(id,['visual_percent','fraction_percent','quantity_percent']);if(mode==='visual_percent')return meta(Q(`${percentVisual(Math.ceil(p/10)*10)}Apakah peratus bahagian berlorek?`,`${Math.ceil(p/10)*10}%`,[N(`${100-Math.ceil(p/10)*10}%`,'percent'),N(`${Math.ceil(p/10)}/10`,'fraction'),N(`${Math.ceil(p/10)*10}`,'percent')],'Setiap petak mewakili 10%.','KSSR · Peratus',true,true),id,mode,'visual','concept','hundred-grid',['percent']);if(mode==='fraction_percent')return meta(Q(`${p/10}/10 bersamaan berapa peratus?`,`${p}%`,[N(`${p/10}%`,'percent'),N(`${100-p}%`,'percent'),N(`${p}`,'percent')],'Penyebut 10: setiap satu bahagian ialah 10%.','KSSR · Peratus',true,true),id,mode,'symbolic','procedure','fraction',['percent']);const base=pick([20,40,60,80,100]),ans=base*p/100;return meta(Q(`${p}% daripada ${base} = ?`,ans,[N(base-p,'percent'),N(p,'percent'),N(ans+10,'operation')],'Tukar peratus kepada bahagian daripada 100.','KSSR · Guna Peratus',true,true),id,mode,'story','application','quantity',['percent']);}
  if(id==='D3.POSITION'||id==='D4.COORD'){const x=R(1,4),y=R(1,4),mode=rotate(id,['read_grid','reverse_axes','move_point']);if(mode==='move_point'){const dx=R(1,2),ans=`(${x+dx},${y})`;return meta(Q(`${coordGrid(x,y)}Titik bergerak ${dx} petak ke kanan. Apakah kedudukan baharu?`,ans,[N(`(${x},${y+dx})`,'coord'),N(`(${y},${x+dx})`,'coord'),N(`(${x-dx},${y})`,'coord')],'Gerak ke kanan menambah nilai mengufuk.','KSSR · Kedudukan',true,true),id,mode,'visual','application','grid',['coord']);}const ans=`(${x},${y})`;return meta(Q(`${coordGrid(x,y)}Apakah koordinat titik ●?`,ans,[N(`(${y},${x})`,'coord'),N(`(${x+1},${y})`,'coord'),N(`(${x},${Math.max(0,y-1)})`,'coord')],'Baca mengufuk dahulu, kemudian mencancang.','KSSR · Kedudukan',true,true),id,mode,'visual',mode==='reverse_axes'?'reasoning':'concept','grid',['coord']);}
  if(['D4.RATIO','D5.RATIO'].includes(id)){const a=R(1,4),b=R(2,6),k=R(2,4),mode=rotate(id,['write_ratio','equivalent_ratio','missing_ratio']);if(mode==='missing_ratio')return meta(Q(`${a}:${b} = ${a*k}:___`,b*k,[N(b+k,'ratio'),N(a*k,'ratio'),N(b,'ratio')],'Darab kedua-dua bahagian dengan faktor yang sama.','KSSR · Nisbah',true,true),id,mode,'symbolic','reasoning','ratio',['ratio']);const ans=mode==='write_ratio'?`${a}:${b}`:`${a*k}:${b*k}`;return meta(Q(mode==='write_ratio'?`Satu kumpulan mempunyai ${a} objek merah dan ${b} objek biru. Apakah nisbah merah kepada biru?`:`Nisbah setara bagi ${a}:${b} ialah?`,ans,[N(`${b}:${a}`,'ratio'),N(`${a+b}:${b}`,'ratio'),N(`${a}:${b*k}`,'ratio')],'Kekalkan urutan kuantiti dan faktor yang sama.','KSSR · Nisbah',true,true),id,mode,mode==='write_ratio'?'story':'symbolic',mode==='write_ratio'?'concept':'procedure','objects',['ratio']);}
  if(['D4.RATE','D5.RATE'].includes(id)){const packs=R(2,5),each=pick([2,3,4,5]),total=packs*each,mode=rotate(id,['unit_rate','scale_rate','missing_rate']);if(mode==='unit_rate')return meta(Q(`${total} botol disusun sama rata dalam ${packs} kotak. Berapa botol dalam satu kotak?`,each,[N(packs,'division'),N(total+packs,'operation'),N(each+1,'division')],'Cari nilai bagi satu kumpulan.','KSSR · Kadaran',true,true),id,mode,'story','concept','packing',['division']);const k=R(2,4),ans=total*k;return meta(Q(`${packs} kotak mengandungi ${total} botol. Pada kadar yang sama, ${packs*k} kotak mengandungi berapa botol?`,ans,[N(total+k,'ratio'),N(packs*k,'division'),N(ans-packs,'operation')],'Darab kedua-dua kuantiti dengan faktor yang sama.','KSSR · Kadaran',true,true),id,mode,'table','application','packing',['ratio']);}
  if(['D5.ADD','D5.SUB','D5.OPS'].includes(id)){let a=R(10000,600000),b=R(1000,200000);if(id==='D5.ADD'){const ans=a+b;return meta(addQ(a,b,ans,'KSSR · Operasi',true),id,'large_add','symbolic','procedure','numbers',['place']);}if(id==='D5.SUB'){if(b>a)[a,b]=[b,a];const ans=a-b;return meta(subQ(a,b,ans,'KSSR · Operasi',true),id,'large_sub','symbolic','procedure','numbers',['place']);}const c=R(2,8),ans=a+b*c;return meta(Q(`${a} + ${b} × ${c} = ?`,ans,[N((a+b)*c,'operation'),N(a+b+c,'operation'),N(a*b+c,'operation')],'Darab dahulu, kemudian tambah.','KSSR · Operasi Bergabung',true,true),id,'combined_order','symbolic','reasoning','numbers',['operation']);}
  if(id==='D6.PROB'){const red=R(1,5),blue=R(1,5),mode=rotate(id,['certain_impossible','compare_chance','fraction_chance']);if(mode==='compare_chance'){const ans=red>blue?'merah':blue>red?'biru':'sama kemungkinan';return meta(Q(`Sebuah beg mengandungi ${red} guli merah dan ${blue} guli biru. Warna manakah lebih besar kemungkinan dipilih?`,ans,[N(ans==='merah'?'biru':'merah','data'),N('mustahil','data'),N('pasti','data')],'Banding bilangan hasil bagi setiap warna.','KSSR · Kebolehjadian',true,true),id,mode,'story','application','bag',['data']);}const total=red+blue,ans=`${red}/${total}`;return meta(Q(`Beg mengandungi ${red} guli merah dan ${blue} guli biru. Pecahan kebarangkalian memilih merah ialah?`,ans,[N(`${blue}/${total}`,'fraction'),N(`${red}/${blue}`,'fraction'),N(`${total}/${red}`,'fraction')],'Hasil dikehendaki ÷ jumlah hasil.','KSSR · Kebolehjadian',true,true),id,mode,'story','reasoning','bag',['fraction']);}
  return null;
 }

 function wrap(key){const original=originals[key];banks[key]=function(id,s,shift){
  let q=measurement(id);if(q)return q;
  q=addedSkill(id);
  // The battle quiz always asks pupils to solve curriculum mathematics.
  // Strategy and misconception tags stay as silent evidence for the adaptive
  // engine, Cikgu Wajar and Parent Mode; they are never replacement questions.
  if(q){q.archetypeId=`content_${q.archetypeId}`;return q;}
  q=original?original(id,s,shift):null;if(!q)return null;
  return baseWithMeta(id,q);
 }}
 ['d1','d2t1','d2t2','d2t3','d2t4','d2t5','d2t6','d2t7','d2t8','d3','d4','d5','d6'].forEach(wrap);
})();
