// Pahlawan Angka — KSSR Year 6 cognitive-depth hardening v3.60.2
// Final D6 wrapper. Load AFTER kssr-year6-space-data-v3.23.0.js.
// Rule: a non-operation topic may use arithmetic, but the arithmetic must be
// necessary to demonstrate the Year 6 domain concept. High-stage items must
// require domain reasoning, not merely a dressed-up basic calculation.
(function(){
'use strict';
const VERSION='3.60.2',banks=window.PAQuestionBanks=window.PAQuestionBanks||{},prior=banks.d6;
if(typeof prior!=='function')return;
const H=window.PAY6KSSRRepair?.helpers||{},VH=window.PAKSSRDepth?.visualHelpers||{};
const choose=a=>pick(a),rand=(a,b)=>R(a,b),Nq=(v,t)=>N(v,t);
const tidy=(v,d=2)=>typeof tidyNumber==='function'?tidyNumber(v,d):Number(Number(v).toFixed(d));
const money=v=>typeof moneyFmtUpper==='function'?moneyFmtUpper(Number(tidy(v,2))):'RM'+Number(v).toFixed(2);
const table=(h,r)=>VH.miniTable?VH.miniTable(h,r):'<table>'+r.map(x=>'<tr>'+x.map(y=>'<td>'+y+'</td>').join('')+'</tr>').join('')+'</table>';
const coord=(pts,scale)=>VH.coordinateMap?VH.coordinateMap(pts,scale):table(['Titik','x','y'],pts.map(p=>[p.label,p.x,p.y]));
const protractor=d=>H.protractorSvg?H.protractorSvg(d):'<div class="kssrDiagram">Sudut '+d+'°</div>';
const polygon=n=>H.regularPolygonSvg?H.regularPolygonSvg(n):'<div class="kssrDiagram">Poligon sekata '+n+' sisi</div>';
const circle=(m,r)=>H.circleSvg?H.circleSvg(m,r):'<div class="kssrDiagram">Bulatan</div>';
const pie=(s,o={})=>H.pieSvg?H.pieSvg(s,o):table(['Kategori','Sudut'],s.map(x=>[x.label,x.angle+'°']));
const bag=(r,b,g=0)=>H.bagVisual?H.bagVisual(r,b,g):table(['Warna','Bilangan'],[['Merah',r],['Biru',b],['Hijau',g]]);
function stage(s){const m=Number(s?.mastery||0),e=Number(s?.evidence||0),c=Number(s?.confidence||0),w=Number(s?.wrong||0);if(e===0)return 2;if(w>=1&&e<=3)return 1;if(w>=2)return 1;if(e>=4&&(m<35||c<35))return 1;if(e<4||m<70||c<60)return 2;return 3}
const REF={
'D6.NUMBERS':['1.1.1','1.1.2','1.1.3','1.1.4','1.1.5','1.3.1','1.4.1'],
'D6.OPS':['1.2.1','2.4.1','2.5.1'],'D6.FRAC':['2.1.1','2.5.1'],'D6.DEC':['2.2.1','2.2.2','2.5.1'],
'D6.PERCENT':['2.3.1','2.3.2','2.3.3','2.5.1'],'D6.MONEY':['3.1.1','3.1.2','3.2.1','3.2.2','3.3.1'],
'D6.TIME':['4.1.1','4.1.2','4.2.1'],'D6.MEASURE':['5.1.1'],'D6.ANGLE':['6.1.1','6.1.2'],
'D6.CIRCLE':['6.2.1','6.2.2'],'D6.SPACE_PROBLEM':['6.3.1'],'D6.COORD':['7.1.1','7.4.1'],
'D6.RATIO':['7.2.1','7.3.1','7.4.1'],'D6.PIE':['8.1.1'],'D6.PROB':['8.2.1','8.2.2'],'D6.DATA_PROBLEM':['8.3.1']
};
const UNIT={1:'Nombor Bulat dan Operasi Asas',2:'Pecahan, Perpuluhan dan Peratus',3:'Wang',4:'Masa dan Waktu',5:'Ukuran dan Sukatan',6:'Ruang',7:'Koordinat, Nisbah dan Kadaran',8:'Pengurusan Data dan Kebolehjadian'};
const U={'D6.NUMBERS':1,'D6.OPS':1,'D6.FRAC':2,'D6.DEC':2,'D6.PERCENT':2,'D6.MONEY':3,'D6.TIME':4,'D6.MEASURE':5,'D6.ANGLE':6,'D6.CIRCLE':6,'D6.SPACE_PROBLEM':6,'D6.COORD':7,'D6.RATIO':7,'D6.PIE':8,'D6.PROB':8,'D6.DATA_PROBLEM':8};
try{if(typeof META!=='undefined')Object.keys(REF).forEach(id=>{if(META[id])Object.assign(META[id],{textbookUnit:U[id],textbookUnitTitle:UNIT[U[id]],kssrStandards:[...REF[id]],mappingConfidence:'verified-kssr-v3.60.2',coverage:'hardened-v3.60.2'})})}catch(_){}
function mark(q,id,sp,mode,rep,demand,s,targets=[]){if(!q)return q;q.source='kssr-year6-v3.60.2';q.standardRef=sp;q.competencyId=sp;q.archetypeId='y6kssr_'+mode;q.representation=rep;q.demand=demand;q.difficultyBand=stage(s)===3?4:stage(s)===2?3:2;q.misconceptionTargets=targets;q.kssrYear6Version=VERSION;return q}
function inherit(q,id,s){if(!q)return q;q.source='kssr-year6-v3.60.2';q.standardRef=q.standardRef||REF[id]?.join('/');q.competencyId=q.competencyId||q.standardRef;q.difficultyBand=stage(s)===3?4:stage(s)===2?3:2;q.kssrYear6Version=VERSION;return q}

function percentQ(id,s){
 const st=stage(s);
 if(st===1){const mode=choose(['convert','add','sub']);
  if(mode==='convert'){const d=choose([1.05,1.2,1.25,1.5,1.75]),a=tidy(d*100,1);return mark(Q('Tukar <b>'+d+'</b> kepada peratus.',a+'%',[Nq((a-100)+'%','percent'),Nq((d*10)+'%','percent'),Nq(d+'%','percent')],'Perpuluhan kepada peratus: darab 100%.','Tahun 6 · Hubungan Peratus',true,true),id,'2.3.1','percent_convert','symbolic','procedure',s,['percent'])}
  if(mode==='add'){const a=choose([25,40,75,120,150]),b=choose([10,20,25,50]),ans=a+b;return mark(Q(a+'% + '+b+'% = ?',ans+'%',[Nq(Math.abs(a-b)+'%','percent'),Nq((ans+10)+'%','percent'),Nq((ans/100)+'%','percent')],'Operasi tambah melibatkan peratus ialah kemahiran Tahun 6.','Tahun 6 · Tambah Peratus',true,true),id,'2.3.2','percent_add','symbolic','procedure',s,['percent'])}
  const a=choose([125,150,175,200]),b=choose([25,50,75]),ans=a-b;return mark(Q(a+'% − '+b+'% = ?',ans+'%',[Nq((a+b)+'%','percent'),Nq((ans+25)+'%','percent'),Nq((ans/100)+'%','percent')],'Tolak nilai peratus dengan teliti.','Tahun 6 · Tolak Peratus',true,true),id,'2.3.2','percent_sub','symbolic','procedure',s,['percent']);
 }
 if(st===2){const pct=choose([110,125,150,175]),base=choose([1.6,2.4,3.2,4.8]),ans=tidy(base*pct/100,3);return mark(Q(pct+'% daripada '+base+' = ?',String(ans),[Nq(String(base),'percent'),Nq(String(tidy(base*(pct-100)/100,3)),'percent'),Nq(String(tidy(base+pct,3)),'operation')],'Lebih 100% bermaksud nilai melebihi kuantiti asal.','Tahun 6 · Nilai Peratus',true,true),id,'2.3.3','percent_over100','symbolic','application',s,['percent','decimal'])}
 const base=choose([2.4,3.2,4.8]),pct=choose([125,150,175]),drop=choose([25,50]),finalPct=pct-drop,ans=tidy(base*finalPct/100,3);
 return mark(Q('Pengeluaran asal '+base+' L ialah 100%. Tetapan dinaikkan kepada '+pct+'%, kemudian dikurangkan '+drop+' mata peratus. Berapakah pengeluaran akhir?',ans+' L',[Nq(tidy(base*pct/100,3)+' L','percent'),Nq(tidy(base*drop/100,3)+' L','percent'),Nq((pct-drop)+' L','operation')],'Tentukan peratus akhir dahulu, kemudian gunakan pada kuantiti asal.','Tahun 6 · Masalah Peratus Pelbagai Langkah',true,true),id,'2.5.1','percent_context_reason','story','reasoning',s,['percent','multi_step']);
}
function moneyQ(id,s){
 const st=stage(s);
 if(st===1){if(Math.random()<.5)return mark(Q('Dokumen yang mengesahkan bayaran telah diterima ialah?','resit',[Nq('invois','financial_term'),Nq('baucer','financial_term'),Nq('liabiliti','financial_term')],'Bezakan fungsi dokumen kewangan.','Tahun 6 · Istilah Kewangan',true,true),id,'3.1.1','money_term','verbal','concept',s,['financial_term']);
  return mark(Q('Tujuan utama insurans atau takaful ialah?','melindungi pencarum atau aset daripada risiko kewangan tertentu',[Nq('menjamin setiap pelaburan sentiasa untung','insurance'),Nq('menghapuskan semua hutang secara automatik','insurance'),Nq('menggantikan fungsi resit','insurance')],'Insurans dan takaful ialah perlindungan terhadap risiko.','Tahun 6 · Insurans dan Takaful',true,true),id,'3.2.1/3.2.2','money_protection','verbal','concept',s,['insurance','risk']);
 }
 if(st===2){if(Math.random()<.5){const cost=choose([80,120,150,200]),delta=choose([15,20,30,40]),profit=Math.random()<.5,sell=profit?cost+delta:cost-delta,ans=(profit?'untung RM':'rugi RM')+delta;return mark(Q('Harga kos RM'+cost+', harga jual RM'+sell+'. Apakah keputusan urus niaga?',ans,[Nq((profit?'rugi RM':'untung RM')+delta,'profit_loss'),Nq('untung RM'+cost,'profit_loss'),Nq('tiada untung atau rugi','profit_loss')],'Banding harga jual dengan harga kos.','Tahun 6 · Untung dan Rugi',true,true),id,'3.1.2','money_profit_loss','story','application',s,['profit_loss'])}
  const price=choose([100,120,160,200]),disc=choose([10,20,25]),reb=choose([5,10]),off=price*disc/100,ans=money(price-off-reb);return mark(Q('Harga RM'+price+'. Diskaun '+disc+'%, kemudian rebat tunai RM'+reb+'. Bayaran akhir?',ans,[Nq(money(price-off),'money'),Nq(money(off+reb),'money'),Nq(money(price+reb),'operation')],'Kira diskaun, kemudian tolak rebat.','Tahun 6 · Diskaun dan Rebat',true,true),id,'3.1.2','money_discount_rebate','story','application',s,['discount','rebate']);
 }
 if(Math.random()<.5){const cost=choose([120,160,200]),markup=choose([30,40,50]),sell=cost+markup,disc=choose([10,20]),paid=sell*(100-disc)/100,p=tidy(paid-cost,2),ans=p>=0?'untung '+money(p):'rugi '+money(Math.abs(p));return mark(Q('Peniaga membeli barang pada '+money(cost)+' dan menetapkan harga jual '+money(sell)+'. Pelanggan mendapat diskaun '+disc+'%. Selepas jualan, peniaga memperoleh?',ans,[Nq('untung '+money(markup),'profit_loss'),Nq(p>=0?'rugi '+money(Math.abs(p)):'untung '+money(Math.abs(p)),'profit_loss'),Nq('tiada untung atau rugi','profit_loss')],'Cari harga selepas diskaun, kemudian banding dengan harga kos.','Tahun 6 · Masalah Pendidikan Kewangan',true,true),id,'3.3.1','money_transaction','story','reasoning',s,['profit_loss','discount','multi_step'])}
 return mark(Q('Sebuah keluarga memiliki motosikal yang digunakan setiap hari. Mereka mahu mengurus risiko kerugian akibat kejadian tidak dijangka. Pilihan paling munasabah?','pertimbang perlindungan insurans atau takaful yang sesuai dengan risiko',[Nq('abaikan perlindungan kerana aset sentiasa kekal nilainya','risk'),Nq('buat pinjaman baharu kerana pinjaman menghapuskan risiko','risk'),Nq('simpan resit sahaja kerana resit menggantikan perlindungan','risk')],'Hubungkan aset, risiko dan tujuan perlindungan.','Tahun 6 · Penaakulan Risiko Kewangan',true,true),id,'3.2.2/3.3.1','money_risk','story','reasoning',s,['insurance','risk']);
}
const Z=[['Kuala Lumpur',8],['Tokyo',9],['Bangkok',7],['Dubai',4]],fmt=(h,m)=>String((h%24+24)%24).padStart(2,'0')+':'+String(m).padStart(2,'0');
function timeQ(id,s){
 const st=stage(s),a=choose(Z),b=choose(Z.filter(x=>x[0]!==a[0])),delta=b[1]-a[1];
 if(st===1)return mark(Q(a[0]+' ialah UTC'+(a[1]>=0?'+':'')+a[1]+' dan '+b[0]+' ialah UTC'+(b[1]>=0?'+':'')+b[1]+'. Beza zon masa?',Math.abs(delta)+' jam',[Nq((Math.abs(delta)+1)+' jam','time'),Nq(Math.max(0,Math.abs(delta)-1)+' jam','time'),Nq((a[1]+b[1])+' jam','time')],'Cari beza nilai UTC.','Tahun 6 · Zon Masa',true,true),id,'4.1.1/4.1.2','time_zone_difference','story','concept',s,['timezone']);
 const h=rand(6,18),m=choose([0,15,30,45]),target=h+delta;
 if(st===2)return mark(Q(a[0]+': '+fmt(h,m)+'. Apakah waktu pada masa yang sama di '+b[0]+'?',fmt(target,m),[Nq(fmt(target+1,m),'time'),Nq(fmt(target-1,m),'time'),Nq(fmt(h,m),'time')],'Laraskan waktu mengikut beza zon.','Tahun 6 · Menentukan Masa Antara Zon',true,true),id,'4.1.2','time_zone_convert','story','application',s,['timezone']);
 const dur=choose([3,4,5,6]),ans=fmt(h+dur+delta,m);return mark(Q('Penerbangan berlepas dari '+a[0]+' pada '+fmt(h,m)+' dan mengambil masa '+dur+' jam. Apakah waktu tempatan ketika tiba di '+b[0]+'?',ans,[Nq(fmt(h+dur,m),'time'),Nq(fmt(h+dur+delta+1,m),'time'),Nq(fmt(h+dur+delta-1,m),'time')],'Tambah tempoh perjalanan, kemudian laraskan beza zon masa.','Tahun 6 · Masalah Zon Masa',true,true),id,'4.2.1','time_zone_travel','story','reasoning',s,['timezone','duration','multi_step']);
}
function measureQ(id,s){
 const st=stage(s);
 if(st===1){const mode=choose(['lm','ll','ml']);
  if(mode==='lm'){const L=choose([2,3,4]),M=choose([0.6,0.9,1.2]),k=choose([2,3]),ans=tidy(M*k,2);return mark(Q(L+' m kabel berjisim '+M+' kg. Kabel sama jenis sepanjang '+(L*k)+' m berjisim?',ans+' kg',[Nq(M+' kg','unit'),Nq(tidy(M+k,2)+' kg','operation'),Nq(tidy(ans+M,2)+' kg','unit')],'Gunakan perkaitan berkadar panjang dengan jisim.','Tahun 6 · Panjang dan Jisim',true,true),id,'5.1.1(i)','measure_length_mass','story','application',s,['length','mass'])}
  if(mode==='ll'){const L=choose([2,4,5]),V=choose([0.5,1,1.25]),k=choose([2,3]),ans=tidy(V*k,2);return mark(Q(L+' m kain memerlukan '+V+' L pewarna. '+(L*k)+' m kain memerlukan?',ans+' L',[Nq(V+' L','unit'),Nq(tidy(V+k,2)+' L','operation'),Nq(tidy(ans+1,2)+' L','unit')],'Skalakan panjang dan isi padu dengan faktor yang sama.','Tahun 6 · Panjang dan Isi Padu Cecair',true,true),id,'5.1.1(ii)','measure_length_liquid','story','application',s,['length','liquid'])}
  const V=choose([1,1.5,2]),M=choose([0.8,1.2,1.6]),k=choose([2,3]),ans=tidy(M*k,2);return mark(Q(V+' L cecair berjisim '+M+' kg. '+(V*k)+' L cecair yang sama berjisim?',ans+' kg',[Nq(M+' kg','unit'),Nq(tidy(M+k,2)+' kg','operation'),Nq(tidy(ans+1,2)+' kg','unit')],'Gunakan perkaitan jisim dan isi padu bagi cecair yang sama.','Tahun 6 · Jisim dan Isi Padu Cecair',true,true),id,'5.1.1(iii)','measure_mass_liquid','story','application',s,['mass','liquid']);
 }
 if(st===2){const L=choose([2,2.5,3]),M=choose([0.5,0.75,1]),need=L*4,total=M*4,limit=tidy(total-0.25,2);return mark(Q(L+' m dawai berjisim '+M+' kg. Projek memerlukan '+need+' m, tetapi had muatan '+limit+' kg. Adakah had mencukupi?','tidak, jisim diperlukan ialah '+total+' kg',[Nq('ya, kerana panjang sahaja menentukan muatan','unit'),Nq('ya, kerana semua dawai kurang 10 kg','unit'),Nq('tidak boleh ditentukan','unit')],'Cari jisim untuk panjang diperlukan, kemudian banding had.','Tahun 6 · Masalah Ukuran',true,true),id,'5.1.1(i)','measure_compare_limit','story','reasoning',s,['length','mass','compare'])}
 const L=choose([2,4]),V=choose([0.5,1]),rolls=choose([3,4]),unused=choose([1,2]),used=L*rolls-unused,ans=tidy(used*(V/L),2);return mark(Q('Setiap '+L+' m kain memerlukan '+V+' L pewarna. Ada '+rolls+' gulung kain '+L+' m, tetapi '+unused+' m tidak digunakan. Berapa liter pewarna diperlukan?',ans+' L',[Nq(tidy(V*rolls,2)+' L','liquid'),Nq(used+' L','operation'),Nq(tidy(ans+V,2)+' L','liquid')],'Cari panjang sebenar yang digunakan, kemudian gunakan kadar pewarna per meter.','Tahun 6 · Ukuran Pelbagai Langkah',true,true),id,'5.1.1(ii)','measure_multi_relation','story','reasoning',s,['length','liquid','multi_step']);
}
function coordQ(id,s){
 const st=stage(s),scale=choose([2,5,10]);
 if(st===1){const horizontal=Math.random()<.5;if(horizontal){const y=rand(1,4),x1=1,x2=rand(3,5),A={x:x1,y,label:'A'},B={x:x2,y,label:'B'},ans=(x2-x1)*scale+' km';return mark(Q(coord([A,B],scale)+'A dan B pada garisan mengufuk sama. 1 petak = '+scale+' km. Jarak A ke B?',ans,[Nq((x2-x1)+' km','scale'),Nq((x2-x1+1)*scale+' km','coord'),Nq(y*scale+' km','coord')],'Cari beza x dan gunakan skala.','Tahun 6 · Jarak Mengufuk Berskala',true,true),id,'7.1.1','coord_horizontal','visual','application',s,['coord','scale'])}
  const x=rand(1,4),y1=1,y2=rand(3,5),A={x,y:y1,label:'A'},B={x,y:y2,label:'B'},ans=(y2-y1)*scale+' km';return mark(Q(coord([A,B],scale)+'A dan B pada garisan mencancang sama. 1 petak = '+scale+' km. Jarak A ke B?',ans,[Nq((y2-y1)+' km','scale'),Nq((y2-y1+1)*scale+' km','coord'),Nq(x*scale+' km','coord')],'Cari beza y dan gunakan skala.','Tahun 6 · Jarak Mencancang Berskala',true,true),id,'7.1.1','coord_vertical','visual','application',s,['coord','scale']);
 }
 const A={x:1,y:1,label:'A'},B={x:rand(3,5),y:rand(3,5),label:'B'},dx=(B.x-A.x)*scale,dy=(B.y-A.y)*scale;
 if(st===2)return mark(Q(coord([A,B],scale)+'Skala 1 petak = '+scale+' km. Nyatakan jarak mengufuk dan mencancang A ke B.',dx+' km mengufuk dan '+dy+' km mencancang',[Nq(dy+' km mengufuk dan '+dx+' km mencancang','coord'),Nq((dx+dy)+' km sahaja','coord'),Nq((B.x-A.x)+' km dan '+(B.y-A.y)+' km','scale')],'Bezakan perubahan x dan y, kemudian gunakan skala.','Tahun 6 · Jarak Berskala',true,true),id,'7.1.1','coord_both','visual','reasoning',s,['coord','scale']);
 const C={x:B.x,y:A.y,label:'C'},ans=dx+dy+' km';return mark(Q(coord([A,B,C],scale)+'Laluan A → C → B bergerak mengufuk kemudian mencancang. 1 petak = '+scale+' km. Jumlah jarak?',ans,[Nq(Math.max(dx,dy)+' km','coord'),Nq((B.x-A.x+B.y-A.y)+' km','scale'),Nq((dx*dy)+' km','operation')],'Cari dua jarak berskala, kemudian jumlahkan.','Tahun 6 · Masalah Koordinat Berskala',true,true),id,'7.4.1','coord_route','visual','reasoning',s,['coord','scale','route']);
}
function spaceQ(id,s){
 const st=stage(s);
 if(st===1){const d=choose([12,16,18,20]),r=d/2,n=choose([3,4,5]),ans=r*n+' m';return mark(Q(circle('parts')+'Taman bulatan berdiameter '+d+' m. '+n+' laluan lurus dibina dari pusat ke tepi. Jumlah panjang semua laluan?',ans,[Nq(d*n+' m','radius_diameter'),Nq(d+' m','radius_diameter'),Nq((r+n)+' m','operation')],'Jejari ialah separuh diameter; setiap laluan ialah satu jejari.','Tahun 6 · Masalah Ruang Bulatan',true,true),id,'6.3.1','space_circle_radius','visual','application',s,['radius_diameter','space_reason'])}
 if(st===2){const p=choose([[3,60],[4,90],[6,120],[8,135]]),n=p[0],deg=p[1],count=choose([2,3]),ans=deg*count+'°';return mark(Q(polygon(n)+protractor(deg)+'Berdasarkan ukuran rajah, '+count+' sudut pedalaman poligon sekata '+n+' sisi dicantum. Jumlah sudut?',ans,[Nq(deg+'°','polygon_angle'),Nq((deg+count)+'°','operation'),Nq((180-deg)+'°','angle_measure')],'Baca ukuran sudut daripada rajah sebelum menggunakannya.','Tahun 6 · Masalah Sudut dan Poligon',true,true),id,'6.3.1','space_polygon','visual','reasoning',s,['polygon_angle','space_reason'])}
 const d=choose([14,18,20]),r=d/2,target=choose([75,105,135]),ans='jangka '+r+' cm dan protraktor '+target+'°';return mark(Q('Reka bentuk memerlukan bulatan berdiameter '+d+' cm dan sudut '+target+'°. Tetapan alat yang betul?',ans,[Nq('jangka '+d+' cm dan protraktor '+target+'°','circle_draw'),Nq('jangka '+r+' cm dan protraktor '+(180-target)+'°','angle_construct'),Nq('jangka '+(d*2)+' cm dan protraktor '+target+'°','circle_draw')],'Tukar diameter kepada jejari untuk jangka dan gunakan sudut sasaran pada protraktor.','Tahun 6 · Rancang Pembinaan Ruang',true,true),id,'6.3.1','space_construction_plan','story','reasoning',s,['circle_draw','angle_construct','space_reason']);
}
function highReason(id,s){
 if(id==='D6.NUMBERS'){const a=rand(2200000,4800000),b=rand(900000,2500000),est=Math.round(a/1000000)*1000000+Math.round(b/1000000)*1000000,good=Math.random()<.5,claim=good?est:est+2000000,ans=good?'munasabah':'tidak munasabah';return mark(Q('Selepas membundar kepada juta terdekat, murid mendakwa '+a.toLocaleString()+' + '+b.toLocaleString()+' ≈ '+claim.toLocaleString()+'. Penilaian?',ans,[Nq(ans==='munasabah'?'tidak munasabah':'munasabah','estimate'),Nq('tepat tanpa pengiraan','estimate'),Nq('tidak boleh ditentukan','estimate')],'Bandingkan magnitud selepas pembundaran.','Tahun 6 · Kewajaran Nombor',true,true),id,'1.4.1','numbers_reason','verbal','reasoning',s,['estimate'])}
 if(id==='D6.OPS'){const boxes=rand(4,9),each=rand(25,60),used=rand(30,90),ans=boxes*each-used;return mark(Q('Ada '+boxes+' kotak, setiap satu '+each+' unit. Selepas '+used+' unit digunakan, baki?',ans,[Nq(boxes*(each-used),'operation'),Nq(boxes+each-used,'operation'),Nq(boxes*each+used,'operation')],'Bina ayat matematik dua operasi.','Tahun 6 · Masalah Operasi Bergabung',true,true),id,'2.5.1','ops_story_reason','story','reasoning',s,['operation'])}
 if(id==='D6.FRAC'){const total=choose([[3,2],[5,2],[7,4]]),serv=choose([[1,4],[1,2],[3,4]]),ans=tidy((total[0]/total[1])/(serv[0]/serv[1]),3);return mark(Q(total[0]+'/'+total[1]+' L jus dibahagi ke bekas '+serv[0]+'/'+serv[1]+' L. Berapa bekas penuh?',String(ans),[Nq(String(tidy((total[0]/total[1])*(serv[0]/serv[1]),3)),'fraction'),Nq(String(total[0]/total[1]),'fraction'),Nq(String(ans+1),'fraction')],'Bilangan bekas = jumlah ÷ kapasiti setiap bekas.','Tahun 6 · Masalah Bahagi Pecahan',true,true),id,'2.5.1','frac_container_reason','story','reasoning',s,['fraction'])}
 if(id==='D6.DEC'){const a=choose([1.2,2.4,3.75]),b=choose([0.5,1.25,2.5]),correct=tidy(a*b,3),wrong=tidy(correct*10,3);return mark(Q('Murid mengira '+a+' × '+b+' = '+wrong+'. Penilaian?','salah, jawapan sepatutnya '+correct,[Nq('betul','decimal'),Nq('salah, jawapan sepatutnya '+tidy(correct/10,3),'decimal'),Nq('tidak boleh disemak tanpa kalkulator','estimate')],'Semak titik perpuluhan dan magnitud hasil.','Tahun 6 · Semak Perpuluhan',true,true),id,'2.2.1','decimal_error_reason','verbal','reasoning',s,['decimal','estimate'])}
 if(id==='D6.RATIO'){const r=choose([[2,3],[3,5],[4,7]]),k=choose([4,5,6]),known=r[0]*k,ans=r[1]*k;return mark(Q('Nisbah sirap:air = '+r[0]+':'+r[1]+'. Jika sirap '+known+' cawan, berapa cawan air mengekalkan kadaran?',ans,[Nq(known+r[1],'ratio'),Nq(known/r[0],'ratio'),Nq(ans+r[1],'ratio')],'Cari faktor skala dan gunakan pada kuantiti kedua.','Tahun 6 · Masalah Kadaran',true,true),id,'7.4.1','ratio_daily_reason','story','reasoning',s,['ratio','proportion'])}
 if(id==='D6.ANGLE'){const deg=choose([105,120,135,150]),wrong=180-deg;return mark(Q(protractor(deg)+'Murid membaca skala bertentangan sebagai '+wrong+'°. Penilaian?','salah, sudut ialah '+deg+'°',[Nq('betul kerana kedua-dua skala sama','angle_measure'),Nq('salah, sudut ialah '+(wrong+15)+'°','angle_measure'),Nq('tidak boleh ditentukan','angle_measure')],'Skala mesti bermula 0° pada garis dasar.','Tahun 6 · Semak Bacaan Protraktor',true,true),id,'6.1.1','angle_scale_reason','visual','reasoning',s,['angle_measure','scale_read'])}
 if(id==='D6.CIRCLE'){const d=choose([10,12,16,18]),r=d/2;return mark(Q('Bulatan perlu berdiameter '+d+' cm. Murid membuka jangka '+d+' cm. Pembetulan?','bukaan jangka mesti '+r+' cm',[Nq('kekal '+d+' cm','circle_draw'),Nq('bukaan mesti '+(d*2)+' cm','circle_draw'),Nq('diameter tidak berkaitan dengan jangka','circle_draw')],'Jangka ditetapkan pada jejari, iaitu separuh diameter.','Tahun 6 · Semak Pembinaan Bulatan',true,true),id,'6.2.2','circle_error_reason','story','reasoning',s,['circle_draw','radius_diameter'])}
 if(id==='D6.PIE'){const labels=['Bas','Kereta','Berjalan','Basikal'],angles=[180,90,45,45].sort(()=>Math.random()-.5),total=choose([40,80,120,160]),sectors=labels.map((l,i)=>({label:l,angle:angles[i],value:total*angles[i]/360,total})),known=sectors.find(x=>x.angle===90),ans=known.value*4;return mark(Q(pie(sectors)+'Sektor '+known.label+' ialah 90° dan mewakili '+known.value+' murid. Jumlah murid?',ans,[Nq(known.value*2,'pie_quantity'),Nq(known.value+90,'operation'),Nq(360,'pie_angle')],'90° ialah satu perempat bulatan.','Tahun 6 · Inferens Carta Pai',true,true),id,'8.1.1','pie_infer_reason','visual','reasoning',s,['pie_quantity'])}
 if(id==='D6.PROB')return mark(Q(table(['Beg','Merah','Bukan merah'],[['A',2,8],['B',6,4]])+'Beg mana lebih berkemungkinan memberi guli merah?','Beg B, kerana bahagian merah daripada jumlah lebih besar',[Nq('Beg A, kerana bukan merah lebih banyak','chance_reason'),Nq('Sama kemungkinan kerana kedua-dua beg ada merah','chance_reason'),Nq('Tidak boleh dibanding tanpa 100 percubaan','chance_reason')],'Banding bahagian hasil dikehendaki daripada semua hasil.','Tahun 6 · Banding Kebolehjadian',true,true),id,'8.2.2','prob_compare_reason','table','reasoning',s,['chance_reason'])
 if(id==='D6.DATA_PROBLEM'){const sectors=[{label:'A',angle:180,value:40},{label:'B',angle:90,value:20},{label:'C',angle:45,value:10},{label:'D',angle:45,value:10}];return mark(Q(pie(sectors)+'Jawatankuasa mahu pilihan dengan sokongan sekurang-kurangnya dua kali pilihan kedua tertinggi. Keputusan?','pilih A, kerana 180° ialah dua kali 90°',[Nq('pilih B, kerana 90° lebih besar daripada 180°','data_reason'),Nq('A dan B sama','data_reason'),Nq('tidak boleh diputuskan','data_reason')],'Banding sektor 180° dengan 90°.','Tahun 6 · Keputusan daripada Data',true,true),id,'8.3.1','data_decision_reason','visual','reasoning',s,['data_reason'])}
 return null;
}
banks.d6=function(id,s,shift){
 if(id==='D6.AREA'||id==='D6.DATA')return null;
 let q=null;
 if(id==='D6.PERCENT')q=percentQ(id,s);
 else if(id==='D6.MONEY')q=moneyQ(id,s);
 else if(id==='D6.TIME')q=timeQ(id,s);
 else if(id==='D6.MEASURE')q=measureQ(id,s);
 else if(id==='D6.COORD')q=coordQ(id,s);
 else if(id==='D6.SPACE_PROBLEM')q=spaceQ(id,s);
 else if(stage(s)===3)q=highReason(id,s);
 if(!q)q=prior(id,s,shift);
 return inherit(q,id,s);
};
window.PAKSSRYear6={version:VERSION,stage,standards:REF,retired:['D6.AREA','D6.DATA']};
document.documentElement?.setAttribute('data-kssr-year6',VERSION);
})();