// v3.11 content layer — genuine mathematical task variation for D1-D6.
(function(){
 const banks=window.PAQuestionBanks||{}, originals={};Object.keys(banks).forEach(k=>originals[k]=banks[k]);
 const hist=id=>((typeof sess!=='undefined'&&sess.questionHistory)||[]).filter(x=>x.skillId===id).slice(-5);
 function rotate(id,modes){const used=hist(id),last=used.at(-1)?.archetypeId,counts=Object.fromEntries(modes.map(x=>[x,used.filter(y=>y.archetypeId===x).length]));return [...modes].sort((a,b)=>(a===last)-(b===last)||counts[a]-counts[b]||Math.random()-.5)[0]}
 function mark(q,id,a,rep,demand,context='general',targets=[]){Object.assign(q,{archetypeId:a,representation:rep,demand,contextId:context,difficultyBand:demand==='reasoning'?4:demand==='application'?3:demand==='procedure'?2:1,misconceptionTargets:targets,familyKey:id});return q}
 function reasonableEstimate(a,b,op){
  if(op==='add'||op==='sub'){const unit=Math.max(a,b)>=1000?100:10,ra=Math.round(a/unit)*unit,rb=Math.round(b/unit)*unit;return op==='add'?ra+rb:ra-rb}
  if(op==='mul'){const unit=a>=100?100:a>=20?10:1;return Math.round(a/unit)*unit*b}
  return a/b;
 }
 function reasonableWrong(a,b,ans,op,existing){
  const estimate=reasonableEstimate(a,b,op),correctDistance=Math.abs(ans-estimate),step=Math.max(10,10**Math.max(1,String(Math.round(Math.abs(ans))).length-2)),seen=new Set([ans]),choices=[];
  const add=value=>{value=Math.round(Number(value));if(Number.isFinite(value)&&value>=0&&!seen.has(value)&&Math.abs(value-estimate)>correctDistance){seen.add(value);choices.push(N(value,'estimate'))}};
  (existing||[]).forEach(x=>add(x?.v));for(let scale=1;choices.length<3&&scale<12;scale++){add(ans+step*scale);add(Math.max(0,ans-step*scale))}return choices.slice(0,3);
 }
 function maxFor(id){if(id.includes('20'))return 20;if(id.includes('1000000'))return 1000000;if(id.includes('100000'))return 100000;if(id.includes('10000'))return 10000;if(id.includes('1000')||id.startsWith('D2.1'))return 1000;return 100}
 function randNumber(max){const min=max<=20?1:max/10;return R(Math.ceil(min),max-1)}
 function numberTask(id){
  const max=maxFor(id),modes=id.startsWith('D1.')?['compare','order','words','sequence','clues']:['compare','order','words','sequence','clues','round'],mode=rotate(id,modes),a=randNumber(max),b=randNumber(max);
  if(mode==='compare'){const ans=a>b?'>':a<b?'<':'=';return mark(Q(`<b>${a}</b> ___ <b>${b}</b>`,ans,[N(ans==='>'?'<':'>','compare'),N('=','compare'),N('Tidak dapat ditentukan','compare')],'Banding digit dari kiri. Jika sama, bergerak ke digit seterusnya.','KSSR · Banding Nombor',true,true),id,mode,'symbolic','concept','compare',['place','same_end'])}
  if(mode==='order'){let xs=[a,b,randNumber(max),randNumber(max)];xs=[...new Set(xs)];while(xs.length<4)xs.push(randNumber(max));const asc=Math.random()<.5,ans=[...xs].sort((x,y)=>asc?x-y:y-x).join(', ');return mark(Q(`Susun nombor berikut secara ${asc?'menaik':'menurun'}:<br><b>${xs.join(', ')}</b>`,ans,[N([...xs].sort((x,y)=>asc?y-x:x-y).join(', '),'compare'),N([xs[1],xs[0],xs[2],xs[3]].join(', '),'same_end'),N(xs.join(', '),'generated')],'Banding dari nilai tempat terbesar.','KSSR · Susun Nombor',true,true),id,mode,'symbolic','procedure','order',['place','same_end'])}
  if(mode==='words'){const n=randNumber(max),ans=numWords(n);return mark(Q(`Pilih nombor dalam perkataan bagi <b>${n}</b>.`,ans,[N(numWords(Math.max(1,n-10)),'place'),N(numWords(Math.min(max,n+100)),'place'),N(numWords(reverseN(n)),'same_end')],'Baca mengikut nilai tempat terbesar dahulu.','KSSR · Angka dan Perkataan',true,true),id,mode,'verbal','concept','number-name',['place'])}
  if(mode==='sequence'){const step=pick(max<=20?[1,2,5]:[10,100,1000].filter(x=>x<max)),down=Math.random()<.5,start=down?R(step*4,max):R(1,max-step*4),xs=[start,start+(down?-step:step),start+(down?-2*step:2*step)],ans=start+(down?-3*step:3*step);return mark(Q(`${xs.join(', ')}, ___`,ans,[N(ans+step,'pattern'),N(ans-step,'pattern'),N(start+(down?-4*step:4*step),'pattern')],'Cari beza yang tetap dan arah pola.','KSSR · Rangkaian Nombor',true,true),id,mode,'symbolic','procedure','sequence',['pattern'])}
  if(mode==='clues'){const n=randNumber(max),p=Math.pow(10,String(n).length-1),lead=Math.floor(n/p);return mark(Q(`Saya nombor kurang daripada <b>${n+Math.min(9,max-n)}</b>, lebih daripada <b>${Math.max(0,n-10)}</b> dan digit terbesar saya bernilai <b>${lead*p}</b>. Nombor manakah paling sesuai?`,n,[N(Math.max(1,n-10),'place'),N(Math.min(max,n+10),'place'),N(reverseN(n),'same_end')],'Gabungkan semua petunjuk, bukan satu sahaja.','KSSR · Teka Nombor',true,true),id,mode,'story','reasoning','clues',['place','same_end'])}
  const unit=max<=100?10:max<=1000?100:max<=10000?1000:max<=100000?10000:100000,n=randNumber(max),ans=Math.round(n/unit)*unit;return mark(Q(`Bundarkan <b>${n}</b> kepada ${unit===10?'puluh':unit===100?'ratus':unit===1000?'ribu':unit===10000?'puluh ribu':'ratus ribu'} terdekat.`,ans,[N(Math.floor(n/unit)*unit,'round'),N(Math.ceil(n/unit)*unit,'round'),N(n,'round')],'Lihat digit di sebelah kanan tempat pembundaran.','KSSR · Pembundaran',true,true),id,mode,'symbolic','procedure','round',['round','place'])
 }
 function placeTask(id){const max=maxFor(id),digits=String(max).length-1,n=R(Math.pow(10,digits-1),max-1),s=String(n),validPositions=Array.from(s,(digit,index)=>+digit?index:null).filter(index=>index!==null),pos=pick(validPositions),d=+s[pos],pow=s.length-1-pos,value=d*10**pow,names=['sa','puluh','ratus','ribu','puluh ribu','ratus ribu','juta'],marked=s.split('').map((digit,index)=>index===pos?`<span style="display:inline-block;padding:0 3px;border-bottom:3px solid #ef9b35;color:#b34f18">${digit}</span>`:digit).join(''),mode=rotate(id,['digit_value','place_name','expanded','compose','missing_part']);
  if(mode==='digit_value'){const step=10**pow,wrongValues=[d,d*10**Math.max(0,pow-1),d*10**Math.min(s.length-1,pow+1),Math.max(0,value-step),value+step].filter((candidate,index,list)=>candidate!==value&&list.indexOf(candidate)===index).slice(0,3);return mark(Q(`Apakah nilai digit yang ditanda pada tempat <b>${names[pow]}</b> dalam <b>${marked}</b>?`,value,wrongValues.map(candidate=>N(candidate,'place')),'Digit yang ditanda berada pada tempat '+names[pow]+'.','KSSR · Nilai Digit',true,true),id,mode,'visual','concept','place',['digit_value','place']);}
  if(mode==='place_name')return mark(Q(`Digit <b>${d}</b> dalam <b>${n}</b> berada pada tempat?`,names[pow],[N(names[Math.max(0,pow-1)],'place'),N(names[Math.min(names.length-1,pow+1)],'place'),N(String(value),'digit_value')],'Kira tempat dari kanan: sa, puluh, ratus dan seterusnya.','KSSR · Nilai Tempat',true,true),id,mode,'symbolic','concept','place',['place']);
  const parts=s.split('').map((x,i)=>+x*10**(s.length-1-i)).filter(Boolean),expanded=parts.join(' + ');
  if(mode==='expanded'){const digitSum=s.split('').join(' + '),wrongPlace=parts.map((x,i)=>i===0?Math.max(1,x/10):x).join(' + ');return mark(Q(`Cerakinkan <b>${n}</b> mengikut nilai tempat.`,expanded,[N(digitSum,'digit_value'),N(wrongPlace,'place'),N(String(n),'generated')],'Tulis nilai sebenar setiap digit dari nilai tempat terbesar ke terkecil.','KSSR · Cerakin',true,true),id,mode,'symbolic','procedure','expanded',['digit_value','place']);}
  if(mode==='compose')return mark(Q(`<b>${expanded}</b> membentuk nombor?`,n,[N(reverseN(n),'place'),N(n+10**pow,'place'),N(Math.max(0,n-10**pow),'place')],'Gabungkan nilai setiap tempat.','KSSR · Bina Nombor',true,true),id,mode,'symbolic','application','compose',['place']);
  return mark(Q(`${expanded.replace(String(value),'___')} = <b>${n}</b>. Nilai yang hilang?`,value,[N(d,'digit_value'),N(10**pow,'place'),N(value+10**pow,'place')],'Cari bahagian nilai tempat yang belum ditulis.','KSSR · Nilai Hilang',true,true),id,mode,'symbolic','reasoning','missing',['digit_value','place'])}
 function operationTask(id,op){const grade=+id[1],limit=[0,100,1000,10000,100000,1000000,1000000][grade],within20=/\.(?:ADD|SUB)20$/.test(id),mode=rotate(id,['direct','story','missing','check']);let a,b,ans,sym;
  if(op==='add'){if(within20){a=R(1,19);b=R(1,20-a)}else{a=R(grade<3?5:100,Math.floor(limit*.6));b=R(2,Math.floor(limit*.3))}ans=a+b;sym='+'}
  if(op==='sub'){a=within20?R(2,20):R(grade<3?10:200,Math.floor(limit*.9));b=R(1,a-1);ans=a-b;sym='−'}
  if(op==='mul'){a=R(2,grade<4?12:99);b=R(2,grade<5?9:25);ans=a*b;sym='×'}
  if(op==='div'){b=R(2,grade<4?10:20);ans=R(2,grade<4?12:40);a=b*ans;sym='÷'}
  const wrong=[N(op==='add'?a-b:op==='sub'?a+b:op==='mul'?a+b:b,'operation'),N(ans+(op==='mul'||op==='div'?b:10),'fact'),N(Math.max(0,ans-(op==='mul'||op==='div'?b:10)),'place')];
  if(mode==='direct')return mark(Q(`${a} ${sym} ${b} = ?`,ans,wrong,`Gunakan operasi ${sym} dan semak nilai tempat.`,'KSSR · Operasi',true,true),id,mode,'symbolic','procedure','direct',['operation']);
  if(mode==='story'){const stem=op==='add'?`Sebuah perpustakaan mempunyai ${a} buku dan menerima ${b} buku lagi.`:op==='sub'?`Sebuah stor mempunyai ${a} kotak dan menghantar ${b} kotak.`:op==='mul'?`Ada ${a} kumpulan dengan ${b} objek dalam setiap kumpulan.`:`${a} objek dibahagi sama rata kepada ${b} kumpulan.`;return mark(Q(`${stem} Berapakah hasilnya?`,ans,wrong,'Kenal pasti perubahan atau kumpulan dalam cerita.','KSSR · Masalah Harian',true,true),id,mode,'story','application','daily',['operation']);}
  if(mode==='missing'){if(op==='add')return mark(Q(`___ + ${b} = ${ans}`,a,[N(ans+b,'operation'),N(ans-b+10,'place'),N(b,'operation')],'Gunakan operasi songsang.','KSSR · Nombor Hilang',true,true),id,mode,'symbolic','reasoning','unknown',['operation']);if(op==='sub')return mark(Q(`${a} − ___ = ${ans}`,b,[N(a+ans,'operation'),N(a-ans+10,'place'),N(ans,'operation')],'Gunakan operasi songsang.','KSSR · Nombor Hilang',true,true),id,mode,'symbolic','reasoning','unknown',['operation']);return mark(Q(`${a} ${sym} ___ = ${ans}`,b,[N(a,'operation'),N(ans,'operation'),N(b+1,'fact')],'Gunakan hubungan operasi songsang.','KSSR · Faktor Hilang',true,true),id,mode,'symbolic','reasoning','unknown',['operation','fact']);}
  return mark(Q(`Tanpa mengira semula sepenuhnya, jawapan manakah munasabah bagi <b>${a} ${sym} ${b}</b>?`,ans,reasonableWrong(a,b,ans,op,wrong),'Anggar dahulu. Pilih satu jawapan yang paling hampir dengan anggaran.','KSSR · Semak Kewajaran',true,true),id,mode,'symbolic','reasoning','estimate',['estimate','operation'])}
 function timeTask(id){const mode=rotate(id,['find_end','find_start','find_duration','compare']),start=R(7,12)*60+R(0,11)*5,dur=pick([20,30,45,60,75,90,120]),end=start+dur,fmt=m=>`${Math.floor(m/60)}:${String(m%60).padStart(2,'0')}`,timeline=timelineSvg(Math.floor(start/60),start%60,Math.floor(end/60),end%60);
  if(mode==='find_end')return mark(Q(`${clockSvg(Math.floor(start/60),start%60)}Aktiviti bermula pada waktu yang ditunjukkan dan berlangsung <b>${dur} minit</b>. Bilakah tamat?`,fmt(end),[N(fmt(start),'time'),N(fmt(end+15),'time'),N(fmt(end-15),'time')],'Tambah tempoh pada masa mula.','KSSR · Masa Tamat',true,true),id,mode,'visual','application','schedule',['time']);
  if(mode==='find_start')return mark(Q(`${clockSvg(Math.floor(end/60),end%60)}Aktiviti tamat pada waktu yang ditunjukkan selepas <b>${dur} minit</b>. Bilakah bermula?`,fmt(start),[N(fmt(end),'time'),N(fmt(start+15),'time'),N(fmt(start-15),'time')],'Tolak tempoh daripada masa tamat.','KSSR · Masa Mula',true,true),id,mode,'visual','application','schedule',['time']);
  if(mode==='find_duration')return mark(Q(`${timeline}Berapakah tempoh dari masa mula hingga masa tamat?`,`${dur} minit`,[N(`${dur+15} minit`,'time'),N(`${Math.max(5,dur-15)} minit`,'time'),N(`${end-start+60} minit`,'time')],'Gunakan garis masa dari mula hingga tamat.','KSSR · Tempoh',true,true),id,mode,'visual','procedure','duration',['time']);
  const d2=dur+pick([-15,15,30]);return mark(Q(`Perjalanan A mengambil ${dur} minit dan B mengambil ${d2} minit. Yang manakah lebih singkat?`,dur<d2?'A':'B',[N(dur<d2?'B':'A','time'),N('Sama','time'),N('Tidak dapat ditentukan','time')],'Banding tempoh dalam unit yang sama.','KSSR · Banding Tempoh',true,true),id,mode,'story','concept','compare',['time'])}
 function dataTask(id){const labels=['A','B','C','D'],vals=labels.map(()=>R(5,25)),mode=rotate(id,['read','most','difference','total','missing']),i=R(0,3),j=(i+1)%4;
  if(mode==='read')return mark(Q(`${barChart(labels,vals)}Berapakah nilai kategori <b>${labels[i]}</b>?`,vals[i],[N(vals[j],'data'),N(vals[i]+5,'data'),N(vals.reduce((a,b)=>a+b,0),'operation')],'Baca label dan tinggi palang.','KSSR · Baca Data',true,true),id,mode,'visual','concept','chart',['data']);
  if(mode==='most'){const mx=Math.max(...vals),ans=labels[vals.indexOf(mx)];return mark(Q(`${barChart(labels,vals)}Kategori manakah paling banyak?`,ans,labels.filter(x=>x!==ans).slice(0,3).map(x=>N(x,'data')),'Cari palang tertinggi.','KSSR · Banding Data',true,true),id,mode,'visual','concept','chart',['data']);}
  if(mode==='difference'){const ans=Math.abs(vals[i]-vals[j]);return mark(Q(`${barChart(labels,vals)}Apakah beza antara ${labels[i]} dengan ${labels[j]}?`,ans,[N(vals[i]+vals[j],'operation'),N(Math.max(vals[i],vals[j]),'data'),N(ans+2,'data')],'Tolak nilai kecil daripada nilai besar.','KSSR · Beza Data',true,true),id,mode,'visual','application','chart',['data','operation']);}
  if(mode==='total'){const ans=vals.reduce((a,b)=>a+b,0);return mark(Q(`${barChart(labels,vals)}Berapakah jumlah semua kategori?`,ans,[N(Math.max(...vals),'data'),N(ans-vals[i],'operation'),N(ans+5,'data')],'Tambah semua nilai mengikut skala.','KSSR · Jumlah Data',true,true),id,mode,'visual','application','chart',['data','operation']);}
  const total=vals[i]+vals[j];return mark(Q(`Jumlah kategori ${labels[i]} dan ${labels[j]} ialah ${total}. Jika ${labels[i]} = ${vals[i]}, nilai ${labels[j]} ialah?`,vals[j],[N(total,'data'),N(Math.abs(total-vals[i])+5,'data'),N(vals[i],'data')],'Cari bahagian yang hilang daripada jumlah.','KSSR · Data Hilang',true,true),id,mode,'table','reasoning','missing',['data','operation'])}
 function fractionTask(id){const g=+id[1],mode=rotate(id,g===6?['mixed_to_improper','improper_to_mixed','compare']:['model','equivalent','missing']),d=pick([4,5,6,8,10]),n=R(1,d-1);
  if(mode==='model')return mark(Q(`${fractionVisual(n,d)}Apakah pecahan bahagian berlorek?`,`${n}/${d}`,[N(`${d-n}/${d}`,'fraction'),N(`${d}/${n}`,'fraction'),N(`${n}/${n+d}`,'fraction')],'Pengangka ialah bahagian berlorek; penyebut ialah semua bahagian sama besar.','KSSR · Model Pecahan',true,true),id,mode,'visual','concept','bar',['fraction']);
  if(mode==='equivalent'){const k=pick([2,3]),ans=`${n*k}/${d*k}`;return mark(Q(`Pecahan setara bagi <b>${n}/${d}</b> ialah?`,ans,[N(`${n}/${d*k}`,'fraction'),N(`${n*k}/${d}`,'fraction'),N(`${n+k}/${d+k}`,'fraction')],'Darab pengangka dan penyebut dengan faktor sama.','KSSR · Pecahan Setara',true,true),id,mode,'symbolic','procedure','equivalent',['fraction']);}
  if(mode==='missing'){const k=pick([2,3]),ans=n*k;return mark(Q(`${n}/${d} = ___/${d*k}`,ans,[N(n+k,'fraction'),N(d*k,'fraction'),N(ans+k,'fraction')],'Cari faktor perubahan pada penyebut dan guna faktor sama.','KSSR · Pengangka Hilang',true,true),id,mode,'symbolic','reasoning','missing',['fraction']);}
  const whole=R(1,5),num=R(1,d-1),improper=whole*d+num;
  if(mode==='mixed_to_improper')return mark(Q(`Tukar <b>${whole} ${num}/${d}</b> kepada pecahan tak wajar.`,`${improper}/${d}`,[N(`${whole+num}/${d}`,'fraction'),N(`${whole*d-num}/${d}`,'fraction'),N(`${improper}/${num}`,'fraction')],'Darab nombor bulat dengan penyebut, kemudian tambah pengangka.','KSSR · Pecahan Tak Wajar',true,true),id,mode,'symbolic','procedure','convert',['fraction']);
  if(mode==='improper_to_mixed')return mark(Q(`Tukar <b>${improper}/${d}</b> kepada nombor bercampur.`,`${whole} ${num}/${d}`,[N(`${num} ${whole}/${d}`,'fraction'),N(`${whole} ${d}/${num}`,'fraction'),N(`${whole+1} ${num}/${d}`,'fraction')],'Bahagi pengangka dengan penyebut; baki menjadi pengangka.','KSSR · Nombor Bercampur',true,true),id,mode,'symbolic','procedure','convert',['fraction']);
  const n2=R(1,d-1),ans=n>n2?`${n}/${d}`:`${n2}/${d}`;return mark(Q(`<div style="display:flex;gap:8px;align-items:center;justify-content:center">${fractionVisual(n,d)}${fractionVisual(n2,d)}</div>Yang manakah lebih besar: <b>${n}/${d}</b> atau <b>${n2}/${d}</b>?`,ans,[N(ans===`${n}/${d}`?`${n2}/${d}`:`${n}/${d}`,'fraction'),N(`${d}/${Math.max(n,n2)}`,'fraction'),N('Sama','fraction')],'Penyebut sama: banding pengangka atau saiz bahagian berlorek.','KSSR · Banding Pecahan',true,true),id,mode,'visual','concept','compare',['fraction'])}
 function decimalTask(id){const g=+id[1],dp=g>=5?2:1,scale=10**dp,a=R(1,scale*8)/scale,b=R(1,Math.max(1,Math.floor(a*scale)-1))/scale,mode=rotate(id,['place','compare','add','subtract']);
  if(mode==='place'){const text=a.toFixed(dp),digit=text.at(-1),place=dp===1?'persepuluh':'perseratus',ans=dp===1?`${digit}/10`:`${digit}/100`;return mark(Q(`Apakah nilai digit terakhir <b>${digit}</b> pada tempat <b>${place}</b> dalam <b>${text}</b>?`,ans,[N(digit,'digit_value'),N(`${digit}/10`,'place'),N(`${digit}/1000`,'place')],'Digit terakhir berada pada tempat '+place+'.','KSSR · Nilai Perpuluhan',true,true),id,mode,'symbolic','concept','place',['decimal','place']);}
  if(mode==='compare'){const ans=a>b?'>':'<';return mark(Q(`<b>${a.toFixed(dp)}</b> ___ <b>${b.toFixed(dp)}</b>`,ans,[N(ans==='>'?'<':'>','decimal'),N('=','decimal'),N('Tidak pasti','generated')],'Selarikan nilai tempat sebelum membanding.','KSSR · Banding Perpuluhan',true,true),id,mode,'symbolic','concept','compare',['decimal']);}
  const add=mode==='add',ans=add?a+b:a-b,sym=add?'+':'−';return mark(Q(`${a.toFixed(dp)} ${sym} ${b.toFixed(dp)} = ?`,ans.toFixed(dp),[N((ans+1/scale).toFixed(dp),'decimal'),N(Math.max(0,ans-1/scale).toFixed(dp),'decimal'),N((a+b+(add?1:-1)).toFixed(dp),'operation')],'Selarikan titik perpuluhan sebelum mengira.','KSSR · Operasi Perpuluhan',true,true),id,mode,'symbolic','procedure','operation',['decimal','operation'])}
 function percentTask(id){const mode=rotate(id,['visual','convert','quantity','missing']),pct=pick([10,20,25,40,50,60,75]),base=pick([20,40,60,80,100,200]),part=base*pct/100;
  if(mode==='visual')return mark(Q(`${percentVisual(Math.ceil(pct/10)*10)}Bahagian berlorek mewakili?`,`${Math.ceil(pct/10)*10}%`,[N(`${100-Math.ceil(pct/10)*10}%`,'percent'),N(`${pct/10}/10`,'fraction'),N(String(pct),'percent')],'Setiap petak daripada 10 mewakili 10%.','KSSR · Model Peratus',true,true),id,mode,'visual','concept','hundred-grid',['percent']);
  if(mode==='convert')return mark(Q(`${pct/10}/10 bersamaan?`,`${pct}%`,[N(`${pct/10}%`,'percent'),N(`${100-pct}%`,'percent'),N(String(pct),'percent')],'Tukarkan kepada bahagian daripada 100.','KSSR · Pecahan dan Peratus',true,true),id,mode,'symbolic','concept','convert',['percent','fraction']);
  if(mode==='quantity')return mark(Q(`${pct}% daripada ${base} = ?`,part,[N(base-part,'percent'),N(pct,'percent'),N(base+pct,'operation')],'Darab kuantiti dengan pecahan per seratus.','KSSR · Peratus Kuantiti',true,true),id,mode,'symbolic','application','quantity',['percent']);
  return mark(Q(`${pct}% daripada ___ ialah ${part}. Apakah nilai keseluruhan?`,base,[N(part,'percent'),N(base-part,'operation'),N(base+pct,'percent')],'Gunakan operasi songsang untuk mencari 100%.','KSSR · Nilai Keseluruhan',true,true),id,mode,'symbolic','reasoning','missing',['percent','operation'])}
 function moneySkillTask(id,s){
  const q=originals.d2t4?originals.d2t4(id,s):null;
  if(q&&(!q.archetypeId||q.archetypeId==='solve_direct')){
    const names={'D2.4.1':'recognise','D2.4.2':'add','D2.4.3':'subtract','D2.4.4':'multiply','D2.4.5':'divide','D2.4.6':'save','D2.4.7':'apply'},name=names[id]||'direct';
    let subMode='';
    if(id==='D2.4.1'){
      if(q.prompt.includes('nilai wang yang ditunjukkan'))subMode='_value';
      else if(q.prompt.includes('jumlah wang semuanya'))subMode='_total';
      else if(q.prompt.includes('nilainya lebih besar'))subMode='_compare';
    }else if(id==='D2.4.7'){
      if(q.prompt.includes('baki wangnya'))subMode='_balance';
      else if(q.prompt.includes('kedua-dua barang'))subMode='_multiitem';
      else if(q.prompt.includes('cukup untuk membelinya'))subMode='_enough';
      else if(q.prompt.includes('wang yang tinggal'))subMode='_savings';
      else if(q.prompt.includes('jumlah yang dibayar'))subMode='_total';
    }
    q.archetypeId='money_'+name+subMode;
    q.representation=/moneyvisual|pricetag/i.test(q.prompt)?'visual':'symbolic';
    q.demand=id==='D2.4.7'||id==='D2.4.6'?'application':id==='D2.4.1'?'concept':'procedure';
    q.difficultyBand=q.demand==='application'?3:q.demand==='concept'?1:2;
    q.misconceptionTargets=(q.misconceptionTargets&&q.misconceptionTargets.length)?q.misconceptionTargets:[q.wrong?.[0]?.tag||'money'];
    q.contextId='money';q.familyKey=id;
  }
  return q;
 }
 function timeSkillTask(id,s){
  const q=originals.d2t5?originals.d2t5(id,s):null;
  if(q&&(!q.archetypeId||q.archetypeId==='solve_direct')){
    const names={'D2.5.1':'read_clock','D2.5.2':'convert_unit','D2.5.3':'duration'},name=names[id]||'direct';
    let subMode='';
    if(id==='D2.5.3'){
      if(q.prompt.includes('aktiviti tamat'))subMode='_end';
      else if(q.prompt.includes('Berapakah tempoh'))subMode='_span';
    }
    q.archetypeId='time_'+name+subMode;
    q.representation=/<svg|clockvisual|timelinevisual/i.test(q.prompt)?'visual':'symbolic';
    q.demand=id==='D2.5.3'?'application':id==='D2.5.2'?'procedure':'concept';
    q.difficultyBand=q.demand==='application'?3:q.demand==='procedure'?2:1;
    q.misconceptionTargets=(q.misconceptionTargets&&q.misconceptionTargets.length)?q.misconceptionTargets:[q.wrong?.[0]?.tag||'time'];
    q.contextId='time';q.familyKey=id;
  }
  return q;
 }
 function moneyTask(id){const mode=rotate(id,['total','change','unit_price','budget']),a=pick([5,10,20,40,50,80]),b=pick([3,6,12,25]),qty=pick([2,3,4]),total=a+b;
  if(mode==='total')return mark(Q(`Buku berharga RM${a} dan alat tulis RM${b}. Jumlah bayaran?`,`RM${total}`,[N(`RM${Math.abs(a-b)}`,'operation'),N(`RM${a}`,'money'),N(`RM${total+10}`,'money')],'Tambah semua harga.','KSSR · Jumlah Wang',true,true),id,mode,'story','application','shopping',['money','operation']);
  if(mode==='change'){const pay=pick([100,200,300]),cost=Math.min(pay-10,total),ans=pay-cost;return mark(Q(`Bayar RM${pay} untuk pembelian RM${cost}. Berapakah baki?`,`RM${ans}`,[N(`RM${cost}`,'money'),N(`RM${pay+cost}`,'operation'),N(`RM${ans+10}`,'money')],'Baki = wang dibayar − jumlah harga.','KSSR · Baki Wang',true,true),id,mode,'story','application','shopping',['money','operation']);}
  if(mode==='unit_price'){const ans=a*qty;return mark(Q(`${qty} barang berharga RM${a} setiap satu. Jumlah harga?`,`RM${ans}`,[N(`RM${a+qty}`,'operation'),N(`RM${a}`,'money'),N(`RM${ans+10}`,'money')],'Darab harga seunit dengan kuantiti.','KSSR · Harga Seunit',true,true),id,mode,'story','procedure','shopping',['money','operation']);}
  const budget=pick([100,200,300]),spent=Math.min(budget-20,total),left=budget-spent;return mark(Q(`Bajet RM${budget}. Selepas membayar RM${spent}, berapakah baki bajet?`,`RM${left}`,[N(`RM${spent}`,'money'),N(`RM${budget+spent}`,'operation'),N(`RM${left+10}`,'money')],'Tolak perbelanjaan daripada bajet.','KSSR · Bajet',true,true),id,mode,'story','reasoning','budget',['money','operation'])}
 function geometryTask(id){const mode=rotate(id,['perimeter','area','missing_side']),l=R(5,14),w=R(3,10),per=2*(l+w),area=l*w,diagram=rectangleMeasureSvg(l,w);
  if(mode==='perimeter')return mark(Q(`${diagram}Berapakah perimeter rajah?`,`${per} cm`,[N(`${area} cm`,'area'),N(`${l+w} cm`,'operation'),N(`${per+2} cm`,'shape')],'Tambah panjang semua sisi.','KSSR · Perimeter',true,true),id,mode,'visual','procedure','rectangle',['area','shape']);
  if(mode==='area')return mark(Q(`${diagram}Berapakah luas rajah?`,`${area} cm²`,[N(`${per} cm²`,'area'),N(`${l+w} cm²`,'operation'),N(`${area+w} cm²`,'area')],'Luas = panjang × lebar.','KSSR · Luas',true,true),id,mode,'visual','procedure','rectangle',['area']);
  return mark(Q(`${diagram}Perimeter rajah ialah <b>${per} cm</b>. Berapakah lebarnya?`,`${w} cm`,[N(`${per-l} cm`,'area'),N(`${per/2} cm`,'shape'),N(`${l+w} cm`,'operation')],'Bahagikan perimeter kepada dua, kemudian tolak panjang.','KSSR · Sisi Hilang',true,true),id,mode,'visual','reasoning','rectangle',['area','operation'])}
 function coordinateTask(id){const mode=rotate(id,['read','move','reverse']),x=R(1,4),y=R(1,4);
  if(mode==='read')return mark(Q(`${coordGrid(x,y)}Apakah koordinat titik ●?`,`(${x},${y})`,[N(`(${y},${x})`,'coord'),N(`(${x+1},${y})`,'coord'),N(`(${x},${Math.max(0,y-1)})`,'coord')],'Baca paksi-x dahulu, kemudian paksi-y.','KSSR · Baca Koordinat',true,true),id,mode,'visual','concept','grid',['coord']);
  if(mode==='move'){const dx=R(1,2);return mark(Q(`${coordGrid(x,y)}Titik ● bergerak <b>${dx} unit ke kanan</b>. Apakah koordinat baharu?`,`(${x+dx},${y})`,[N(`(${x},${y+dx})`,'coord'),N(`(${y},${x+dx})`,'coord'),N(`(${x-dx},${y})`,'coord')],'Gerak kanan menambah nilai x.','KSSR · Gerak Titik',true,true),id,mode,'visual','application','grid',['coord']);}
  return mark(Q(`${coordGrid(x,y)}Pilih bacaan koordinat titik ● yang betul.`,`(${x},${y})`,[N(`(${y},${x})`,'coord'),N(`(${x+1},${y})`,'coord'),N(`(${x},${y+1})`,'coord')],'Urutan ialah x kemudian y.','KSSR · Urutan Paksi',true,true),id,mode,'visual','reasoning','grid',['coord'])}
 function ratioTask(id){const mode=rotate(id,['equivalent','missing','simplify']),a=R(1,4),b=R(2,6),k=R(2,4);
  if(mode==='equivalent')return mark(Q(`Nisbah setara bagi ${a}:${b} ialah?`,`${a*k}:${b*k}`,[N(`${a+k}:${b+k}`,'ratio'),N(`${b*k}:${a*k}`,'ratio'),N(`${a}:${b*k}`,'ratio')],'Darab kedua-dua bahagian dengan faktor sama.','KSSR · Nisbah Setara',true,true),id,mode,'symbolic','procedure','ratio',['ratio']);
  if(mode==='missing')return mark(Q(`${a}:${b} = ${a*k}:___`,b*k,[N(b+k,'ratio'),N(a*k,'ratio'),N(b,'ratio')],'Gunakan faktor yang sama pada kedua-dua bahagian.','KSSR · Nisbah Hilang',true,true),id,mode,'symbolic','reasoning','ratio',['ratio']);
  return mark(Q(`Ringkaskan nisbah ${a*k}:${b*k}.`,`${a}:${b}`,[N(`${b}:${a}`,'ratio'),N(`${a*k-k}:${b*k-k}`,'ratio'),N(`${a}:${b*k}`,'ratio')],'Bahagi kedua-dua bahagian dengan faktor sepunya.','KSSR · Ringkas Nisbah',true,true),id,mode,'symbolic','procedure','ratio',['ratio'])}
 function year1Task(id){const mode=rotate(id,['recognise','compare','apply']);
  if(id==='D1.FRAC'){const d=pick([2,4]),n=R(1,d-1);if(mode==='recognise')return mark(Q(`${fractionVisual(n,d)}Apakah pecahan berlorek?`,`${n}/${d}`,[N(`${d-n}/${d}`,'fraction'),N(`${d}/${n}`,'fraction'),N(`${n}/${n+d}`,'fraction')],'Kira bahagian berlorek dan semua bahagian sama besar.','Tahun 1 · Pecahan',true,true),id,mode,'visual','concept','fraction',['fraction']);if(mode==='compare')return mark(Q(`Yang manakah menunjukkan bahagian lebih besar?`,d===2?'1/2':'3/4',[N(d===2?'1/4':'1/4','fraction'),N('1/8','fraction'),N('Sama','fraction')],'Banding saiz bahagian daripada keseluruhan sama.','Tahun 1 · Banding Pecahan',true,true),id,mode,'symbolic','concept','fraction',['fraction']);return mark(Q(`Sebuah kek dibahagi kepada ${d} bahagian sama besar. ${n} bahagian dimakan. Pecahan yang dimakan?`,`${n}/${d}`,[N(`${d}/${n}`,'fraction'),N(`${d-n}/${d}`,'fraction'),N(`${n}/${n+d}`,'fraction')],'Pengangka ialah bahagian yang dipilih.','Tahun 1 · Pecahan Harian',true,true),id,mode,'story','application','food',['fraction']);}
  if(id==='D1.MONEY'){const moneyMode=rotate(id,['recognise','compare','combine','enough']),coinPool=[5,10,20,50,60,70,80,90];
    if(moneyMode==='recognise'){const v=pick(coinPool);return mark(Q(`${moneyVisual(v)}Berapakah nilai wang ini?`,moneyFmt(v),moneyWrongSet(v,[v+10,Math.max(5,v-10),v*2]),'Baca nilai yang tertulis pada syiling.','Tahun 1 · Kenal Wang',true,true),id,moneyMode,'visual','concept','coin',['money']);}
    if(moneyMode==='compare'){const v=pick(coinPool),b=pick(coinPool.filter(x=>x!==v)),ans=Math.max(v,b);return mark(Q(`${moneyVisual(v)}${moneyVisual(b)}Nilai manakah lebih besar?`,moneyFmt(ans),moneyWrongSet(ans,[Math.min(v,b),v+b]),'Banding nilai kedua-dua wang.','Tahun 1 · Banding Wang',true,true),id,moneyMode,'visual','concept','coin',['money']);}
    if(moneyMode==='combine'){const v=pick(coinPool),b=pick(coinPool),total=v+b;return mark(Q(`${moneyVisual(v)}${moneyVisual(b)}Berapakah jumlah wang kedua-dua syiling ini?`,moneyFmt(total),moneyWrongSet(total,[Math.abs(v-b),v,total+10]),'Tambah nilai kedua-dua syiling.','Tahun 1 · Jumlah Wang',true,true),id,moneyMode,'visual','application','coin',['money','operation']);}
    const price=pick(coinPool),have=Math.random()<.5?Math.min(90,price+pick([5,10,20])):Math.max(5,price-pick([5,10,20])),ans=have>=price?'Cukup':'Tidak cukup';
    return mark(Q(`${priceTag('Harga gula-gula',price)}Wang yang ada ialah ${moneyFmt(have)}. Adakah wang itu cukup untuk membeli gula-gula?`,ans,[N(ans==='Cukup'?'Tidak cukup':'Cukup','money'),N('Perlu 10 sen lagi','money'),N('Tidak dapat ditentukan','money')],'Banding wang yang ada dengan harga barang.','Tahun 1 · Cukup Atau Tidak',true,true),id,moneyMode,'story','application','spending',['money','compare']);
  }
  if(id==='D1.TIME'){const forms=[{m:0,label:'tepat jam'},{m:30,label:'setengah jam'},{m:15,label:'suku jam'},{m:45,label:'tiga suku jam'}],form=pick(forms),h=R(1,11),mm=String(form.m).padStart(2,'0'),timeStr=`${h}:${mm}`;
    if(mode==='recognise'){const otherForms=shuffle(forms.filter(f=>f.m!==form.m)).slice(0,2).map(f=>N(`${h}:${String(f.m).padStart(2,'0')}`,'time')),diffHour=N(`${(h%11)+1}:${mm}`,'time');
      return mark(Q(`${clockSvg(h,form.m)}Apakah waktu yang ditunjukkan?`,timeStr,[...otherForms,diffHour],form.m===0?'Jarum minit pada 12 menunjukkan tepat jam.':form.m===30?'Jarum minit pada 6 menunjukkan setengah jam.':form.m===15?'Jarum minit pada 3 menunjukkan suku jam.':'Jarum minit pada 9 menunjukkan tiga suku jam.','Tahun 1 · Baca Waktu ('+form.label+')',true,true),id,mode,'visual','concept','clock',['time']);}
    if(mode==='compare'){const h2=(h%11)+1,altMm=form.m===0?'30':'00';return mark(Q(`${clockSvg(h,form.m)}${clockSvg(h2,form.m)}Jam yang manakah menunjukkan waktu lebih awal?`,timeStr,[N(`${h2}:${mm}`,'time'),N('Kedua-duanya sama','time'),N(`${h}:${altMm}`,'time')],'Waktu lebih awal berlaku dahulu.','Tahun 1 · Awal dan Lewat',true,true),id,mode,'visual','concept','sequence',['time']);}
    return mark(Q(`${clockSvg(h,form.m)}Kelas bermula pada waktu yang ditunjukkan. Apakah waktu satu jam kemudian?`,`${h+1}:${mm}`,[N(timeStr,'time'),N(`${h+2}:${mm}`,'time'),N(`${Math.max(1,h-1)}:${mm}`,'time')],'Tambah satu pada nilai jam dan kekalkan minit.','Tahun 1 · Satu Jam Kemudian ('+form.label+')',true,true),id,mode,'visual','application','daily',['time']);}
  if(id==='D1.MEASURE'){const cfg=pick([{a:'pensel',b:'pemadam',attr:'panjang',unit:'cm'},{a:'tembikai',b:'epal',attr:'jisim',unit:'kg'},{a:'baldi',b:'cawan',attr:'kapasiti',unit:'L'}]);if(mode==='recognise')return mark(Q(`Unit sesuai untuk mengukur ${cfg.attr} ${cfg.a}?`,cfg.unit,[N('jam','unit'),N('RM','unit'),N(cfg.unit==='cm'?'kg':'cm','unit')],'Pilih unit yang sepadan dengan perkara yang diukur.','Tahun 1 · Pilih Unit',true,true),id,mode,'story','concept','measurement',['unit']);if(mode==='compare')return mark(Q(`Yang manakah biasanya lebih ${cfg.attr==='panjang'?'panjang':cfg.attr==='jisim'?'berat':'banyak isinya'}: ${cfg.a} atau ${cfg.b}?`,cfg.a,[N(cfg.b,'unit'),N('Sama','unit'),N('Tidak boleh dibanding','unit')],'Banding berdasarkan pengalaman dengan objek sebenar.','Tahun 1 · Banding Ukuran',true,true),id,mode,'story','concept','compare',['unit']);return mark(Q(`Ali mahu mengukur ${cfg.attr} ${cfg.a}. Alat atau unit manakah paling sesuai?`,cfg.unit,[N('kalender','unit'),N('syiling','unit'),N('jam','unit')],'Fikir sifat yang hendak diukur.','Tahun 1 · Guna Ukuran',true,true),id,mode,'story','application','measurement',['unit']);}
  if(id==='D1.SHAPE'){const shapes=[['segi tiga',3,'triangle'],['segi empat sama',4,'square'],['segi empat tepat',4,'rectangle'],['bulatan',0,'circle']],x=pick(shapes),visual=shapeSvg(x[2]);
    if(mode==='recognise')return mark(Q(`${visual}Apakah nama bentuk ini?`,x[0],shuffle(shapes.filter(y=>y[0]!==x[0])).slice(0,3).map(y=>N(y[0],'shape')),'Perhatikan bilangan sisi lurus dan bentuk keseluruhan.','Tahun 1 · Kenal Bentuk',true,true),id,mode,'visual','concept','shape',['shape']);
    if(mode==='compare'){const desc=n=>n===0?'Tiada sisi lurus dan tiada bucu':`${n} sisi lurus dan ${n} bucu`,wrongCounts=[0,3,4,5].filter(n=>n!==x[1]).slice(0,3);return mark(Q(`${visual}Berapakah bilangan sisi lurus dan bucu pada bentuk ini?`,desc(x[1]),wrongCounts.map(n=>N(desc(n),'shape')),'Kira sisi lurus dan bucu bentuk ini satu demi satu.','Tahun 1 · Ciri Bentuk',true,true),id,mode,'visual','concept','shape',['shape']);}
    const objects={triangle:'bumbung rumah',square:'jubin lantai',rectangle:'pintu',circle:'jam dinding bulat'},wrongObjects={triangle:['buku','roda basikal','tingkap segi empat sama'],square:['bumbung rumah','jam dinding bulat','pinggan'],rectangle:['jubin lantai','roda basikal','set square'],circle:['bumbung rumah','buku','petak dam']};
    return mark(Q(`${visual}Objek harian manakah biasanya mempunyai bentuk seperti rajah?`,objects[x[2]],wrongObjects[x[2]].map(v=>N(v,'shape')),'Padankan rajah dengan bentuk objek harian.','Tahun 1 · Bentuk Harian',true,true),id,mode,'visual','application','daily',['shape']);}
  if(id==='D1.DATA'){const labelSets=[['Bola','Buku','Pensel'],['Epal','Pisang','Oren'],['Kucing','Ayam','Itik'],['Beg','Payung','Botol']],labels=pick(labelSets);let vals=[];while(vals.length<3){const v=R(2,8);if(!vals.includes(v))vals.push(v)}
    if(mode==='recognise')return mark(Q(`${barChart(labels,vals)}Berapakah bilangan ${labels[0]}?`,vals[0],[N(vals[1],'data'),N(vals[2],'data'),N(vals.reduce((a,b)=>a+b,0),'operation')],'Baca palang bagi label yang diminta.','Tahun 1 · Baca Data',true,true),id,mode,'visual','concept','chart',['data']);
    const mx=Math.max(...vals),mn=Math.min(...vals);
    if(mode==='compare')return mark(Q(`${barChart(labels,vals)}Yang manakah paling banyak?`,labels[vals.indexOf(mx)],labels.filter(x=>x!==labels[vals.indexOf(mx)]).map(x=>N(x,'data')).concat([N('Sama','data')]).slice(0,3),'Cari palang tertinggi.','Tahun 1 · Banding Data',true,true),id,mode,'visual','concept','chart',['data']);
    return mark(Q(`${barChart(labels,vals)}Yang manakah paling sedikit?`,labels[vals.indexOf(mn)],labels.filter(x=>x!==labels[vals.indexOf(mn)]).map(x=>N(x,'data')).concat([N('Sama','data')]).slice(0,3),'Cari palang paling rendah.','Tahun 1 · Tafsir Data',true,true),id,mode,'visual','application','chart',['data']);}
  if(id==='D1.CMP100'){
    if(mode==='recognise'){const a=R(1,100),b=R(1,100),ans=a>b?'>':a<b?'<':'=';return mark(Q(`<b>${a}</b> ___ <b>${b}</b>`,ans,[N(ans==='>'?'<':'>','compare'),N('=','compare'),N('Tidak dapat ditentukan','compare')],'Banding digit puluh dahulu, kemudian digit sa.','Tahun 1 · Banding Nombor',true,true),id,mode,'symbolic','concept','compare',['place','same_end']);}
    if(mode==='compare'){let xs=[R(1,100),R(1,100),R(1,100)];xs=[...new Set(xs)];while(xs.length<3)xs.push(R(1,100));xs=xs.slice(0,3);const asc=Math.random()<.5,ans=[...xs].sort((x,y)=>asc?x-y:y-x).join(', ');return mark(Q(`Susun nombor berikut secara ${asc?'menaik':'menurun'}:<br><b>${xs.join(', ')}</b>`,ans,[N([...xs].sort((x,y)=>asc?y-x:x-y).join(', '),'compare'),N([xs[1],xs[0],xs[2]].join(', '),'same_end'),N(xs.join(', '),'generated')],'Banding nilai puluh, kemudian sa.','Tahun 1 · Susun Nombor',true,true),id,mode,'symbolic','procedure','order',['place','same_end']);}
    const target=R(10,90);let a=R(1,100),b=R(1,100),guard=0;while((a===b||Math.abs(a-target)===Math.abs(b-target))&&guard++<25){a=R(1,100);b=R(1,100)}
    const near=Math.abs(a-target)<Math.abs(b-target)?a:b,far=near===a?b:a;
    return mark(Q(`Nombor manakah lebih hampir dengan <b>${target}</b>: <b>${a}</b> atau <b>${b}</b>?`,near,[N(far,'compare'),N(target,'generated'),N(Math.abs(a-b),'operation')],'Kira beza setiap nombor daripada nombor sasaran.','Tahun 1 · Nombor Terhampir',true,true),id,mode,'symbolic','reasoning','closer-to',['compare','estimate']);
  }
  return null}
 function inferNative(q,id){
  if(!q)return q;const t=String(q.prompt||'').replace(/<[^>]*>/g,' ').replace(/\d+(?:\.\d+)?/g,'#').toLowerCase();let a='direct',rep=/<svg|<table|moneyvisual|class="(?:clock|ruler|scale|bar|chart)/i.test(q.prompt)?'visual':'symbolic';
  const rules=[['words',/perkataan|ejaan|menulis nombor/],['compare',/lebih besar|lebih kecil|banding|paling banyak|paling sedikit/],['sequence',/pola|rangkaian|nombor seterusnya|lengkapkan siri/],['round',/bundar/],['estimate',/anggar|hampir/],['place',/nilai digit|nilai tempat|cerakin/],['missing',/___|kosong|hilang/],['story',/mempunyai|membeli|diberi|berkongsi|perjalanan|bermula|tamat/],['visual_read',/rajah|carta|jam|pembaris|penimbang|silinder|berlorek/],['convert',/tukarkan|bersamaan|berapa .* dalam/],['property',/ciri|sisi|bucu|permukaan|bentuk/],['total',/jumlah|semuanya/],['difference',/beza|baki/]];
  for(const [name,re] of rules)if(re.test(t)){a=name;break}if(rep==='visual'&&a==='direct')a='visual';
  q.archetypeId=`native_${a}`;q.representation=rep;q.demand=/story|difference|missing/.test(a)?'application':/compare|property|place|visual/.test(a)?'concept':'procedure';q.contextId=a;q.difficultyBand=q.demand==='application'?3:q.demand==='procedure'?2:1;q.misconceptionTargets=q.misconceptionTargets||[q.wrong?.[0]?.tag||'generated'];q.familyKey=id;return q;
 }
 function year2Words(id){const mode=rotate(id,['number_to_words','words_to_number','expanded_to_number']),n=R(101,999);if(mode==='number_to_words')return mark(Q(`Bagaimanakah <b>${n}</b> ditulis dalam perkataan?`,numWords(n),[N(numWords(n+10),'place'),N(numWords(Math.max(1,n-10)),'place'),N(numWords(reverseN(n)),'same_end')],'Baca ratus, puluh dan sa mengikut tertib.','Tahun 2 · Tulis Nombor',true,true),id,mode,'verbal','concept','number-name',['place']);if(mode==='words_to_number')return mark(Q(`Pilih angka bagi <b>${numWords(n)}</b>.`,n,[N(reverseN(n),'same_end'),N(n+100,'place'),N(Math.max(1,n-10),'place')],'Bina angka mengikut nilai tempat.','Tahun 2 · Kenal Angka',true,true),id,mode,'verbal','concept','number-name',['place']);const h=Math.floor(n/100)*100,t=Math.floor(n%100/10)*10,u=n%10,parts=[h,t,u].filter(Boolean).join(' + ');return mark(Q(`<b>${parts}</b> membentuk nombor?`,n,[N(reverseN(n),'same_end'),N(n+10,'place'),N(Math.max(1,n-100),'place')],'Gabungkan nilai ratus, puluh dan sa.','Tahun 2 · Bina Nombor',true,true),id,mode,'symbolic','application','expanded',['place','digit_value'])}
 function year2Sequence(id){const mode=rotate(id,id==='D2.1.3'?['next','internal']:id==='D2.1.7'?['next','rule']:['next','internal','rule']),step=pick([1,2,5,10,100]),down=Math.random()<.5,start=down?R(step*5,999):R(1,999-step*5),at=k=>start+(down?-step*k:step*k),xs=[at(0),at(1),at(2),at(3),at(4)];if(mode==='next')return mark(Q(`${xs.slice(0,4).join(', ')}, ___`,xs[4],[N(xs[3],'pattern'),N(xs[4]+step,'pattern'),N(xs[4]+(down?step*2:-step*2),'pattern')],'Cari beza tetap dan arah pola.','Tahun 2 · Sambung Rangkaian',true,true),id,mode,'symbolic','procedure','sequence',['pattern']);if(mode==='internal')return mark(Q(`${xs[0]}, ${xs[1]}, ___, ${xs[3]}, ${xs[4]}`,xs[2],[N(xs[1],'pattern'),N(xs[3],'pattern'),N(xs[2]+step,'pattern')],'Gunakan nombor sebelum dan selepas tempat kosong.','Tahun 2 · Nombor Hilang',true,true),id,mode,'symbolic','reasoning','sequence',['pattern']);return mark(Q(`Apakah aturan bagi ${xs.slice(0,4).join(', ')}?`,`${down?'Tolak':'Tambah'} ${step}`,[N(`${down?'Tambah':'Tolak'} ${step}`,'pattern'),N(`Tambah ${step*2}`,'pattern'),N(`Tolak ${step*2}`,'pattern')],'Banding beza antara dua nombor berturutan.','Tahun 2 · Aturan Pola',true,true),id,mode,'verbal','concept','sequence',['pattern'])}
 function year2Estimate(id){const mode=rotate(id,['nearest_ten','range','reasonable']),n=R(12,988),nearest=Math.round(n/10)*10;if(mode==='nearest_ten')return mark(Q(`Anggaran kepada puluh terdekat bagi <b>${n}</b> ialah?`,nearest,[N(Math.floor(n/10)*10,'estimate'),N(Math.ceil(n/10)*10,'estimate'),N(n,'estimate')],'Cari puluh yang paling hampir.','Tahun 2 · Anggar Puluh',true,true),id,mode,'number-line','concept','estimate',['estimate']);if(mode==='range'){const lo=Math.floor(n/100)*100,hi=lo+100;return mark(Q(`Nombor <b>${n}</b> berada antara?`,`${lo} dan ${hi}`,[N(`${lo-100} dan ${lo}`,'estimate'),N(`${hi} dan ${hi+100}`,'estimate'),N(`${n} dan ${n+100}`,'estimate')],'Cari dua ratus yang mengapit nombor.','Tahun 2 · Julat Anggaran',true,true),id,mode,'symbolic','concept','estimate',['estimate','place']);}return mark(Q(`Sebuah bekas mempunyai kira-kira <b>${n}</b> manik. Anggaran manakah paling munasabah?`,nearest,[N(nearest+100,'estimate'),N(Math.max(0,nearest-100),'estimate'),N(n+333,'estimate')],'Pilih nilai bulat yang dekat, bukan terlalu jauh.','Tahun 2 · Anggaran Munasabah',true,true),id,mode,'story','application','estimate',['estimate'])}
 function year2Round(id){const mode=rotate(id,['round_ten','round_hundred','missing_source']),n=R(101,999);if(mode==='round_ten'){const ans=Math.round(n/10)*10;return mark(Q(`Bundarkan <b>${n}</b> kepada puluh terdekat.`,ans,[N(Math.floor(n/10)*10,'round'),N(Math.ceil(n/10)*10,'round'),N(n,'round')],'Lihat digit sa.','Tahun 2 · Bundar Puluh',true,true),id,mode,'number-line','procedure','round',['round']);}if(mode==='round_hundred'){const ans=Math.round(n/100)*100;return mark(Q(`Bundarkan <b>${n}</b> kepada ratus terdekat.`,ans,[N(Math.floor(n/100)*100,'round'),N(Math.ceil(n/100)*100,'round'),N(Math.round(n/10)*10,'round')],'Lihat digit puluh.','Tahun 2 · Bundar Ratus',true,true),id,mode,'number-line','procedure','round',['round']);}const base=R(2,8)*100,ans=base+R(1,4)*10;return mark(Q(`Nombor manakah akan dibundarkan kepada <b>${base}</b> pada ratus terdekat?`,ans,[N(base+60,'round'),N(base+100,'round'),N(Math.max(0,base-100),'round')],'Nombor dalam separuh julat terdekat membundar kepada ratus itu.','Tahun 2 · Semak Bundaran',true,true),id,mode,'symbolic','reasoning','round',['round'])}
 function year2Measure(id){const cfg=id==='D2.6.1'?{item:'reben',unit:'cm',quality:'panjang'}:id==='D2.6.2'?{item:'beras',unit:'g',quality:'jisim'}:id==='D2.6.3'?{item:'air',unit:'mL',quality:'isi padu'}:pick([{item:'reben',unit:'cm',quality:'panjang'},{item:'beras',unit:'g',quality:'jisim'},{item:'air',unit:'mL',quality:'isi padu'}]),mode=rotate(id,id==='D2.6.4'?['unit_choice','compare','operation']:['unit_choice','compare','operation','read']),a=R(2,8)*10,b=R(1,5)*10;
  if(mode==='read'){const readVal=cfg.unit==='cm'?R(2,19):pick([100,200,300,400,500,600,700,800,900]),visual=cfg.unit==='cm'?rulerSvg(readVal):cfg.unit==='g'?scaleSvg(readVal):cylinderSvg(readVal),label=cfg.unit==='cm'?'Berapakah panjang yang ditunjukkan?':cfg.unit==='g'?'Jarum penimbang menunjukkan berapa gram?':'Berapakah isi padu air yang ditunjukkan?',step=cfg.unit==='cm'?1:100,bigUnit=cfg.unit==='cm'?'m':cfg.unit==='g'?'kg':'L';return mark(Q(`${visual}${label}`,`${readVal} ${cfg.unit}`,[N(`${readVal+step} ${cfg.unit}`,'unit'),N(`${Math.max(0,readVal-step)} ${cfg.unit}`,'unit'),N(`${readVal} ${bigUnit}`,'unit')],'Baca senggatan pada alat pengukur dengan teliti.','Tahun 2 · Baca Alat Ukur',true,true),id,mode,'visual','concept','instrument',['unit']);}
  if(mode==='unit_choice')return mark(Q(`Unit sesuai untuk mengukur ${cfg.quality} ${cfg.item}?`,cfg.unit,[N('jam','unit'),N('RM','unit'),N(cfg.unit==='cm'?'kg':'cm','unit')],'Pilih unit yang sepadan dengan perkara yang diukur.','Tahun 2 · Unit Ukuran',true,true),id,mode,'story','concept','measurement',['unit']);
  if(mode==='compare'){const larger=a>b?'A':a<b?'B':'Sama';return mark(Q(`${comparisonBarsSvg(a,b,cfg.unit,`${cfg.item} A`,`${cfg.item} B`)}Yang manakah lebih besar nilainya?`,larger,[N(larger==='A'?'B':'A','unit'),N(larger==='Sama'?'A':'Sama','unit'),N('Tidak dapat ditentukan','unit')],'Banding nilai dalam unit yang sama.','Tahun 2 · Banding Ukuran',true,true),id,mode,'visual','concept','measurement',['unit']);}
  const ans=a+b;return mark(Q(`${comparisonBarsSvg(a,b,cfg.unit,`${cfg.item} A`,`${cfg.item} B`)}Berapakah jumlah kedua-dua ukuran?`,`${ans} ${cfg.unit}`,[N(`${Math.abs(a-b)} ${cfg.unit}`,'operation'),N(`${a} ${cfg.unit}`,'unit'),N(`${ans+10} ${cfg.unit}`,'unit')],'Tambah nilai kerana unitnya sama.','Tahun 2 · Masalah Ukuran',true,true),id,mode,'visual','application','measurement',['unit','operation'])}
 function year2Shape(id){const mode=rotate(id,['name','property','classify']),shapes=[['segi tiga',3,3,'triangle'],['segi empat sama',4,4,'square'],['segi empat tepat',4,4,'rectangle'],['bulatan',0,0,'circle']],cfg=pick(shapes),[name,sides,vertices,key]=cfg,visual=shapeSvg(key);if(mode==='name')return mark(Q(`${visual}Apakah nama bentuk ini?`,name,shuffle(shapes.filter(y=>y[0]!==name)).slice(0,3).map(y=>N(y[0],'shape')),'Perhatikan sisi lurus, bucu dan bentuk keseluruhan.','Tahun 2 · Kenal Bentuk',true,true),id,mode,'visual','concept','shape',['shape']);if(mode==='property'){const answer=`${sides} sisi lurus dan ${vertices} bucu`,counts=['0 sisi lurus dan 0 bucu','2 sisi lurus dan 2 bucu','3 sisi lurus dan 3 bucu','4 sisi lurus dan 4 bucu'];return mark(Q(`${visual}Berapakah bilangan sisi lurus dan bucu bentuk ini?`,answer,counts.filter(value=>value!==answer).slice(0,3).map(value=>N(value,'shape')),'Kira sisi lurus dan bucu secara berasingan.','Tahun 2 · Ciri Bentuk',true,true),id,mode,'visual','concept','shape',['shape']);}const properties={'segi tiga':'3 sisi lurus dan 3 bucu','segi empat sama':'4 sisi sama panjang dan 4 bucu','segi empat tepat':'2 sisi panjang, 2 sisi pendek dan 4 bucu','bulatan':'tiada sisi lurus dan tiada bucu'},answer=properties[name];return mark(Q(`${visual}Pilih ciri yang paling tepat bagi bentuk ini.`,answer,shuffle(Object.entries(properties).filter(([shape])=>shape!==name)).map(([,property])=>N(property,'shape')),'Gunakan semua ciri, terutama panjang sisi dan bilangan bucu.','Tahun 2 · Kelaskan Bentuk',true,true),id,mode,'visual','application','classify',['shape'])}
 function year2Chapter3Task(id){
  if(id==='D2.3.1'){const mode=rotate(id,['bar_model','object_set','verbal_part','compare_model','missing_part']),d=pick([2,3,4,5,6,8,10]),n=R(1,d-1),ans=`${n}/${d}`;
   if(mode==='bar_model')return mark(Q(`${fractionVisual(n,d)}Apakah pecahan bahagian yang berlorek?`,ans,fractionWrongChoices(n,d),'Pengangka ialah bahagian berlorek; penyebut ialah jumlah semua bahagian sama besar.','Tahun 2 · Pecahan Wajar',true,true),id,mode,'visual','concept','bar',['fraction']);
   if(mode==='object_set')return mark(Q(`${fractionSetVisual(n,d)}Apakah pecahan objek berwarna hijau?`,ans,fractionWrongChoices(n,d),'Kira objek hijau dan jumlah semua objek.','Tahun 2 · Pecahan Set Objek',true,true),id,mode,'visual','concept','set',['fraction']);
   if(mode==='verbal_part')return mark(Q(`Satu keseluruhan dibahagi kepada <b>${d} bahagian sama besar</b>. Sebanyak <b>${n} bahagian</b> dipilih. Apakah pecahannya?`,ans,fractionWrongChoices(n,d),'Bilangan dipilih menjadi pengangka; jumlah bahagian menjadi penyebut.','Tahun 2 · Bina Pecahan',true,true),id,mode,'verbal','application','part-whole',['fraction']);
   if(mode==='compare_model'){const compareDen=d===2?4:d,first=d===2?pick([1,2,3]):n;let n2=R(1,compareDen-1);while(n2===first)n2=R(1,compareDen-1);const f1=`${first}/${compareDen}`,f2=`${n2}/${compareDen}`,big=first>n2?f1:f2;return mark(Q(`<div style="display:flex;gap:8px;justify-content:center">${fractionVisual(first,compareDen)}${fractionVisual(n2,compareDen)}</div>Antara <b>${f1}</b> dengan <b>${f2}</b>, yang manakah lebih besar?`,big,[N(big===f1?f2:f1,'fraction'),N('Sama','fraction'),N(`${compareDen}/${Math.max(first,n2)}`,'fraction')],'Penyebut sama: banding bahagian berlorek atau pengangka.','Tahun 2 · Banding Pecahan',true,true),id,mode,'visual','reasoning','compare',['fraction']);}
   return mark(Q(`${fractionVisual(n,d)}Jika satu lagi bahagian dilorek, apakah pecahan baharu?`,`${n+1}/${d}`,[N(ans,'fraction'),N(`${n}/${d+1}`,'fraction'),N(`${d}/${n+1}`,'fraction')],'Tambah satu pada bahagian berlorek; jumlah bahagian kekal.','Tahun 2 · Pecahan Berubah',true,true),id,mode,'visual','reasoning','change',['fraction']);
  }
  if(id==='D2.3.2'){const mode=rotate(id,['tenths_model','fraction_to_decimal','number_line','compare_decimal']),n=R(1,9),dec=(n/10).toFixed(1);
   if(mode==='tenths_model')return mark(Q(`${fractionVisual(n,10)}Apakah nilai bahagian berlorek dalam perpuluhan?`,dec,[N(`0.${Math.max(0,n-1)}`,'decimal'),N(`${n}.0`,'decimal'),N(`0.${Math.min(9,n+1)}`,'decimal')],'Setiap bahagian ialah satu persepuluh atau 0.1.','Tahun 2 · Perpuluhan Persepuluh',true,true),id,mode,'visual','concept','tenths',['decimal']);
   if(mode==='fraction_to_decimal')return mark(Q(`Tukarkan <b>${n}/10</b> kepada perpuluhan.`,dec,[N(String(n),'decimal'),N(`${n}.0`,'decimal'),N(`0.${Math.max(0,n-1)}`,'decimal')],'Persepuluh ditulis satu digit selepas titik perpuluhan.','Tahun 2 · Pecahan ke Perpuluhan',true,true),id,mode,'symbolic','procedure','convert',['decimal','fraction']);
   if(mode==='number_line')return mark(Q(`${numberLineSvg(0,10,1,n)}Titik merah berada ${n} persepuluh dari sifar. Apakah nilainya?`,dec,[N(`0.${Math.max(0,n-1)}`,'decimal'),N(`${n}.0`,'decimal'),N(`0.${Math.min(9,n+1)}`,'decimal')],'Setiap langkah pada garis nombor mewakili 0.1.','Tahun 2 · Garis Perpuluhan',true,true),id,mode,'visual','application','number-line',['decimal']);
   let m=R(1,9);while(m===n)m=R(1,9);const other=(m/10).toFixed(1),big=n>m?dec:other;return mark(Q(`Yang manakah lebih besar: <b>${dec}</b> atau <b>${other}</b>?`,big,[N(big===dec?other:dec,'decimal'),N('Sama','decimal'),N('1.0','decimal')],'Banding digit pada tempat persepuluh.','Tahun 2 · Banding Perpuluhan',true,true),id,mode,'symbolic','reasoning','compare',['decimal']);
  }
  if(id==='D2.3.3'){const mode=rotate(id,['visual_match','decimal_to_fraction','matching_pair','mixed_compare']),n=R(1,9),frac=`${n}/10`,dec=(n/10).toFixed(1);
   if(mode==='visual_match')return mark(Q(`${fractionVisual(n,10)}Notasi manakah sepadan dengan rajah?`,dec,[N(`0.${Math.max(0,n-1)}`,'decimal'),N(`${n}.0`,'decimal'),N(`0.${Math.min(9,n+1)}`,'decimal')],'Rajah menunjukkan persepuluh yang sama dalam bentuk pecahan dan perpuluhan.','Tahun 2 · Hubungan Pecahan-Perpuluhan',true,true),id,mode,'visual','concept','match',['fraction','decimal']);
   if(mode==='decimal_to_fraction')return mark(Q(`Tukarkan <b>${dec}</b> kepada pecahan persepuluh.`,frac,[N(`${10}/${n}`,'fraction'),N(`${n}/100`,'fraction'),N(`${Math.max(1,n-1)}/10`,'fraction')],'Satu digit selepas titik menunjukkan persepuluh.','Tahun 2 · Perpuluhan ke Pecahan',true,true),id,mode,'symbolic','procedure','convert',['fraction','decimal']);
   if(mode==='matching_pair')return mark(Q(`Pasangan manakah mempunyai nilai yang sama?`,`${frac} dan ${dec}`,[N(`${frac} dan ${n}.0`,'decimal'),N(`${n}/100 dan ${dec}`,'fraction'),N(`${Math.max(1,n-1)}/10 dan ${dec}`,'decimal')],'Tukar kedua-dua notasi kepada persepuluh.','Tahun 2 · Padankan Nilai',true,true),id,mode,'verbal','reasoning','equivalence',['fraction','decimal']);
   let m=R(1,9);while(m===n)m=R(1,9);const d2=(m/10).toFixed(1),big=n>m?frac:d2;return mark(Q(`Yang manakah lebih besar: <b>${frac}</b> atau <b>${d2}</b>?`,big,[N(big===frac?d2:frac,'decimal'),N('Sama','decimal'),N('1.0','decimal')],'Nyatakan kedua-duanya sebagai persepuluh sebelum membanding.','Tahun 2 · Banding Dua Notasi',true,true),id,mode,'symbolic','reasoning','compare',['fraction','decimal']);
  }
  if(id==='D2.3.4'){const mode=rotate(id,['coloured_card','filled_bottle','ribbon_compare','remaining_part']),n=R(1,9),dec=(n/10).toFixed(1);
   if(mode==='coloured_card')return mark(Q(`${fractionVisual(n,10)}Aina mewarnakan ${n} daripada 10 bahagian kad. Berapakah bahagian yang diwarnakan dalam perpuluhan?`,dec,[N(`0.${Math.max(0,n-1)}`,'decimal'),N(`${n}.0`,'decimal'),N(`0.${Math.min(9,n+1)}`,'decimal')],`${n} daripada 10 ialah ${n}/10 dan ${dec}.`,'Tahun 2 · Masalah Kad',true,true),id,mode,'visual','application','daily',['fraction','decimal']);
   if(mode==='filled_bottle')return mark(Q(`${fractionVisual(n,10)}Paras air memenuhi ${n} daripada 10 bahagian sama besar. Apakah pecahan yang berisi air?`,`${n}/10`,fractionWrongChoices(n,10),'Jumlah bahagian ialah 10; bahagian berisi menjadi pengangka.','Tahun 2 · Masalah Air',true,true),id,mode,'visual','application','measure',['fraction']);
   if(mode==='ribbon_compare'){let m=R(1,9);while(m===n)m=R(1,9);const larger=n>m?'Reben A':'Reben B';return mark(Q(`${comparisonBarsSvg(n,m,'persepuluh','Reben A','Reben B')}Reben A ialah ${dec} m dan Reben B ialah ${(m/10).toFixed(1)} m. Yang manakah lebih panjang?`,larger,[N(larger==='Reben A'?'Reben B':'Reben A','decimal'),N('Sama panjang','decimal'),N('Tidak dapat ditentukan','decimal')],'Banding nilai persepuluh kedua-dua reben.','Tahun 2 · Masalah Reben',true,true),id,mode,'visual','application','measure',['decimal']);}
   return mark(Q(`${fractionVisual(n,10)}Jika ${n}/10 bahagian telah digunakan, apakah pecahan yang masih tinggal?`,`${10-n}/10`,[N(`${n}/10`,'fraction'),N(`${10}/${n}`,'fraction'),N(`${10-n}/100`,'fraction')],'Bahagian tinggal = semua 10 bahagian − bahagian digunakan.','Tahun 2 · Bahagian Tinggal',true,true),id,mode,'visual','reasoning','remaining',['fraction']);
  }
  return null;
 }
 function year2Task(id,s){
  if(id==='D2.1.2')return year2Words(id);if(id==='D2.1.3'||id==='D2.1.7')return year2Sequence(id);if(id==='D2.1.4')return placeTask(id);if(id==='D2.1.5')return year2Estimate(id);if(id==='D2.1.6')return year2Round(id);
  if(/^D2\.3\.[1-4]$/.test(id))return year2Chapter3Task(id);if(/^D2\.4\.[1-7]$/.test(id))return moneySkillTask(id,s);if(id==='D2.5.1'||id==='D2.5.2'||id==='D2.5.3')return timeSkillTask(id,s);if(['D2.6.1','D2.6.2','D2.6.3','D2.6.4'].includes(id))return year2Measure(id);if(id==='D2.7.2')return year2Shape(id);
  return null}
 function varied(id,s){
  if(+id[1]===1){const y1=year1Task(id);if(y1)return y1;}
  if(+id[1]===2){const y2=year2Task(id,s);if(y2)return y2;}
  if(/^D[1-5]\.(N|CMP)|^D[2345]\.N\d/.test(id)||id==='D6.NUMBERS')return numberTask(id);
  if(id.includes('PV'))return placeTask(id);
  if(/ADD/.test(id))return operationTask(id,'add');if(/SUB/.test(id))return operationTask(id,'sub');
  if(/\.MUL$|\.2\.3$/.test(id))return operationTask(id,'mul');if(/\.DIV$|\.2\.4$/.test(id))return operationTask(id,'div');
  if(+id[1]>=3&&/\.TIME$/.test(id))return timeTask(id);if(+id[1]>=3&&/\.DATA$/.test(id))return dataTask(id);
  if(+id[1]>=3&&/\.FRAC$/.test(id))return fractionTask(id);if(+id[1]>=3&&/\.DEC$/.test(id))return decimalTask(id);if(+id[1]>=3&&/\.PERCENT$/.test(id))return percentTask(id);
  if(+id[1]>=3&&/\.MONEY$/.test(id))return moneyTask(id);if(+id[1]>=3&&/\.SHAPE$|\.PERIM$|\.AREA$/.test(id))return geometryTask(id);
  if(/\.COORD$|\.POSITION$/.test(id))return coordinateTask(id);if(/\.RATIO$/.test(id))return ratioTask(id);
  if(id==='D5.OPS'||id==='D6.OPS')return operationTask(id,rotate(id,['add','sub','mul'])==='add'?'add':Math.random()<.5?'sub':'mul');
  return null;
 }
 function wrap(key){const original=originals[key];banks[key]=function(id,s,shift){const custom=varied(id,s);if(custom)return custom;let q=null,last=hist(id).at(-1)?.archetypeId;for(let i=0;i<8;i++){q=original?original(id,s,shift):null;if(id.startsWith('D2.')&&(!q?.archetypeId||q.archetypeId==='solve_direct'))q=inferNative(q,id);if(!q||q.archetypeId!==last)break}return q}}
 ['d1','d2t1','d2t2','d2t3','d2t4','d2t5','d2t6','d2t7','d2t8','d3','d4','d5','d6'].forEach(wrap);
})();
