/* Cikgu Dimensi — production regrouping pilot Y3-PV-A2 v0.3.0.
 * One active curriculum skill, three diagnostic paths, two genuine representations,
 * and independent KSSR transfer before tutor success. Adaptive mastery is untouched.
 */
(function(root){
  'use strict';
  const PROTOTYPE_ID='Y3-PV-A2',SKILL_ID='D3.SUB10000',MISCONCEPTION_ID='PV-005',CURRICULUM_VERSION='SEMAKAN_2017_DPK_EDISI_3';
  const BASE={id:'BASE_TEN_EXCHANGE',representationId:'R2_PLACE_VALUE'};
  const DECOMP={id:'DECOMPOSITION',representationId:'R7_DECOMPOSITION'};
  const CFG={enabled:true,evidenceThreshold:2,delayedRevisitMs:24*60*60*1000};
  root.DIMENSIONAL_VIEW_CFG=Object.assign({},CFG,root.DIMENSIONAL_VIEW_CFG||{});

  function getDb(){try{if(typeof db!=='undefined')return db}catch(_){ }return root.db||null}
  function getSess(){try{if(typeof sess!=='undefined')return sess}catch(_){ }return root.sess||null}
  function saveDb(){try{if(typeof save==='function')save()}catch(_){ }}
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function reducedMotion(){return !!root.matchMedia?.('(prefers-reduced-motion: reduce)')?.matches}
  function telemetry(type,payload={}){try{root.PATelemetry?.record?.(type,{prototypeId:PROTOTYPE_ID,skillId:SKILL_ID,conceptId:'subtraction_regrouping',...payload})}catch(_){ }}
  function semantic(event,payload={}){const d=ensureSession();if(d)d.semanticEvents.push({event,at:Date.now(),...payload});telemetry('dv_semantic_evidence',{event,context:d?.evidenceContext||'guided',...payload})}

  function freshDimension(){return{active:false,prototypeId:PROTOTYPE_ID,skillId:SKILL_ID,state:'IDLE',stage:null,path:null,diagnosis:null,strategy:null,strategyOrder:[],strategyIndex:0,evidenceContext:null,originalQuestionToken:null,originalBattleState:null,semanticEvents:[],prerequisiteAttempts:0,prerequisitePassed:null,guidedSuccess:false,checkAttempts:0,cleanAttempts:0,transferQuestion:null,resumeScheduled:false,outcome:null,triedStrategies:[],enteredAt:0}}
  function ensureSession(){const s=getSess();if(!s)return null;if(!s.dimension||typeof s.dimension!=='object')s.dimension=freshDimension();return s.dimension}
  function setState(stage){const d=ensureSession();if(!d)return false;d.state=stage;d.stage=stage;setStage(stage);telemetry('dv_stage_changed',{stage,path:d.path,strategyId:d.strategy?.id||null});return true}

  function policy({stage,path,strategy,event}={}){
    if(path==='CARELESS'&&stage==='FAHAM'&&event==='RECHECK_READY')return'GUNA';
    if(stage==='FAHAM'&&event==='PREREQ_PASS')return'BINA';
    if(stage==='FAHAM'&&event==='PREREQ_FAIL')return'BINA';
    if(stage==='BINA'&&event==='GUIDED_PASS')return'SAMBUNG';
    if(stage==='SAMBUNG'&&event==='BRIDGE_READY')return'CUBA';
    if(stage==='CUBA'&&event==='CHECK_PASS')return'GUNA';
    if(stage==='CUBA'&&event==='CHECK_FAIL'&&strategy===BASE.id)return'FAHAM';
    if(stage==='CUBA'&&event==='CHECK_FAIL'&&strategy===DECOMP.id)return'GUNA';
    if(stage==='GUNA'&&(event==='TRANSFER_PASS'||event==='TRANSFER_FAIL'))return'COMPLETE';
    return stage||'IDLE';
  }

  function eligibleQuestion(skillId,q){if(!root.DIMENSIONAL_VIEW_CFG.enabled||skillId!==SKILL_ID||!q?.dimensional)return false;const m=q.dimensional,a=Number(m.operands?.minuend),b=Number(m.operands?.subtrahend);return m.prototypeId===PROTOTYPE_ID&&m.curriculumVersion===CURRICULUM_VERSION&&m.transferStage==='ENTRY'&&root.PAPlaceValueEngine?.onesRegroupRequired?.(a,b)===true}
  function captureResponseEvidence(skillId,ok,tag,sec,usedHint,q){if(ok||!eligibleQuestion(skillId,q)||!['units_only','place'].includes(tag))return null;const result=root.PADimensionalMemory?.recordEvidence?.({conceptId:'subtraction_regrouping',skillId,misconceptionId:MISCONCEPTION_ID,itemId:String(q.token||mItem(q)||''),tag,type:'REGROUPING_PATTERN',distinctItem:true,context:'natural-assessment'});if(result?.added){telemetry('dv_evidence_added',{tag,latencyBand:Number(sec)<1.15?'RAPID':Number(sec)>12?'EXTENDED':'NORMAL',usedHint:!!usedHint,evidenceCount:result.independentEvidenceCount,confidence:result.confidence});saveDb()}return result}
  function mItem(q){return q?.dimensional?.itemId||`${q?.dimensional?.operands?.minuend||''}-${q?.dimensional?.operands?.subtrahend||''}`}
  function skillHistory(){const d=getDb();return d?.skills?.[SKILL_ID]||{}}
  function evaluateEntry(skillId,q){if(!eligibleQuestion(skillId,q))return null;const node=root.PADimensionalMemory?.ensureMisconception?.(MISCONCEPTION_ID,'subtraction_regrouping');const count=Number(node?.independentEvidenceCount||0),distinct=new Set((node?.evidence||[]).filter(x=>x.context==='natural-assessment').map(x=>x.itemId)).size,same=(node?.evidence||[]).filter(x=>x.type==='REGROUPING_PATTERN').length;const diagnosis=root.PADimensionalCatalog?.diagnoseRegrouping?.({wrongEvidenceCount:count,distinctWrongItems:distinct,samePatternCount:same,history:skillHistory()})||{failureType:'UNKNOWN',confidence:0};if(diagnosis.failureType==='CARELESS_RECHECK')return{prototypeId:PROTOTYPE_ID,skillId,diagnosis,evidenceCount:count,question:q};if(count>=Math.max(2,Number(root.DIMENSIONAL_VIEW_CFG.evidenceThreshold||2)))return{prototypeId:PROTOTYPE_ID,skillId,diagnosis,evidenceCount:count,question:q};return null}

  function ensureOverlay(){if(typeof document==='undefined')return null;let o=document.getElementById('dimensionalViewOverlay');if(o)return o;o=document.createElement('div');o.id='dimensionalViewOverlay';o.className='dvOverlay';o.setAttribute('role','dialog');o.setAttribute('aria-modal','true');o.setAttribute('aria-labelledby','dvTitle');o.innerHTML='<div class="dvBackdrop"></div><section class="dvPanel"><header class="dvHead"><div class="dvTeacher is-active" aria-hidden="true"><span class="dvDimensionalCharacter is-active" data-dimensi-state="active"><span class="dvDimensionalPortrait"><img class="dvDimensionalBase" src="assets/coach/cikgu-wajar/welcome.webp" alt=""><img class="dvDimensionalAura" src="assets/coach/cikgu-dimensi/dimensional-aura.svg" alt=""></span></span></div><div><small>CIKGU DIMENSI</small><h2 id="dvTitle">Tolak dengan mengumpul semula</h2></div><span class="dvStage" id="dvStage"></span></header><div id="dvBody" class="dvBody" aria-live="polite"></div></section>';document.body.appendChild(o);return o}
  function setStage(v){const e=typeof document!=='undefined'&&document.getElementById('dvStage');if(e)e.textContent=v||''}
  function setBody(html){const e=typeof document!=='undefined'&&document.getElementById('dvBody');if(!e)return;e.innerHTML=html;e.querySelector('button,input')?.focus?.({preventScroll:true})}
  function showOverlay(){const o=ensureOverlay();if(o){o.classList.add('show');document.body.classList.add('dvTeaching')}}
  function hideOverlay(){const o=typeof document!=='undefined'&&document.getElementById('dimensionalViewOverlay');o?.classList.remove('show');document.body?.classList.remove('dvTeaching')}
  function disableBattle(){if(typeof document==='undefined')return;document.querySelectorAll('#game .ans,#game .hintBtn').forEach(el=>{el.dataset.dvWasDisabled=el.disabled?'1':'0';el.disabled=true});document.getElementById('battleArena')?.classList.add('dvBattleFrozen')}
  function releaseBattle(){if(typeof document==='undefined')return;document.getElementById('battleArena')?.classList.remove('dvBattleFrozen');document.querySelectorAll('#game .ans,#game .hintBtn').forEach(el=>{el.disabled=el.dataset.dvWasDisabled==='1';delete el.dataset.dvWasDisabled})}
  function freezeBattle(){const s=getSess(),d=ensureSession();if(!s||!d)return;d.originalBattleState={hp:s.hp,ehp:s.ehp,start:s.start,retryState:s.retryState||null,frozenAt:Date.now(),journeyGeneration:root.PABattlePresentation?.generation?.()??null};root.PABattlePresentation?.cancel?.();disableBattle();telemetry('dv_battle_frozen',{hp:s.hp,enemyHp:s.ehp})}

  function currentMemory(){return root.PADimensionalMemory?.snapshot?.(SKILL_ID)||{}}
  function start(intervention){
    if(!intervention||intervention.prototypeId!==PROTOTYPE_ID)return false;const s=getSess();if(!s||s.dimension?.active)return false;
    root.PADimensionalMemory?.ensure?.();s.dimension=freshDimension();const d=s.dimension;d.active=true;d.enteredAt=Date.now();d.originalQuestionToken=String(intervention.question?.token||s.q?.token||'');d.diagnosis=intervention.diagnosis||root.PADimensionalCatalog?.diagnoseRegrouping?.({wrongEvidenceCount:Number(intervention.evidenceCount||2),distinctWrongItems:Number(intervention.evidenceCount||2),samePatternCount:Number(intervention.evidenceCount||2),history:skillHistory()})||{failureType:'UNKNOWN',confidence:.5};d.path=d.diagnosis.failureType==='CARELESS_RECHECK'?'CARELESS':'DISCRIMINATE';d.strategyOrder=root.PADimensionalCatalog?.orderStrategies?.(currentMemory())||[BASE,DECOMP];d.strategy=d.strategyOrder[0]||BASE;d.originalQuestion=intervention.question||s.q||null;
    root.PADimensionalMemory?.markInterventionStarted?.(SKILL_ID,d.diagnosis.misconceptionId||MISCONCEPTION_ID);freezeBattle();showOverlay();telemetry('dv_intervention_started',{failureType:d.diagnosis.failureType,confidence:d.diagnosis.confidence,evidenceCount:intervention.evidenceCount||0});setState('FAHAM');if(d.path==='CARELESS')renderCareless();else renderPrerequisiteDiscriminator();saveDb();return true
  }

  function renderCareless(){const d=ensureSession();if(!d)return;d.evidenceContext='understanding-check';setBody('<div class="dvIntro"><b>Cuba tengok bahagian sa sekali lagi.</b><span>Tak perlu belajar semula semuanya. Semak satu soalan baru dengan teliti.</span></div><div class="dvChoices"><button onclick="PADimensionalView.carelessReady()">Cuba soalan baru</button></div>')}
  function carelessReady(){const d=ensureSession();if(!d||d.stage!=='FAHAM'||d.path!=='CARELESS')return;setState(policy({stage:'FAHAM',path:'CARELESS',event:'RECHECK_READY'}));renderGuna()}

  function renderPrerequisiteDiscriminator(){const d=ensureSession();if(!d)return;d.evidenceContext='understanding-check';setBody(`<div class="dvIntro"><b>Kita semak satu hubungan dahulu.</b><span>Satu puluh dan sepuluh sa mempunyai nilai yang sama.</span></div><div class="dvMeaning"><div class="dvMeaningRow"><div class="dvMeaningCard"><div class="dvTenRod"></div><strong>1 puluh</strong></div><span class="dvMeaningEquals">=</span><div class="dvMeaningCard"><div class="dvTenOnes">${Array.from({length:10},()=>'<i></i>').join('')}</div><strong>10 sa</strong></div></div></div><p class="dvPrompt">1 puluh bersamaan berapa sa?</p><div class="dvChoices"><button onclick="PADimensionalView.answerPrerequisite(10)">10 sa</button><button onclick="PADimensionalView.answerPrerequisite(1)">1 sa</button><button onclick="PADimensionalView.answerPrerequisite(100)">100 sa</button></div><div class="dvFeedback" id="dvFeedback"></div>`)}
  function answerPrerequisite(value){const d=ensureSession();if(!d||d.stage!=='FAHAM')return;d.prerequisiteAttempts++;d.prerequisitePassed=Number(value)===10;const diag=root.PADimensionalCatalog?.diagnoseRegrouping?.({wrongEvidenceCount:Math.max(2,Number(d.diagnosis?.evidenceCount||2)),distinctWrongItems:2,samePatternCount:2,history:skillHistory(),prerequisitePassed:d.prerequisitePassed});d.diagnosis=diag||d.diagnosis;d.path=d.prerequisitePassed?'REGROUPING':'PREREQUISITE';telemetry('dv_prerequisite_result',{result:d.prerequisitePassed?'PASS':'FAIL',attempts:d.prerequisiteAttempts,failureType:d.diagnosis?.failureType});if(d.prerequisitePassed&&d.strategyOrder[0]?.id===DECOMP.id){d.strategy=DECOMP;setState('FAHAM');renderDecompFaham();return}setState(policy({stage:'FAHAM',event:d.prerequisitePassed?'PREREQ_PASS':'PREREQ_FAIL'}));renderBaseTenBina()}

  function baseScenario(){return root.PAPlaceValueEngine?.subtractionScenario?.(52,27)}
  function renderBaseTenFaham(){const d=ensureSession();if(!d)return;d.strategy=BASE;d.evidenceContext='guided';setBody('<div class="dvIntro"><b>Kita tukar dimensi sekali lagi.</b><span>Kali ini lihat nilai tempat sebagai puluh dan sa. Nilainya mesti kekal sama.</span></div><div class="dvEquation"><b>52 = 5 puluh + 2 sa</b><span>1 puluh boleh ditukar kepada 10 sa</span></div><div class="dvChoices"><button onclick="PADimensionalView.startBaseTenBuild()">Bina dengan blok</button></div>')}
  function startBaseTenBuild(){const d=ensureSession();if(!d||d.stage!=='FAHAM')return;setState('BINA');renderBaseTenBina()}
  function renderBaseTenBina(){const d=ensureSession(),sc=baseScenario();if(!d||!sc?.ok)return abort('BASE_TEN_ENGINE');d.strategy=BASE;if(!d.triedStrategies.includes(BASE.id))d.triedStrategies.push(BASE.id);d.evidenceContext='guided';root.PADimensionalMemory?.recordStrategy?.(SKILL_ID,BASE.id,{representationId:BASE.representationId,result:'OPENED',context:'guided',supportLevel:'FULL_SUPPORT'});const rods=Array.from({length:5},(_,i)=>`<button class="dvTenRod" aria-label="Puluh ${i+1}" onclick="PADimensionalView.exchangeTen()"></button>`).join('');const ones=Array.from({length:2},()=>'<i></i>').join('');setBody(`<div class="dvIntro"><b>${d.path==='PREREQUISITE'?'Kita bina 1 puluh = 10 sa.':'52 ada 5 puluh dan 2 sa.'}</b><span>Nak tolak 7 sa, tetapi kita cuma ada 2 sa. Tukar satu puluh kepada 10 sa.</span></div><div class="dvMeaning"><div class="dvMeaningRow"><div class="dvMeaningCard"><div style="display:flex;gap:6px;justify-content:center">${rods}</div><strong>5 puluh</strong></div><div class="dvMeaningCard"><div class="dvTenOnes">${ones}</div><strong>2 sa</strong></div></div></div><p class="dvPrompt">Tekan satu batang puluh untuk menukarnya.</p><div class="dvFeedback" id="dvFeedback"></div>`)}
  function exchangeTen(){const d=ensureSession(),sc=baseScenario();if(!d||d.stage!=='BINA'||d.strategy?.id!==BASE.id||!sc?.ok)return;const ex=root.PAPlaceValueEngine?.exchangeBaseTen?.(sc.before,'TENS','ONES',{expectedValue:52});if(!ex?.ok||!root.PAPlaceValueEngine?.isExpectedSingleTenExchange?.(sc.before,ex.state))return abort('INVARIANT_FAILURE');semantic('TEN_EXCHANGED',{representationId:BASE.representationId,beforeValue:52,afterValue:root.PAPlaceValueEngine.placeValueValue(ex.state)});d.guidedSuccess=true;root.PADimensionalMemory?.recordGuidedOutcome?.(SKILL_ID,'PASS','FULL_SUPPORT');root.PADimensionalMemory?.recordStrategy?.(SKILL_ID,BASE.id,{representationId:BASE.representationId,result:'PASS',context:'guided',supportLevel:'FULL_SUPPORT'});setState(policy({stage:'BINA',event:'GUIDED_PASS'}));renderBaseTenSambung()}
  function renderBaseTenSambung(){const d=ensureSession();if(!d)return;d.evidenceContext='scaffolded';setBody('<div class="dvIntro"><b>Nilainya tidak berubah.</b><span>Kita cuma tulis 52 dengan susunan nilai tempat yang lain.</span></div><div class="dvEquation"><b>52 = 5 puluh + 2 sa</b><span>↓ tukar 1 puluh kepada 10 sa</span><b>52 = 4 puluh + 12 sa</b></div><div class="dvMeaning"><p>Jadi dalam bentuk lazim, 12 sa boleh ditolak dengan 7 sa. Inilah sebab langkah mengumpul semula itu sah.</p></div><div class="dvChoices"><button onclick="PADimensionalView.bridgeReady()">Cuba sendiri</button></div>')}
  function bridgeReady(){const d=ensureSession();if(!d||d.stage!=='SAMBUNG')return;setState(policy({stage:'SAMBUNG',event:'BRIDGE_READY'}));renderCuba()}

  function renderDecompFaham(){const d=ensureSession();if(!d)return;d.strategy=DECOMP;if(!d.triedStrategies.includes(DECOMP.id))d.triedStrategies.push(DECOMP.id);d.evidenceContext='guided';root.PADimensionalMemory?.recordStrategy?.(SKILL_ID,DECOMP.id,{representationId:DECOMP.representationId,result:'OPENED',context:'guided',supportLevel:'REDUCED_SUPPORT'});setBody('<div class="dvIntro"><b>Kita lihat hubungan yang sama tanpa blok.</b><span>Untuk 73 − 28, kita perlukan lebih banyak sa. Pecahkan 73 kepada dua bahagian yang masih bernilai 73.</span></div><p class="dvPrompt">Yang manakah masih sama dengan 73 dan memudahkan tolak 8 sa?</p><div class="dvChoices"><button onclick="PADimensionalView.chooseDecomposition(60,13)">60 + 13</button><button onclick="PADimensionalView.chooseDecomposition(70,3)">70 + 3</button><button onclick="PADimensionalView.chooseDecomposition(50,13)">50 + 13</button></div><div class="dvFeedback" id="dvFeedback"></div>')}
  function chooseDecomposition(a,b){const d=ensureSession();if(!d||d.stage!=='FAHAM'||d.strategy?.id!==DECOMP.id)return;if(Number(a)+Number(b)!==73||Number(b)<8){const f=document.getElementById('dvFeedback');if(f)f.textContent='Cari pecahan yang masih bernilai 73 dan memberi sekurang-kurangnya 8 sa.';return}semantic('DECOMPOSITION_SELECTED',{representationId:DECOMP.representationId,parts:[a,b]});setState('BINA');renderDecompBina()}
  function renderDecompBina(){const sc=root.PAPlaceValueEngine?.decompositionScenario?.(73,28);if(!sc?.ok)return abort('DECOMPOSITION_ENGINE');setBody(`<div class="dvIntro"><b>Pecahkan kedua-dua nombor mengikut nilai tempat.</b><span>Tiada batang puluh kali ini. Kita bekerja dengan bahagian nombor.</span></div><div class="dvEquation"><b>73 = 60 + 13</b><b>28 = 20 + 8</b></div><p class="dvPrompt">Pilih ayat yang betul.</p><div class="dvChoices"><button onclick="PADimensionalView.answerDecompBuild(true)">(60 − 20) + (13 − 8)</button><button onclick="PADimensionalView.answerDecompBuild(false)">(60 − 8) + (13 − 20)</button></div>`)}
  function answerDecompBuild(ok){const d=ensureSession();if(!d||d.stage!=='BINA'||d.strategy?.id!==DECOMP.id)return;if(!ok){return}semantic('DECOMPOSITION_SELECTED',{representationId:DECOMP.representationId,operation:'PARTWISE_SUBTRACTION'});d.guidedSuccess=true;root.PADimensionalMemory?.recordGuidedOutcome?.(SKILL_ID,'PASS','REDUCED_SUPPORT');root.PADimensionalMemory?.recordStrategy?.(SKILL_ID,DECOMP.id,{representationId:DECOMP.representationId,result:'PASS',context:'guided',supportLevel:'REDUCED_SUPPORT'});setState(policy({stage:'BINA',event:'GUIDED_PASS'}));renderDecompSambung()}
  function renderDecompSambung(){setBody('<div class="dvIntro"><b>Hubungkan semula kepada kiraan sekolah.</b><span>Nilai yang sama, cuma dipecahkan supaya sa boleh ditolak.</span></div><div class="dvEquation"><b>73 − 28</b><span>= (60 − 20) + (13 − 8)</span><span>= 40 + 5</span><b>= 45</b></div><div class="dvChoices"><button onclick="PADimensionalView.bridgeReady()">Cuba sendiri</button></div>')}

  function renderCuba(){const d=ensureSession();if(!d)return;d.evidenceContext='understanding-check';d.checkAttempts=0;const decomp=d.strategy?.id===DECOMP.id;const a=decomp?64:73,b=decomp?28:28;setBody(`<div class="dvIntro"><b>Sekarang cuba tanpa petunjuk langkah.</b><span>${decomp?'Gunakan idea pecahan nombor jika perlu.':'Gunakan hubungan 1 puluh = 10 sa jika perlu.'}</span></div><p class="dvPrompt"><b>${a} − ${b} = ?</b></p><div class="dvAnswerRow"><input id="dvCheckAnswer" inputmode="numeric" autocomplete="off" aria-label="Jawapan"><button onclick="PADimensionalView.submitCheck(${a-b})">Semak</button></div><div class="dvFeedback" id="dvFeedback"></div>`)}
  function submitCheck(answer){const d=ensureSession();if(!d||d.stage!=='CUBA')return;d.checkAttempts++;const input=document.getElementById('dvCheckAnswer'),ok=Number(input?.value)===Number(answer);root.PADimensionalMemory?.recordUnderstandingCheck?.(SKILL_ID,ok?'PASS':'FAIL',{strategyId:d.strategy?.id,representationId:d.strategy?.representationId});if(ok){root.PADimensionalMemory?.recordStrategy?.(SKILL_ID,d.strategy.id,{representationId:d.strategy.representationId,result:'PASS',context:'understanding-check',supportLevel:'NO_STEP_PROMPTS'});setState(policy({stage:'CUBA',strategy:d.strategy.id,event:'CHECK_PASS'}));renderGuna();return}root.PADimensionalMemory?.recordStrategy?.(SKILL_ID,d.strategy.id,{representationId:d.strategy.representationId,result:'FAIL',context:'understanding-check',supportLevel:'NO_STEP_PROMPTS'});const alternate=d.strategyOrder.find(x=>!d.triedStrategies.includes(x.id));if(alternate){d.strategy=alternate;setState('FAHAM');if(alternate.id===DECOMP.id)renderDecompFaham();else renderBaseTenFaham();return}setState('GUNA');renderGuna()}

  function makeTransferQuestion(){try{const bank=root.PAQuestionBanks?.d3;if(typeof bank==='function'){for(let i=0;i<12;i++){const q=bank(SKILL_ID,skillHistory(),false);if(q?.dimensional&&root.PAPlaceValueEngine?.onesRegroupRequired?.(q.dimensional.operands?.minuend,q.dimensional.operands?.subtrahend))return q}}}catch(_){ }return{prompt:'4322 − 207 = ?',answer:4115,kind:'Darjah 3',dimensional:{prototypeId:PROTOTYPE_ID,curriculumVersion:CURRICULUM_VERSION,transferStage:'KSSR_CLEAN',operands:{minuend:4322,subtrahend:207}}}}
  function renderGuna(){const d=ensureSession();if(!d)return;d.evidenceContext='independent-transfer';d.cleanAttempts=0;d.transferQuestion=makeTransferQuestion();const q=d.transferQuestion;setBody(`<div class="dvIntro"><b>Guna pada soalan biasa.</b><span>Tiada blok, tiada langkah bercahaya. Buat seperti soalan KSSR biasa.</span></div><p class="dvPrompt dvCleanPrompt">${q.prompt}</p><div class="dvAnswerRow"><input id="dvCleanAnswer" inputmode="numeric" autocomplete="off" aria-label="Jawapan KSSR"><button onclick="PADimensionalView.submitTransfer()">Hantar</button></div><div class="dvFeedback" id="dvFeedback"></div>`)}
  function submitTransfer(){const d=ensureSession();if(!d||d.stage!=='GUNA'||!d.transferQuestion)return;d.cleanAttempts++;const input=document.getElementById('dvCleanAnswer'),ok=String(input?.value??'').trim()===String(d.transferQuestion.answer).trim();const rep=d.path==='CARELESS'?null:d.strategy?.representationId||null,strategy=d.path==='CARELESS'?'MINIMAL_RECHECK':d.strategy?.id||null;root.PADimensionalMemory?.recordIndependentTransfer?.(SKILL_ID,ok?'PASS':'FAIL',{strategyId:strategy,representationId:rep});telemetry('dv_independent_transfer',{result:ok?'PASS':'FAIL',attempt:d.cleanAttempts,questionKind:d.transferQuestion.kind||'Darjah 3'});d.outcome=ok?'SUCCESS':'UNRESOLVED';root.PADimensionalMemory?.markInterventionCompleted?.(SKILL_ID,{success:ok});root.PADimensionalMemory?.scheduleRevisit?.({skillId:SKILL_ID,dueAfter:Date.now()+Number(root.DIMENSIONAL_VIEW_CFG.delayedRevisitMs||CFG.delayedRevisitMs),reason:ok?'regrouping_delayed_confirmation':'regrouping_unresolved'});setState(policy({stage:'GUNA',event:ok?'TRANSFER_PASS':'TRANSFER_FAIL'}));saveDb();renderComplete(ok)}
  function renderComplete(ok){setBody(`<div class="dvIntro"><b>${ok?'Bagus. Cara itu berjaya pada soalan biasa.':'Belum kukuh lagi.'}</b><span>${ok?'Kita akan semak semula kemudian untuk pastikan ia kekal.':'Kita berhenti bantuan di sini dan cuba semula pada sesi lain. Tiada penguasaan diberi daripada langkah berpandu tadi.'}</span></div><div class="dvChoices"><button onclick="PADimensionalView.continueBattle()">Kembali ke pertempuran</button></div>`)}

  function continueBattle(){const s=getSess(),d=ensureSession();if(!s||!d||d.resumeScheduled)return false;d.resumeScheduled=true;d.active=false;releaseBattle();hideOverlay();root.PABattlePresentation?.cancel?.();s.retryState=null;s.hint=false;s.hintLevel=0;saveDb();telemetry('dv_battle_resume',{outcome:d.outcome,originalQuestionToken:d.originalQuestionToken});try{if(typeof nextQ==='function')nextQ();else root.nextQ?.()}catch(err){console.error('Cikgu Dimensi resume gagal',err);return false}return true}
  function abort(reason){const d=ensureSession();if(!d)return false;d.outcome='ABORTED';telemetry('dv_intervention_aborted',{reason});setState('COMPLETE');setBody('<div class="dvIntro"><b>Kita sambung semula.</b><span>Cikgu akan cuba cara ini pada masa lain.</span></div><div class="dvChoices"><button onclick="PADimensionalView.continueBattle()">Kembali ke pertempuran</button></div>');return false}

  function installAdapters(){
    const original=root.beginHintRetry;if(typeof original==='function'&&!original.__paDimensiPhase2){const wrapped=function(o,btn,q){const out=original.apply(this,arguments);try{const s=getSess();if(!s?.dimension?.active){const sec=s?.retryState?.firstSeconds??0;captureResponseEvidence(q?.skill,false,o?.tag,sec,false,q);const entry=evaluateEntry(q?.skill,q);if(entry)start(entry)}}catch(err){console.warn('Cikgu Dimensi routing gagal',err)}return out};wrapped.__paDimensiPhase2=true;wrapped.__paDimensiOriginal=original;root.beginHintRetry=wrapped}
    const originalNext=root.nextQ;if(typeof originalNext==='function'&&!originalNext.__paDimensiPhase2){const wrapped=function(){if(getSess()?.dimension?.active)return;return originalNext.apply(this,arguments)};wrapped.__paDimensiPhase2=true;wrapped.__paDimensiOriginal=originalNext;root.nextQ=wrapped}
  }

  root.PADimensionalView={version:'0.3.0',prototypeId:PROTOTYPE_ID,skillId:SKILL_ID,start,evaluateEntry,captureResponseEvidence,eligibleQuestion,policy,carelessReady,answerPrerequisite,startBaseTenBuild,exchangeTen,chooseDecomposition,answerDecompBuild,bridgeReady,submitCheck,submitTransfer,continueBattle,abort,installAdapters,_test:{freshDimension,makeTransferQuestion,baseScenario}};
  root.evaluateDimensionalIntervention=evaluateEntry;
  installAdapters();
})(typeof window!=='undefined'?window:globalThis);
