window.PAQuestionBanks = window.PAQuestionBanks || {};
window.PAQuestionBanks.d4 = function(id,s,shift){
 if(id==="D4.N100000"){let a=R(10000,99999),b=R(10000,99999);return Q(`Yang manakah lebih besar?<br><b>${a}</b> atau <b>${b}</b>`,Math.max(a,b),[N(Math.min(a,b),"compare"),N(a+b,"operation"),N(Math.abs(a-b),"operation")],"Banding digit dari kiri.","Darjah 4",true,shift)}
 if(id==="D4.PV100000"){let n=uniqueDigitNumber(5),s=String(n),pos=R(0,4),d=+s[pos],pow=4-pos,ans=d*Math.pow(10,pow),place=['puluh ribu','ribu','ratus','puluh','sa'][pos];return Q(`Apakah nilai digit <b>${d}</b> pada tempat <b>${place}</b> dalam <b>${n}</b>?`,ans,[N(d,"digit_value"),N(d*Math.pow(10,Math.max(0,pow-1)),"place"),N(ans+1000,"place")],"Nilai digit ikut tempatnya.","Darjah 4",true,true)}
 if(id==="D4.ADD"){let a=R(10000,60000),b=R(1000,25000),ans=a+b;return addQ(a,b,ans,"Darjah 4",shift)}
 if(id==="D4.SUB"){let a=R(20000,99999),b=R(1000,Math.min(25000,a-1)),ans=a-b;return subQ(a,b,ans,"Darjah 4",shift)}
 if(id==="D4.MUL"){let a=R(12,99),b=pick([3,4,5,6,7,8,9]),ans=a*b;return Q(`${a} × ${b} = ?`,ans,[N(a+b,"operation"),N(ans+b,"fact"),N(Math.round(ans/10)*10,"fact")],"Darab ikut pecahan nilai tempat atau fakta darab.","Darjah 4",true,true)}
 if(id==="D4.DIV"){let b=pick([3,4,5,6,8,9]),ans=R(12,60),a=b*ans;return Q(`${a} ÷ ${b} = ?`,ans,[N(b,"operation"),N(ans+2,"division"),N(Math.max(1,ans-2),"division")],"Semak berapa kumpulan sama banyak.","Darjah 4",true,true)}
 if(id==="D4.FRAC"){let d=pick([4,5,6,8,10]),n=R(1,d-1),m=R(1,d-n),ans=`${n+m}/${d}`;return Q(`${fractionVisual(n,d)}Tambah pecahan <b>${n}/${d}</b> + <b>${m}/${d}</b> = ?`,ans,[N(`${n+m}/${d+1}`,"fraction"),N(`${n*m}/${d}`,"fraction"),N(`${n+m}/${m}`,"fraction")],"Penyebut sama: tambah pengangka sahaja.","Darjah 4",true,true)}
 if(id==="D4.DEC"){let a=R(10,99)/10,b=R(1,49)/10,ans=a+b;return Q(`${decimalFmt(a,1)} + ${decimalFmt(b,1)} = ?`,decimalFmt(ans,1),[N(decimalFmt(ans+.5,1),"decimal"),N(decimalFmt(ans+.1,1),"decimal"),N(decimalFmt(Math.max(0,ans-.1),1),"decimal")],"Selarikan titik perpuluhan.","Darjah 4",true,true)}
 if(id==="D4.MONEY"){let price=R(15,80),qty=pick([2,3,4]),ans=price*qty;return Q(`Seunit RM${price}. Jika beli ${qty} unit, jumlahnya?`,`RM${ans}`,[N(`RM${price+qty}`,"operation"),N(`RM${ans+10}`,"same_end"),N(`RM${price}`,"money")],"Darab harga dengan kuantiti.","Darjah 4",true,true)}
 if(id==="D4.TIME"){let h=R(7,11),m=R(0,11)*5,dur=pick([25,35,45,50,60,75,90]),mins=h*60+m+dur,ans=`${Math.floor(mins/60)}:${String(mins%60).padStart(2,'0')}`;return Q(`Bas bertolak ${h}:${String(m).padStart(2,'0')} dan perjalanan ${dur} minit. Tiba pukul?`,ans,[N(`${h}:${String(m).padStart(2,'0')}`,"time"),N(`${Math.floor((mins+15)/60)}:${String((mins+15)%60).padStart(2,'0')}`,"time"),N(`${Math.floor((mins-15)/60)}:${String((mins-15)%60).padStart(2,'0')}`,"time")],"Tambah tempoh pada masa mula.","Darjah 4",true,true)}
 if(id==="D4.MEASURE"){let m=R(1,9),cm=R(1,19)*5,ans=m*100+cm;return Q(`${m} m ${cm} cm = berapa cm?`,ans,[N(m+cm,"unit"),N(m*10+cm,"unit"),N(ans+10,"unit")],"1 m = 100 cm.","Darjah 4",true,true)}
 if(id==="D4.PERIM"){let l=R(4,12),w=R(3,10),ans=2*(l+w);return Q(`Segi empat tepat panjang ${l} cm dan lebar ${w} cm. Perimeter?`,ans,[N(l*w,"area"),N(l+w,"operation"),N(ans+4,"shape")],"Perimeter = 2 × (panjang + lebar).","Darjah 4",true,true)}
 if(id==="D4.DATA"){let labels=['Isnin','Selasa','Rabu'],vals=[R(12,30),R(12,30),R(12,30)],mx=Math.max(...vals),ans=labels[vals.indexOf(mx)];return Q(`${barChart(labels,vals)}Hari manakah paling banyak?`,ans,labels.filter(x=>x!==ans).map(x=>N(x,"data")).concat([N(String(vals.reduce((a,b)=>a+b,0)),"operation")]).slice(0,3),"Pilih palang paling tinggi.","Darjah 4",false,true)}
 return null;
};
