// questions/v2/renderers/d3/p0-kssr.js
// Phase 3A-2 semantic-hardening renderer for Darjah 3 T2/T3/T5/T6/T9.
// Pure function: no DOM/Node globals.
(function(){
'use strict';
function esc(s){return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function svg(w,h,b){return '<svg viewBox="0 0 '+w+' '+h+'" width="100%" style="max-width:'+w+'px;height:auto" xmlns="http://www.w3.org/2000/svg" role="img" aria-hidden="true">'+b+'</svg>';}
var stroke='#2b2540',fill='#f4f0fa',accent='#7254a8',light='#ffffff';
function bar(v){var p=v.parts||[],total=p.reduce(function(a,x){return a+Math.abs(Number(x)||0);},0)||1,x=8,b='';for(var i=0;i<p.length;i++){var w=Math.max(28,220*Math.abs(Number(p[i])||0)/total);b+='<rect x="'+x+'" y="28" width="'+w+'" height="42" rx="5" fill="'+(p[i]<0?'#f8e9e9':fill)+'" stroke="'+stroke+'" stroke-width="2"/><text x="'+(x+w/2)+'" y="54" text-anchor="middle" font-size="11" font-family="sans-serif">'+esc((v.labels||[])[i]||String(p[i]))+'</text>';x+=w;}return svg(Math.max(250,x+8),92,b);}
function grouping(v){var g=Math.max(1,Math.min(8,Number(v.groups)||1)),each=v.each,b='';for(var i=0;i<g;i++){var x=12+(i%4)*64,y=12+Math.floor(i/4)*54;b+='<rect x="'+x+'" y="'+y+'" width="52" height="40" rx="7" fill="'+fill+'" stroke="'+stroke+'" stroke-width="2"/><text x="'+(x+26)+'" y="'+(y+25)+'" text-anchor="middle" font-size="10" font-family="sans-serif">'+esc(each)+'</text>';}return svg(276,g>4?120:66,b);}
function fractionStrip(n,d,x0,y0,W,H){var b='';for(var i=0;i<d;i++){var w=W/d;b+='<rect x="'+(x0+i*w)+'" y="'+y0+'" width="'+w+'" height="'+H+'" fill="'+(i<n?accent:light)+'" stroke="'+stroke+'" stroke-width="1.2"/>';}return b;}
function fractionArea(v){var d=Math.max(1,Number(v.denominator)||1),n=Math.max(0,Number(v.numerator)||0),count=Math.max(1,Math.min(4,Number(v.count)||1)),b='',W=86,H=52;for(var c=0;c<count;c++)b+=fractionStrip(n,d,8+c*(W+8),12,W,H);return svg(16+count*(W+8),78,b);}
function fractionPair(v){var a=v.a||{},q=v.b||{},b='';b+=fractionStrip(Number(a.numerator)||0,Math.max(1,Number(a.denominator)||1),8,16,96,48);b+='<text x="126" y="48" text-anchor="middle" font-size="20" font-family="sans-serif">'+esc(v.operation||'+')+'</text>';b+=fractionStrip(Number(q.numerator)||0,Math.max(1,Number(q.denominator)||1),148,16,96,48);return svg(254,82,b);}
function mixedNumber(v){var whole=Math.max(0,Math.min(4,Number(v.whole)||0)),n=Math.max(0,Number(v.numerator)||0),d=Math.max(1,Number(v.denominator)||1),W=58,H=48,b='',x=6;for(var i=0;i<whole;i++){b+=fractionStrip(d,d,x,14,W,H);x+=W+6;}b+=fractionStrip(n,d,x,14,W,H);return svg(Math.max(130,x+W+8),76,b);}
function hundred(v){var shaded=Math.max(0,Math.min(100,Number(v.shaded)||0)),b='',s=11;for(var i=0;i<100;i++){var x=8+(i%10)*s,y=8+Math.floor(i/10)*s;b+='<rect x="'+x+'" y="'+y+'" width="'+s+'" height="'+s+'" fill="'+(i<shaded?accent:light)+'" stroke="'+stroke+'" stroke-width=".55"/>';}return svg(126,126,b);}
function numberLine(v){var vals=(v.values||[]).map(Number),min=Math.min.apply(null,vals),max=Math.max.apply(null,vals);if(!isFinite(min)||min===max){min=0;max=1;}var b='<line x1="18" y1="45" x2="242" y2="45" stroke="'+stroke+'" stroke-width="2"/>';for(var i=0;i<vals.length;i++){var x=18+(vals[i]-min)/(max-min)*224;b+='<line x1="'+x+'" y1="36" x2="'+x+'" y2="54" stroke="'+accent+'" stroke-width="2"/><text x="'+x+'" y="70" text-anchor="middle" font-size="11" font-family="sans-serif">'+esc((v.marks||[])[i]||vals[i])+'</text>';}return svg(260,82,b);}
function clock(v){var h=Number(v.hour)||0,m=Number(v.minute)||0,cx=70,cy=70,r=52,ma=(m*6-90)*Math.PI/180,ha=((h%12)*30+m*.5-90)*Math.PI/180,b='<circle cx="'+cx+'" cy="'+cy+'" r="'+r+'" fill="'+light+'" stroke="'+stroke+'" stroke-width="3"/>';for(var i=1;i<=12;i++){var a=(i*30-90)*Math.PI/180;b+='<text x="'+(cx+Math.cos(a)*42)+'" y="'+(cy+Math.sin(a)*42+4)+'" text-anchor="middle" font-size="9" font-family="sans-serif">'+i+'</text>';}b+='<line x1="'+cx+'" y1="'+cy+'" x2="'+(cx+Math.cos(ha)*28)+'" y2="'+(cy+Math.sin(ha)*28)+'" stroke="'+stroke+'" stroke-width="4" stroke-linecap="round"/><line x1="'+cx+'" y1="'+cy+'" x2="'+(cx+Math.cos(ma)*40)+'" y2="'+(cy+Math.sin(ma)*40)+'" stroke="'+accent+'" stroke-width="3" stroke-linecap="round"/>';return svg(140,140,b);}
function timeline(v){var start=Number(v.start)||0,end=Number(v.end)||1,raw=[start].concat(v.markers||[]).concat([end]),labels=v.labels||[],b='<line x1="18" y1="38" x2="252" y2="38" stroke="'+stroke+'" stroke-width="3"/>';raw.forEach(function(q,i){var x=18+(Number(q)-start)/Math.max(1,end-start)*234;b+='<circle cx="'+x+'" cy="38" r="4" fill="'+accent+'/><text x="'+x+'" y="58" text-anchor="middle" font-size="9" font-family="sans-serif">'+esc(i===0?String(start):i===raw.length-1?String(end):(labels[i-1]||String(q)))+'</text>';});return svg(270,72,b);}
function calendar(v){var names=['Ahad','Isnin','Selasa','Rabu','Khamis','Jumaat','Sabtu'],b='<div style="max-width:300px;margin:4px auto 10px;font:600 11px/1.2 sans-serif"><div style="text-align:center;font-weight:900;margin-bottom:5px">'+esc(v.month)+' '+esc(v.year)+'</div><div style="display:grid;grid-template-columns:repeat(7,1fr);gap:2px">';for(var i=0;i<7;i++)b+='<div style="text-align:center;font-size:9px">'+names[i].slice(0,2)+'</div>';for(var e=0;e<Number(v.startDay||0);e++)b+='<div></div>';for(var d=1;d<=Number(v.days||30);d++){var hot=d===Number(v.highlight);b+='<div style="text-align:center;border:1px solid '+(hot?stroke:'#bbb')+';border-radius:4px;padding:4px;'+(hot?'font-weight:900;outline:2px solid '+accent+';outline-offset:-2px':'')+'">'+d+'</div>';}return b+'</div></div>';}
function table(v){var hs=v.headers||[],rows=v.rows||[],html='<table class="qsv2-d3p0-table" style="border-collapse:collapse;margin:4px auto 10px;font:600 12px/1.3 sans-serif">';html+='<tr>'+hs.map(function(h){return'<th style="border:1px solid #888;padding:5px 8px">'+esc(h)+'</th>';}).join('')+'</tr>';rows.forEach(function(r){html+='<tr>'+r.map(function(x){return'<td style="border:1px solid #aaa;padding:5px 8px;text-align:center">'+esc(x)+'</td>';}).join('')+'</tr>';});return html+'</table>';}
function ruler(v){var val=Number(v.value)||0,max=Math.max(val,Number(v.max)||val||1),pct=Math.max(0,Math.min(1,val/max)),b='<line x1="16" y1="48" x2="244" y2="48" stroke="'+stroke+'" stroke-width="4"/>';for(var i=0;i<=10;i++){var x=16+i*22.8;b+='<line x1="'+x+'" y1="35" x2="'+x+'" y2="54" stroke="'+stroke+'" stroke-width="1"/>';}b+='<line x1="16" y1="26" x2="'+(16+228*pct)+'" y2="26" stroke="'+accent+'" stroke-width="5"/><text x="130" y="72" text-anchor="middle" font-size="12" font-family="sans-serif">'+esc(v.mixedLabel||String(val)+' '+(v.label||''))+'</text>';return svg(260,84,b);}
function scale(v){var val=Number(v.value)||0,max=Math.max(val,Number(v.max)||val||1),pct=Math.max(0,Math.min(1,val/max)),ang=(-120+240*pct)*Math.PI/180,cx=70,cy=70,r=45,b='<path d="M25 75 A45 45 0 0 1 115 75" fill="none" stroke="'+stroke+'" stroke-width="3"/><line x1="'+cx+'" y1="'+cy+'" x2="'+(cx+Math.cos(ang)*35)+'" y2="'+(cy+Math.sin(ang)*35)+'" stroke="'+accent+'" stroke-width="4"/><circle cx="70" cy="70" r="4" fill="'+stroke+'"/><text x="70" y="98" text-anchor="middle" font-size="11" font-family="sans-serif">'+esc(v.mixedLabel||String(val)+' '+(v.label||''))+'</text>';return svg(140,108,b);}
function container(v){var val=Number(v.value)||0,max=Math.max(val,Number(v.max)||val||1),pct=Math.max(0,Math.min(1,val/max)),h=90*pct,y=108-h,b='<path d="M35 14 L45 110 L115 110 L125 14 Z" fill="none" stroke="'+stroke+'" stroke-width="3"/><rect x="45" y="'+y+'" width="70" height="'+h+'" fill="'+fill+'" stroke="none"/>';for(var i=1;i<5;i++){var yy=110-i*20;b+='<line x1="108" y1="'+yy+'" x2="120" y2="'+yy+'" stroke="'+stroke+'"/>';}b+='<text x="80" y="130" text-anchor="middle" font-size="11" font-family="sans-serif">'+esc(v.mixedLabel||String(val)+' '+(v.label||''))+'</text>';return svg(160,142,b);}
function timeUnits(v){var val=Number(v.value)||0,max=Math.max(1,Number(v.max)||val||1),pct=Math.max(0,Math.min(1,val/max)),b='<rect x="18" y="28" width="220" height="28" rx="8" fill="'+light+'" stroke="'+stroke+'" stroke-width="2"/><rect x="18" y="28" width="'+(220*pct)+'" height="28" rx="8" fill="'+fill+'"/><text x="128" y="47" text-anchor="middle" font-size="12" font-family="sans-serif">'+esc(val)+' '+esc(v.label||'')+'</text>';return svg(256,78,b);}
function placeValue(v){var op=v.operation==='div'?'÷':'×',text=v.value||((v.base||'')+' '+op+' '+(v.factor||'')),b='<rect x="18" y="18" width="224" height="54" rx="8" fill="'+fill+'" stroke="'+stroke+'" stroke-width="2"/><text x="130" y="50" text-anchor="middle" font-size="18" font-family="monospace">'+esc(text)+'</text>';return svg(260,90,b);}
function decimalOp(v){var text=String(v.a||'')+' '+String(v.operation||'+')+' '+String(v.b||''),b='<rect x="18" y="18" width="224" height="54" rx="8" fill="'+fill+'" stroke="'+stroke+'" stroke-width="2"/><text x="130" y="50" text-anchor="middle" font-size="20" font-family="monospace">'+esc(text)+'</text>';return svg(260,90,b);}
function classification(v){return '<div style="max-width:300px;margin:4px auto 10px;padding:8px;border:1px solid #aaa;border-radius:8px;font:600 12px/1.5 sans-serif;text-align:center">'+(v.items||[]).map(esc).join(' · ')+'</div>';}
function barChart(v){var vals=v.values||[],labs=v.labels||[],mx=Math.max.apply(null,vals.concat([1])),b='';for(var i=0;i<vals.length;i++){var h=80*vals[i]/mx,x=26+i*58;b+='<rect x="'+x+'" y="'+(102-h)+'" width="34" height="'+h+'" fill="'+fill+'" stroke="'+stroke+'" stroke-width="2"/><text x="'+(x+17)+'" y="118" text-anchor="middle" font-size="11" font-family="sans-serif">'+esc(labs[i])+'</text><text x="'+(x+17)+'" y="'+(96-h)+'" text-anchor="middle" font-size="9" font-family="sans-serif">'+esc(vals[i])+'</text>';}return svg(220,130,b);}
function pictograph(v){var labs=v.labels||[],vals=v.values||[],html='<div style="display:grid;grid-template-columns:auto 1fr;gap:4px 8px;max-width:280px;margin:4px auto 10px;font:600 12px sans-serif">';for(var i=0;i<labs.length;i++){html+='<span>'+esc(labs[i])+'</span><span>'+new Array((Number(vals[i])||0)+1).join('● ')+'</span>';}return html+'</div>';}
function pie(v){var vals=v.values||[],labs=v.labels||[],sum=vals.reduce(function(a,b){return a+Number(b||0);},0)||1,ang=-Math.PI/2,b='',cx=70,cy=70,r=52;for(var i=0;i<vals.length;i++){var next=ang+2*Math.PI*Number(vals[i]||0)/sum,x1=cx+r*Math.cos(ang),y1=cy+r*Math.sin(ang),x2=cx+r*Math.cos(next),y2=cy+r*Math.sin(next),large=(next-ang)>Math.PI?1:0;b+='<path d="M '+cx+' '+cy+' L '+x1+' '+y1+' A '+r+' '+r+' 0 '+large+' 1 '+x2+' '+y2+' Z" fill="'+(i%2?fill:light)+'" stroke="'+stroke+'" stroke-width="1.5"/>';var mid=(ang+next)/2,label=labs[i]+(v.showValues?' ('+vals[i]+')':'');b+='<text x="'+(cx+Math.cos(mid)*33)+'" y="'+(cy+Math.sin(mid)*33+4)+'" text-anchor="middle" font-size="9" font-family="sans-serif">'+esc(label)+'</text>';ang=next;}return svg(140,140,b);}
function renderOne(v){if(!v)return '';if(v.kind==='bar_model')return bar(v);if(v.kind==='grouping')return grouping(v);if(v.kind==='fraction_area')return fractionArea(v);if(v.kind==='fraction_area_pair')return fractionPair(v);if(v.kind==='mixed_number')return mixedNumber(v);if(v.kind==='hundred_grid')return hundred(v);if(v.kind==='number_line')return numberLine(v);if(v.kind==='clock')return clock(v);if(v.kind==='timeline')return timeline(v);if(v.kind==='calendar')return calendar(v);if(v.kind==='table')return table(v);if(v.kind==='classification')return classification(v);if(v.kind==='pie_chart')return pie(v);if(v.kind==='bar_chart')return barChart(v);if(v.kind==='pictograph')return pictograph(v);if(v.kind==='multi_chart')return '<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px">'+renderOne(v.pictograph)+renderOne(v.bar)+'</div>';if(v.kind==='place_value_shift'||v.kind==='place_value_decimal')return placeValue(v);if(v.kind==='decimal_operation')return decimalOp(v);if(v.kind==='ruler')return ruler(v);if(v.kind==='scale')return scale(v);if(v.kind==='container')return container(v);if(v.kind==='time_units')return timeUnits(v);return '<div class="qsv2-d3p0-visual" data-kind="'+esc(v.kind)+'"></div>';}
registerRenderer('d3p0',function(question){return renderOne(question&&question.visual);});
})();
