// Darjah 2 Learning Camp content bank.
// Singapore-inspired structure: Concrete/Virtual -> Pictorial -> Abstract -> Transfer.
// Each skill keeps the same 5-stage shell, but uses concept-specific teaching content.
window.PALessonsD2 = {
  'D2.1.1': {title:'Nilai nombor hingga 1000', goal:'Faham bahawa nombor tiga digit dibina daripada ratus, puluh dan sa.', faham:'Bayangkan 426 sebagai 4 kumpulan seratus, 2 kumpulan sepuluh dan 6 unit.', visual:'base100', build:'Bina nombor dengan kumpulan besar dahulu: ratus → puluh → sa.', bridge:'426 = 400 + 20 + 6', good:'Pisahkan ikut ratus, puluh dan sa', bad:'Lihat digit paling besar sahaja', transfer:'Bolehkan kamu mengenal nilai nombor walaupun bentuk soalan berubah?'},
  'D2.1.2': {title:'Menulis nombor', goal:'Hubungkan nama nombor dengan digit pada kedudukan yang betul.', faham:'“Tiga ratus empat puluh dua” bermaksud 3 ratus, 4 puluh dan 2 sa.', visual:'placeSlots', build:'Dengar atau baca setiap bahagian, kemudian letakkan digit pada lajurnya.', bridge:'3 ratus + 4 puluh + 2 sa → 342', good:'Letak setiap nilai pada tempatnya', bad:'Susun digit ikut urutan perkataan sahaja', transfer:'Tukar antara perkataan, cerakin dan angka.'},
  'D2.1.3': {title:'Rangkaian nombor', goal:'Kenal perubahan tetap antara nombor, bukan hafal urutan.', faham:'Jika 120, 130, 140… setiap langkah bertambah 10.', visual:'numberLine', build:'Cari beza antara dua nombor bersebelahan dahulu.', bridge:'130 − 120 = 10, jadi langkah seterusnya +10', good:'Cari beza yang berulang', bad:'Teka nombor yang nampak sesuai', transfer:'Kenal pola walaupun nombor permulaan berubah.'},
  'D2.1.4': {title:'Nilai tempat hingga 1000', goal:'Bezakan digit, nilai tempat dan nilai digit.', faham:'Dalam 532, digit 3 berada di tempat puluh, jadi nilainya 30.', visual:'placeTable', build:'Cari kedudukan digit dahulu, kemudian tukar kepada nilainya.', bridge:'digit 3 → tempat puluh → nilai 30', good:'Tempat dahulu, nilai kemudian', bad:'Jawab dengan digit itu sahaja', transfer:'Gunakan idea yang sama pada nombor lain dan dalam cerakin.'},
  'D2.1.5': {title:'Menganggar', goal:'Faham anggaran sebagai nilai hampir yang munasabah untuk bilangan objek.', faham:'Anggaran tidak meminta bilangan tepat. Lihat keseluruhan kumpulan dan pilih nilai hampir yang masuk akal.', visual:'estimateDots', build:'Bandingkan saiz kumpulan dengan kumpulan kecil yang mudah dikenal, contohnya kira-kira 10 objek.', bridge:'Kumpulan ini nampak hampir 50 objek, bukan tepat 50.', good:'Pilih nilai hampir dan munasabah', bad:'Mengira tepat atau menggunakan aturan pembundaran nombor', transfer:'Anggar bilangan objek dalam susunan dan konteks berbeza.'},
  'D2.1.6': {title:'Membundar', goal:'Faham kenapa nombor bergerak ke puluh/ratus terdekat.', faham:'347 berada lebih dekat kepada 300 atau 400? Lihat kedudukannya di garisan nombor.', visual:'roundLine', build:'Tentukan dua jiran ratus/puluh, kemudian lihat nombor lebih dekat ke mana.', bridge:'347 lebih dekat 300 berbanding 400 → 300', good:'Banding jarak kepada dua nilai jiran', bad:'Naikkan nombor setiap kali', transfer:'Bundar nombor baru tanpa bergantung pada satu contoh.'},
  'D2.1.7': {title:'Pola nombor', goal:'Kenal aturan yang konsisten dalam pola.', faham:'Pola ialah perubahan yang berulang, contohnya +5 setiap langkah.', visual:'patternTiles', build:'Banding dua pasangan berturutan untuk sahkan aturan sama.', bridge:'205 → 210 → 215 bermaksud +5', good:'Sahkan aturan pada lebih daripada satu langkah', bad:'Tengok dua nombor sahaja lalu meneka', transfer:'Teruskan pola menaik atau menurun dengan aturan sama.'},
  'D2.1.8': {title:'Masalah nombor', goal:'Terjemah cerita kepada hubungan kuantiti sebelum pilih operasi.', faham:'Kenal apa yang diketahui, apa yang berubah dan apa yang dicari.', visual:'barModel', build:'Lukis/modelkan bahagian diketahui dan bahagian tambahan/berkurang.', bridge:'jumlah = bahagian pertama + bahagian kedua', good:'Tentukan hubungan cerita dahulu', bad:'Cari keyword dan terus pilih operasi', transfer:'Selesaikan cerita dengan susunan ayat yang berbeza.'},

  'D2.2.1': {title:'Tambah hingga 1000', goal:'Faham pengumpulan semula apabila sa atau puluh cukup 10.', faham:'34 + 28: 4 sa + 8 sa = 12 sa = 1 puluh 2 sa.', visual:'regroupAdd', build:'Gabungkan sa dahulu, tukar 10 sa kepada 1 puluh jika perlu.', bridge:'34 + 28 = (30+20) + (4+8) = 50 + 12 = 62', good:'Gabung ikut nilai tempat dan kumpul semula', bad:'Tambah semua digit tanpa ikut tempat', transfer:'Gunakan pengumpulan semula pada nombor tiga digit.'},
  'D2.2.2': {title:'Tolak hingga 1000', goal:'Faham pengumpulan semula sebagai menukar 1 puluh kepada 10 sa.', faham:'52 − 28: 2 sa tak cukup tolak 8, jadi 1 puluh ditukar menjadi 10 sa.', visual:'regroupSub', build:'Tukar satu unit nilai tempat lebih besar bila bahagian kecil tak cukup.', bridge:'52 = 4 puluh 12 sa, kemudian 12−8 dan 4−2', good:'Tukar nilai tanpa mengubah jumlah keseluruhan', bad:'Tolak digit kecil daripada digit besar tanpa melihat kedudukan', transfer:'Gunakan idea sama bila perlu pinjam pada puluh/ratus.'},
  'D2.2.3': {title:'Darab asas', goal:'Faham darab sebagai kumpulan sama banyak.', faham:'3 × 4 bermaksud 3 kumpulan, setiap kumpulan ada 4.', visual:'equalGroups', build:'Bina kumpulan yang sama saiz, kemudian kira jumlah keseluruhan.', bridge:'4 + 4 + 4 = 3 × 4 = 12', good:'Fikir bilangan kumpulan × isi setiap kumpulan', bad:'Campur dua nombor sekali sahaja', transfer:'Kenal darab dalam susunan objek dan cerita.'},
  'D2.2.4': {title:'Bahagi asas', goal:'Faham bahagi sebagai membahagi sama rata atau membuat kumpulan sama banyak.', faham:'12 ÷ 3 boleh bermaksud 12 objek dibahagi kepada 3 kumpulan sama rata.', visual:'shareGroups', build:'Agihkan satu demi satu sehingga semua kumpulan sama banyak.', bridge:'12 ÷ 3 = 4 kerana 3 × 4 = 12', good:'Semak bahagi menggunakan hubungan darab', bad:'Tolak sekali sahaja dan berhenti', transfer:'Bezakan “berapa setiap kumpulan” dan “berapa kumpulan”.'},
  'D2.2.5': {title:'Masalah operasi', goal:'Pilih operasi berdasarkan hubungan kuantiti, bukan keyword.', faham:'Cerita boleh guna perkataan yang berbeza tetapi hubungan matematik tetap sama.', visual:'barModel', build:'Tandakan jumlah, bahagian, kumpulan atau perubahan sebelum kira.', bridge:'Model → operasi → pengiraan', good:'Bina model hubungan dahulu', bad:'Nampak “lagi” terus tambah', transfer:'Pilih operasi dalam cerita yang tidak menggunakan keyword biasa.'},

  'D2.3.1': {title:'Pecahan wajar', goal:'Faham pecahan sebagai bahagian sama besar daripada satu keseluruhan.', faham:'3/4 bermaksud 3 bahagian dipilih daripada 4 bahagian yang sama besar.', visual:'fractionParts', build:'Pastikan keseluruhan dibahagi sama besar sebelum kira bahagian.', bridge:'3 bahagian dipilih ÷ 4 bahagian sama besar → 3/4', good:'Lihat keseluruhan dan bahagian sama besar', bad:'Kira bahagian tanpa periksa sama besar', transfer:'Kenal pecahan pada bentuk, set objek dan cerita.'},
  'D2.3.2': {title:'Perpuluhan persepuluh', goal:'Faham satu tempat perpuluhan sebagai bahagian persepuluh.', faham:'0.4 bermaksud 4 daripada 10 bahagian sama besar.', visual:'tenthsGrid', build:'Hubungkan 4/10 dengan empat petak daripada sepuluh.', bridge:'4/10 = 0.4', good:'Fikir “berapa persepuluh”', bad:'Baca 0.4 sebagai empat nombor penuh', transfer:'Tukar visual persepuluh kepada perpuluhan.'},
  'D2.3.3': {title:'Hubungan pecahan & perpuluhan', goal:'Nampak bahawa pecahan persepuluh dan perpuluhan boleh mewakili kuantiti sama.', faham:'7/10 dan 0.7 menunjukkan bahagian yang sama daripada satu keseluruhan.', visual:'fractionDecimal', build:'Gunakan grid 10 bahagian sebagai jambatan antara dua notasi.', bridge:'7/10 ↔ 0.7', good:'Banding kuantiti, bukan rupa simbol', bad:'Anggap pecahan dan perpuluhan sentiasa nilai berbeza', transfer:'Padankan notasi berbeza yang mewakili nilai sama.'},
  'D2.3.4': {title:'Masalah pecahan/perpuluhan', goal:'Gunakan model bahagian-keseluruhan untuk memahami cerita.', faham:'Kenal keseluruhan dahulu, kemudian berapa bahagian digunakan atau tinggal.', visual:'fractionBar', build:'Lukis satu bar sebagai keseluruhan dan warnakan bahagian berkaitan.', bridge:'model bahagian → pecahan/perpuluhan → jawapan', good:'Tentukan keseluruhan dahulu', bad:'Gunakan nombor atas/bawah tanpa konteks', transfer:'Selesaikan cerita dengan model berbeza.'},

  'D2.4.1': {title:'Nilai wang hingga RM100', goal:'Faham nilai wang ditentukan oleh jumlah nilai, bukan bilangan keping.', faham:'RM10 + RM10 + RM5 bernilai RM25 walaupun hanya 3 keping.', visual:'moneyPieces', build:'Kumpulkan nilai setiap nota/syiling sebelum jumlah.', bridge:'10 + 10 + 5 = RM25', good:'Jumlahkan nilai setiap keping', bad:'Kira bilangan keping sahaja', transfer:'Bina nilai sama menggunakan kombinasi wang berbeza.'},
  'D2.4.2': {title:'Tambah wang', goal:'Tambah ringgit dan sen dengan nilai tempat yang betul.', faham:'RM12.50 + RM3.20: ringgit dengan ringgit, sen dengan sen.', visual:'moneyColumns', build:'Susun unit wang sejajar sebelum menambah.', bridge:'RM12.50 + RM3.20 = RM15.70', good:'Sejajarkan ringgit dan sen', bad:'Campur semua digit tanpa unit', transfer:'Tambah harga dalam situasi pembelian.'},
  'D2.4.3': {title:'Tolak wang', goal:'Faham baki sebagai beza antara jumlah asal dan jumlah dibayar/digunakan.', faham:'Jika ada RM20 dan guna RM7, baki ialah bahagian yang tinggal.', visual:'moneyBar', build:'Modelkan jumlah asal sebagai satu bar dan keluarkan bahagian digunakan.', bridge:'RM20 − RM7 = RM13', good:'Tentukan jumlah asal dan bahagian yang keluar', bad:'Tolak nombor mengikut susunan ayat sahaja', transfer:'Cari baki atau beza harga dalam cerita.'},
  'D2.4.4': {title:'Darab wang', goal:'Faham jumlah kos untuk beberapa item dengan harga sama.', faham:'3 buku × RM4 setiap satu ialah 3 kumpulan RM4.', visual:'moneyGroups', build:'Ulang nilai harga yang sama bagi setiap item.', bridge:'RM4 + RM4 + RM4 = 3 × RM4 = RM12', good:'Bilangan item × harga setiap item', bad:'Tambah bilangan item kepada harga', transfer:'Kira kos kumpulan item lain.'},
  'D2.4.5': {title:'Bahagi wang', goal:'Faham pembahagian wang sama rata.', faham:'RM12 dibahagi kepada 3 orang bermaksud setiap orang menerima bahagian sama.', visual:'moneyShare', build:'Agihkan nilai secara sama rata kepada setiap kumpulan.', bridge:'RM12 ÷ 3 = RM4', good:'Semak semua bahagian sama dan jumlah kembali sama', bad:'Bahagi digit tanpa fikir nilai wang', transfer:'Cari nilai setiap bahagian atau bilangan bahagian.'},
  'D2.4.6': {title:'Simpanan & kewangan', goal:'Faham simpanan sebagai wang yang tidak dibelanjakan dan berubah dari masa ke masa.', faham:'Jika dapat RM10 dan belanja RM6, RM4 boleh disimpan.', visual:'saveSpend', build:'Pisahkan wang kepada bahagian belanja dan simpan.', bridge:'wang diterima − wang dibelanja = simpanan', good:'Bezakan masuk, keluar dan baki', bad:'Jumlah semua nilai tanpa lihat arah wang', transfer:'Banding pilihan simpanan dalam situasi berbeza.'},
  'D2.4.7': {title:'Masalah wang', goal:'Gunakan unit dan hubungan wang untuk memilih operasi.', faham:'Kenal sama ada cerita mencari jumlah kos, baki, harga setiap item atau simpanan.', visual:'moneyFlow', build:'Tandakan wang masuk, wang keluar dan apa yang dicari.', bridge:'model aliran wang → operasi', good:'Tentukan arah wang dan unit', bad:'Pilih operasi berdasarkan satu perkataan', transfer:'Selesaikan masalah wang pelbagai langkah mudah.'},

  'D2.5.1': {title:'Jam & minit', goal:'Hubungkan bacaan jam dengan kedudukan jarum dan unit masa.', faham:'Jarum minit bergerak 5 minit bagi setiap nombor pada jam.', visual:'clockFace', build:'Baca jarum jam dahulu, kemudian jarum minit.', bridge:'jarum minit di 6 → 30 minit', good:'Bezakan fungsi dua jarum', bad:'Baca nombor yang ditunjuk sebagai minit terus', transfer:'Baca masa pada muka jam yang berbeza.'},
  'D2.5.2': {title:'Perkaitan masa', goal:'Faham hubungan 1 jam = 60 minit dan unit masa berkaitan.', faham:'60 minit membentuk satu jam penuh.', visual:'timeBlocks', build:'Gabungkan kumpulan minit sehingga cukup 60.', bridge:'120 minit = 2 × 60 minit = 2 jam', good:'Tukar melalui hubungan unit', bad:'Anggap 100 minit = 1 jam', transfer:'Tukar jam kepada minit dan sebaliknya.'},
  'D2.5.3': {title:'Masalah masa', goal:'Faham tempoh sebagai jarak antara masa mula dan masa tamat.', faham:'Dari 2:15 ke 3:00 ialah 45 minit, bukan 85 minit.', visual:'timeLine', build:'Lompat pada garis masa dalam bahagian mudah.', bridge:'2:15 → 2:30 → 3:00 = 15 + 30 minit', good:'Kira jarak masa pada garis masa', bad:'Tolak digit masa seperti nombor biasa', transfer:'Cari masa mula, tamat atau tempoh.'},

  'D2.6.1': {title:'Panjang', goal:'Faham panjang sebagai ukuran jarak dan pilih unit sesuai.', faham:'Pensel sesuai diukur dalam cm; bilik lebih sesuai dalam m.', visual:'ruler', build:'Sejajarkan objek dengan titik sifar dan baca hujungnya.', bridge:'panjang = bacaan hujung − bacaan mula', good:'Pilih unit dan titik mula dengan betul', bad:'Mula mengukur dari tepi pembaris tanpa lihat sifar', transfer:'Banding dan ukur objek dalam konteks lain.'},
  'D2.6.2': {title:'Jisim', goal:'Faham jisim sebagai berapa berat sesuatu objek dan unit yang sesuai.', faham:'Objek kecil biasanya dalam g, objek lebih berat dalam kg.', visual:'balance', build:'Banding objek pada neraca dan kaitkan dengan nilai unit.', bridge:'1000 g = 1 kg', good:'Pilih unit mengikut saiz jisim', bad:'Pilih unit berdasarkan saiz rupa objek sahaja', transfer:'Banding atau kira jisim dalam cerita.'},
  'D2.6.3': {title:'Isi padu cecair', goal:'Faham isi padu sebagai jumlah cecair dalam bekas.', faham:'Bekas yang tinggi tidak semestinya mengandungi lebih banyak; baca skala.', visual:'measuringJug', build:'Lihat paras cecair sejajar dengan tanda skala.', bridge:'setiap tanda mewakili nilai tertentu', good:'Baca skala dan unit', bad:'Teka berdasarkan bentuk bekas', transfer:'Banding isi padu pada bekas berlainan.'},
  'D2.6.4': {title:'Masalah ukuran', goal:'Pilih ukuran, unit dan operasi yang sesuai dengan situasi.', faham:'Masalah ukuran perlu kekalkan unit yang sama sebelum mengira.', visual:'measureFlow', build:'Tandakan kuantiti, unit dan apa yang dicari.', bridge:'samakan unit → pilih operasi → kira', good:'Semak unit sebelum operasi', bad:'Campur nombor berlainan unit terus', transfer:'Selesaikan masalah panjang, jisim atau isi padu.'},

  'D2.7.1': {title:'Bentuk 3D', goal:'Kenal bentuk 3D melalui muka, sisi dan bucu, bukan rupa sahaja.', faham:'Kubus mempunyai muka rata yang sama bentuk; sfera tiada muka rata.', visual:'solidFeatures', build:'Sentuh/bayangkan ciri: boleh bergolek? ada muka rata? ada bucu?', bridge:'ciri-ciri → nama bentuk', good:'Kenal melalui beberapa ciri', bad:'Pilih sebab bentuk nampak hampir sama', transfer:'Kenal objek dunia sebenar melalui cirinya.'},
  'D2.7.2': {title:'Bentuk 2D', goal:'Kenal bentuk 2D melalui bilangan sisi, bucu dan sifat.', faham:'Segi tiga tetap segi tiga walaupun dipusing kerana masih ada 3 sisi.', visual:'shapeRotate', build:'Kira sisi dan bucu tanpa bergantung pada orientasi.', bridge:'3 sisi + 3 bucu → segi tiga', good:'Gunakan ciri yang kekal', bad:'Kenal berdasarkan arah atau warna', transfer:'Kenal bentuk yang dipusing atau saiz berubah.'},
  'D2.7.3': {title:'Masalah ruang', goal:'Gunakan ciri bentuk untuk menyelesaikan soalan, bukan hafal nama sahaja.', faham:'Jika soalan minta bentuk yang boleh bergolek dan ada muka rata, fikir cirinya.', visual:'featureSort', build:'Senaraikan syarat dan tapis bentuk satu demi satu.', bridge:'syarat → ciri → pilihan bentuk', good:'Padankan semua syarat', bad:'Pilih berdasarkan satu ciri sahaja', transfer:'Aplikasikan ciri pada objek sebenar.'},

  'D2.8.1': {title:'Kumpul dan susun data', goal:'Kira berapa banyak item dalam setiap kumpulan.', faham:'Mula-mula asingkan item mengikut jenis. Selepas itu, kira setiap kumpulan.', visual:'tally', build:'Contohnya, semua epal dalam satu kumpulan dan semua oren dalam kumpulan lain. Kemudian kira satu kumpulan pada satu masa.', bridge:'asingkan → kira → tulis jumlah', good:'Asingkan ikut kumpulan dahulu', bad:'Campur semua item sekali', transfer:'Cuba dengan kumpulan dan nombor yang berbeza.'},
  'D2.8.2': {title:'Baca carta palang', goal:'Cari nilai yang ditunjukkan oleh setiap palang.', faham:'Setiap palang mewakili satu kumpulan. Palang yang lebih tinggi menunjukkan nilai yang lebih besar.', visual:'barChart', build:'Cari nama kumpulan di bawah palang. Selepas itu, lihat tinggi palang untuk tahu nilainya.', bridge:'nama kumpulan → tinggi palang → nilai', good:'Lihat nama dan tinggi palang', bad:'Teka daripada warna palang', transfer:'Cuba baca carta lain dengan susunan yang berbeza.'},
  'D2.8.3': {title:'Guna maklumat dalam carta', goal:'Baca dua nilai daripada carta, kemudian kira jumlah atau beza.', faham:'Jangan kira sebelum tahu nombor yang ditunjukkan oleh carta. Baca nilainya dahulu.', visual:'barCompare', build:'Contoh: jika Epal = 8 dan Oren = 5, beza ialah 8 − 5 = 3.', bridge:'baca dua nilai → pilih tambah atau tolak → kira', good:'Baca nombor dahulu, baru kira', bad:'Teka daripada rupa palang', transfer:'Cuba soalan baru menggunakan carta yang lain.'}
};
