window.PAQuestionBanks = window.PAQuestionBanks || {};
window.PAQuestionBanks.d3 = function(id,s,shift){
 if(id==="D3.N10000"){let a=R(1000,9999),b=R(1000,9999);return Q(`Yang manakah lebih besar?<br><b>${a}</b> atau <b>${b}</b>`,Math.max(a,b),[N(Math.min(a,b),"compare"),N(a+b,"operation"),N(Math.abs(a-b),"operation")],"Banding ribu dahulu.","Darjah 3",true,shift)}
 if(id==="D3.PV10000"){let n=uniqueDigitNumber(4),s=String(n),pos=R(0,3),d=+s[pos],pow=3-pos,ans=d*Math.pow(10,pow),place=["ribu","ratus","puluh","sa"][pos];return Q(`Apakah nilai digit <b>${d}</b> pada tempat <b>${place}</b> dalam <b>${n}</b>?`,ans,[N(d,"digit_value"),N(d*Math.pow(10,Math.max(0,pow-1)),"place"),N(ans+100,"place")],"Nilai digit bergantung pada tempatnya.","Darjah 3",true,true)}
 if(id==="D3.ADD10000"){let a=R(1000,7000),b=R(200,2500),ans=a+b;return addQ(a,b,ans,"Darjah 3",shift)}
 if(id==="D3.SUB10000"){let a=R(3000,9999),b=R(200,Math.min(3000,a-1)),ans=a-b,q=subQ(a,b,ans,"Darjah 3",shift);if((a%10)<(b%10)&&Math.floor(a/10)%10>0){q.dimensional={curriculumVersion:"SEMAKAN_2017_DPK_EDISI_3",conceptId:"subtraction_regrouping",prototypeId:"Y3-PV-A2",misconceptionTargets:["PV-005"],prerequisiteIds:["PV-EXCHANGE-10-1"],canonicalRepresentation:"BENTUK_LAZIM",interventionRepresentation:"R2_PLACE_VALUE",transferStage:"ENTRY",operands:{minuend:a,subtrahend:b}}}return q}
 if(id==="D3.MUL"){let a=R(2,12),b=R(2,12),ans=a*b,context=Math.random()<.45;return Q(context?`Ada <b>${a}</b> kumpulan dengan <b>${b}</b> objek setiap kumpulan. Berapakah jumlah objek?`:`${a} × ${b} = ?`,ans,[N(a+b,"operation"),N(ans+a,"fact"),N(Math.max(1,ans-b),"fact")],"Gunakan fakta darab.","Darjah 3",true,true)}
 if(id==="D3.DIV"){let b=R(2,12),ans=R(2,12),a=b*ans,context=Math.random()<.45;return Q(context?`${a} biji guli dibahagi sama rata kepada <b>${b}</b> orang. Setiap orang mendapat berapa?`:`${a} ÷ ${b} = ?`,ans,[N(b,"operation"),N(ans+1,"division"),N(Math.max(1,ans-1),"division")],"Gunakan hubungan darab-bahagi.","Darjah 3",true,true)}
 if(id==="D3.FRAC"){let d=pick([2,3,4,5,6]),n=R(1,d-1),k=pick([2,3]),ans=`${n*k}/${d*k}`;return Q(`${fractionVisual(n,d)}Pecahan setara bagi <b>${n}/${d}</b> ialah?`,ans,[N(`${n}/${d*k}`,"fraction"),N(`${n*k}/${d}`,"fraction"),N(`${n+k}/${d+k}`,"fraction")],"Darab pengangka dan penyebut dengan nombor yang sama.","Darjah 3",true,true)}
 if(id==="D3.DEC"){let a=(R(1,49)/10).toFixed(1),b=(R(1,49)/10).toFixed(1),ans=(+a + +b).toFixed(1);return Q(`${a} + ${b} = ?`,ans,[N((+ans+1).toFixed(1),"decimal"),N(String((+a*10)+(+b*10)),"decimal"),N((+ans-.1).toFixed(1),"decimal")],"Selarikan titik perpuluhan.","Darjah 3",true,true)}
 if(id==="D3.MONEY"){let price=R(12,70),pay=pick([50,100]),ans=pay-price; if(ans<0){pay=100;ans=pay-price} return Q(`Harga RM${price}, bayar RM${pay}. Baki?`,`RM${ans}`,[N(`RM${price}`,"money"),N(`RM${pay+price}`,"operation"),N(`RM${ans+10}`,"same_end")],"Baki = bayaran − harga.","Darjah 3",true,true)}
 if(id==="D3.TIME"){let h=R(7,10),m=pick([0,15,30,45]),dur=pick([30,45,60,90]),start=h*60+m,end=start+dur,ans=`${Math.floor(end/60)}:${String(end%60).padStart(2,'0')}`;return Q(`Mula ${h}:${String(m).padStart(2,'0')}, tempoh ${dur} minit. Tamat?`,ans,[N(`${h}:${String(m).padStart(2,'0')}`,"time"),N(`${Math.floor((end+30)/60)}:${String((end+30)%60).padStart(2,'0')}`,"time"),N(`${Math.floor((end-30)/60)}:${String((end-30)%60).padStart(2,'0')}`,"time")],"Tukar kepada minit jika perlu.","Darjah 3",true,true)}
 if(id==="D3.MEASURE"){let cm=R(11,99)*10,ans=decimalFmt(cm/100,1).replace('.0',''); return Q(`${cm} cm bersamaan berapa m?`,ans,[N(String(cm),"unit"),N(decimalFmt(cm/10,1).replace('.0',''),"unit"),N(decimalFmt(cm/100+1,1).replace('.0',''),"unit")],"100 cm = 1 m.","Darjah 3",true,true)}
 if(id==="D3.SHAPE"){let l=R(3,9),w=R(2,7),ans=2*(l+w);return Q(`Segi empat tepat panjang ${l} cm dan lebar ${w} cm. Perimeternya?`,ans,[N(l*w,"area"),N(l+w,"operation"),N(ans+2,"shape")],"Perimeter = jumlah semua sisi.","Darjah 3",true,true)}
 if(id==="D3.DATA"){let labels=['A','B','C'],vals=[R(3,15),R(3,15),R(3,15)],sum=vals.reduce((a,b)=>a+b,0);return Q(`${barChart(labels,vals)}Jumlah semua data?`,sum,[N(Math.max(...vals),"data"),N(sum+3,"data"),N(sum-3,"data")],"Tambah semua nilai pada carta.","Darjah 3",true,true)}
 return null;
};
